### PR TITLE
area/helm: Added support for embedded cache in helm chart

### LINKED ISSUE #10371: Supporting embedded cache in helm chart
**Is your feature request related to a problem? Please describe.**
Loki offers various results caching methods for improved performance, I'd like to use them.
**Describe the solution you'd like**
Configure Loki to use an embedded cache.

The chart currently uses templating for such things. The template could be extended. At the same time it also appears to me a lot could be gained by reducing the templating. Currently, the template only supports memcached results caching, even though Loki offers many options. If instead of offering a simple, separate memcached section that is precisely templated into a query_range config section maintainers could decide to simply do less, and let users configure the yaml much as they would if they configured loki directly. In my estimation:
* reduces maintenance burden, you get to do less!
* makes features available as they are available in Loki
* allows following the documentation on the Loki website instead of reading it, then mapping that to the values.yaml template, then updating your own config (this is more complex than writing my own yaml! Plus, configuring directly from "simple" values.yaml requires elaborate comments explaining what each option does which currently the values.yaml doesn't have.)
* less opportunity to introduce confusion or bugs (I just opened #10370 which is an example of this)

**Describe alternatives you've considered**
Opening a PR to further extend the template to allow embedded or memcached.

**Additional context**
-

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
**What this PR does / why we need it**:
Loki offers various results caching methods for improved performance.
**Which issue(s) this PR fixes**:
Fixes #10371 

**Special notes for your reviewer**:

Configured Loki to use to chunk and results cache as per Grafana loki documentation,
reference: https://grafana.com/docs/loki/latest/operations/caching/

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)

### CODE REVIEW

**Comment by JStickler** [comment]
This was part of the PR template checklist, any change to the Helm Charts requires a version bump.  Please update the Helm chart version in 
- production/helm/loki/Chart.yaml  
- production/helm/loki/CHANGELOG.md 
- production/helm/loki/README.md. 
- [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
(Depending on if other Helm updates merge before this PR, you may need to update the version more than once.)

**Comment by Sheikh-Abubaker** [comment]
Hi @JStickler, I have updated the chart version as you asked and also resolved all the merge conflicts can you please check if everything is up to the mark,

**Comment by JStickler** [comment]
@Sheikh-Abubaker I'm a technical writer, not a developer.  Someone from the Engineering team will need to review and approve your Go code.

**Comment by Sheikh-Abubaker** [comment]
@trevorwhitney can you please look into this PR if this is upto to the mark, I'm not in any sort of hurry but I have participated in Hacktoberfest so just wanted to know.

**Comment by Sheikh-Abubaker** [comment]
@JStickler can you please request review for this PR it's been a while since I've opened this PR, if there is any changes needed I'd be glad to contribute.

**Comment by bassie1995** [comment]
Was this eventually changed? I cannot use the Helm Chart to set up an embedded cache for `chunk_store_config`, but can use it for `query_range` because it includes the entire block if it finds one... Chunks and results caching are documented with the embedded config, but in reality those configurations in the Helm Chart only specify settings for a singular type of deployment of the caches, which is to me unexpected behaviour.

**Pull request closed without merging**
