### PR TITLE
Removes all GRPC warning.

### PR DESCRIPTION
**Pull request by cyriltovena**
This works for logcli, promtail and Loki.

Cherry on top, this removes a lot of dependencies.

Ciao

```
2021-11-15 17:08:17.031269 I | proto: duplicate proto type registered: purgeplan.DeletePlan
2021-11-15 17:08:17.031380 I | proto: duplicate proto type registered: purgeplan.ChunksGroup
2021-11-15 17:08:17.031386 I | proto: duplicate proto type registered: purgeplan.ChunkDetails
2021-11-15 17:08:17.031391 I | proto: duplicate proto type registered: purgeplan.Interval
2021-11-15 17:08:17.041388 I | proto: duplicate proto type registered: grpc.PutChunksRequest
2021-11-15 17:08:17.041407 I | proto: duplicate proto type registered: grpc.GetChunksRequest
2021-11-15 17:08:17.041413 I | proto: duplicate proto type registered: grpc.GetChunksResponse
2021-11-15 17:08:17.041416 I | proto: duplicate proto type registered: grpc.Chunk
2021-11-15 17:08:17.041420 I | proto: duplicate proto type registered: grpc.ChunkID
2021-11-15 17:08:17.041423 I | proto: duplicate proto type registered: grpc.DeleteTableRequest
2021-11-15 17:08:17.041428 I | proto: duplicate proto type registered: grpc.DescribeTableRequest
2021-11-15 17:08:17.041432 I | proto: duplicate proto type registered: grpc.WriteBatch
2021-11-15 17:08:17.041436 I | proto: duplicate proto type registered: grpc.WriteIndexRequest
2021-11-15 17:08:17.041439 I | proto: duplicate proto type registered: grpc.DeleteIndexRequest
2021-11-15 17:08:17.041443 I | proto: duplicate proto type registered: grpc.QueryIndexResponse
2021-11-15 17:08:17.041446 I | proto: duplicate proto type registered: grpc.Row
2021-11-15 17:08:17.041450 I | proto: duplicate proto type registered: grpc.IndexEntry
2021-11-15 17:08:17.041454 I | proto: duplicate proto type registered: grpc.QueryIndexRequest
2021-11-15 17:08:17.041457 I | proto: duplicate proto type registered: grpc.UpdateTableRequest
2021-11-15 17:08:17.041462 I | proto: duplicate proto type registered: grpc.DescribeTableResponse
2021-11-15 17:08:17.041466 I | proto: duplicate proto type registered: grpc.CreateTableRequest
2021-11-15 17:08:17.041470 I | proto: duplicate proto type registered: grpc.TableDesc
2021-11-15 17:08:17.041473 I | proto: duplicate proto type registered: grpc.TableDesc.TagsEntry
2021-11-15 17:08:17.041477 I | proto: duplicate proto type registered: grpc.ListTablesResponse
2021-11-15 17:08:17.041480 I | proto: duplicate proto type registered: grpc.Labels
2021-11-15 17:08:17.041584 I | proto: duplicate proto type registered: storage.Entry
2021-11-15 17:08:17.041592 I | proto: duplicate proto type registered: storage.ReadBatch
````

Signed-off-by: Cyril Tovena <cyril.tovena@gmail.com>

### CODE REVIEW

**Review by owen-d — APPROVED** [review]

**Review by kavirajk — APPROVED** [review]
Thanks a ton! ❤️

**Review by sandeepsukhani — APPROVED** [review]
Nice! LGTM!

**Comment by rgl** [comment]
when will this be released in a proper loki release? :-)

**Comment by rahulpadti** [comment]
May I know when is the tentative next release date ?

**Pull request merged**
