### PR TITLE
Upgrade Cortex, Prometheus and Thanos

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does / why we need it**:
I'm in the process of upgrading Cortex and Prometheus in a downstream project (Grafana Enterprise Metrics). Unfortunately we can't upgrade it until we upgrade it in Loki too due to some breaking changes done both in Cortex and Prometheus.

Breaking changes:
- Cortex: added the ability to specific request headers to forward downstream when decoding a request (https://github.com/cortexproject/cortex/pull/4486)
- Prometheus: moved some packages (no logic change) (https://github.com/prometheus/prometheus/pull/9478)
- Prometheus: defined data types for series ref (https://github.com/prometheus/prometheus/pull/9501 https://github.com/prometheus/prometheus/pull/9536)
  - All data types are `uint64` so there's no logic change

How I addressed the changes:
- Cortex: request headers to foward
  - Do not forward any request header (previous logic is preserved, we didn't forward any request header)
- Prometheus: moved some packages
  - I just renamed the imports
- Prometheus: defined data types for series ref
  - I kept the same pattern used in Prometheus: in-memory series ref have been converted to `chunks.HeadSeriesRef` while when working with TSDB interfaces I used `storage.SeriesRef` (Prometheus TSDB does the same). Again, both types are `uint64` and Loki was using `uint64` before so I don't expect any logic change.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by pracucci** [comment]
I'm investigating the failing `TestIngesterWALReplaysUnorderedToOrdered`.

**Comment by pracucci** [comment]
> I'm investigating the failing `TestIngesterWALReplaysUnorderedToOrdered`.

Fixed in this commit: https://github.com/grafana/loki/pull/4830/commits/db2c5ff7f7e206c87d0777f249bc33e56074292d

**Comment by pracucci** [comment]
> # github.com/thanos-io/thanos/pkg/httpconfig
> vendor/github.com/thanos-io/thanos/pkg/httpconfig/http.go:94:28: constant 90000000000 overflows int
> vendor/github.com/thanos-io/thanos/pkg/httpconfig/http.go:95:28: constant 10000000000 overflows int
> vendor/github.com/thanos-io/thanos/pkg/httpconfig/http.go:97:28: constant 10000000000 overflows int

I'm on it.

**Review by dannykopping — APPROVED** [review]
LGTM, thanks a lot @pracucci 
Once you've resolved that overflow issue and CI passes, please ping me and I'll merge

**Pull request merged**
