### PR TITLE
remove logcli config part

### PR DESCRIPTION
**Pull request by daixiang0**
Load config in getConfig function.

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
yes, i find root cause, kinpin does not support this way to use config, it only supports 
```
$ cat config
--addr=xxx
$ ./logcli @config
```
refer to [comment](https://github.com/alecthomas/kingpin/issues/272#issuecomment-478152697), v2 does not support it.

So there is three ways to decide:
- config with `@config`
- remove all config part
- use v3 while is not unstable

i pefer to the third way, WDYT @davkal

**Comment by davkal** [comment]
We should not use kingpin v3 yet, not because it's beta, but because its documentation is hard to find.
If you can use logcli without a config file (e.g., by using flags or env vars), I recommend removing the config file loader. If this is really important for your use case, continue with the `@` notation, but be aware that having this extra feature adds complexity.

**Comment by daixiang0** [comment]
Got it.

**Comment by daixiang0** [comment]
@davkal done

**Comment by daixiang0** [comment]
@davkal hi, any input?

**Comment by davkal** [comment]
Works. Also cleaner now 😄

**Comment by daixiang0** [comment]
：）

**Pull request merged**
