### PR TITLE
Docs: Modify label names of configuration blocks

### PR DESCRIPTION
**Pull request by KMiller-Grafana**
Goal: improve usability of the configuration section of the docs by identifying label that a set of configuration nests within, while keeping the same format/style as has been copied from Prometheus docs.

### CODE REVIEW

**Comment by KMiller-Grafana** [comment]
Marking this PR as a draft (to start).  Please comment on the wording and content for the 2 sections updated.  Once we have consensus, I'll commit the remainder of the section changes and then move this PR from draft status to open.

**Comment by 09jvilla** [comment]
Screen Shot 2021-11-19 at 7 40 38 AM

fwiw, Prometheus seems to have "fixed" this problem too.  Everything has _config in it, both the section name and the reference in the docs. 

What's nice about the prometheus docs is that you can actually click on the sections in the yaml. So you can click on "scrape_config" for example and it takes you to the "scrape_config" detailed section. 
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file

I figure it would be a painful and breaking change to rename all the headers in code from "distributor" -> "distributor_config". 

Would it be crazy to just rename all the "distributor_config" parts to just "distributor"?

**Comment by KMiller-Grafana** [comment]
@09jvilla I can rename all the (appropriate) pieces to be without the `_config` in the docs.  The change requires updates to any links that reference one of the to-be-renamed subsections.  I'll expect you to make that decision and tell me if you want the rename.

**Comment by 09jvilla** [comment]
My ideal outcome is that we just renamed the sections to include an "_config". 
For example, today we have a `limits_config` block. That is good. 
Screen Shot 2021-11-19 at 12 19 51 PM

But we have a `table_manager` block, rather than a `table_manager_config` block. 
Screen Shot 2021-11-19 at 12 19 55 PM

I'd like to rename all the sections [here](https://github.com/grafana/loki/blob/3597b16cf94a901cde2578181b32dc4463908600/docs/sources/configuration/_index.md#supported-contents-and-default-values-of-lokiyaml) so that the left side and the right side of the expression have the same text, and so that they all end in "_config" for consistency. 

@slim-bean @trevorwhitney @DylanGuedes -- WDYT? I think this is a breaking change and therefore thought it was probably out of scope at least for now. Please confirm. 

Assuming that, my proposal is instead to just make the left side and right side have the same text, by changing what's on the right side of the expression. 
Screen Shot 2021-11-19 at 12 22 54 PM

In this example, the right side goes from "querier_config" to "querier" so that it matches the left. 

WDTY?

**Comment by KMiller-Grafana** [comment]
Ok.  So I'll modify and finish this PR to have no code changes. The only thing that changes will be the docs.  It will be a separate discussion to perhaps modify the code such that we're consistent in the naming of all YAML sections to either have the `_config` piece or all not have the `_config` piece.

**Comment by 09jvilla** [comment]
perfect.

**Comment by KMiller-Grafana** [comment]
For reviewers of the PR:
There are now 2 possible places within the configuration YAML to place storage details. There is still a section called `storage_config`, and there is the `storage` section within the `common` block. There are a dozen other locations within the docs that present YAML examples that use the (older) `storage_config` to define storage.  I did not change those examples, as they would have to be refactored to use the `common` block.  I consider it out of scope for this PR to rework those examples.

**Review by 09jvilla — APPROVED** [review]
Perfecto. approved!

**Comment by DylanGuedes** [comment]
LGTM. About changing the section titles, I vote for not changing them until a major release.

**Review by DylanGuedes — APPROVED** [review]

**Review by sandeepsukhani — APPROVED** [review]
LGTM

**Pull request merged**
