### PR TITLE
docs: Replace instances of k6.io/docs with grafana.com/docs/k6

### PR DESCRIPTION
**Pull request by heitortsergent**
**What this PR does / why we need it**:

This PR updates all the links to k6.io/docs to grafana.com/docs/k6. This is part of the SEO work we're doing to try to make the Grafana version of the k6 docs to start to show up higher in search results.

I found these links by searching the website repository. Ideally, we'd update these links for all versions (v1.4.x to v1.7.x, and v2.5.x to v3.0.x).

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by jdbaldry — APPROVED** [review]
Nice! I checked all the links work too.

**Review by JStickler — APPROVED** [review]
[docs team] LGTM

**Comment by heitortsergent** [comment]
Thanks! @JStickler @jdbaldry is there anything I need to do to make sure this gets applied to all the versions that are on the website (enterprise-logs v1.4.x to v1.7.x, and loki v2.5.x to v3.0.x)?

**Comment by JStickler** [comment]
@heitortsergent I've already backported to the versions that we're keeping updated.  The database products only backport to the latest two versions.  (Currently there's an issue with merging to the 2.9 branch, but I've already pinged the engineering team about it).

**Pull request merged**
