### PR TITLE
Build logcli for mac(darwin/amd64) with CGO enabled to work around some Go DNS issues

### LINKED ISSUE #1161: logcli on OSX does not respect VPN DNS
**Describe the bug**
When connected over a VPN, on OSX, the logcli binary doesn't use the scutil resolvers configured by the vpn, instead it tries to parse /etc/resolv.conf and use the native go resolver. This is due to the way the go resolver system works on OSX.

**To Reproduce**
Connect with vpn.
use logcli
observe host not found error

**Expected behavior**
logcli connected to the appropriate server and working

Let's just cut to the resolution here, many go cli tools have suffered the same problem, including kubectl. The solution is to compile cgo support when building for darwin/osx. Here are the relevant kubectl issues:
https://github.com/kubernetes/kubernetes/issues/23130
https://github.com/kubernetes/release/issues/469
and some linked background material:
https://inconshreveable.com/04-30-2014/cross-compiling-golang-programs-with-native-libraries/

### PR DESCRIPTION
**Pull request by slim-bean**
Fixes #1161

### CODE REVIEW

**Comment by slim-bean** [comment]
@brokenjacobs would you be able to test this for us?  I don't have a VPN setup which the DNS causes this issue

Clone the loki repo and run:

```
docker run --rm -i -v `pwd`:/src/loki grafana/loki-build-image:0.7.2 dist
```

This should create a `dist` folder which has the new logcli binary in it

**Comment by brokenjacobs** [comment]
I’ll test this out tomorrow!

**Comment by brokenjacobs** [comment]
cloning master didn't get me the desired change:
```
CGO_ENABLED=0 gox -ldflags "-extldflags \"-static\" -s -w -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Branch=master -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Version=master-fa79c24 -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Revision=fa79c246 -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.BuildUser=root@87f3e3051098 -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.BuildDate=2019-10-19T15:58:05Z" -tags netgo -mod vendor -parallel=4 -output="dist/{{.Dir}}-{{.OS}}-{{.Arch}}" -osarch="linux/amd64 linux/arm64 linux/arm darwin/amd64 windows/amd64 freebsd/amd64" ./cmd/logcli
```
I'll have to get this branch.

**Comment by brokenjacobs** [comment]
I got this to compile running gox from OSX (and compiling the C bits with clang I assume).

But no joy:
```
$ CGO_ENABLED=1 gox -ldflags "-s -w -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Branch=logcli-cgo-mac -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Version=logcli-cgo-mac-e5329ce -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Revision=e5329ce8 -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.BuildUser=root@c0817939cc35 -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.BuildDate=2019-10-19T16:06:23Z" -tags netgo -mod vendor -cgo -parallel=4 -output="dist/{{.Dir}}-{{.OS}}-{{.Arch}}" -osarch="darwin/amd64" ./cmd/logcli
Number of parallel builds: 4

-->    darwin/amd64: github.com/grafana/loki/cmd/logcli
$ dist/logcli-darwin-amd64 -z UTC query --forward --no-labels --limit 10 --since 12h '{app="pachd"}'
http://loki1.k8s.ci.neoninternal.org:3100/loki/api/v1/query_range?direction=FORWARD&end=1571502122442514000&limit=10&query=%7Bapp%3D%22pachd%22%7D&start=1571458922442514000
Query failed: Get http://loki1.k8s.ci.***.org:3100/loki/api/v1/query_range?direction=FORWARD&end=1571502122442514000&limit=10&query=%7Bapp%3D%22pachd%22%7D&start=1571458922442514000: dial tcp: lookup loki1.k8s.ci.***.org on 192.168.11.20:53: no such host

$ ping loki1.k8s.ci.****.org
PING loki1.k8s.ci.****.org (10.206.28.152): 56 data bytes
```

**Comment by brokenjacobs** [comment]
Adding:
```GODEBUG="netdns=cgo+1"```
Gives this message:
```go package net: built with netgo build tag; using Go's DNS resolver```

Building without the tag:
```
CGO_ENABLED=1 gox -ldflags "-s -w -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Branch=logcli-cgo-mac -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Version=logcli-cgo-mac-e5329ce -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Revision=e5329ce8 -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.BuildUser=root@c0817939cc35 -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.BuildDate=2019-10-19T16:06:23Z" -mod vendor -cgo -parallel=4 -output="dist/{{.Dir}}-{{.OS}}-{{.Arch}}" -osarch="darwin/amd64" ./cmd/logcli
Number of parallel builds: 4

-->    darwin/amd64: github.com/grafana/loki/cmd/logcli
```
Causes dns lookups to work, but then the http requests fail to loki and logs don't display.

**Comment by brokenjacobs** [comment]
Looks like this may be necessary to integrate into the build container:
https://github.com/inconshreveable/gonative

**Comment by brokenjacobs** [comment]
@slim-bean this breaks the build, and doesn't work, see above.

**Comment by slim-bean** [comment]
This should stay open, I will try to catch back up with this next week!

**Pull request closed without merging**
