### PR TITLE
helm: Add rbac.pspAnnotations

### PR DESCRIPTION
**Pull request by hervenicol**
**What this PR does / why we need it**:

Allows to define annotations for PSPs.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [x] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Comment by QuentinBisson** [comment]
That's a great PR

**Comment by QuentinBisson** [comment]
@MichelHollands Could you take a look?

**Comment by MichelHollands** [comment]
@hervenicol Thanks for adding this feature. Can you:
- rebase and fix the merge conflicts
- For Helm chart changes bump the Helm chart version in production/helm/loki/Chart.yaml and update production/helm/loki/CHANGELOG.md and production/helm/loki/README.md. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
Once these are done I can merge this.

**Review by jeschkies — APPROVED** [review]

**Comment by hervenicol** [comment]
Rebased and updated chart version @MichelHollands @jeschkies 

Tests are failing, but at a different step at each run, and I can't see how it's related to my changes. I think it's just flaky tests :grimacing: 
Can you confirm? Should I keep re-run the tests until it passes?

**Pull request merged**
