### PR TITLE
Replace person with team for documentation reviews

### PR DESCRIPTION
**Pull request by osg-grafana**
(Internal) See https://github.com/grafana/technical-documentation/issues/520.

### CODE REVIEW

**Review by dannykopping — APPROVED** [review]
LGTM

**Comment by osg-grafana** [comment]
@dannykopping, thank you. There is a tad bit more to do, which I have described just now in the description of https://github.com/grafana/technical-documentation/issues/520. tl;dr, we need to create and add the team to the maintainers.

**Comment by dannykopping** [comment]
@osg-grafana can you please reach out to @slim-bean? Only he has permissions to do this I believe

**Comment by osg-grafana** [comment]
> @osg-grafana can you please reach out to @slim-bean? Only he has permissions to do this I believe

#7647

**Pull request merged**
