### PR TITLE
Fixed typo in Helm values docs

### PR DESCRIPTION
**Pull request by MrWong99**
**What this PR does / why we need it**:
There is a typo...

**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [x] Documentation added
- [x] Tests updated
- [x] `CHANGELOG.md` updated
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by MichelHollands — APPROVED** [review]
LGTM

**Comment by MichelHollands** [comment]
@MrWong99 Thanks for this fix. Can you rebase this? It doesn't let me merge otherwise.

**Review by jeschkies — APPROVED** [review]
Thanks. Much appreciated 😊

**Comment by MrWong99** [comment]
> @MrWong99 Thanks for this fix. Can you rebase this? It doesn't let me merge otherwise.

@MichelHollands sorry for the delay and @jeschkies thanks for the merge anyways 🙂 Feels good to see the change already in the next docs 👍🏻

**Pull request merged**
