### PR TITLE
[bugfix]  Remove hardwired '127.0.0.1' values in default addresses

### PR DESCRIPTION
**Pull request by isodude**
While running all-in-one Loki instance, it's not possible to listen on anything other than IPv4 since compactor_address is then set to http://127.0.0.1. This enables listening on only IPv6.

Also if frontent_address, scheduler_ring and scheduler_address is not set, the default value is to connect to '127.0.0.1:<grpc_listen_port'. Which means that grpc_listen_address is ignored.

**What this PR does / why we need it**:
It's not possible to use compactor while using an all-in-one instance and listening to IPv6.

Let's not ignore grpc_listen_address to not confuse users.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

As noted in the first commit, the default behavior is changed from defaulting to `127.0.0.1` to `localhost`. Not sure how major that change is though.
My /etc/hosts says
```
$ grep localhost /etc/hosts
127.0.0.1 localhost
```

**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [ ] ~~Documentation added~~
- [ ] ~~Tests updated~~
- [ ] ~~`CHANGELOG.md` updated~~
- [ ] ~~Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`~~

### CODE REVIEW

**Comment by isodude** [comment]
Sigh, why does not Github add a sign-off in their commits.

**Comment by isodude** [comment]
Seems that compactor_client is not possible to configure though.
https://github.com/isodude/loki/blob/c6b55e75122ae0761102395651a4da647c639039/pkg/loki/loki.go#L78

**Comment by isodude** [comment]
> Seems that compactor_client is not possible to configure though. https://github.com/isodude/loki/blob/c6b55e75122ae0761102395651a4da647c639039/pkg/loki/loki.go#L78

Actually, running with `target: all` that works as well.
I am now getting logs back when sending a query.

**Comment by isodude** [comment]
For those in the dark I am running with client certificates, to ensure that the compactor_client connects with the proper information one needs the above patch and this config:
```
target: all
server:
  http_listen_address: "[${IPV6}]"
  http_listen_port: 443
  http_tls_config:
    cert_file: ${CREDENTIALS_DIRECTORY}/default.crt
    key_file: ${CREDENTIALS_DIRECTORY}/default.key
    client_auth_type: RequireAndVerifyClientCert
    client_ca_file: ${CREDENTIALS_DIRECTORY}/ca.crt
compactor_client:
  tls_enabled: true
  tls_cert_path: ${CREDENTIALS_DIRECTORY}/default.crt
  tls_key_path: ${CREDENTIALS_DIRECTORY}/default.key
  tls_ca_path: ${CREDENTIALS_DIRECTORY}/ca.crt
  tls_server_name: "${HOSTNAME}"
common:
  compactor_address: "[${IPV6}]"
```

**Review by chaudum — APPROVED** [review]

**Comment by isodude** [comment]
Shall I do the same here, in the same PR?
https://github.com/grafana/loki/blob/c3e92b876c9a2079a9989c3954f420336e3c8182/pkg/querier/worker_service.go#L115

**Comment by chaudum** [comment]
> Shall I do the same here, in the same PR?
> 
> https://github.com/grafana/loki/blob/c3e92b876c9a2079a9989c3954f420336e3c8182/pkg/querier/worker_service.go#L115

Good catch! Yes, you can do it on the same PR. Make sure you change the PR title, otherwise it may get confusing.

**Comment by isodude** [comment]
> > Shall I do the same here, in the same PR?
> > https://github.com/grafana/loki/blob/c3e92b876c9a2079a9989c3954f420336e3c8182/pkg/querier/worker_service.go#L115
> 
> Good catch! Yes, you can do it on the same PR. Make sure you change the PR title, otherwise it may get confusing.

Sure! I'm testing out the patch right now.

**Comment by isodude** [comment]
> > Shall I do the same here, in the same PR?
> > https://github.com/grafana/loki/blob/c3e92b876c9a2079a9989c3954f420336e3c8182/pkg/querier/worker_service.go#L115
> 
> Good catch! Yes, you can do it on the same PR. Make sure you change the PR title, otherwise it may get confusing.

PR updated and commit force pushed.

I changed the commit message of the first commit.

**Comment by chaudum** [comment]
> As noted in the first commit, the default behavior is changed from defaulting to 127.0.0.1 to localhost. Not sure how major that change is though.

That should not cause any problems.

@isodude May I ask one last change before merging: Could you add a changelog entry under Loki / Fixes, stating something like this: "Fix default values of connect addresses for compactor and querier workers to work with IPv6"

**Comment by isodude** [comment]
> @isodude May I ask one last change before merging: Could you add a changelog entry under Loki / Fixes, stating something like this: "Fix default values of connect addresses for compactor and querier workers to work with IPv6"

Sounds fine. Pushed.

**Comment by chaudum** [comment]
@isodude Thanks for your contribution!

**Pull request merged**
