### PR TITLE
Remove unused querier base.

### PR DESCRIPTION
**Pull request by jeschkies**
**What this PR does / why we need it**:
This change removed unused code from the base querier that have been imported from Cortex. Only the base ruler tests depend on the querier.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by jeschkies** [comment]
@dannykopping and @owen-d this PR is blocked on fixing the base ruler test. Should we rather move the tests to the ruler? The base querier is only used by the base ruler. And the base ruler is warpped by the Loki ruler which does not have any tests. So I'm reluctant to remove the base ruler tests...

**Comment by dannykopping** [comment]
@jeschkies can you please add a description to the PR? I've got no context on what this is about or why we need this

**Comment by dannykopping** [comment]
I've removed myself as a reviewer as I'm getting notified about this PR every couple days, and it seems to still be in draft.
Feel free to add me again once you're ready

**Comment by jeschkies** [comment]
Superseded by #5633

**Pull request closed without merging**
