### PR TITLE
Fix wrong file reference in Promtail mixin

### LINKED ISSUE #4477: Missing file / wrong reference in promtail-mixin
**Describe the bug**
Building the promtail dashboard(s) doesn't work, because there is no file "dashboard-utils.libsonnet" anywhere in the "promtail-mixin" folder. This reference seems to be wrong:
https://github.com/grafana/loki/blob/6498c8cb1344c6212c2c135da090a98ba9e34775/production/promtail-mixin/dashboards.libsonnet#L3 

Manually copying the "dashboard-utils.libsonnet" from the "loki-mixin" and / or changing the reference is needed for the build to succeed.

**To Reproduce**
`mkdir test; cd test; jb init; jb install https://github.com/grafana/loki/production/promtail-mixin@main; mkdir dashboards; jsonnet -J vendor -m dashboards -e '(import "vendor/promtail-mixin/mixin.libsonnet").grafanaDashboards'`

**Expected behavior**
Dashboards can be build without error message. Copying files or changing references should not be needed.

**Environment:**
Ubuntu 20.04

**Terminal output**
```
RUNTIME ERROR: couldn't open import "loki-mixin/dashboards/dashboard-utils.libsonnet": no match locally or in the Jsonnet library paths.
        vendor/promtail-mixin/dashboards.libsonnet:3:26-82      thunk <loki_mixin_utils>
        vendor/promtail-mixin/dashboards.libsonnet:8:7-23       thunk <dashboard>
        vendor/promtail-mixin/dashboards.libsonnet:38:5-14      object <anonymous>
        During manifestation
```

### PR DESCRIPTION
**Pull request by DaveOHenry**
**What this PR does / why we need it**:
Fixes a wrong file reference / Makes people happy, because they can build the Promtail dashboard without errors.

**Which issue(s) this PR fixes**:
Fixes #4477 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by dannykopping** [comment]
Thanks for this @DaveOHenry! It looks like you're duplicating the file from `production/loki-mixin/dashboards/dashboard-utils.libsonnet`, correct? I wonder if we can instead move this dashboard into a common location so it can be used by both the `promtail-mixin` and `loki-mixin`.

**Comment by DaveOHenry** [comment]
I thought the same, but then it should be done for the cortex, tempo and loki mixins as well:
https://github.com/search?p=3&q=org%3Agrafana+dashboard-utils&type=Code

**Comment by DaveOHenry** [comment]
What about simply adding the Loki mixin as dependency?

**Review by jeschkies — APPROVED** [review]

**Comment by DaveOHenry** [comment]
Superseded by #4848

**Comment by jeschkies** [comment]
@DaveOHenry sorry that I didn't pick up your fix. I vaguely remembered your issue but didn't think about it when I enabled linting. Anyhow, your issue and PR triggered me to create the CI job.

**Pull request closed without merging**
