### PR TITLE
sync with Cortex v0.3.0-rc.0 and resolve conflict

### LINKED ISSUE #1033: Prometheus version conflict with Cortex
**Describe the bug**
After sync with Cortex through `dep ensure -v -update github.com/cortexproject/cortex`, Loki build will have problem in `engine.go`. 

The reason is that Cortex used a new version of Prometheus, please find diff sample in https://github.com/prometheus/prometheus/blob/master/pkg/labels/labels.go#L158 vs https://github.com/grafana/loki/blob/master/vendor/github.com/prometheus/prometheus/pkg/labels/labels.go#L153.

Seems Loki is out of update with latest Cortex for quite a long time.
```
if v.grouping.without {
				groupingKey = metric.HashWithoutLabels(v.grouping.groups...)
			} else {
				groupingKey = metric.HashForLabels(v.grouping.groups...)
			}
```

This breaks all the syncing with Cortex. Seems everyone will meet this issue if he want to do any code change in Cortex and port it back.

**To Reproduce**
1. Run below command
```
dep ensure -v -update github.com/cortexproject/cortex
```

**Expected behavior**
Update Cortex should not have conflict.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, promtail config, or terminal output**
If applicable, add any output to help explain your problem.

### PR DESCRIPTION
**Pull request by mizeng**
**What this PR does / why we need it**:
Sync with Cortex and fix conflict, so it will not break Loki build.

**Which issue(s) this PR fixes**:
Fixes #1033 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by mizeng** [comment]
@cyriltovena Could you help to review?

**Comment by mizeng** [comment]
what's CI go version? I see this error:
```
#!/bin/bash -eo pipefail
make BUILD_IN_CONTAINER=false test
>> writing assets
GOOS=linux go generate -x -v ./pkg/promtail/server/ui
pkg/promtail/server/ui/assets_vfsdata.go
pkg/promtail/server/ui/doc.go
go run -tags=dev assets_generate.go
writing assets_vfsdata.go
CGO_ENABLED=1 go build -ldflags "-s -w -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Branch=pull/1047 -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Version=pull-1047-75adaee -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.Revision=75adaee2 -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.BuildUser=root@7f45bd800e3d -X github.com/grafana/loki/vendor/github.com/prometheus/common/version.BuildDate=2019-09-24T01:24:56Z" -tags netgo -o cmd/promtail/promtail ./cmd/promtail
# github.com/grafana/loki/vendor/github.com/prometheus/prometheus/tsdb/goversion
vendor/github.com/prometheus/prometheus/tsdb/goversion/init.go:17:9: undefined: _SoftwareRequiresGOVERSION1_12
```

google showed it should be related to GO version under 1.12?

**Comment by cyriltovena** [comment]
@gouthamve is cortex using 1.12 now ?

**Comment by mizeng** [comment]
I think it is using go 1.13 now.. https://github.com/cortexproject/cortex/commit/9d6c4d122bae4423410ec69853f6caf92b3f2f9c

**Comment by cyriltovena** [comment]
We will have to wait for #1062

**Comment by mizeng** [comment]
@cyriltovena rebased with latest Loki code, could you plz help review again?

**Comment by mizeng** [comment]
btw, I don't understand why "build/promtail-windows" failed and how to resolve.

**Comment by cyriltovena** [comment]
I would prefer to wait for  the final 0.3

**Comment by mizeng** [comment]
make sense

**Comment by cyriltovena** [comment]
0.3 is out @mizeng if you want to resume the work.

**Comment by mizeng** [comment]
@cyriltovena seems no need. Loki works well with Cortex v0.3.0, seems someone fixed the conflict.

**Pull request closed without merging**
