### PR TITLE
Helm: fix egress-dicovery netpols

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
**What this PR does / why we need it**:

This PR fix an issue happening when deploying the `egress-discovery` networkPolicy or ciliumNetworkPolicy. When one wants to deploy the `egress-discovery` netpol, one only has to specify the `networkPolicy.discovery.port` field in the values. However, with the current state of the templates, when this field is specified, **both** the networkPolicy and the ciliumNetworkPolicy are generated since the only condition for their creation is `if .Values.networkPolicy.discovery.port`. 

I thus added an additional condition : `eq .Values.networkPolicy.flavor "cilium"` (or `"kubernetes"` for the networkPolicy) so that only one of these is generated according to the `flavor` specified in the values.

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [x] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Nice finding

**Comment by QuentinBisson** [comment]
@MichelHollands would you have the time to review this PR?

**Comment by QuentinBisson** [comment]
Hey @JStickler do you know if another maintainer could help us get this merged? This is blocking us at the moment and the change looks quite small :)

**Review by MichelHollands — APPROVED** [review]
LGTM

**Pull request merged**
