### PR TITLE
Move from dep to go modules

### PR DESCRIPTION
**Pull request by gouthamve**
Need some automation around this in Makefile. I'll do that, if this move is okay.

### CODE REVIEW

**Comment by daixiang0** [comment]
I also look into it :)
please take a look at [this](https://github.com/golang/go/issues/30161)

**Comment by tomwilkie** [comment]
Happy to move to go modules, but probably want to move cortex first.

**Comment by vtolstov** [comment]
cortex moved to go modules. https://github.com/cortexproject/cortex/pull/1303

**Comment by vtolstov** [comment]
it will be cool to move loki to go modules too, for easy building and integrating.

**Comment by vtolstov** [comment]
does this superseeded by #571  ?

**Pull request closed without merging**
