### PR TITLE
Feat: Allow filename as source to add custom label from __path__

### LINKED ISSUE #775: Promtail: Cant get the value of filename in relabel_configs
In relabel_configs, I would like to get the filename label value to rewrite to a specific label.

For instance, there are some log files in the directory.
- /logs/example-out.log
- /logs/example-error.log

I expect set a label called "service" equal to "example"

Then, I have the setting below in the relabel_configs of promtail

```yaml
static_configs:
- targets:
    - localhost
  labels:
    job: test
    __path__: /logs/*.log
relabel_configs:
- source_labels: [filename]
  regex: '^.*\/(.+)-(out|error)\.log$'
  replacement: '${1}'
  target_label: service
  action: replace
```

I have tested "filename" and "__path__" into the source_labels.

There is no value return when source_labels set to "filename".  
When the source_label set to "__path__", the value equals to "/logs/*.log" 

How can i get the correct file path in relabel_configs?

### PR DESCRIPTION
**Pull request by adityacs**
**what this PR does?**

Allow filename as source to add custom label from __path__

**Which issue(s) this PR fixes**:
Fixes #775 

@cyriltovena @sandlis I am not sure if this change is a good way to handle the issue described in #775 but I couldn't think of anything better than this. Let me know your thoughts.

### CODE REVIEW

**Comment by slim-bean** [comment]
I think the approach I would rather take for this is to add `label` as another key along side `source` in the regex stage such that you could use any label as an input to the stage

**Comment by adityacs** [comment]
@slim-bean Makes sense. Have made the changes. Kindly review. If this is fine, I will fix tests and modify the docs.

**Comment by cyriltovena** [comment]
Can you check if the full filename is part of labels coming in ?

**Comment by adityacs** [comment]
@cyriltovena I am just checking this `sourceInput := string(labels[model.LabelName(*r.cfg.Source.Label)])`. So, input label can be anything .Also, `filename` would be anyway expanded by promtail before pipelinestage begins

**Comment by cyriltovena** [comment]
Yeah I'm not too keen on breaking the configuration right now. @slim-bean should we just merge extracted with labels coming in ?

**Comment by adityacs** [comment]
@cyriltovena 
> Yeah I'm not too keen on breaking the configuration right now
  Makes sense. 

Any approach is fine to me. Let know, I will push my changes accordingly.

**Comment by slim-bean** [comment]
Yeah I'm going to have to agree on not wanting to make a breaking config change.

I am debating if there are any disadvantages to having `source` look both at labels and the extractedMap.

The most obvious would be naming collisions between data in the extracted map and labels, and which takes precedence.  

I am thinking because such collisions are easily controlled by the person creating the config, it would make sense if `source` could pull from both labels and extractedMap, that the value in the extractedMap would take precedence.  

Or put another way, source would check for a matching label if nothing was found in the extractedMap.

I am going to sleep on it and hopefully not change my mind tomorrow, but I'm thinking right now lets just keep source the way it is in config, but in the implementation first look in the extractedMap and if nothing is found, look for a label.

**Comment by adityacs** [comment]
@slim-bean
> Or put another way, source would check for a matching label if nothing was found in the extractedMap.
 
have made changes accordingly. Kindly review.

**Comment by cyriltovena** [comment]
Can you update the documentation ? or give a hint about this new way of working for the source parameter ?

Thanks !

**Comment by adityacs** [comment]
Closing this PR in favour of #1122

**Pull request closed without merging**
