### PR TITLE
fix: fix setting of info log level when trying to detect level from log lines

### PR DESCRIPTION
**Pull request by sandeepsukhani**
**What this PR does / why we need it**:
I made a mistake while setting log level for info logs with logfmt/json format. This PR fixes it.

### CODE REVIEW

**Review by trevorwhitney — APPROVED** [review]

**Comment by maetolay** [comment]
Please rollout this version soon, this bug affecting our production logs

**Comment by tanadeau** [comment]
Could we get a 3.x release with this fix soon?

**Comment by kjq** [comment]
When will the Loki Helm charts be updated?  We just updated with Helm v6.5.1 (v3.0.0) and it still shows the wrong log-level (i see it is tagged for a 3.1.x release)

**Comment by kjq** [comment]
Is there an ETA on when this will be merged in?  It was fixed 3 weeks ago and the latest Loki does not reflect the changes so the image tag version in the Helm charts cannot even be updated.

**Comment by Usergitbit** [comment]
Still hasn't been released?

**Pull request merged**
