### PR TITLE
docs: Update Kubernetes terminology in setup/install/helm/reference.md

### LINKED ISSUE #11944: Use correct Kubernetes terminology throughout documentation
For example, _Pod_ not _pod_ and _Deployment_ not _deployment_.

https://grafana.com/docs/writers-toolkit/write/style-guide/capitalization-punctuation/#kubernetes-objects

### PR DESCRIPTION
**Pull request by edsoncelio**
**What this PR does / why we need it**:
Update docs to use the correct Kubernetes terminology.
https://grafana.com/docs/writers-toolkit/write/style-guide/capitalization-punctuation/#kubernetes-objects

**Which issue(s) this PR fixes**:
Fixes #11944 

**Special notes for your reviewer**:
Command to check using vale:
```
vale --filter='.Name =="Grafana.Kubernetes"' docs/sources/setup/install/helm/reference.md
```

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by edsoncelio** [comment]
> Thank you for this contribution and for reading through our style guide!
> 
> It's great to have the style guide propagating through our docs, the consistency will surely make them easier to read :)
> 
> I'll let the Loki technical writer double check the changes.
Thanks!

I'm in doubt in this PR because looks like this file is generated automatically (or almost that) running a command instead of manually created.

Based on that error:
`Please generate Helm Chart reference by running 'make -C docs sources/setup/install/helm/reference.md'`

**Comment by JStickler** [comment]
@edsoncelio Did you edit this file directly? Or was this change automatically generated? The Helm reference should be updated in production/helm/loki/reference.md.gotmlp. There's a note to that effect at line 11 of the docs/sources/setup/install/helm/reference.md. file, you might have missed it.

Also any Helm changes (even documentation) requires that you bump the Helm chart version in production/helm/loki/Chart.yaml and update production/helm/loki/CHANGELOG.md and production/helm/loki/README.md. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

**Comment by edsoncelio** [comment]
> @edsoncelio Did you edit this file directly? Or was this change automatically generated? The Helm reference should be updated in `production/helm/loki/reference.md.gotmlp`. There's a note to that effect at line 11 of the `docs/sources/setup/install/helm/reference.md` file, you might have missed it.
> 
> Also any Helm changes (even documentation) requires that you bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

Hi!
I've edited it directly. 
Thanks for clarifying I missed the note.
I'll update the PR during the week :)

**Comment by JStickler** [comment]
Thanks.  And don't be surprised if you have to update the Helm version more than once.  It depends on how many Helm updates we have on any given day.

**Comment by edsoncelio** [comment]
I'll close this PR and open a new with the updated branch :)

**Pull request closed without merging**
