### PR TITLE
added mount to docker-driver config

### PR DESCRIPTION
**Pull request by tonycox**
related to:
https://github.com/grafana/loki/issues/694
https://github.com/grafana/loki/issues/700

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by tonycox** [comment]
As I'm not sufficient good in Go - I ve just proposed this change

**Comment by cyriltovena** [comment]
Can you explain how to use this ? I think I have an idea but I would like to see what was your plan.

**Comment by tonycox** [comment]
currently I need to do this trick while deploying my app with docker
`
LOKI_ID=$(sudo docker plugin inspect -f '{{.Id}}' loki); echo $ID)
sudo rm -rf /var/lib/docker/plugins/$LOKI_ID/rootfs/opt/tool; mkdir -p /var/lib/docker/plugins/$LOKI_ID/rootfs/opt/tool
cp docker/loki-pipeline.yml /var/lib/docker/plugins/$LOKI_ID/rootfs/opt/tool/loki-pipeline.yml
`
It would be better to specify visible folders for plugin in env configuration scripts. for example workspace of an app.

`/var/log` is just a placeholder - it can be empty or more general.

**Comment by cyriltovena** [comment]
how can it be empty ? where will you put your file after  ? I think this need a bit of documentation.

**Comment by tonycox** [comment]
for file on my local env /folder/sub/pipeline.yml 
I'll set to the source param by 
```
docker plugin set loki mount.source=/folder/sub
```
and then I'll set 
```
docker run --log-driver=loki \
    ...
    --log-opt loki-pipeline-stage-file=pipeline.yml
```

**Comment by cyriltovena** [comment]
Yeah I think this is good, I would like a bit of documentation on the usage in the PR if you don't mind.

**Comment by tonycox** [comment]
Ok, I'll take time to generate details in the PR

**Comment by cyriltovena** [comment]
That would be great to do a step by step on how to mount the config.

- disable the plugin.
- etc...

**Comment by iabughosh** [comment]
Dears,
I tried the below command : 
`docker plugin set loki mount.source={my-path}`
But I've received this error : 
`Error response from daemon: setting "mount" not found in the plugin configuration`

I am using the latest loki-docker-driver plugin and my docker version is 19.03.8 OS MacOs.

**Comment by m0rtalis** [comment]
Can this be added? I think @mfut did basically all the work in his PR maytech/loki#1

**Pull request closed without merging**
