### PR TITLE
Allow environment variables for scrape_configs

### PR DESCRIPTION
**Pull request by base698**
https://github.com/grafana/loki/issues/319

### CODE REVIEW

**Comment by davkal** [comment]
@slim-bean this PR is stalling a bit. Got feedback?

**Comment by garo** [comment]
If I understood correctly this allows one to inject labels to the scrape_configs based on Promtail environment variables, which is a nice feature to add. Hope to get this merged =)

**Comment by base698** [comment]
Yeah that was the idea.

**Comment by Kuqd** [comment]
Closing in favor of https://github.com/grafana/loki/pull/510

**Pull request closed without merging**
