### PR TITLE
[helm] Fix tracing configuration

### PR DESCRIPTION
**Pull request by QuentinBisson**
**What this PR does / why we need it**:

This PR allows user to enable tracing in the new SSD setup and fixes incorrect documentation because it is currently impossible to enable tracing in this chart (cf. https://github.com/grafana/loki/blob/766f27645d2610a36eaaca8418482b740ae14215/cmd/loki/main.go#L81)

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by QuentinBisson** [comment]
@MichelHollands could you please take a look ?

**Comment by JStickler** [comment]
Hi @QuentinBisson, thanks for your contribution.  Please note this line in the PR checklist (For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`.).  You need to updated the version in the chart.yaml, but also need to update the CHANGELOG and README.

**Comment by QuentinBisson** [comment]
Thanks i'll take a look :)

**Comment by QuentinBisson** [comment]
@JStickler is looks better now :)

**Comment by QuentinBisson** [comment]
@JStickler do you know who could help review that ?

**Comment by QuentinBisson** [comment]
@dannykopping could you take a look at this PR ?

**Review by MichelHollands — APPROVED** [review]
LGTM

**Pull request merged**
