### PR TITLE
loki-mixin: Fix selector configuration in chunks dashboard

### PR DESCRIPTION
**Pull request by DaveOHenry**
**What this PR does / why we need it**:
#4850 introduced some changes, but it looks like it's no longer possible to configure the chunks dashboard now. Somehow overriding the `local labelsSelector = ...` definition doesn't work as expected (or I simply don't know how to do it).

This PR makes the selector configurable via a hidden field again and also fixes a hardcoded query.

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by jeschkies** [comment]
@cstyan should take a look but he's out for now. I don't have enough context. I'm sorry.

**Comment by DaveOHenry** [comment]
No problem 😃 I don't understand how it is supposed to work as all other dashboards can somehow be configured. 
The promtail-mixin currently has the same issue and I'd like to also create a PR for that, but I guess we should wait for clarification first.

**Comment by cstyan** [comment]
Hi Dave, can you give me some more context regarding your use case and what additional labels you're wanting to add in to the labels selectors in this dashboard?

Personally I was planning to remove such configurability of the labels selector. In most of the jsonnet dashboards within the mixin the configurability complicates the jsonnet code and is done in a way that reads strangely. I'd like to get consensus from some others on whether we should have configurability of the labels selectors for each dashboard, or none.

If we keep the configurability we should check how else we can do so, I really dislike the usage of fields via `dashboards[<dashboard-name>].field` such as ```$.queryPanel('sum(loki_ingester_memory_chunks{%s})' % dashboards['loki-chunks.json'].labelsSelector, 'series')```.

**Comment by DaveOHenry** [comment]
Hi cstyan. My use case is described in more detail in #4838.
Basically our "cluster" label is called "monitoring_stack" and the job names are not in the "($namespace)/$job" format. 

I agree that the current state of the mixin is not ideal, but it's better than to have no configurability at all. What is the point of a mixin when it can not be configured?

**Comment by DaveOHenry** [comment]
Dear stale bot. Please keep this issue open.

**Comment by DaveOHenry** [comment]
superseded by #5535 #5536

**Pull request closed without merging**
