### PR TITLE
Add loki.frontend to config

### LINKED ISSUE #8414: loki frontend: Make loki frontend config block configurable
**Is your feature request related to a problem? Please describe.**
Currently there is no template for the [frontend configuration block](https://grafana.com/docs/loki/latest/configuration/#frontend) in the loki values under `loki.config`.

**Describe the solution you'd like**
An include for `frontend` configuration should be added to the `loki.config` template. 

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by ldawert-sys11**
**What this PR does / why we need it**:
Adds frontend configuration to loki.config and also adds empty default value.

**Which issue(s) this PR fixes**:
Fixes #8414

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [x] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by chaudum — CHANGES_REQUESTED** [review]
Generally LGTM
Can you please also add a changelog entry describing the new ENHANCEMENT?

**Comment by ldawert-sys11** [comment]
> Generally LGTM Can you please also add a changelog entry describing the new ENHANCEMENT?

Changelog updated in new commit.

**Comment by chaudum** [comment]
@ldawert-sys11 Sorry for the late reply. Could you please rebase your branch, in the meantime 4.7 of the chart was released.

**Comment by ldawert-sys11** [comment]
> @ldawert-sys11 Sorry for the delayed reply. Could you please rebase your branch, in the meantime 4.7 of the chart was released.

done, @chaudum

**Comment by MasslessParticle** [comment]
There has been no activity on this for four months. Closing for inactivity

**Pull request closed without merging**
