### PR TITLE
Promtail: update certificates used for syslog’s tests

### LINKED ISSUE #6527: Recreate SSL certs used by Promtail tests
**Is your feature request related to a problem? Please describe.**
We had to recently disable a bunch of tests in https://github.com/grafana/loki/pull/6520 to get around a CI failure in a hurry.

**Describe the solution you'd like**
We should regenerate these with an expiry of like 10 years (or more if you're bullish on the lifespan of Promtail :trollface:)

**Describe alternatives you've considered**
Leaving the tests disabled, but that's not ideal

**Additional context**
@johanfleury you introduced these tests in #3907 (thanks!). Would you like to do the honours of renewing these certs (but please pick a longer expiry this time hehe)?

### PR DESCRIPTION
**Pull request by johanfleury**
**What this PR does / why we need it**:

Update certificates used for syslog’s tests

All the certificates now have a 20 year lifetime.

This reverts commit 2fc20af9a4e55483afe0f09f8a8119ab380daea9.

**Which issue(s) this PR fixes**:

Fixes #6527

**Special notes for your reviewer**:

I included the CA key in case someone wants to generate new cert (or regen existing ones) without regenerating everything.

The certificates were generated using [cert-manager](https://cert-manager.io/). Here are the full manifests:

```
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: promtail-test-ca
spec:
  secretName: promtail-test-ca-certificate
  duration: 175320h # 20 years
  commonName: Promtail Test Root CA
  isCA: true
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: promtail-test-ca
spec:
  ca:
    secretName: promtail-test-ca-certificate

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: promtail-test-client
spec:
  secretName: promtail-test-client-certificate
  duration: 175320h # 20 years
  commonName: Promtail Test Client Certificate
  privateKey:
    algorithm: RSA
    size: 4096
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    kind: Issuer
    name: promtail-test-ca

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: promtail-test-server
spec:
  secretName: promtail-test-server-certificate
  duration: 175320h # 20 years
  commonName: Promtail Test Server Certificate
  privateKey:
    algorithm: RSA
    size: 4096
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "promtail.example.com"
  issuerRef:
    kind: Issuer
    name: promtail-test-ca
```

**Checklist**

- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by johanfleury** [comment]
CI failed, but I don’t think it’s related to my PR. Can someone re-run the failed job please?

**Comment by dannykopping** [comment]
> CI failed, but I don’t think it’s related to my PR. Can someone re-run the failed job please?

@johanfleury thanks for the PR!
The lint failure is related to your changes, I believe: https://drone.grafana.net/grafana/loki/13340/2/9

The other failures look like garbage, I'll sort that out if CI breaks again after your lint fixes.

**Comment by johanfleury** [comment]
I think you're looking at a previous CI job. I fixed the lint issue, now it's lint-jsonnet that fails.

**Review by DylanGuedes — APPROVED** [review]
lgtm

**Review by dannykopping — APPROVED** [review]
LGTM, thanks for jumping in so quickly to assist with this @johanfleury :raised_hands:

**Pull request merged**
