### PR TITLE
Correct parameter name in README.md

### PR DESCRIPTION
**Pull request by jeffqumata**
Fixes a typo in the parameter name. 

See https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L600

### CODE REVIEW

**Review by chaudum — APPROVED** [review]
Thanks for spotting and fixing this!

**Comment by kavirajk** [comment]
@jeffqumata can you rebase the branch?. CI fails for some unrelated changes.

**Comment by jeffqumata** [comment]
@kavirajk rebased but I still see one failing job. Not sure if this is expected or not.

**Comment by chaudum** [comment]
@jeffqumata Sorry for asking you again to rebase.

**Comment by jeffqumata** [comment]
@chaudum done. :crossed_fingers:

**Comment by chaudum** [comment]
@jeffqumata Sorry for the confusion. 
The change you made to the README actually needs to go into `README.md.gotmpl` instead. Then you run `docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.8.1` to generate the `README.md`. You need to commit both.

**Pull request closed without merging**
