### PR TITLE
Add fallback_formats for timestamp stage

### PR DESCRIPTION
**Pull request by aminjam**
**Which issue(s) this PR fixes**:
Fixes grafana/loki#2590

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

**Review by cyriltovena — APPROVED** [review]
LGTM

@slim-bean if you're ok with the name of the property I let you merge it.

**Comment by cyriltovena** [comment]
@aminjam in the meantime can you sign the CLA ?

**Review by sandeepsukhani — APPROVED** [review]
LGTM. Thanks for the PR!

**Comment by slim-bean** [comment]
Hi @aminjam would love to merge this but we need to get the CLA "signed".

If you've "signed" it and it fails, this is usually because the email address in your commit doesn't match any in your github account.

Fixing this usually requires amending the commit with an email address you have in github and force pushing back to your branch.

Let me know if you have any questions or problems!

**Comment by aminjam** [comment]
Thank you all for your patience. I have been working through getting the authorization to sign the CLA. I hope to have more updates on the progress this week.

**Comment by slim-bean** [comment]
Nice thanks again @aminjam!

**Pull request merged**
