### PR TITLE
scheduler: use 'loki' prefix in metrics rather than 'cortex'

### LINKED ISSUE #5094: Rename scheduler metrics such as cortex_query_scheduler_queue_length to have loki related prefix
**Is your feature request related to a problem? Please describe.**
Currently the query-scheduler has metrics that start with `cortex_query_scheduler_`. This software is loki, not cortex.

**Describe the solution you'd like**
Change the prefix to e.g. `loki_query_scheduler_`.

**Additional context**
e.g. https://github.com/grafana/loki/blob/6ef934b24c695ed5a7872d212552265d82b303a7/pkg/scheduler/scheduler.go#L153

### PR DESCRIPTION
**Pull request by james-callahan**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #5094

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by dannykopping** [comment]
Thanks for the PR @james-callahan. I think we're a bit reticent to rename the metrics as this could cause issues for folks (alerts might misfire or not fire at all, dashboards will break, etc). It's a real pity that Prometheus doesn't support some kind of metric aliasing.

If we're going to do this, we should do it across the board, and not just for the scheduler IMO. Interested to hear what my fellow maintainers think.

image

**Comment by DylanGuedes** [comment]
> Thanks for the PR @james-callahan. I think we're a bit reticent to rename the metrics as this could cause issues for folks (alerts might misfire or not fire at all, dashboards will break, etc). 

+1 for not renaming it right now. Anyway, maybe we can accumulate and rename all `cortex_X` metrics for 3.x and list the changes in the upgrading guide? :thinking:

**Comment by owen-d** [comment]
Hey James, thanks for the PR. Unfortunately, I think we'll need to do the rest of these metrics all at once, _and_ update all dashboards/etc to use the correct metrics.

**Comment by dannykopping** [comment]
Seems we're in agreement; closing this for now.
Thanks for getting the conversation started @james-callahan :+1:

**Comment by james-callahan** [comment]
Given the query scheduler is a new component without documentation, IMO it would seem best to make this change as soon as possible: I do no think there are many users yet, and I doubt anyone has really built out monitoring yet.

**Pull request closed without merging**
