### PR TITLE
updated versions to the latest release v2.7.1

### LINKED ISSUE #7768: Upgrade version in ksonnet to the latest release 2.7.0
**Describe the bug**
Loki deployed with Tanka in microservices mode still uses 2.6.1

**Expected behavior**
Loki deployed with Tanka should use version 2.7.0

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: jsonnet

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

### PR DESCRIPTION
**Pull request by irizzant**
Signed-off-by: irizzant <i.rizzante@gmail.com>

**What this PR does / why we need it**:
This PR updates Loki version to v2.7.1

**Which issue(s) this PR fixes**:
Fixes #7768

**Special notes for your reviewer**:

**Checklist**
- [X] Reviewed the `CONTRIBUTING.md` guide
- [X] Documentation added
- [X] Tests updated
- [X] `CHANGELOG.md` updated
- [X] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by kavirajk — APPROVED** [review]
Thanks @irizzant :+1: 

can you add the regexp/glob pattern you used to find and replace this versions in different places to the PR description? Would be nice  reference when doing it for later versions (or when we want automate to script)

**Comment by irizzant** [comment]
@kavirajk I've searched for 2.6.1 in all `*.hcl,*.yaml,*sonnet,docker.md,README.md` files and then replaced with 2.7.1

**Comment by irizzant** [comment]
@kavirajk is there anything else needed to merge this PR?

**Comment by MichelHollands** [comment]
@irizzant Thanks for updating this. I've restarted the CI. Did you sign the license?

**Comment by irizzant** [comment]
@MichelHollands I've contributed to Loki before and all the commits are signed-off , what am I supposed to do?

**Comment by MichelHollands** [comment]
> @MichelHollands you're most welcome. I've contributed to Loki before and all the commits are signed-off , what am I supposed to do?

Looks like there was a hitch with the license check. Can you go to the URL https://cla-assistant.io/check/grafana/loki?pullRequest=7940 to sign it manually?

Without the license sign off we can't accept outside contributions I'm afraid.

**Comment by irizzant** [comment]
@MichelHollands  I see that now all checks passed

**Pull request merged**
