### PR TITLE
RFC: Release Cadence

### PR DESCRIPTION
**Pull request by dannykopping**
This PR adds a Request For Comment (RFC) for a release cadence proposal.

We invite the community to provide feedback.

We ask that you please keep the feedback substantive; comments like "i don't like this" are not very useful; please provide specific detail and make suggestions on what can be improved/changes.

### CODE REVIEW

**Comment by james-callahan** [comment]
>  - **[MINOR](https://semver.org/#spec-item-7)** releases: around **once a quarter**

I think holding back a minor release with a useful feature in it because "it's not time yet" isn't a positive trait: if there is a new feature merged, why not make a release sooner rather than later?

**Comment by dannykopping** [comment]
> > * **[MINOR](https://semver.org/#spec-item-7)** releases: around **once a quarter**
> 
> I think holding back a minor release with a useful feature in it because "it's not time yet" isn't a positive trait: if there is a new feature merged, why not make a release sooner rather than later?

There is a clause just above it which states:

> The below are our proposals for the target times between releases; we might release sooner if the severity warrants it.

Maybe I should replace "severity" with "priority". Would that then communicate the sentiment a bit more clearly, do you think?

**Comment by james-callahan** [comment]
> Maybe I should replace "severity" with "priority". Would that then communicate the sentiment a bit more clearly, do you think?

To take an extreme position: why would the smallest relatively insignificant new feature deserve an immediate release. I think probable answers are:
  - It takes time to do the release process
    e.g. because the release process has manual steps; or there's a significant "pre-release" QA process
  - worried about version number explosion

But to be just slightly more reasonable: why not a minor release e.g. once a week?

**Comment by periklis** [comment]
Look on this I have to say first that this is an good start and finally a good point in time to involve the community. Thank you @dannykopping writing this down. :rocket: 

My comments on improving this document are:
1. I suggest to add a section about handling deprecations. Across the 1.x and 2.x lines we have certainly pilled up config knobs and operating modes that we might want to discuss deprecating. How long to users have to expect that deprecations hold? Removing deprecations usually have an impact on rolling out new releases on production environments and/or add upgrade procedures into the loki-operator and helm charts. From the loki-operator perspective it is easy to pin the version till we've done the job, but helm chart users might need to be aware of the deprecation schedule before bumping a version in a variable.
2. The patch release cadence sounds super aggressive to me and if I count correctly we will have 3 active minor releases at a time supporting patch-releases every two weeks. That counts up to 6 patch releases every second week if and only if we have content to release. Is this currently possible in regards of CI resources and release management bookkeeping?
3. FWIW we should add a section about supporting features that are currently only available behind feature gates. Planning and executing long-term changes (e.g. TSDB) under the hood require to introduce piece by piece at a time. Moving along the timeline means that various minor releases might have include incomplete pieces (e.g. TSDB store in 15.1.0 but no sharding until 15.3.0). In turn this means disabled features under construction should not expect to get supported in any minor releases until we declare them GA. A couple of historical examples are the boltdb_shipper and the memberlist.

WDYT?

**Comment by jeschkies** [comment]
@periklis 

> I suggest to add a section about handling deprecations.

I had similar thoughts. However, this would be related to compatibility IMHO and that discussion is out of scope of the release cadence.

**Comment by afayngelerindbx** [comment]
+1 to explicit deprecation semantics

Another thing to consider is possibly codifying pre-release behavior for minor/major versions: having beta/alpha artifacts consistently available would make it easier to solicit community feedback on larger releases.

**Comment by periklis** [comment]
> @periklis
> 
> > I suggest to add a section about handling deprecations.
> 
> I had similar thoughts. However, this would be related to compatibility IMHO and that discussion is out of scope of the release cadence.

I agree my point is truly optional for this doc and it documenting the deprecation semantics deserves a separate RFC. AFAIK we have not deprecated anything yet, but I bet the timing before a future 3.x becomes reality is good to start deprecating pieces.

**Comment by dannykopping** [comment]
> Look on this I have to say first that this is an good start and finally a good point in time to involve the community. Thank you @dannykopping writing this down. rocket

Thanks for your thoughts @periklis - see my responses below:

> 
> My comments on improving this document are:
> 
> 1. I suggest to add a section about handling deprecations. Across the 1.x and 2.x lines we have certainly pilled up config knobs and operating modes that we might want to discuss deprecating. How long to users have to expect that deprecations hold? Removing deprecations usually have an impact on rolling out new releases on production environments and/or add upgrade procedures into the loki-operator and helm charts. From the loki-operator perspective it is easy to pin the version till we've done the job, but helm chart users might need to be aware of the deprecation schedule before bumping a version in a variable.

We decided to not complicate this RFC with additional details like this; it would've made the review too unwieldy. We can certainly get that RFC started in parallel. Would you be interested in driving this, or contributing in some other way?

> 2. The patch release cadence sounds super aggressive to me and if I count correctly we will have 3 active minor releases at a time supporting patch-releases every two weeks. That counts up to 6 patch releases every second week if and only if we have content to release. Is this currently possible in regards of CI resources and release management bookkeeping?

We intentionally made the schedule on the more aggressive side as a forcing function to drive some automation around releases. The more releases we do and the more painful they are, the more impetus we have to improve the situation.

> if I count correctly we will have 3 active minor releases at a time

How did you come to 3 here? We will only backport fixes to the current and previous minor release, so it'll just be 2 patch releases every ~2 weeks.

> 3. FWIW we should add a section about supporting features that are currently only available behind feature gates. Planning and executing long-term changes (e.g. TSDB) under the hood require to introduce piece by piece at a time. Moving along the timeline means that various minor releases might have include incomplete pieces (e.g. TSDB store in 15.1.0 but no sharding until 15.3.0). In turn this means disabled features under construction should not expect to get supported in any minor releases until we declare them GA. A couple of historical examples are the boltdb_shipper and the memberlist.
> 
> WDYT?

I'd vote for letting this evolve naturally. Adding feature gates will further overload the cognitive burden that operators have when running our rather complex software. To use your example, if folks absolutely need TSDB sharding they should wait until v15.3.0 before using the feature.

**Comment by dannykopping** [comment]
> +1 to explicit deprecation semantics
> 
> Another thing to consider is possibly codifying pre-release behavior for minor/major versions: having beta/alpha artifacts consistently available would make it easier to solicit community feedback on larger releases.

@afayngelerindbx please see my message above regarding the deprecation semantics.

Your second point is a good one: we also release weekly container images (our current one is [k88](https://hub.docker.com/r/grafana/loki/tags?page=1&name=k88)), and it's worth documenting the availability of these. We will probably not do any beta/alpha/RC/GA releases yet, but we will move in this direction in the future if the desire is there.

**Comment by jeschkies** [comment]
@dannykopping i think this should be converted to a LID 🤷🏼‍♂️

**Comment by MasslessParticle** [comment]
I agree with @jeschkies. Also, we haven't discussed this in nearly 9 months so I'm not sure how relevant it still is. I'm going to close it for now.

**Pull request closed without merging**
