### PR TITLE
Docs: Fix small spelling error 

### PR DESCRIPTION
**Pull request by ivanahuckova**
Updates `contains` -> `contain`.

### CODE REVIEW

**Review by kavirajk — APPROVED** [review]
LGTM

**Review by sandeepsukhani — APPROVED** [review]
LGTM

**Comment by ivanahuckova** [comment]
@kavirajk @sandeepsukhani Can you then merge this PR cause I don't have merging rights in loki repo. 🙂

**Comment by kavirajk** [comment]
@ivanahuckova Sure. Restarted CI (was failing unrelated flaky test). Will merge once all green.

**Pull request merged**
