### PR TITLE
bugfix:add cases.NoLower option

### PR DESCRIPTION
**Pull request by wujunwei**
**What this PR does / why we need it**:
see #7048 
 if we don't apply cases.NoLower, it will upper first alphabet lower the others
```go
package main

import (
	"fmt"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"strings"
)

func main() {
	source := "testAPI"
	fmt.Println(cases.Title(language.Und).String(source)) // out: Testapi
	fmt.Println(cases.Title(language.Und, cases.NoLower).String(source)) // out: TestAPI
	fmt.Println(strings.Title(source)) // out: TestAPI
}
```
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by kavirajk — COMMENTED** [review]
Thanks @wujunwei. Can you please add a small test to lock this behaviour?

**Comment by wujunwei** [comment]
> Thanks @wujunwei. Can you please add a small test to lock this behaviour?

I 'd like to do that , something like this ?
```go
        source := "testAPI"
        assert.Equal(t,cases.Title(language.Und, cases.NoLower).String(source), strings.Title(source))
        assert.NotEqual(t,cases.Title(language.Und).String(source), strings.Title(source))
}
```

**Comment by kavirajk** [comment]
> I 'd like to do that , something like this ?
> source := "testAPI"
> assert.Equal(t,cases.Title(language.Und, cases.NoLower).String(source), strings.Title(source))
> assert.NotEqual(t,cases.Title(language.Und).String(source), strings.Title(source))

No. not really.

I mean we should test how we use it in Loki [pkg/util/cfg/flag.go](https://github.com/grafana/loki/pull/7052/files#diff-64ef68bf7d6149412aecc68763805eeb90472143ef5ad3cbcbc13d46940398ee)

Can you add a test case in flag_test.go?

**Comment by wujunwei** [comment]
> No. not really.
> 
> I mean we should test how we use it in Loki [pkg/util/cfg/flag.go](https://github.com/grafana/loki/pull/7052/files#diff-64ef68bf7d6149412aecc68763805eeb90472143ef5ad3cbcbc13d46940398ee)
> 
> Can you add a test case in flag_test.go?

Thanks for explaining.  I have add some test case , Please take a look :)

**Review by kavirajk — APPROVED** [review]
Thanks @wujunwei for addressing the feedback. LGTM :+1: 

Looks like CI is failing for some unrelated reasons. Can you please rebase your branch to main? I will merge it then.

**Comment by wujunwei** [comment]
Have done so :) .

**Pull request merged**
