### PR TITLE
Promtail: Break on iterate journal failure

### PR DESCRIPTION
**Pull request by farodin91**
**What this PR does / why we need it**:

```
{"caller":"journaltarget.go:214","err":"failed to iterate journal: bad message","level":"error","msg":"received unexpected error while following the journal","ts":"2023-04-17T12:24:26.803335195Z"}
{"caller":"journaltarget.go:214","err":"failed to iterate journal: bad message","level":"error","msg":"received unexpected error while following the journal","ts":"2023-04-17T12:24:26.903980219Z"}
{"caller":"journaltarget.go:214","err":"failed to iterate journal: bad message","level":"error","msg":"received unexpected error while following the journal","ts":"2023-04-17T12:24:27.0042025Z"}
```

https://github.com/coreos/go-systemd/blob/main/sdjournal/journal.go#L583 origin 

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [x] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by farodin91** [comment]
@dannykopping Would you like to review? I have no idea why drone is failing

**Comment by farodin91** [comment]
@dannykopping Will this be backported?

**Comment by dannykopping** [comment]
Sure 👍

**Comment by dannykopping** [comment]
@farodin91 done: https://github.com/grafana/loki/pull/9403

**Comment by frittentheke** [comment]
I just observed an constant stream of these errors:

`promtail-linux-amd64[3829221]: level=error ts=2023-07-19T08:51:50.694001179Z caller=journaltarget.go:205 msg="received error during sdjournal follow" err="failed to iterate journal: bad message"`

with Promtail 2.8.1. A restart of Promtail then "fixed" it.

Isn't this supposed to be covered by this patch or likely a new issue @dannykopping ?

**Pull request merged**
