### PR TITLE
Running Loki as non-root in Kubernetes

### PR DESCRIPTION
**Pull request by Red-GV**
**What this PR does / why we need it**:
This PR defines the `USER` in the Dockerfile as `10001`. When running the Loki image as `nonroot` in Kubernetes, the resulting pod(s) will have a `CreateContainerConfigError`. This is because the `USER` in the image is a non-numerical value and thus it cannot resolve if the `USER` is a non-root user by default.

The work around for this in Kubernetes is to define the user to be some non-zero user. However, since the `USER` is already intended to be `10001`, the variable should be actually defined as this numeric value.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by DylanGuedes** [comment]
Good catch, gj. Just in case, do you think this could be a breaking change for users relying on the former USER?

**Comment by Red-GV** [comment]
Thanks @DylanGuedes. Hmm, that I'm not sure about. I don't think it should, but maybe there are some cases that I'm unaware about in which the change could be breaking.

**Comment by DylanGuedes** [comment]
> Thanks @DylanGuedes. Hmm, that I'm not sure about. I don't think it should, but maybe there are some cases that I'm unaware about in which the change could be breaking.

Got it, thanks. I'll let this open for a few days for others to have a chance to have a look, if no one shows any objection, I'll proceed to merge it.

**Review by vlad-diachenko — APPROVED** [review]
as long as `loki` user id is `10001` I think that should not break anything. it's the same user, we just used the id instead of the name

**Pull request merged**
