### PR TITLE
GitHub: Add CIFuzz integration

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Signed-off-by: David Korczynski <david@adalogics.com>

**What this PR does / why we need it**:

Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which Loki already runs.

CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of more features (see the URL above). 

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:
Loki OSS-Fuzz integration: https://github.com/google/oss-fuzz/tree/master/projects/loki

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by dannykopping** [comment]
Thanks for this @DavidKorczynski :+1:
Do you have a sense for how much time this will add to our CI jobs? I see `fuzz-seconds` is set to 600, and adding 10m to every PR would be intolerable. I'm thinking maybe we should run this on every merge to `main` instead?

We also want to have all our CI run in Drone; would you be willing to refactor this into https://github.com/grafana/loki/blob/main/.drone/drone.jsonnet?

**Comment by slim-bean** [comment]
Thanks for this PR @DavidKorczynski! I love fuzzing.

If it is 10mins, instead of running with each PR I think it would be better to run it separately on a schedule maybe once or twice a day. The only catch there is making sure failures are reported in a way someone notices.

**Comment by DavidKorczynski** [comment]
> Thanks for this @DavidKorczynski +1 Do you have a sense for how much time this will add to our CI jobs? I see `fuzz-seconds` is set to 600, and adding 10m to every PR would be intolerable. I'm thinking maybe we should run this on every merge to `main` instead?
> 
> We also want to have all our CI run in Drone; would you be willing to refactor this into https://github.com/grafana/loki/blob/main/.drone/drone.jsonnet?

Am happy to switch to `main` but I doubt I have time to refactor into Drone, sorry! 

@slim-bean it already is! Please see here: https://github.com/google/oss-fuzz/blob/master/projects/loki/project.yaml am happy to add your email on there as well

**Comment by jeschkies** [comment]
@cyriltovena didn't you already enable fuzzing or did you plan to?

**Comment by cyriltovena** [comment]
There is already this is to have it per PR.

**Comment by jeschkies** [comment]
@dannykopping and @trevorwhitney should we merge it or migrate to Drone instead?

**Comment by slim-bean** [comment]
I would also be relatively strongly opposed to a running on every build if
it adds any length to the existing CI time.

I also wonder if at this point it would be better to wait and do something
with the built in fuzzing coming in go 1.18?

**Comment by trevorwhitney** [comment]
I am very strongly opposed to running this on every build. Fuzzing is not a verification tool, it's more of an exploratory testing tool. IMO fuzzing falls more under QA. I think for PRs we are verifying the changes did not break any known restraints/cases (as expressed in other tests). Blocking a PR because if fails an unknown case, as identified by fuzzing, is unreasonable. Those sorts of things, when discovered, should be filed as bugs, not tacked on to feature work during the PR phase.

I would be in favor of having fuzzing happen either against each commit to main, or on a cron/schedule.

**Comment by trevorwhitney** [comment]
> CIFuzz can help detect catch regressions

I disagree with this statement. My understanding of fuzzing is it inherently uses randomization, which means it's not testing the exact same thing on each run. In order to detect a regression you need a deterministic test, with consistent inputs and outputs, so you can affirm the same inputs are not longer producing the same outputs (and hence a regression).

**Comment by trevorwhitney** [comment]
Interesting, thanks for the education on how fuzzers have evolved. While that information makes me much more keen on the idea of running this somewhere, I'm still strongly opposed to running this on every PR. This sounds very exhaustive, and feels like more of a nightly job to me. When the fuzzer fails, how clear is it exactly where the bug in the PR is? Our unit tests are usually pretty specific, allowing the contributor to quickly identify the bug. Will fuzzers provide that same directness and clarity? If not I feel it could prove a pretty frustrating experience to the contributor.

**Comment by DavidKorczynski** [comment]
>  I'm still strongly opposed to running this on every PR. This sounds very exhaustive, and feels like more of a nightly job to me.

The OSS-Fuzz will continue to run on a daily basis -- CIFuzz will only run the fuzzers for a few minutes (you can specify the number of seconds) whereas OSS-Fuzz runs them for much longer (depending on the fuzzer). If I remember correctly Loki does not have a lot of fuzzers deveoped yet though.

> how clear is it exactly where the bug in the PR is?

It is clear in the sense that CIFuzz compares if a given crash exists in older (OSS-Fuzz) builds, i.e. if the bug exists in yesterdays code then no bug will be filed. More details on the conditions for triggering a bug is here https://google.github.io/oss-fuzz/getting-started/continuous-integration/#how-it-works 

> Will fuzzers provide that same directness and clarity?

Difficult to say -- the crash will be shown with a stack trace, which fuzzer triggered it and also the specific input that triggered the bug.

**Pull request closed without merging**
