### PR TITLE
Copy `cortex/util/fakeauth` package dependency into Loki

### PR DESCRIPTION
**Pull request by kavirajk**
**What this PR does / why we need it**:
As a part of removing Loki dependent on cortex packages, we decided to copy the `fakeauth` package from cortex to Loki itself.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Review by chaudum — APPROVED** [review]

**Review by DylanGuedes — APPROVED** [review]
LGTM!
Just one observation, I noticed you removed the changelog entries as this code doesn't change anything for users. I think at the end of the latest release, all PRs part of the release were listed in the changelog, regardless of being a user-end change or not.

**Comment by kavirajk** [comment]
> I think at the end of the latest release, all PRs part of the release were listed in the changelog, regardless of being a user-end change or not.

I think it make more sense to add only user facing changes on CHANGELOG?. I consider this as more like _chore/refactoring_ rather than _something new_

**Comment by DylanGuedes** [comment]
> > I think at the end of the latest release, all PRs part of the release were listed in the changelog, regardless of being a user-end change or not.
> 
> I think it make more sense to add only user facing changes on CHANGELOG?. I consider this as more like _chore/refactoring_ rather than _something new_

I'm with you :smile: just saying that I think in Loki releases all PRs are added to the CHANGELOG (on the day of the release). I'm saying this because I remember not adding some of my PRs in the CHANGELOG but in the end they were added anyway.

**Comment by sandeepsukhani** [comment]
> > > I think at the end of the latest release, all PRs part of the release were listed in the changelog, regardless of being a user-end change or not.
> > 
> > 
> > I think it make more sense to add only user facing changes on CHANGELOG?. I consider this as more like _chore/refactoring_ rather than _something new_
> 
> I'm with you smile just saying that I think in Loki releases all PRs are added to the CHANGELOG (on the day of the release). I'm saying this because I remember not adding some of my PRs in the CHANGELOG but in the end they were added anyway.

I haven't closely followed the public release process but let us keep the changelog entries limited to user visible/facing changes.

**Review by sandeepsukhani — APPROVED** [review]
LGTM

**Pull request merged**
