### PR TITLE
fixed typo in lambda-promtail doc

### PR DESCRIPTION
**Pull request by klu4ic**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
fixing typo in labmda-promtail  _index.md 
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by chaudum — APPROVED** [review]
@klu4ic Thanks for spotting and fixing the type! Please sign the CLA so I can merge the PR.

**Comment by klu4ic** [comment]
@chaudum  thanks!  I have signed CLA.

**Comment by MasslessParticle** [comment]
@klu4ic It's still not picking it up. It looks like we're getting this message:

**Evgenii K** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=7898) it.

Is your email address properly configured?

Thanks again for contributing and sorry for the hassle

**Comment by jeschkies** [comment]
@klu4ic the email of the commit must be your GitHub email. Is it the same?

**Comment by klu4ic** [comment]
maybe it was another email, I have tried to sign SLA from that account, but the error is not disappear

**Review by JStickler — APPROVED** [review]
[docs team] LGTM

**Comment by MasslessParticle** [comment]
Seems like the CLA issue hasn't been resolved in 6 months. I'm going to close this for inactivity.

**Pull request closed without merging**
