### PR TITLE
fix(promtail): Fix UDP receiver on syslog transport

### LINKED ISSUE #6772: Promtail: syslog job over UDP is not working
**Describe the bug**
Promtail will not deliver "Syslog UDP" logs to Loki, but "Syslog TCP" logs works fine.

**To Reproduce**
1. Enable "**udp**" as "**listen_protocol**" option for syslog config, e.g.
```
    syslog:
      idle_timeout: 60s
      listen_protocol: udp
      label_structured_data: true
      labels:
        job: syslog
      listen_address: 0.0.0.0:514

```
Try to send some logs using UDP, I've used this example or real hardware switches which only support UDP syslog
https://gist.github.com/xtavras/4a01f7d1f94237a4abcdfb02074453c1

I can see in tcpdump that logs are coming to promtail machine, but nothing in Loki. I've tried to run promtail with debug option but don't see any additional errors.
2. Enable "**tcp**" as "**listen_protocol**" (it's default), e.g.
```
    syslog:
      idle_timeout: 60s
      listen_protocol: tcp
      label_structured_data: true
      labels:
        job: syslog
      listen_address: 0.0.0.0:514
```
Send logs using tcp, I've used this example
https://gist.github.com/xtavras/be13760713e2a9ee1a8bdae2ed6d2565

Logs are visible in tcpdump and are coming and visible in Loki.

**Expected behavior**
Logs sent to UDP syslogs should be delivered to Loki same way as TCP syslogs

**Environment:**
 - Loki: 2.5.0
 - Promtail: 2.6.1

**Screenshots, Promtail config, or terminal output**
Promtail config

```
server:
  http_listen_port: 9080


positions:
  filename: /var/lib/promtail/positions.yml


clients:
  - basic_auth:
      password: xxxxxxxxxxxxxxxx
      username: loki
    tenant_id: 1
    url: https://loki.example.com/api/prom/push


scrape_configs:
  - file_sd_configs:
    - files:
      - /etc/promtail/file_sd/*.yml
      - /etc/promtail/file_sd/*.yaml
      - /etc/promtail/file_sd/*.json
    job_name: file_sd

  - job_name: syslog-logs
    relabel_configs:
    - source_labels:
      - __syslog_message_hostname
      target_label: host
    syslog:
      idle_timeout: 60s
      listen_protocol: udp
      label_structured_data: true
      labels:
        job: syslog
      listen_address: 0.0.0.0:514
```

### PR DESCRIPTION
**Pull request by joshuapare**
Simple fix to convert the incoming datagram into a bytes reader that the ParseStream can handle. currently it freezes up because the datagrams are sent as is without separation so the reader routine blocks until an interrupt.

Issue first resolved in grafana/agent, mirror PR to that: https://github.com/grafana/agent/pull/5297

Fixes #6772

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] `CHANGELOG.md` updated

### CODE REVIEW

**Comment by cstyan** [comment]
@joshuapare looks like there's some test failures + a merge conflict with the changelog. Assigning myself as reviewer.

**Comment by cstyan** [comment]
@joshuapare we can move forward here, no issues with the promtail maintenance mode bit. Is there any easy openings for tests here? I'm not very familiar with syslog so I don't know why the reading from the wire needs to be read in this manner to handle UDP.

**Comment by joshuapare** [comment]
> @joshuapare we can move forward here, no issues with the promtail maintenance mode bit. Is there any easy openings for tests here? I'm not very familiar with syslog so I don't know why the reading from the wire needs to be read in this manner to handle UDP.

Unfortunately not - in the other repo, it was deemed simple enough to merge in, so I assume it would follow the same pattern here: https://github.com/grafana/agent/pull/5297#pullrequestreview-1710636246

**Comment by cstyan** [comment]
> @cstyan Unfortunately not - in the other repo, it was deemed simple enough to merge in, so I assume it would follow the same pattern here: [grafana/agent#5297 (review)](https://github.com/grafana/agent/pull/5297#pullrequestreview-1710636246)

fair enough, the agent/alloy team would have worked with this part of the code more recently anyways :+1: lets see if CI is still green, then we can merge

**Review by cstyan — APPROVED** [review]

**Comment by cstyan** [comment]
@joshuapare thanks for your patience :+1:

**Comment by joshuapare** [comment]
@cstyan Same to you! I should have checked back far sooner 😅 thanks for getting this in

**Pull request merged**
