### PR TITLE
fluentd: Make fluentd version requirements permissive

### PR DESCRIPTION
**Pull request by tarokkk**
**What this PR does / why we need it**:
This PR reverts the change to use a fixed Fluentd version. As a plugin, it is counterproductive to fix a very specific version of Fluentd.

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

**Comment by ahma** [comment]
@cyriltovena Thanks for the rapid review! Could you please let me know how/when it will released into the rubygems repo? Thanks for your support!

**Comment by cyriltovena** [comment]
will do now.

**Comment by cyriltovena** [comment]
ho you did not update the gem version :/ let me try to yank it.

**Comment by cyriltovena** [comment]
ho that didn't work. well I need to push a new version

**Comment by tarokkk** [comment]
Thanks I forgot that my bad :)

**Pull request merged**
