### PR TITLE
support extract parsed field

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #https://github.com/grafana/loki/issues/2675

ref https://github.com/grafana/loki/pull/2674

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by cyriltovena** [comment]
@zjj2wry Thank you for this.

I'm wondering why this labelMap is not working for you https://grafana.com/docs/loki/latest/clients/fluentbit/#labelmappath it is supposed to do the same ? no ? Is it just because you don't want to use a file ?

**Comment by zjj2wry** [comment]
> @zjj2wry Thank you for this.
> 
> I'm wondering why this labelMap is not working for you https://grafana.com/docs/loki/latest/clients/fluentbit/#labelmappath it is supposed to do the same ? no ? Is it just because you don't want to use a file ?

it works fine when collecting pod logs, but I want to collect kubelet、contained logs. it's come from systems, this pr can convert SYSLOG_IDENTIFIER、_HOSTNAME into labels. Because the log needs to have a unique label, otherwise will get a 400 error

**Comment by cyriltovena** [comment]
> > @zjj2wry Thank you for this.
> > I'm wondering why this labelMap is not working for you https://grafana.com/docs/loki/latest/clients/fluentbit/#labelmappath it is supposed to do the same ? no ? Is it just because you don't want to use a file ?
> 
> it works fine when collecting pod logs, but I want to collect kubelet、contained logs. it's come from systemd, this pr can convert SYSLOG_IDENTIFIER、_HOSTNAME into labels. Because the log needs to have a unique label, otherwise will get a 400 error

I get it I'm saying you can already do that with the json labelmap.

```
{
  "SYSLOG_IDENTIFIER": "syslog",
  "_HOSTNAME": "host",
}
```

**Comment by zjj2wry** [comment]
> > > @zjj2wry Thank you for this.
> > > I'm wondering why this labelMap is not working for you https://grafana.com/docs/loki/latest/clients/fluentbit/#labelmappath it is supposed to do the same ? no ? Is it just because you don't want to use a file ?
> > 
> > 
> > it works fine when collecting pod logs, but I want to collect kubelet、contained logs. it's come from systemd, this pr can convert SYSLOG_IDENTIFIER、_HOSTNAME into labels. Because the log needs to have a unique label, otherwise will get a 400 error
> 
> I get it I'm saying you can already do that with the json labelmap.
> 
> ```
> {
>   "SYSLOG_IDENTIFIER": "syslog",
>   "_HOSTNAME": "host",
> }
> ```

I thought it would only handle k8s labels，revisit the code and it should work, thank you very much

**Comment by cyriltovena** [comment]
May be we should document it better or give this syslog example.

**Pull request closed without merging**
