### PR TITLE
Create promtail-examples.md

### PR DESCRIPTION
**Pull request by sleleko**
simple configs and description

### CODE REVIEW

**Comment by daixiang0** [comment]
look at [doc](https://github.com/grafana/loki/blob/master/docs/promtail.md)

**Comment by sleleko** [comment]
Hello! But there no simple examples for run in docker.. С уважением Лелеко Сергей.12.04.2019, 07:02, "Xiang Dai" <notifications@github.com>:look at doc

**Comment by daixiang0** [comment]
find a default [config](https://github.com/grafana/loki/blob/master/cmd/promtail/promtail-docker-config.yaml) for docker, you may write an example based on it and add some scrap config description.

**Comment by sleleko** [comment]
Ok! I,m will do it , and send later pull request. С уважением Лелеко Сергей.12.04.2019, 07:23, "Xiang Dai" <notifications@github.com>:find a default config for docker, you may write an example based on it and add some scrap config description.

**Comment by sleleko** [comment]
Updated in PR(https://github.com/grafana/loki/pull/477)

**Pull request closed without merging**
