### PR TITLE
Upgrade Prometheus and Cortex to `LabelNames()` with matchers versions

### PR DESCRIPTION
**Pull request by colega**
**What this PR does / why we need it**:
This bumps prometheus up to the changes from https://github.com/prometheus/prometheus/pull/9083 and Cortex to https://github.com/cortexproject/cortex/pull/4380

Those changes made a breaking change in the `LabelQuerier`'s `LabelNames` interface adding a slice of matchers, just like `LabelValues` already did. This isn't yet needed in Loki, but it's preventing us from smoothly upgrading further.

**Which issue(s) this PR fixes**:
None, AFAIK.

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Review by trevorwhitney — APPROVED** [review]
LGTM

**Comment by colega** [comment]
Rebased on latest `main`

**Review by dannykopping — APPROVED** [review]
LGTM, thanks for this @colega :+1:

**Review by cyriltovena — APPROVED** [review]
LGTM

**Pull request merged**
