### PR TITLE
Implement `LegacySample`, `LegacyLabelPair` proto messages

### PR DESCRIPTION
**Pull request by DylanGuedes**
**What this PR does / why we need it**:
This PR adds two new proto messages to logproto: `LegacySample`, which contains the same body as [Cortex Sample type](https://github.com/cortexproject/cortex/blob/86d5f52b41d6e8078bdb84388067a9b12578c8bb/pkg/cortexpb/cortex.proto#L38), and `LegacyLabelPair`, which contains the same body as Cortex LabelPair type.

In [PR 5151](https://github.com/grafana/loki/pull/5151) I forked `cortexpb` into Loki and modified Loki's codebase to use it. However, I overlooked that Cortex `Sample` differs slightly from Loki's `Sample`, and that Cortex `LabelPair` differs from Loki's `LabelPair` - both a retro compatibility break.

By adding `LegacySample` and `LegacyLabelPair` and reverting our code base to use it, we fix that retro compatibility problem without the need of adding Cortex as a dependency again.

On a side-note, this was only affecting Loki instances in special cases where, during a rollout, one Loki instance is communicating with other instances through a gRPC connection, and just for those specific protobuf messages.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
N/A

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by DylanGuedes** [comment]
I recommend reviewing this commit-by-commit (and to skip the second commit).

**Comment by DylanGuedes** [comment]
Obs: The failing test has no relation to these changes I believe.

**Review by trevorwhitney — COMMENTED** [review]
This looks good, but I think it's worthwhile to add a test to catch this bug, and then make sure this change fixes it. My understanding is that something was sending us messages built using the `cortexpb` protos (that were in cache maybe?), and they could not be deserialzed to `logproto.Sample`. Is there a way to capture that payload, either as JSON or a binary file in test fixtures, in a way that does not require a dependency on cortex or `cortexpb`, but that allows us to confirm this new message type de-serialzes the legacy message correctly?

**Review by owen-d — APPROVED** [review]
LGTM, nice cleanup.

**Pull request merged**
