### PR TITLE
Add toggle for persistence disk in single-binary mode

### PR DESCRIPTION
**Pull request by jkroepke**
Signed-off-by: Jan-Otto Kröpke <jok@cloudeteer.de>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Dev/Test scenarios, persistence can be omitted.

**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [x] Documentation added
- [ ] Tests updated
- [x] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by jkroepke** [comment]
@jeschkies generated

**Comment by jkroepke** [comment]
Can I help here to move forward? @trevorlauder @jeschkies

**Review by jeschkies — APPROVED** [review]

**Comment by MasslessParticle** [comment]
@jkroepke Looks like the task is complaining about the end-of-file whitespace. If you add that, I _think_ it'll be good to go.

**Comment by jkroepke** [comment]
rebased

**Pull request merged**
