### PR TITLE
chore(helm): various helm fixes

### PR DESCRIPTION
**Pull request by dannykopping**
**What this PR does / why we need it**:
- allow minio address to be overridden.
- `query-scheduler-discovery` service will now be prefixed by query scheduler full name.
- fix `helm-tests` Go source which was missing a param following #12245.

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [x] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by trevorwhitney — APPROVED** [review]
Nice to see a PR from you @dannykopping! LGTM!

**Comment by dannykopping** [comment]
Thanks for the quick review @trevorwhitney!

I added another quick fix which caught me out today: https://github.com/grafana/loki/pull/12675/commits/1f6de5ecb4ff1842c258d814b38a27be8de3c995

I also had to [update the version](https://github.com/grafana/loki/pull/12675/commits/f532d90cf29bea359bb9f8ec2ee93e1307ce3b44) due to a conflict.

**Comment by dannykopping** [comment]
@trevorwhitney the build appears to be blocked, would you mind kicking it?
My access got revoked 😞

**Comment by trevorwhitney** [comment]
@dannykopping looks ready to go!

**Comment by dannykopping** [comment]
@trevorwhitney all green, thanks for the review!
Hope you folks are all doing well, miss you all ❤️

**Comment by cyriltovena** [comment]
will resolve those, my bad

**Pull request merged**
