### PR TITLE
feat: support ruler sidecar in singleBinary mode

### LINKED ISSUE #10967: Helm: sidecar is not part of singleBinary
**Describe the bug**
When I deploy loki in singleBinary mode, but `sidecar.rules.enabled` is `true`, I expect the sidecar to be deployed with loki.
But it's not, a code search (`repo:grafana/loki path:/^production\/helm\/loki\/templates\// sidecar`) shows that sidecar is only present in `statefulset-backend.yaml`.

What I did:
Switched to the "scalable" deployment, got better query speeds at the same time !

### PR DESCRIPTION
**Pull request by okozachenko1203**
**What this PR does / why we need it**:
support ruler sidecar in singleBinary mode

**Which issue(s) this PR fixes**:
Fixes #10967

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by 3deep5me** [comment]
I would also need & love this feature!

**Comment by 3deep5me** [comment]
Hi @okozachenko1203,
i think you need to sign the CLA that the PR can be proceeded.

**Comment by tyriis** [comment]
would be great to have this resolved :)

**Comment by jazzlyn** [comment]
any chance to get this merged?

**Comment by janisii** [comment]
Any updates on this?

**Review by trevorwhitney — APPROVED** [review]
LGTM

**Comment by 3deep5me** [comment]
Thanks for merging this!

Just a notice, please update the Chart.yaml in the next time. With this MR semantic versioning has been eliminated.  
I had a fixed Chart-Version in ArgoCD and out of nowhere a new sidecar with new mounts appeared in my deployments.

**Pull request merged**
