### PR TITLE
support multiple config files for loki and promtail

### LINKED ISSUE #3389: promtail: Allow inclusion of config files
It would be very nice if promtail would support the inclusion of config files. Since the configuration on different clients may differ it would increase the manageability and structure if the scrape_configs for different sources can be seperated into single config files.

### PR DESCRIPTION
**Pull request by adityacs**
**What this PR does / why we need it**:
support multiple config files for loki and promtail

**Which issue(s) this PR fixes**:
Fixes #3389 

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

**Comment by sandeepsukhani** [comment]
The problems with passing multiple config files would be harder to debug and I can't think of a use-case for this.
Can you please share an example where this would be relevant?

**Comment by adityacs** [comment]
Following are the usecases requested from the users.

https://github.com/grafana/loki/issues/3389
https://github.com/grafana/loki/issues/1723

Also, if anyone are running multiple instances of Loki may be Staging, Prod etc... They would want to keep a base config and then override that config based on the environment. So, they can have 3 config files like `loki-config-base.yaml`, `loki-config-staging.yaml`, `loki-config-production.yaml` and when running Loki in `Staging` they will pass `base` and `staging` file and when running in `Prod` they will pass `base` and `prod` file. This way all the common configurations go in to one base file and only the required fields can be overridden.

**Comment by zipkid** [comment]
@adityacs Could you still Sign the CLA so this could get added?

**Comment by TomRitserveldt** [comment]
this would still be nice to have...

**Comment by bogdankatishev** [comment]
I am also a big fan to have this added

**Pull request closed without merging**
