### PR TITLE
[Helm] Remove unused value and set default values explicitly

### LINKED ISSUE #7575: [Helm] `monitoring.alerts` not used
**Describe the bug**
As far as I can see, https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L600-L609 is not being used for anything.

**To Reproduce**
1. `helm template loki grafana/loki --set monitoring.alerts.enabled=true > enabled.yaml`
2. `helm template loki grafana/loki --set monitoring.alerts.enabled=false > disabled.yaml`
3. `diff enabled.yaml disabled.yaml` returns 0

**Expected behavior**
It should either be removed, or replace `monitoring.rules.alerting`

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [helm]

### PR DESCRIPTION
**Pull request by AndersBennedsgaard**
**What this PR does / why we need it**:
`monitoring.alerts` are not used in the Loki Helm chart. This removes it.
Furthermore, some values are referenced in the templates, but not used in the values file. This adds the default values.

**Which issue(s) this PR fixes**:
Fixes #7575

**Special notes for your reviewer**:
https://github.com/AndersBennedsgaard/loki/blob/main/production/helm/loki/templates/single-binary/pdb.yaml#L15 should probably also be updated since `podDisruptionBudget` is not referenced in the values file. However, I am unsure what default values should be used.
https://github.com/AndersBennedsgaard/loki/blob/main/production/helm/loki/templates/networkpolicy.yaml#L124 should probably also be updated since the `loki.rulerSelectorLabels` is not a valid helper function. However, I am unsure which selector labels to use. Especially since it seems like `ruler` is not used. Perhaps any reference to `ruler` should be removed?

**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [x] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by AndersBennedsgaard** [comment]
Drone is complaining that I should run `make -C docs sources/installation/helm/reference.md`, but I have :(

**Review by trevorwhitney — APPROVED** [review]
lgtm, thanks so much for the cleanup! was this done manually or did you have a linter to help out? If there's a linter that can do this sort of stuff I would be love in include it in the CI build.

**Comment by trevorwhitney** [comment]
@jeschkies any insight into the `reference.md` issues here?

**Comment by AndersBennedsgaard** [comment]
> lgtm, thanks so much for the cleanup! was this done manually or did you have a linter to help out? If there's a linter that can do this sort of stuff I would be love in include it in the CI build.

I used @tim-koehler's https://github.com/tim-koehler/Helm-Intellisense, which is an extension to VSCode, so it would probably not be easy to implement it in CI pipeline

**Comment by AndersBennedsgaard** [comment]
@trevorwhitney do you have an opinion on:
> https://github.com/AndersBennedsgaard/loki/blob/main/production/helm/loki/templates/single-binary/pdb.yaml#L15 should probably also be updated since `podDisruptionBudget` is not referenced in the values file. However, I am unsure what default values should be used.
> https://github.com/AndersBennedsgaard/loki/blob/main/production/helm/loki/templates/networkpolicy.yaml#L124 should probably also be updated since the `loki.rulerSelectorLabels` is not a valid helper function. However, I am unsure which selector labels to use. Especially since it seems like `ruler` is not used. Perhaps any reference to `ruler` should be removed?

**Comment by jeschkies** [comment]
Thanks @AndersBennedsgaard. Could you generate the reference file with `BUILD_IN_CONTAINER=false make -BC docs sources/installation/helm/reference.md` or `make -BC docs sources/installation/helm/reference.md`

**Comment by AndersBennedsgaard** [comment]
@jeschkies it still fails with either command. I get a warning about a missing template:
```
level=warning msg="Error generating documentation for chart /helm-docs/production/helm/loki: template: /helm-docs/production/helm/loki:38:19: executing \"chart.valuesTableHtml\" at <{{template \"chart.valueDefaultColumnRender\" .}}>: template \"chart.valueDefaultColumnRender\" not defined"
mv "../production/helm/loki/reference.md" "sources/installation/helm/reference.md"
```

**Comment by jeschkies** [comment]
@AndersBennedsgaard seems merging main fixed it. Checkout https://github.com/AndersBennedsgaard/loki/pull/1 I've generated the reference for you.

**Comment by AndersBennedsgaard** [comment]
@jeschkies I haven't tried to do a squash commit before, but I think it worked. I forgot to run `make -BC docs sources/installation/helm/reference.md`, but it seems to work now :partying_face:

**Pull request merged**
