### PR TITLE
chore(query-scheduler) Remove nosiy "inflight" requests log entries

### PR DESCRIPTION
**Pull request by kavirajk**
**What this PR does / why we need it**:
We have enough metrics now (queue time, queue length and metrics.go statistics)
that makes these log entries obselete.

Signed-off-by: Kaviraj <kavirajkanagaraj@gmail.com>

**Which issue(s) this PR fixes**:
Fixes #NA

**Special notes for your reviewer**:
Quickly checked internal and external mixins to verify it's not used in any dashboards or alerts.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by dannykopping — COMMENTED** [review]
Do we have a metric expressing query processing time on a per-tenant basis?

**Review by slim-bean — APPROVED** [review]
LGTM, thanks!

**Comment by kavirajk** [comment]
> Do we have a metric expressing query processing time on a per-tenant basis?

No. not per tenant basis. ( [I tried once](https://github.com/grafana/loki/pull/5485), but reverted because of cardinality explosion)

The reason to remove is mainly it's noisy (two log entries per every request) and also we pay quite a bit for this (heard it from @slim-bean).

**Comment by dannykopping** [comment]
> > Do we have a metric expressing query processing time on a per-tenant basis?
> 
> No. not per tenant basis. ( [I tried once](https://github.com/grafana/loki/pull/5485), but reverted because of cardinality explosion)
> 
> The reason to remove is mainly it's noisy (two log entries per every request) and also we pay quite a bit for this (heard it from @slim-bean).

Cool, I'm happy to defer to Ed's _LGTM_ here.
Thanks for the clarification.

**Pull request merged**
