### PR TITLE
Move `cortex/pkg/tenant` dependency to Loki.

### PR DESCRIPTION
**Pull request by kavirajk**
**What this PR does / why we need it**:
As a part of removing Loki dependent on `cortex` packages, we decided to copy the `tenant` package from cortex to Loki itself.

Some work done by @aknuds1 in this [PR](https://github.com/grafana/loki/pull/4338) (but got too much conflict to resolve).

**Which issue(s) this PR fixes**:
Fixes #NA

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [x] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by aknuds1** [comment]
Should I close my PR?

**Comment by kavirajk** [comment]
@aknuds1 I can close it. Thanks for the efforts :)

**Review by DylanGuedes — APPROVED** [review]
lgtm!

**Review by cyriltovena — APPROVED** [review]
Lgtm

**Pull request merged**
