### PR TITLE
check version increment when necessary

### PR DESCRIPTION
**Pull request by daixiang0**
Check all changed files, if include helm, check helm chart version
increment.

Signed-off-by: Xiang Dai <764524258@qq.com>

**Checklist**
- [x] Tests updated

### CODE REVIEW

**Comment by daixiang0** [comment]
Not every time, now the logic is always skip, but if changed helm, check is necessary.

**Comment by slim-bean** [comment]
I like this idea, but have some concerns with implementation, specifically any changes to the README.md in the helm directory would cause this check to fail and force incrementing the helm chart version number.

Also as @steven-sheehy mentioned I think we are going to head in the direction of locking the helm chart to the Loki release.  I think this would happen in the 1.0 release.  Though this isn't totally decided yet. 

I'm afraid this PR may have to wait until we have completely figured out all our future version plans

**Comment by daixiang0** [comment]
The check rule can be customized as wish.

**Comment by daixiang0** [comment]
update

**Comment by daixiang0** [comment]
@slim-bean any update?

**Comment by daixiang0** [comment]
@sh0rez @rfratto  @slim-bean any update?

**Comment by daixiang0** [comment]
@slim-bean any input?

**Comment by daixiang0** [comment]
@rfratto @sh0rez mind have a look?

**Comment by daixiang0** [comment]
update

**Comment by daixiang0** [comment]
update

**Comment by daixiang0** [comment]
hold

**Pull request closed without merging**
