### PR TITLE
Enable -race when running tests. Fixed couple of race errors.

### PR DESCRIPTION
**Pull request by pstibrany**
Fixed couple of reported errors when running tests with -race option.

There are few more remaining.

### CODE REVIEW

**Comment by pstibrany** [comment]
If races in promtail are fixed, then there is still race in some new ingester tests. @rfratto would you please take a look?

**Comment by rfratto** [comment]
@pstibrany I fixed the test errors in the ingester.

**Comment by pstibrany** [comment]
Wonderful, thanks a lot @rfratto!

**Comment by slim-bean** [comment]
working on the fix for the tail lib, and I have a fix for the other promtail test

**Comment by slim-bean** [comment]
keep this open pls stalebot

**Pull request closed without merging**
