### PR TITLE
fix(helm): Removed duplicate bucketNames from documentation and fixed key name `deploymentMode`

### PR DESCRIPTION
**Pull request by ddaskal**
**What this PR does / why we need it**:
Fixes documentation for Helm deployments to not have duplicate values and utilize correct `deploymentMode` key name.

**Which issue(s) this PR fixes**:
Fixes [#12610](https://github.com/grafana/loki/issues/12610)

**Special notes for your reviewer**:

**Checklist**
- [X] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [X] Documentation added
- [X] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [x] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by JStickler** [comment]
@ddaskal   Please note this item in the PR checklist and update the other files, and sign the contributor license agreement.
For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

**Comment by ddaskal** [comment]
@JStickler I believe this is ready for review again. Do I need to squash my commits first or are you able to do a squash & merge?

**Comment by JStickler** [comment]
@ddaskal No need to squash, we squash and merge.  I've already tagged someone who works on the Helm charts to review this (I'm the technical writer on the team, so I only approve doc updates and leave the code changes to the engineering team).

**Review by MichelHollands — APPROVED** [review]
LGTM

**Pull request merged**
