### PR TITLE
Adding RegEx Capture to Create Log Labels

### PR DESCRIPTION
**Pull request by base698**
https://github.com/grafana/loki/issues/88

Obviously this could be abused.  Some questions:

* What's the max cardinality Loki could reasonably handle?  10s of things?  100s?  10000s?
* What's the risk of destroying the Loki cluster after an errant promtail config that add's new labels as time stamps?

### CODE REVIEW

**Comment by base698** [comment]
Having trouble figuring out how to test it:

```
$ logcli --addr=http://localhost:3100 query '{level="warn"}'
http://localhost:3100/api/prom/query?query=%7Blevel%3D%22warn%22%7D&limit=30&start=1549928444165755649&end=1549932044165755649&direction=BACKWARD&regexp=
2019/02/11 16:40:44 Failed to parse labels: syntax error
```

Seeing syntax errors for labels when using logcli.

**Comment by base698** [comment]
@tomwilkie Is there some way to access CircleCI to dig into the failures?

**Comment by slim-bean** [comment]
Hey @base698 thanks for the PR!   We are just starting to look into how to extract labels from log lines, and are pretty early in the discussion.  I think I'm going to be putting together a design doc shortly and will link to it in the project.  Questions like the ones you have asked are going to be very important considerations.  

Please bare with us as it may take a little bit to sort out the details of how to best extract metrics and labels from logs, but hopefully you may have saved us some work :)

In regards to the circleci failure, I think you should be able to click on the Details link next to the `test-build-deploy` step and then drill in on the piece that failed. In this case it looks like a lint issue.

**Comment by base698** [comment]
@slim-bean @tomwilkie You guys going to be at GrafanaCon?

**Comment by slim-bean** [comment]
Yes we will!

**Comment by base698** [comment]
@slim-bean I'm in LA, Would like to talk to you guys about it if you are around.  Going to try to make it one or both days.

**Comment by slim-bean** [comment]
@base698 if you make it to the con ping me (ewelch) on our public slack grafana.slack.com

**Comment by slim-bean** [comment]
@base698 it's been a whirlwind last few weeks and sorry we didn't get to meet up when I was in LA, but I'm now looking at this PR and we are figuring out how to incorporate your work along with some other changes, would you be interested in chatting about this further? If so could you join or public slack: grafana.slack.com and ping me @ewelch?

**Comment by base698** [comment]
Will do!  How do I get invited into slack?

Saying this:  Don't have an account on this workspace yet?  Contact the
workspace administrator for an invitation.

Email is: justin.thomas1@gmail.com

**Comment by slim-bean** [comment]
Hey Justin, sent you an email, not sure if you got it, the correct URL for
our slack is http://slack.grafana.com/ sorry about that!

**Comment by Kuqd** [comment]
@base698 Can we close this ? Design is here https://github.com/grafana/loki/blob/master/docs/design/labels.md and implementation is starting here : https://github.com/grafana/loki/tree/label-extraction

**Comment by base698** [comment]
Sure, will check those out.

**Pull request closed without merging**
