### PR TITLE
Docs: Change service names in docker-compose files

### PR DESCRIPTION
**Pull request by 7olstoy**
In docker-compose files, we use grafana image but it is named nginx. It can make some misunderstandings

### CODE REVIEW

**Comment by owen-d** [comment]
Good catch - I'm not sure how it ended up like that. Would you mind accepting the CLA and we can get this merged?

**Comment by 7olstoy** [comment]
@owen-d Done

**Review by dannykopping — APPROVED** [review]

**Comment by dannykopping** [comment]
@7olstoy thanks for the PR :+1: 
Can you please merge `main` into your branch? We're getting some failing tests in CI.

**Comment by 7olstoy** [comment]
@dannykopping done

**Comment by dannykopping** [comment]
Thanks for your contribution @7olstoy!

**Pull request merged**
