### PR TITLE
【RFR】fix Config reload with /reload endpoint causes metrics scraping error

### PR DESCRIPTION
**Pull request by liguozhong**
**What this PR does / why we need it**:
fix Config reload with /reload endpoint causes metrics scraping error

pipeline.go adds a Close() interface, which releases the resources configured last time when promtail reloads. Currently, only the metrics stage implements the Close() interface

**Which issue(s) this PR fixes**:
Fixes #https://github.com/grafana/loki/issues/8174

**Special notes for your reviewer**:
Because the Unregister function of prometheus only works on collectorsByID, the original metrics stage uses a custom Collector that belongs to uncheckedCollectors. Therefore, metrics.go is re-implemented, and the original collector is replaced with the original sdk of prometheus/counter/gauge/histogram.
```go		
c.registry.Unregister(m)
```

```go
type Registry struct {
	collectorsByID        map[uint64]Collector // ID is a hash of the descIDs.
	uncheckedCollectors   []Collector
}
```

```go
// Unregister implements Registerer.
func (r *Registry) Unregister(c Collector) bool {
	var (
		descChan    = make(chan *Desc, capDescChan)
		descIDs     = map[uint64]struct{}{}
		collectorID uint64 // All desc IDs XOR'd together.
	)
	go func() {
		c.Describe(descChan)
		close(descChan)
	}()
	for desc := range descChan {
		if _, exists := descIDs[desc.id]; !exists {
			collectorID ^= desc.id
			descIDs[desc.id] = struct{}{}
		}
	}

	r.mtx.RLock()
	if _, exists := r.collectorsByID[collectorID]; !exists {
		r.mtx.RUnlock()
		return false
	}
	r.mtx.RUnlock()

	r.mtx.Lock()
	defer r.mtx.Unlock()

	delete(r.collectorsByID, collectorID)
	for id := range descIDs {
		delete(r.descIDs, id)
	}
	// dimHashesByName is left untouched as those must be consistent
	// throughout the lifetime of a program.
	return true
}
```

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by liguozhong** [comment]
> Thanks for the quick fix @liguozhong! I think we should add a test case for this, though.

OK, I will be on vacation for the next two weeks, and I will come back in two weeks to continue to complete this PR

**Comment by owen-d** [comment]
Enjoy the time off!

**Comment by liguozhong** [comment]
done.

Because the Unregister function of prometheus only works on collectorsByID, the original metrics stage uses a custom Collector that belongs to uncheckedCollectors. Therefore, metrics.go is re-implemented, and the original collector is replaced with the original sdk of prometheus/counter/gauge/histogram.

```
=== RUN   TestPipeline_Reload
    pipeline_test.go:497: 
        	Error Trace:	/Users/fuling/go/src/github.com/grafana/loki/clients/pkg/logentry/stages/pipeline_test.go:497
        	Error:      	Received unexpected error:
        	            	collected metric "promtail_custom_debug_metrics" { label:<name:"action" value:"GET" > label:<name:"match" value:"false" > label:<name:"status_code" value:"200" > label:<name:"stream" value:"stderr" > counter:<value:1 > } was collected before with the same name and label values
        	Test:       	TestPipeline_Reload
--- FAIL: TestPipeline_Reload (0.00s)

```

**Comment by cstyan** [comment]
@liguozhong is this PR still relevant?

**Comment by chaudum** [comment]
Promtail is superseded by [Grafana Agent](https://grafana.com/docs/agent/latest/) and [Grafana Alloy](https://grafana.com/docs/alloy/latest/).

**Pull request closed without merging**
