### PR TITLE
feat: area/helm: Modified helm template to use http_listen_port and grpc_listen_port instead of hardcoded value

### LINKED ISSUE #11641: Actually plug http_listen_port and grpc_listen_port into helm code
**Describe the bug**
PR https://github.com/grafana/loki/pull/7137 (later amended by https://github.com/grafana/loki/pull/7174) introduced some server configs, but it seems that they weren't fully plugged the helm code, causing some problems when they get set to something different from the default.

**To Reproduce**
1. install loki with helm and set the `loki.server.grpc_listen_port` value to e.g. `9096`
2. the `loki-read` pod logs will start showing lots and lots of errors like the following:

```
level=warn ts=2024-01-10T16:32:00.721694775Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.12.235:9095: connect: connection refused\"" addr=172.28.12.235:9095
level=warn ts=2024-01-10T16:32:00.735794161Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.13.194:9095: connect: connection refused\"" addr=172.28.13.194:9095
level=warn ts=2024-01-10T16:32:00.982868119Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.12.235:9095: connect: connection refused\"" addr=172.28.12.235:9095
```

This is because the `query-scheduler-discovery` headless service returns that port:

```
$ k get svc/query-scheduler-discovery -o yaml
...
spec:
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  - name: grpc
    port: 9095
    protocol: TCP
    targetPort: grpc
```

**Expected behavior**

The backend service will use the configs because the port is passed as one of the parameters [here](https://github.com/grafana/loki/blob/0dc8c7533186c22b4649779f4098ea88aa82ff50/production/helm/loki/values.yaml#L97-L100).

The `query-scheduler-discovery` kubernetes service should also point to the requested port, but the helm template [doesn't use that variable, and instead uses the hardcoded value of `9095`](https://github.com/grafana/loki/blob/0dc8c7533186c22b4649779f4098ea88aa82ff50/production/helm/loki/templates/backend/service-backend-headless.yaml#L35).

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

---

I'll test a potential fix in the next days.

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
**What this PR does / why we need it**:
This PR basically modifies helm template to use parameters http_listen_port and grpc_listen_port instead of hardcoded value to handle the cases where user assigns some other port other than default.
**Which issue(s) this PR fixes**:
Fixes #11641

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by bebosudo — COMMENTED** [review]
Is it working for you?
My loki-read pod is stuck in an endless list of errors:
```
level=warn ts=2024-01-11T08:43:57.902636597Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.12.169:9095: connect: connection refused\"" addr=172.28.12.169:9095
level=warn ts=2024-01-11T08:43:57.985055672Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.12.169:9095: connect: connection refused\"" addr=172.28.12.169:9095
level=error ts=2024-01-11T08:43:58.268012236Z caller=frontend_scheduler_worker.go:237 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.12.169:9095: connect: connection refused\"" addr=172.28.12.169:9095
level=error ts=2024-01-11T08:43:58.619265229Z caller=frontend_scheduler_worker.go:237 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.12.169:9095: connect: connection refused\"" addr=172.28.12.169:9095
level=warn ts=2024-01-11T08:43:59.015424721Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.12.169:9095: connect: connection refused\"" addr=172.28.12.169:9095
level=warn ts=2024-01-11T08:43:59.171403506Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.12.169:9095: connect: connection refused\"" addr=172.28.12.169:9095
level=warn ts=2024-01-11T08:43:59.206568576Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.12.169:9095: connect: connection refused\"" addr=172.28.12.169:9095
```

The `172.28.12.169` address is the backend pod address.

There are many more places where we need to edit hardcoded values. I'll open a PR to your personal branch.

**Comment by Sheikh-Abubaker** [comment]
> The memberlist port is still hardcoded to `7946` (grep for it in the helm templates) though.

May I substitute those harcdoded value with varibles ? as we did it for http and grpc ?

**Comment by bebosudo** [comment]
> > The memberlist port is still hardcoded to `7946` (grep for it in the helm templates) though.
> 
> May I substitute those harcdoded value with varibles ? as we did it for http and grpc ?

The problem with that port number is that there is currently no variable in the helm values that defines the port, so the default port is hardcoded everywhere: if you `grep` for the port number `7946` you'll only find occurrences in service.yaml files, but not in config files! So if we search-and-replace it everywhere, loki will spawn the process on the default 7946, but the services would be listening on another port number.

From the [loki docs](https://grafana.com/docs/loki/latest/configure/#memberlist) it seems it can be set with the following variable:

```
# Gossip port to advertise to other members in the cluster. Used for NAT
# traversal.
# CLI flag: -memberlist.advertise-port
[advertise_port: <int> | default = 7946]
```

In the values file we can define values to be set in the [memberlist section](https://github.com/grafana/loki/blob/3b2278d6ff4e0a2fd722848467457afeae60afbb/production/helm/loki/values.yaml#L106-L108) of the config. Therefore I added to my values the following:
```
loki:
  extraMemberlistConfig:  
    advertise_port: 7498
```

And the value shows up correctly in the configmap:
```
[alberto@fedora]$ k get cm/loki -o yaml
apiVersion: v1
data:
  config.yaml: |2
    ...
    memberlist:
      advertise_port: 7498
      join_members:
      - loki-memberlist
```

And loki seems to read it without any issue:
```
$ curl loki-backend:3101/config

target: backend
http_prefix: ""
...
memberlist:
  node_name: ""
  ...
  advertise_addr: ""
  advertise_port: 7498
```

But the pods are not obeying it somehow:
```
[alberto@fedora]$ k exec -it pod/loki-backend-0 -c loki -- sh
/ $ netstat -tuplen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::3101                 :::*                    LISTEN      1/loki
tcp        0      0 :::9096                 :::*                    LISTEN      1/loki
tcp        0      0 :::7946                 :::*                    LISTEN      1/loki
```

For this reason I'd open a separate issue. If you find a solution ping me in the new PR and I'll happily test it!

**Comment by Sheikh-Abubaker** [comment]
> But the pods are not obeying it somehow:
> 
> ```
> [alberto@fedora]$ k exec -it pod/loki-backend-0 -c loki -- sh
> / $ netstat -tuplen
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
> tcp        0      0 :::3101                 :::*                    LISTEN      1/loki
> tcp        0      0 :::9096                 :::*                    LISTEN      1/loki
> tcp        0      0 :::7946                 :::*                    LISTEN      1/loki
> ```
> 
> For this reason I'd open a separate issue. If you find a solution ping me in the new PR and I'll happily test it!

@bebosudo We'll together find the solution together about the pods not obeying, I'm onto completing the above memberlist port task

**Comment by Sheikh-Abubaker** [comment]
> > But the pods are not obeying it somehow:
> > ```
> > [alberto@fedora]$ k exec -it pod/loki-backend-0 -c loki -- sh
> > / $ netstat -tuplen
> > Active Internet connections (only servers)
> > Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
> > tcp        0      0 :::3101                 :::*                    LISTEN      1/loki
> > tcp        0      0 :::9096                 :::*                    LISTEN      1/loki
> > tcp        0      0 :::7946                 :::*                    LISTEN      1/loki
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For this reason I'd open a separate issue. If you find a solution ping me in the new PR and I'll happily test it!
> 
> @bebosudo We'll together find the solution together about the pods not obeying, as of now I'll do the above memberlist port task

**Comment by bebosudo** [comment]
I'd discourage putting the memberlist port task change in this PR: these are different changes and it'd be better fixing them in different PRs.
1 PR, 1 simple fix.

**Comment by Sheikh-Abubaker** [comment]
> advertise_port:

@bebosudo okk, is there anything I'm supposed to do for this PR ?

**Comment by bebosudo** [comment]
> @bebosudo okk, is there anything I'm supposed to do for this PR ?

Nope, it's ready for review by a maintainer :-)

**Comment by Sheikh-Abubaker** [comment]
> Nope, it's ready for review by a maintainer :-)

It was great working with you, looking forward to connecting. solving more issues and opening PR's together :-)

**Review by MichelHollands — APPROVED** [review]

**Comment by MaxThom** [comment]
Hey guys! I think this PR introduced an issue on the templates/monitoring/_helpers-monitoring.tpl.
So this PR changed from hardcoded to the templated values, but in the printf function, its using %s instead of %d which causes this error in the agent.

```
grafana-agent 2024/03/17 22:40:27 error loading config file /var/lib/grafana-agent/config/agent.yml: parse "http://hummus-loki.max-dev.svc.cluster.local:%!s(float64=3100)/loki/api/v1/push": invalid port ":%!s(float64=3100)" after host 
```

If I overwrite the http_listen_port to "3100" (with quotes), then it works, but then the loki core fails with same error: want int instead of string.

I think we simply need to modify the _helpers file with %d instead of %s

Ive been trying the single binary installation, here's my values:
```yaml
  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: "filesystem"
  singleBinary:
    replicas: 1
```

**Comment by MichelHollands** [comment]
> Hey guys! I think this PR introduced an issue on the templates/monitoring/_helpers-monitoring.tpl. So this PR changed from hardcoded to the templated values, but in the printf function, its using %s instead of %d which causes this error in the agent.

@MaxThom Apologies, that did indeed cause a problem. The fix is here: https://github.com/grafana/loki/pull/12242

**Pull request merged**
