### PR TITLE
feat(lambda-promtail): build lambda with zip file

### PR DESCRIPTION
**Pull request by maxforasteiro**
**What this PR does / why we need it**: 
Avoid having to create ECRs repos and building image with terraform instead.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:
This is my first contribution. Let me know if there's anything else I can do to get this pushed to main. Our idea is to use `tools/lambda-promtail` as a module from our IaC without any extra steps. We have already implemented and tested a similar solution in our IaC and it works.

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [ ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by maxforasteiro** [comment]
> Hey @maxforasteiro . There are a lot of users who already use lamda promatail in the way it was before. could you change your implementation to support both schenarious? I mean to leave it possible to use the link to the image in GCR or upload the archive directly....

Hey @vlad-diachenko, thanks for the quick code review! I just added the ability to either pass the image tag or generate it from the repo itself if it is absent.

**Comment by maxforasteiro** [comment]
hold on, it doesn't seem to work as expected, I'm performing some tests on my side

**Comment by maxforasteiro** [comment]
hey @vlad-diachenko! can you take a look now?

**Comment by vlad-diachenko** [comment]
> hey @vlad-diachenko! can you take a look now?

sure, I will review it today

**Review by vlad-diachenko — APPROVED** [review]
looks great. thanks @maxforasteiro

**Pull request merged**
