### PR TITLE
Publish backported documentation to the v2.0.x release directory

### PR DESCRIPTION
**Pull request by jdbaldry**
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

### CODE REVIEW

**Comment by jdbaldry** [comment]
I think this is still valid and will try and rerun the CI.

**Comment by jdbaldry** [comment]
I'm not sure I'm able to approve builds in Drone. I get "not found" when I click on the button.

**Comment by jdbaldry** [comment]
Another bump for this PR. I'm happy to close it if it is not a priority.

**Review by MichelHollands — APPROVED** [review]
LGTM but you might have to rebase as it's failing in a Helm and Docker step in the CI.

**Comment by jdbaldry** [comment]
Is it failing? I can't investigate the drone pipelines which report as "pending" to me. The CircleCI is failing at least so I will rebase and see if it fixes.

**Comment by jdbaldry** [comment]
I just fetched and I don't believe there are any changes to the `release-2.0.1` branch that I can rebase on.

**Comment by jdbaldry** [comment]
@grafana/loki-squad could somebody override CI and merge this quick fix?

**Pull request merged**
