### PR TITLE
promtail: GCPLog fixing `failed to receive pubsub messages` error

### LINKED ISSUE #6505: GCPLog stops consuming messages
**Describe the bug**
I have three instances of promtail running with the gcplog configuration and I noticed that they all had stopped consuming messages during the weekend. They all got `caller=target.go:111 msg="failed to receive pubsub messages" error="context deadline exceeded"` at different times during the day and after that stopped consuming messages completely. I'm running version `2.5.0`. 
I narrowed down the issue to this part of the code. If `sub.Receive` returns an error the gcplog target will stop consuming messages and cancel its context according to these lines 👇 

https://github.com/grafana/loki/blob/d9a522e5e6f93965324410d4b75a4cabd9ea1ac6/clients/pkg/promtail/targets/gcplog/target.go#L102-L115

**Expected behaviour**
- The gcplog target should retry on timeout issues 

**Environment**
* Infrastructure: GKE 1.22
* Promtail 2.5.0

### PR DESCRIPTION
**Pull request by dmitri-lerko**
1. Read our CONTRIBUTING.md guide
2. Name your PR as `<Feature Area>: Describe your change`.
  a. Do not end the title with punctuation. It will be added in the changelog.
  b. Start with an imperative verb. Example: Fix the latency between System A and System B.
  c. Use sentence case, not title case.
  d. Use a complete phrase or sentence. The PR title will appear in a changelog, so help other people understand what your change will be.
3. Rebase your PR if it gets out of sync with main
-->

**What this PR does / why we need it**:
Upgrades PubSub to the latest. Myself and other users observe frequent disconnects from PubSub which was addressed upstream. High load production testing has proven that this fixes the problem. As an extra bonus, PubSub seems to ingest ~33% faster with the latest library.

**Which issue(s) this PR fixes**:
Fixes #6505

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [x] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by dmitri-lerko** [comment]
I did not include `go mod vendor` in this PR as it adds 37 files to `vendor/`. Not sure what is the right approach for this kind of changes.

**Comment by slim-bean** [comment]
This is awesome @dmitri-lerko thanks for this and thanks for testing/sharing your outcomes!

**Comment by slim-bean** [comment]
to make the CI happy you have to run:
```
go mod vendor
go mod tidy
```

I suspect you are missing the `tidy`

**Comment by dmitri-lerko** [comment]
Thanks @slim-bean . I've followed your suggestion and that bloats this PR enormously. However, I've checked previous bumps similar to this and they all seem to be massive. [Example](https://github.com/grafana/loki/pull/6912/files).

**Comment by slim-bean** [comment]
> Thanks @slim-bean . I've followed your suggestion and that bloats this PR enormously. However, I've checked previous bumps similar to this and they all seem to be massive. [Example](https://github.com/grafana/loki/pull/6912/files).

Yep... this is fairly typical, and thanks for checking other examples!

**Review by slim-bean — APPROVED** [review]
LGTM

**Comment by slim-bean** [comment]
Thanks again @dmitri-lerko!

**Pull request merged**
