### PR TITLE
fix: Missing password for Loki-Canary when loki.auth_enabled is true

### LINKED ISSUE #10873: [Helm] Self-Monitoring fails when loki.auth_enabled is true and/or gateway.basicAuth.enabled is true
**Describe the bug**
Logs of the self monitoring deployment cannot be shipped to loki tenancy is activated (default) and/or if the gateway basic authentication is enabled.

Issue:
1. The grafana agent is not configured with basic authentication credentials but only with the `tenant_id` field which sets the `X-Scope-OrgID` header [source-code](https://github.com/grafana/loki/blob/8e9635f41a4c32c79d5779b8d719473ea413542e/production/helm/loki/templates/monitoring/_helpers-monitoring.tpl#L23), [promtail-doc](https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#clients).
2. The default gateway config overrides the `X-Scope-OrgID` header with the basic auth username which is resulting in an empty header value [source-code](https://github.com/grafana/loki/blob/8e9635f41a4c32c79d5779b8d719473ea413542e/production/helm/loki/values.yaml#L1407)
3. The grafana agent cannot push logs to loki as now the org id header is set to an empty value

Relevant agent log:

```bash
ts=2023-10-12T13:01:44.570096519Z caller=client.go:430 level=error component=logs logs_config=loki/loki component=client host=loki-gateway.loki.svc.cluster.local msg="final error sending batch" status=401 tenant=self-monitoring error="server returned HTTP status 401 Unauthorized (401): no org id"
```

Gateway logs with the default configuration:

```bash
10.42.0.104 - - [12/Oct/2023:12:45:03 +0000]  401 "POST /loki/api/v1/push HTTP/1.1" 10 "-" "GrafanaAgent/" "-"
```

Gateway logs when the `proxy_set_header` directive in the gateways nginx.conf is commented:

```bash
10.42.0.104 - - [12/Oct/2023:12:41:42 +0000]  204 "POST /loki/api/v1/push HTTP/1.1" 0 "-" "GrafanaAgent/" "-"
```

**To Reproduce**
1. Use the loki helm chart with the following config (for local deployment with rancher for example):
```yaml
minio:
  enabled: true

write:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    maxReplicas: 6
  affinity: ""

read:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    maxReplicas: 6
  affinity: ""

backend:
  replicas: 3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 6
  affinity: ""
```
```bash
kubectl create ns loki && helm install --values loki.yml -n loki loki grafana/loki
```

2. Check the logs of the agent: 
```bash
kubectl logs -n loki -l operator.agent.grafana.com/type=logs
```

**Expected behavior**
The default configuration works to send logs with the agent to loki (`loki.auth_enabled: true`). I.e. the agent configuration contains at least `basic_auth.username` so that nginx set's the correct header. And if basic auth on the gateway is enabled also the password.
Inspect the config:
```bash
kubectl get secrets -n loki loki-logs-config -o go-template='{{ index .data "agent.yml" }}' | base64 -d
```

Generated configuration with the default loki multi tenancy configuration (above):

```yaml
logs:
    configs:
        - clients:
            - external_labels:
                cluster: loki
              tenant_id: self-monitoring
              url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
          name: loki/loki
          scrape_configs:
            (...)
```

Expected when gateway basic auth is not enabled:
```yaml
logs:
    configs:
        - clients:
            - external_labels:
                cluster: loki
              tenant_id: self-monitoring
              url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
              basic_auth:
                username: self-monitoring
                (password: if needed some random value)
          name: loki/loki
          scrape_configs:
            (...)
```
(This could also be fixed by adjusting the default nginx config mentioned in the comment below)

Expected when gateway basic auth is enabled:
```yaml
logs:
    configs:
        - clients:
            - external_labels:
                cluster: loki
              tenant_id: self-monitoring
              url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
              basic_auth:
                username: self-monitoring
                password: some-password-set
          name: loki/loki
          scrape_configs:
            (...)
```

The password could either be set on the selfMonitoring tenant or in the loki tenants, but then it should be documented that the tenant the self monitoring uses must be configured with a password in the loki tenants (relevant [source-code](https://github.com/grafana/loki/blob/8e9635f41a4c32c79d5779b8d719473ea413542e/production/helm/loki/values.yaml#L1379).

**Environment:**
 - Infrastructure: Kubernetes on rancher desktop
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
See above

### PR DESCRIPTION
**Pull request by win5923**
**What this PR does / why we need it**:

When `loki.auth_enabled` is true, `loki-canary` cannot set a password. Add a password parameter to address this issue. Additionally, the functionality can also be achieved through existSecret, but this PR does not implement that feature.

**Which issue(s) this PR fixes**:
Fixes #10873

**Special notes for your reviewer**:

**Checklist**
- [X] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by win5923** [comment]
Hi @JStickler, this PR is ready. If there are any issues, please let me know. Thank you!

**Comment by win5923** [comment]
@MichelHollands. Would you be able to review?

**Comment by MichelHollands** [comment]
@win5923 Thanks for the contribution. If you rebase/merge on the latest version then I'll approve this.

**Comment by MichelHollands** [comment]
> > @win5923 Thanks for the contribution. If you rebase/merge on the latest version then I'll approve this.
> 
> Done!

Thanks but something went wrong. The new version should be 6.3.2

**Review by MichelHollands — APPROVED** [review]

**Comment by MichelHollands** [comment]
@win5923 1 more change is needed. The documentation needs to be updated. Please run the command mentioned in the failing CI step.

**Comment by win5923** [comment]
Sorry for the delay, it's done!

**Pull request merged**
