### PR TITLE
fix(helm): Loki Helm Chart: Adjust HPA template for ingester

### PR DESCRIPTION
**Pull request by ivanfavi**
**What this PR does / why we need it**:
When configuring the Horizontal Pod Autoscaler for loki ingester I encountered the following error message
```
│ Events:                                                                                                                                                                               │
│   Type     Reason          Age                From                       Message                                                                                                      │
│   ----     ------          ----               ----                       -------                                                                                                      │
│   Warning  FailedGetScale  10s (x3 over 40s)  horizontal-pod-autoscaler  no matches for kind "Statefulset" in group "apps

The kind is incorrectly written as "Statefulset" instead of "StatefulSet" in the HPA template.
This change will allow the Helm chart to recognize the kind properly and deploy the HPA without errors.

```
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Checklist**
- [X] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [X] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [X] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by oleksii-boiko-ua — APPROVED** [review]

**Comment by JStickler** [comment]
Error message for the failing helm-ci/Link Helm Chart check "Documentation not up to date. Please run helm-docs and commit changes!"

**Comment by ivanfavi** [comment]
@JStickler I've updated the docs, let me know if anything is missing

**Review by DylanGuedes — APPROVED** [review]

**Comment by DylanGuedes** [comment]
@ivanfavi could you fix the conflicts? i'm adding this one to my tracking page so it won't slip

**Comment by JStickler** [comment]
Closed as duplicate of #13158

**Pull request closed without merging**
