### PR TITLE
[ui] add '/config' page

### PR DESCRIPTION
**Pull request by liguozhong**
[ui] add '/config' page
image

### CODE REVIEW

**Comment by cyriltovena** [comment]
Love it Thanks @liguozhong. We'll need to merge main though but that looks super good.

**Comment by sandeepsukhani** [comment]
@liguozhong can you please rebase this to get it merged?

**Comment by liguozhong** [comment]
> @liguozhong can you please rebase this to get it merged?

👌

**Comment by liguozhong** [comment]
> @liguozhong can you please rebase this to get it merged?

done.

**Comment by liguozhong** [comment]
> > @liguozhong can you please rebase this to get it merged?
> 
> done.

@sandeepsukhani  Review required

**Review by dannykopping — APPROVED** [review]
LGTM, thanks for this!

**Review by kavirajk — APPROVED** [review]
🎉

**Pull request merged**
