### PR TITLE
[release-2.4] Docs: add an empty subsection for v2.4.2 bug fix items

### PR DESCRIPTION
**Pull request by grafanabot**
Backport c03614efe5032c7e4b0a94a12e94407bd806526b from #5056

### CODE REVIEW

**Comment by KMiller-Grafana** [comment]
v2.4.2 release team and REVIEWERS: Do not merge in the PR until ready to release 2.4.2.  Merging in this PR will cause the published v2.4 docs to have the 2.4.2 release notes, and that would be a poor idea. v2.4.1 docs readers could/would be confused by seeing 2.4.2 info prior to a 2.4.2 release.

**Comment by dannykopping** [comment]
> v2.4.2 release team and REVIEWERS: Do not merge in the PR until ready to release 2.4.2. Merging in this PR will cause the published v2.4 docs to have the 2.4.2 release notes, and that would be a poor idea. v2.4.1 docs readers could/would be confused by seeing 2.4.2 info prior to a 2.4.2 release.

@KMiller-Grafana I've marked the PR as draft to prevent an accidental merge.

**Review by dannykopping — APPROVED** [review]
Approving to unblock, I think we can proceed with this PR now?

**Comment by KMiller-Grafana** [comment]
@dannykopping I think that this PR got pulled in in a different way when doing the 2.4.2 release.  I see the released docs with the 2.4.2 release notes.

What should happen to this PR?  Just close it?

**Comment by kavirajk** [comment]
@KMiller-Grafana yea. we can just close the PR in that case.

Closing it :)

**Pull request closed without merging**
