### PR TITLE
fix error of remark

### PR DESCRIPTION
**Pull request by shadon178**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by dannykopping — APPROVED** [review]
Thank you! Please sign the CLA so we can merge this

**Comment by dannykopping** [comment]
@shadon178 please sign the CLA so we can merge this PR

**Comment by kavirajk** [comment]
@shadon178 another reminder to sign the CLA :)

**Comment by owen-d** [comment]
Going to close this due to lack of CLA :( . Happy to merge if/when it's signed+reopened

**Pull request closed without merging**
