### PR TITLE
Helm: add support for additional labels on loki-canary pods

### PR DESCRIPTION
**Pull request by terjesannum**
Add support for setting additional labels on the loki-canary pods

### CODE REVIEW

**Review by MichelHollands — APPROVED** [review]
LGTM

**Comment by MichelHollands** [comment]
@terjesannum  Sorry, I approved this too quickly. Can you also update production/helm/loki/CHANGELOG.md?

**Review by JStickler — APPROVED** [review]
l[docs team] LGTM, just note Michel's comment about updating the CHANGELOG.

**Comment by MichelHollands** [comment]
@terjesannum Thanks for the contribution. 5.7.0 is already taken now. Can you change the version to 5.7.1? Once that is done I'll merge it.

**Review by MichelHollands — APPROVED** [review]
LGTM

**Pull request merged**
