### PR TITLE
feat(mixins): Allow hiding useless rows in loki-operational

### PR DESCRIPTION
**Pull request by QuentinBisson**
**What this PR does / why we need it**:

Loki operationnal exposes a lot of rows that are usually not used because we do not send data to 5 different storage backends so it makes sense to be able to hide the rows we do not need to make for a cleaner dashboard

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by QuentinBisson** [comment]
hey @cstyan do you know if I could have some reviews on my mixins PRs?

**Review by cstyan — APPROVED** [review]
@QuentinBisson Sorry, I was away on vacation for a few weeks. 

Tested this one locally and it looks good to me! We'll definitely make use of this ourselves to hide some rows that are no longer relevant to us.

**Comment by QuentinBisson** [comment]
@cstyan no worries, I know you're really busy :) Thank you for the reviews. I feel bad that I have to ping you for those actually.

On another topic, as I'm in the process a becoming a Grafana Champion, do you think it would make sense that I help out in the maintenance of the mixins and maybe helm chart for loki as we use them quite heavily? This might help you with the high load of open source PRs :) 

I'll merge the ones in conflicts today

**Comment by cstyan** [comment]
> @cstyan no worries, I know you're really busy :) Thank you for the reviews. I feel bad that I have to ping you for those actually.

No worries at all, I appreciate you keeping up with the reminders, it can be easy to lose track of some PRs!

> On another topic, as I'm in the process a becoming a Grafana Champion, do you think it would make sense that I help out in the maintenance of the mixins and maybe helm chart for loki as we use them quite heavily? This might help you with the high load of open source PRs :)

That's great to hear! I was actually going to check internally if we could do anything like send you a shirt or something, LMK if they don't do that as apart of the Grafana Champion program. We would love help maintaining the mixins and helm charts, so by all means go for it :+1:

**Comment by QuentinBisson** [comment]
Do you know if it is possible to be added to the codeowners for the mixins and helm chart or would you prefer some first thoughts on the PRs and a ping so someone in your team a second look and approve? What do you think would be the best course of action?

**Pull request merged**
