### PR TITLE
Remove unused code from cortex

### PR DESCRIPTION
**Pull request by cyriltovena**
Signed-off-by: Cyril Tovena <cyril.tovena@gmail.com>

**What this PR does / why we need it**:

When forking cortex we added a lot of unused code, this PR removes it.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by cyriltovena** [comment]
Similar to https://github.com/grafana/loki/pull/5627 but removes even more.

**Review by dannykopping — APPROVED** [review]
LGTM

**Review by sandeepsukhani — APPROVED** [review]
LGTM

**Review by simonswine — APPROVED** [review]
Nice. LGTM

**Review by jeschkies — APPROVED** [review]
Nice. I've failed doing this at #5633. However, ideally our ruler would be tested not the imported one. That's probably too much of an effort.

**Pull request merged**
