### PR TITLE
Added option that loki service run as nodeport

### PR DESCRIPTION
**Pull request by jmvizcainoio**
I was added to service  to allow work as  NodePort

### CODE REVIEW

**Comment by daixiang0** [comment]
Do you want to push data with some custom scripts which running at nodes? It is not common use case i think.

**Comment by jmvizcainoio** [comment]
> Do you want to push data with some custom scripts which running at nodes? It is not common use case i think.

Hi, 

I have some internals k8s cluster and using loki to manage the logs but i want only one grafana for this reason i need to expose ( internally ) loki to grafana. 

Thanks

**Comment by daixiang0** [comment]
If your Grafana is in k8s, you can use `http://loki:3100` as loki url, the `loki` is service name, the `3100` is port, no need to use nodePort.

**Comment by jmvizcainoio** [comment]
Hi,

its outside of this k8s cluster.

I have three k8s clusters with loki but only one with grafana. In the loki
that are installed in the same cluster that grafana i don't need use
nodeport, and i'm using http://loki:3100 but in the another clusters that
loki is installed without grafana is necessary expose the port to allow
grafana access to loki.

Thanks

**Pull request merged**
