### PR TITLE
Helm: Fix single binary checksum annotation for config.yaml

### LINKED ISSUE #9545: no template "loki/templates/configmap.yaml" associated with template "gotpl"
Hi,

I'm getting the following error when trying to deploy the latest helm chart (5.5.10):

```
  Warning  error  78s (x2 over 10h)  helm-controller  Helm install failed: template: loki/templates/single-binary/statefulset.yaml:42:28: executing "loki/templates/single-binary/statefulset.yaml" at <include (print .Template.BasePath "/configmap.yaml") .>: error calling include: template: no template "loki/templates/configmap.yaml" associated with template "gotpl"
```
Could it be that the following reference is wrong and should be pointing to `/config.yaml`?:

https://github.com/grafana/loki/blob/d1fd6b78832e2c4dff1e0adf7bcf1b884ca7c251/production/helm/loki/templates/single-binary/statefulset.yaml#LL42C65-L42C74

These are the relevant settings I set in my config:

```yaml
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
    singleBinary:
      replicas: 1
```

### PR DESCRIPTION
**Pull request by andrebossi**
**What this PR does / why we need it**:
This PR fix name to config checksum annotation

**Which issue(s) this PR fixes**:
Fixes #9545

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] `CHANGELOG.md` updated
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Comment by MichelHollands** [comment]
@andrebossi Thanks for this contribution. Can you update the helm readme as well and rebase?

**Comment by andrebossi** [comment]
I performed the rebase with the master branch and fixed the correction in the changelog

**Review by MichelHollands — APPROVED** [review]
LGTM

**Comment by yellowhat** [comment]
Hi,
I do not think that this fix is part of 5.5.11.
Maybe you forgot to bump the chart version?

Thanks

**Comment by andrebossi** [comment]
Hi, Before sending I updated the version to 5.5.11

**Comment by andrebossi** [comment]
Sorry you are correct other change are incremented in 5.5.11 this release was supposed to be 5.5.12

**Comment by MichelHollands** [comment]
@andrebossi @yellowhat This will be fixed in https://github.com/grafana/loki/pull/9576

**Pull request merged**
