### PR TITLE
Add query-frontend option to select request headers in query logs

### LINKED ISSUE #11422: Log value of arbitrary request headers in query frontend stats log
**Is your feature request related to a problem? Please describe.**
For greater visibility into the source of a query, add the ability in Loki to log the value of an arbitrary set of request headers in the query frontend stats log.

For example, if a Loki operator wanted to log the originating IP address of the sender after being sent the data through a proxy, adding the header X-Forwarded-For could be added to this configuration to log the IP address to the query stats log.

**Describe the solution you'd like**
Implementing similiar functionality as https://github.com/grafana/mimir/pull/5030 in loki. Specifically for this log line https://github.com/jmichalek132/loki/blob/main/pkg/logql/metrics.go#L120.

**Describe alternatives you've considered**
There is support for logging key values present in a header `X-Query-Tags`. But that would require proxy populating those headers. Instead I think it would make sense to support something that is already supported in Mimir.

**Additional context**
Linking original issue for implementing the same in mimir https://github.com/grafana/mimir/issues/4815.
If maintainer are willing to accept this change I am willing to implement it.

### PR DESCRIPTION
**Pull request by jmichalek132**
**What this PR does / why we need it**:

Adding feature present in mimir, specifically https://github.com/grafana/mimir/pull/5030.

Adds a config option to the query-frontend to specify a list of request headers to include in query logs.

For example, setting -frontend.log-query-request-headers="X-Grafana-Org-Id" and sending a query with X-Grafana-Org-Id:1 results in query log lines that include header_x_grafana_org_id=1.

**Which issue(s) this PR fixes**:
Fixes #11422

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [x] Tests updated
- [x] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by jmichalek132** [comment]
Not sure how to safely update docs.

**Comment by JStickler** [comment]
>Not sure how to safely update docs.

@jmichalek132  I'm not quite sure what you mean by "safely" update the docs?  All docs updates are published to the "next" branch until the next Loki release is cut.  Doc updates aren't published to the current release unless someone backports the PR.  So any changes to docs won't  published until the code changes are part of a release.  You can either do the docs updates as part of this PR (my recommendation) or as a separate PR.

**Comment by jmichalek132** [comment]
> > Not sure how to safely update docs.
> 
> @jmichalek132 I'm not quite sure what you mean by "safely" update the docs? All docs updates are published to the "next" branch until the next Loki release is cut. Doc updates aren't published to the current release unless someone backports the PR. So any changes to docs won't published until the code changes are part of a release. You can either do the docs updates as part of this PR (my recommendation) or as a separate PR.

Hi, sorry for the late reply, I meant if there is something in the makefile that would generate the the docs for flags from the code, or is it just maintained manually?

**Comment by JStickler** [comment]
@jmichalek132   The configuration reference and Helm reference are the only docs that I know of that we're automatically generating,  as far as I know we're not generating any docs from Go files.

**Comment by jmichalek132** [comment]
@JStickler I updated the docs.

**Comment by JStickler** [comment]
@jmichalek132 The configuration reference should be updated in `docs/sources/configure/index.template`. There's a note to that effect at line 12 of the `docs/sources/configure/_index.md` file, you must have missed it.

**Comment by jmichalek132** [comment]
> @jmichalek132 The configuration reference should be updated in `docs/sources/configure/index.template`. There's a note to that effect at line 12 of the `docs/sources/configure/_index.md` file, you must have missed it.

I haven't modified that file directly, I ran `make doc`, which updated the file.

**Comment by JStickler** [comment]
Looks like we've got a file conflict, and this error message "Please format code by running 'make format' and committing the changes" that needs fixing.

**Comment by jmichalek132** [comment]
> Looks like we've got a file conflict, and this build error message "Please format code by running 'make format' and committing the changes" that needs fixing.

Fixed both.

**Comment by jmichalek132** [comment]
fyi the conflict comes from changelog, and will happen every time someone else updates. it.

**Review by dannykopping — APPROVED** [review]
Very cool, thank you for your contribution @jmichalek132 👍

**Pull request merged**
