### PR TITLE
Helm: Use stable autoscaling/v2 if possible

### PR DESCRIPTION
**Pull request by mstrzele**
**What this PR does / why we need it**:
It checks if the Kubernetes cluster, on which Loki is being installed using Helm, supports the stable version of the autoscaling API group.

[`HorizontalPodAutoscaler` v2 graduated to GA in Kubernetes 1.23](https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/#horizontalpodautoscaler-v2-graduates-to-ga). The v2beta1 and v2beta2 became deprecated, and they will be removed in Kubernetes 1.26 which is going to be released in December 2022.

**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [x] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by mstrzele** [comment]
```
GET https://github.com/grafana/mimir/archive/91986521f324c84a9cf869529bd901f077ddf8bc.tar.gz 200
34s
8	archive install failed: open /src/loki/production/loki-mixin/vendor/.tmp/jsonnetpkg-github.com-grafana-mimir-operations-mimir-mixin-91986521f324c84a9cf869529bd901f077ddf8bc165508893.tar.gz: no such file or directory
38s
9	retrying with git...
38s
10	jb: error: failed to install packages: downloading: chdir /src/loki/production/loki-mixin/vendor/.tmp/jsonnetpkg-github.com-grafana-mimir-operations-mimir-mixin-91986521f324c84a9cf869529bd901f077ddf8bc165508893: no such file or directory
38s
11	make: *** [Makefile:212: loki-mixin] Error 1
```

I assume it isn't related to the changes I've made, is it?

**Review by jeschkies — APPROVED** [review]

**Comment by trevorwhitney** [comment]
@mstrzele I think that mixin check was broken on master, would you bind rebasing this with `main` and seeing if that fixes it?

**Comment by MichelHollands** [comment]
@mstrzele Thanks for this contribution. Can you rebase? Once that is done I'll merge it.

**Comment by quentinplessis** [comment]
@mstrzele 
I think this change broke the helm chart for kubernetes versions supporting `autoscaling/v2` API.
I got the following error:
```
Error: Failed to render chart: exit status 1: Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2.ResourceMetricSource]
```

I think the HPA settings are based on `autoscaling/v2beta1` specification, which is incompatible with `autoscaling/v2`.
https://github.com/grafana/loki/blob/main/production/helm/loki/templates/gateway/hpa.yaml#L25

Adjusting HPA settings to support `autoscaling/v2` is the long-term option, but as the chart is currently broken would it be possible to revert this change ? Should I create an issue ?

**Pull request merged**
