### PR TITLE
fix(helm): add default wal dir to ruler config

### PR DESCRIPTION
**Pull request by thevops**
**What this PR does / why we need it**:

The change adds a default configuration for `rulerConfig`.

There are many issues related to the lack of the setting from this Pull Requests. For example:
- https://github.com/grafana/loki/issues/9114
- https://github.com/grafana/loki/issues/9351
- https://github.com/grafana/loki/issues/7377

The issues are not directly related, but examples of configuration shared by people often contains such change. It's worth to add it since anyway users do it.

**Which issue(s) this PR fixes**:
Fixes -

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by trevorwhitney — APPROVED** [review]
Please add a CHANGELOG entry, thanks!

**Comment by thevops** [comment]
@trevorwhitney changelog entry done. We can continue with CI and merge.

**Comment by trevorwhitney** [comment]
@thevops the helm chart has it's own [CHANGELOG.md](https://github.com/grafana/loki/blob/e0ac0d0efd02b9af607fdb3de682619bdf7de80d/production/helm/loki/CHANGELOG.md?plain=1#L1), please update that file instead

**Comment by thevops** [comment]
@trevorwhitney oh, sorry.
Added 67e721134b4656b7e641b509446aca946e789462

**Pull request merged**
