### PR TITLE
Build debug images with `make debug`

### PR DESCRIPTION
**Pull request by slim-bean**
Builds a set of docker images which include delve and wrap the promtail/loki binaries with the delve command and open a connection for a remote debugger.

### CODE REVIEW

**Comment by daixiang0** [comment]
could it support with helm?
since now `ks` has abandoned, less and less users would use it.

**Comment by davkal** [comment]
@daixiang0 IMO the helm use case is less relevant here, since those are images with debuggers. What helm would need is a debug option to run the normal images with debug log output, which is different from shipping images with a debugger.

**Comment by daixiang0** [comment]
i got it.
But since `ks` does not update, when k8s  upgrade, would be hard to debug with `ks`

**Comment by slim-bean** [comment]
When running locally if the k8 deployment image tag is `latest`, you can
just delete the pod and it will use the newest image when it is recreated

**Pull request merged**
