### PR TITLE
Helm: Loki config resource use secret instead of configmap

### LINKED ISSUE #7357: [Helm] Create loki config as Secret instead of ConfigMap
**Is your feature request related to a problem? Please describe.**
In some environments we are required to utilize S3 Programmatic Credentials and when these are created in cluster via the Helm chart these credentials get created within a ConfigMap, since there are credentials that should be obfuscated, the config should be within a Secret resource similar to the [`loki` helm-chart setup](https://github.com/grafana/helm-charts/blob/loki-2.14.0/charts/loki/templates/secret.yaml#L10).

**Describe the solution you'd like**
Loki configuration is placed within a Kubernetes Secret resource instead of ConfigMap.

**Describe alternatives you've considered**
In a few environments we have utilized `existingSecretForConfig` but we use ephemeral clusters and it's much simpler to have the config created in-cluster as a secret compared to creating the secret ourselves and placing it in-cluster next to the Helm-chart via gitops.

### PR DESCRIPTION
**Pull request by rgarcia6520**
Signed-off-by: garcia.ryan <garcia.ryan@solute.us>

**What this PR does / why we need it**:
Since there are options for credentials to be fed into the Loki config, it should be created as a kubernetes Secret opposed to a ConfigMap, this matches setup for (now deprecated) loki single-binary helm-chart. 

**Which issue(s) this PR fixes**:
Fixes #7357

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by trevorwhitney — CHANGES_REQUESTED** [review]
Do you think it should always be a secret? I'm torn on this because we do our secret injections through other means, and I find it much nicer to have a configmap I can edit by hand when in a pinch (ie. a production outage). We already have the option `.Values.loki.existingSecretForConfig` for those who want to put the config in a secret. I understand they lose the benefit of the generated config, so I'm open to an option for putting this in a secret, but I don't think a secret should be the only option.

**Comment by rgarcia6520** [comment]
> I'd say the way should be to use environment and run Loki with expand env or support #7279

That would be fine. Only data that would need obfuscating in the secret are the AWS credentials, so if those could be placed in their own secret and mounted as environment vars (if values are present) or yes more reliable support for using IAM Roles would also work.

**Comment by trevorwhitney** [comment]
I'm also open to an option of opting in to putting the config in a secret, I just don't think it should by default always go into a secret.

**Comment by gclawes** [comment]
Mimir already offers the ability to specify the config storage type (`ConfigMap` or `Secret`), I'd suggest just porting this functionality over:

https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml#L78-L81
https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L109-L123
https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/mimir-config.yaml#L3-L7

**Comment by trevorwhitney** [comment]
I would be happy to approve a PR that does this in the way mimir does as suggested by @gclawes.

**Comment by trevorwhitney** [comment]
Closing this and replacing with an issue to make the config resource type configurable: https://github.com/grafana/loki/issues/8268

**Comment by trevorwhitney** [comment]
https://github.com/grafana/loki/issues/8268

**Pull request closed without merging**
