### PR TITLE
[Optimization] boltdb readpath: reduce the code block affected by the lock tablesMtx in the TableManager.query() function

### PR DESCRIPTION
**Pull request by liguozhong**
**What this PR does / why we need it**:
[Optimization] boltdb: reduce the code block affected by the lock tablesMtx in the TableManager.query() function.

util.DoParallelQueries(ctx, table, queries, callback) , free lock.
@sandeepsukhani  boltdb issue.
image

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Review by sandeepsukhani — APPROVED** [review]
Thanks for the PR! The changes look good to me but I doubt it would help much with the write latency since the read path is using a shared lock.

**Comment by sandeepsukhani** [comment]
@liguozhong this PR might help somewhat https://github.com/grafana/loki/pull/5830

**Comment by liguozhong** [comment]
> Thanks for the PR! The changes look good to me but I doubt it would help much with the write latency since the read path is using a shared lock.



> Thanks for the PR! The changes look good to me but I doubt it would help much with the write latency since the read path is using a shared lock.

I just started reading boltdb code, trying to find lock related code, check if there are optimized code blocks.
This pr is because I saw it during the viewing process.
I'm still trying to find performance optimization points for writes.
We're working on switching from Cassandra to boltdb-shipper, which is a huge change for us, and we hope our team will be more familiar with the boltdb-shipper part of the code before switching to boltdb-shipper from cassandra.

**Comment by liguozhong** [comment]
> @liguozhong this PR might help somewhat #5830

👍，The code of this PR would be helpful. After the PR is merged, we will release boltdb-shipper again to observe the optimization effect.

**Pull request merged**
