### PR TITLE
rename shipper package to boltdbshipper for clarity

### PR DESCRIPTION
**Pull request by sandeepsukhani**
**What this PR does / why we need it**:
The package for `boltdb-shipper` index client was initially named `shipper` to be concise. However, we now have `indexshipper` package taking care of the shipping part and the `shipper` only contains code for reading/writing boltdb files for `boltdb-shipper` index client. To keep things clear, it would be good to rename `shipper` to `boltdbshipper`.

### CODE REVIEW

**Comment by chaudum** [comment]
@sandeepsukhani Do you wanna update this PR?

**Comment by jeschkies** [comment]
@sandeepsukhani would you mind updating your branch?

**Review by jeschkies — APPROVED** [review]

**Comment by jeschkies** [comment]
@sandeepsukhani should we drop this?

**Comment by chaudum** [comment]
@sandeepsukhani This is obsolete now, right?

**Comment by jeschkies** [comment]
@chaudum let's close this. Sandeep can always reopen the PR.

**Pull request closed without merging**
