### PR TITLE
Deprecate Charts as they have been moved

### LINKED ISSUE #2593: Central helm charts repository for grafana?
As the [helm/charts](https://github.com/helm/charts/issues/21103) repository is being deprecated many charts are moving to new location.

For example all Prometheus related charts are being moved to [prometheus-community](https://github.com/prometheus-community) GitHub organisation.

At https://github.com/scottrigby/prometheus-helm-charts you find the current state of that migration. That repository hosts multiple helm charts, CI pipeline is set up using GitHub actions e.g. [kind](https://github.com/helm/kind-action) to spin up a Kubernetes cluster,  [chart-testing](https://github.com/helm/chart-testing-action) to verify helm charts and [super-linter](
https://github.com/github/super-linter) to check the syntax.

While doing that migration the discussion came up wat to do with dependent charts which are still in stable repository. See https://github.com/scottrigby/prometheus-helm-charts/issues/30 and https://github.com/scottrigby/prometheus-helm-charts/pull/1#discussion_r474766376

In the meantime @zanhsieh started migrating [stable/grafana](https://github.com/helm/charts/pull/23662) to [https://github.com/grafana](grafana) GitHub Org.

The goal would be to to have a similar setup to Prometheus or [Jenkins](https://github.com/jenkinsci/helm-charts).
Charts index.ysml is provided via GitHub Pages which even allows to use custom domains like https://charts.jenkins.io/. The chart packages (tgz) are normal GitHub releases. Check https://github.com/scottrigby/prometheus-helm-charts/releases for an example.

Now my question: Would you be interested in hosting the loki charts together with grafana chart in a similar way?

.

### PR DESCRIPTION
**Pull request by torstenwalter**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #2593

**Special notes for your reviewer**:

This should only be merged once grafana/helm-charts#39 is merged and we confirmed that everything is working.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Review by scottrigby — COMMENTED** [review]
@torstenwalter This looks great. Since these charts will not become "un-deprecated" here, do you want to make a follow-up PR to remove the source code from this repo per https://helm.sh/docs/topics/charts/#deprecating-charts?

If you prefer to leave the deprecated source code here, would you instead also add a deprecation note to the `templates/NOTES.txt` file in each of these charts?

**Comment by owen-d** [comment]
It'd be nice to remove the source eventually as @scottrigby suggested. All in all, looks great!

**Comment by torstenwalter** [comment]
@owen-d @scottrigby does it make sense to deprecate the charts here at all or should we simple remove the source code here and leave a note where to find it instead?

**Comment by scottrigby** [comment]
We want to at least create a release to the repo with a deprecated version, so that existing users will have a way to know where to migrate to for future versions.

**Comment by torstenwalter** [comment]
Makes sense. This PR is already updated to do that.

**Review by slim-bean — APPROVED** [review]
LGTM

**Pull request merged**
