### PR TITLE
Setting Julie Stickler as codeowner for docs

### PR DESCRIPTION
**Pull request by dannykopping**
Welcome @JStickler!!

### CODE REVIEW

**Review by kavirajk — APPROVED** [review]
:tada: 

Q: why not add @JStickler to `@grafana/docs-logs` squad instead?

**Comment by dannykopping** [comment]
> 🎉
> 
> Q: why not add @JStickler to `@grafana/docs-logs` squad instead?

We don't need the whole group to be informed whenever there's a Loki docs PR; that was a temporary measure when we had no tech writer.

**Comment by kavirajk** [comment]
>We don't need the whole group to be informed whenever there's a Loki docs PR;

Yea. but that's why it's @grafana/docs-logs. Specific to logs?. My concern is mainly creating PR everytime. Instead add or remove people to the right group which we already have it as codeowner.

**Comment by dannykopping** [comment]
> > We don't need the whole group to be informed whenever there's a Loki docs PR;
> 
> Yea. but that's why it's @grafana/docs-logs. Specific to logs?. My concern is mainly creating PR everytime. Instead add or remove people to the right group which we already have it as codeowner.

Ah, I missed that detail. Well, it's functionally the same for now - if we add any more tech writers later to the Loki team we'll move it back to the group

**Comment by osg-grafana** [comment]
@GrafanaWriter, can you weigh in here given that it is now an exception, given all the other subteams that we use.

**Comment by osg-grafana** [comment]
> > We don't need the whole group to be informed whenever there's a Loki docs PR;
> 
> Yea. but that's why it's @grafana/docs-logs. Specific to logs?. My concern is mainly creating PR everytime. Instead add or remove people to the right group which we already have it as codeowner.

Yes, this is the logic. We now have to manage that Loki does things differently, so heavily in favor or reverting this PR.

**Comment by osg-grafana** [comment]
Relates to https://github.com/grafana/technical-documentation/issues/520.

**Comment by dannykopping** [comment]
@osg-grafana I'm happy to revert this change.

https://github.com/orgs/grafana/teams/docs-logs/members seems to only have yourself and Kim in it; should you replace yourselves with Julie?

**Comment by osg-grafana** [comment]
> @osg-grafana I'm happy to revert this change.
> 
> https://github.com/orgs/grafana/teams/docs-logs/members seems to only have yourself and Kim in it; should you replace yourselves with Julie?

Yes, please replace me and Kim with Julie. Thank you!

**Comment by dannykopping** [comment]
@osg-grafana I don't have permission to do so

**Pull request merged**
