### PR TITLE
[new feature] logql: introduce timestamp syntax

### LINKED ISSUE #7714: [new feature] logql : add timestamp_format
**Is your feature request related to a problem? Please describe.**
My loki is out of order because the time of promtail is not the time in the log, but the system time. I will solve this out-of-order problem by introducing a timestamp stage to promtail.

out of order log in grafana loki explore.
```
2022-11-15 02:49:52 [INFO] /controller.go:actionLoop:309 approached target: 2
2022-11-15 02:49:51 [INFO] /controller.go:actionLoop:309 approached target: 1
2022-11-15 02:49:53 [INFO] /controller.go:actionLoop:309 approached target: 3
```
I've tried to extract the time from the log via logql, but in the end I failed.
`{log_type="system_log"}|="1ac5d591-43a9-4349-a678-c91f7cc0b48d" |regexp `(?P<event_time>.*?) \[` |label_format event_timestemp=`{{ toDate "2006-01-02 15:04:05" .event_time }}`|label_format __timestamp__=`{{.event_timestemp}}`
`
**Describe the solution you'd like**
add `timestamp_format`

`{log_type="system_log"}|="1ac5d591-43a9-4349-a678-c91f7cc0b48d" |regexp `(?P<event_time>.*?) \[` |label_format event_timestemp=`{{ toDate "2006-01-02 15:04:05" .event_time }}`|timestamp_format `{{.event_timestemp}}`

**Describe alternatives you've considered**
Extract the time in the log through the promtail `timestamp` stage, but this requires restarting all promtails(5000+pod), and the time format in the log is random format, it is difficult to convince my boss to approve this solution .

**Additional context**
log out of order log
image

### PR DESCRIPTION
**Pull request by liguozhong**
**What this PR does / why we need it**:

fix out of order log in grafana loki explore on read.
```
2022-11-15 02:49:52 [INFO] /controller.go:actionLoop:309 approached target: 2
2022-11-15 02:49:51 [INFO] /controller.go:actionLoop:309 approached target: 1
2022-11-15 02:49:53 [INFO] /controller.go:actionLoop:309 approached target: 3
```
add `timestamp_format` syntax , Extract the timestamp in the log through logql

for example.
```
{log_type="system_log"}|="1ac5d591-43a9-4349-a678-c91f7cc0b48d" 
|regexp `(?P<event_time>.*?) \[` 
|label_format event_timestemp=`{{ toDate "2006-01-02 15:04:05" .event_time }}`
|timestamp_format `{{.event_timestemp}}`
```

**Which issue(s) this PR fixes**:
Fixes #7714  and  https://github.com/grafana/loki/issues/3535

**Special notes for your reviewer**:
now logql support `label_format` and `line_format` , `timestamp_format` is schema on read road too.

https://grafana.com/docs/loki/latest/logql/template_functions/

This PR has not completed the doc yet, if this PR is merged, then submit a doc pr separately

**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by jeschkies** [comment]
This is a create idea. I would rename the command though. We are not formatting the timestamp but overriding the original. That said, could you rebase onto `main`? We can then discuss the details.

**Comment by liguozhong** [comment]
> This is a create idea. I would rename the command though. We are not formatting the timestamp but overriding the original. That said, could you rebase onto `main`? We can then discuss the details.

rebase done. ready for review.

**Comment by jeschkies** [comment]
Thanks. I'm still not sure if this should be a formatter. As that's always done in the label format. All this does is parse a timestamp from a label and overrides it.

**Comment by liguozhong** [comment]
> Thanks. I'm still not sure if this should be a formatter. As that's always done in the label format. All this does is parse a timestamp from a label and overrides it.



```
type LogEntry struct {
 log string
 timestamp int64
 labels <[__timestamp__:xxx]>
}
```
`label_format '__timestamp__ | ... ' 
`
`label_format` can only affect `__timestamp__` in LogEntry.labels, but grafana log explore is sorted by LogEntry.timestamp int64. This PR is try to modify LogEntry.timestamp int64 in logql.

**Comment by liguozhong** [comment]
If label_format '__timestamp__ | data xxx' can complete log explore sorting, we can provide a document stating that these two issues have been resolved.
My previous attempts failed, so I submitted this PR to try to solve the sorting problem of log explore.
https://github.com/grafana/loki/issues/7714 and https://github.com/grafana/loki/issues/3535

**Comment by JStickler** [comment]
@liguozhong This PR is over a year old. Can we close it? Or are you still hoping to get this merged?

**Comment by marcinfigiel** [comment]
As this PR was closed without merging, is there any workaround for the issue it addressed?

**Pull request closed without merging**
