### PR TITLE
Add custom help info

### PR DESCRIPTION
**Pull request by daixiang0**
Add help info about how to customize config with helm deployment.

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
@steven-sheehy hi, even users use whole values.yaml, helm only overload changed part. Then when they upgrade with `helm upgrade --install`, the fixed parts would be applied.
What you said only occur when users change the part we fix.
In the other hand, not use whole file, users can not get true template then easily go into wrong format.

**Comment by steven-sheehy** [comment]
@daixiang0 That's not Helm [works](https://github.com/helm/helm/blob/master/docs/chart_template_guide/values_files.md). If you pass a custom `values.yaml` via `helm upgrade --install -f custom.yaml` all keys in that yaml will override the one built into the chart.

**Comment by daixiang0** [comment]
Of cource, but users only changes they want, use whole values.yaml still works.

**Comment by daixiang0** [comment]
@davkal hi, any input about this?

**Comment by daixiang0** [comment]
@davkal hi, any input about this?

**Pull request merged**
