### PR TITLE
Remove `cortex/pkg/chunk`

### PR DESCRIPTION
**Pull request by DylanGuedes**
**What this PR does / why we need it**:
Now that we've forked all packages that were relying on `cortex/pkg/chunk`, we can finally get rid of it. This PR removes it.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Review by kavirajk — APPROVED** [review]
LGTM :+1:

**Comment by kavirajk** [comment]
@DylanGuedes looks like license/cla is stuck, can you do some push again? (may be after rebase?)

**Review by sandeepsukhani — APPROVED** [review]
LGTM

**Comment by DylanGuedes** [comment]
> @DylanGuedes looks like license/cla is stuck, can you do some push again? (may be after rebase?)

good call, I did a rebase and looks like it worked

**Pull request merged**
