### PR TITLE
Helm: Add priorityClassName for Grafana Agent and Loki Canary

### PR DESCRIPTION
**Pull request by sjmiller609**
**What this PR does / why we need it**:

- Allow configuring PriorityClassName for the GrafanaAgent daemonset
- Allow configuring PriorityClassName for the loki canary daemonset without also configuring for read deployment
- Helpful when an administrator wants to prioritize logging on their nodes

**Special notes for your reviewer**:

- Used _coalese_ style like it was already in the case of loki canary
- For loki canary, specifying on the canary takes higher precedence than on the reader, but lower than global
- For grafana agent, global takes precedence over grafana agent to match the existing style, but maintainers might consider flipping that around so that most-specific is also most-prioritized

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide

### CODE REVIEW

**Review by JStickler — APPROVED** [review]
[Docs squad] Documentation LGTM

**Comment by sjmiller609** [comment]
@JStickler Anything I can do to help get this in?

**Review by jeschkies — APPROVED** [review]

**Comment by jseiser** [comment]
Just wanted to add that this ends up making the Canary not function, if you are using AWS Karpenter to scale your work loads. 

Karpenter expects DS to have `"system-cluster-critical"`

**Comment by MichelHollands** [comment]
> Karpenter expects DS to have `"system-cluster-critical"`

What do you mean with DS here?

**Comment by sjmiller609** [comment]
> Just wanted to add that this ends up making the Canary not function, if you are using AWS Karpenter to scale your work loads.
> 
> Karpenter expects DS to have `"system-cluster-critical"`

I have submitted this PR in order to configure system-node-critical for daemonsets, I found some did not have a priority class set.

**Comment by sjmiller609** [comment]
🙌

**Pull request merged**
