### PR TITLE
Make sure all ring/kv store/memberlist metrics are prefixed with loki_

### PR DESCRIPTION
**Pull request by cstyan**
This PR contains a subset of the changes from https://github.com/grafana/loki/pull/6439. 

Here I am ensuring that metrics related to the ring (which includes those created by the lifecycler), KV store clients, and general memberlist metrics, are prefixed with `loki_` instead of `cortex_` (or nothing).

None of these metrics are used in the `production/` directory for dashboards or alerts/recording rules

EDIT: Note that this is essentially the minimum changeset to get all memberlist migration related metrics to be prefixed properly with loki since we create an instance of the metrics struct separately per component/service (in the ingester code, distributor code, compactor code, etc.)

Signed-off-by: Callum Styan <callumstyan@gmail.com>

### CODE REVIEW

**Review by dannykopping — APPROVED** [review]
Looks great @cstyan!

Before we merge this, we should perhaps start a v3.0 branch and merge it into that; these changes could be breaking for users' dashboards, so we need to be a bit careful

**Comment by slim-bean** [comment]
I know this will be a bit tedious but can we generate a list of all the metric names that will be changed?

We should include this list in the upgrade guide so people know exactly what metrics need to change.

Changing metrics is always a bit rough as it does break dashboards, however, these are pretty obscure metrics and as long as we are clear in the upgrade guide I think I'm ok with it.

**Comment by cstyan** [comment]
These are the metrics that would have name changes:
```
cortex_consul_request_duration_seconds_bucket -> loki_consul_request_duration_seconds_bucket
cortex_consul_request_duration_seconds_count -> loki_consul_request_duration_seconds_count
cortex_consul_request_duration_seconds_sum -> loki_consul_request_duration_seconds_sum
cortex_dns_failures_total -> loki_dns_failures_total
cortex_dns_lookups_total -> loki_dns_lookups_total
cortex_kv_request_duration_seconds_bucket -> loki_kv_request_duration_seconds_bucket
cortex_kv_request_duration_seconds_count -> loki_kv_request_duration_seconds_count
cortex_kv_request_duration_seconds_sum -> loki_kv_request_duration_seconds_sum
cortex_member_consul_heartbeats_total -> loki_member_consul_heartbeats_total
cortex_ring_members -> loki_ring_members
cortex_ring_oldest_member_timestamp -> loki_ring_oldest_member_timestamp
cortex_ring_tokens_total -> loki_ring_tokens_total
ring_member_heartbeats_total -> loki_ring_member_heartbeats_total
ring_member_tokens_owned -> loki_ring_member_tokens_owned
ring_member_tokens_to_own -> loki_ring_member_tokens_to_own
cortex_ruler_ring_check_errors_total -> loki_ruler_ring_check_errors_total
```

I'll update the changelog and upgrade guide now.

**Review by dannykopping — CHANGES_REQUESTED** [review]
I'll refer to the comment I left in the related PR:
https://github.com/grafana/loki/pull/6439#pullrequestreview-1056800389

I'm changing my review to _Request changes_ because I feel that this could be quite an impactful change if we don't do this carefully, and I want to prevent an accidental merge since we already have approvals.

**Pull request closed without merging**
