### PR TITLE
Add query scheduler to "Read Resources" mixin dashboard

### PR DESCRIPTION
**Pull request by chaudum**
This component has been around for a while but has not been added to the
loki-mixin yet.

Signed-off-by: Christian Haudum <christian.haudum@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by kavirajk — APPROVED** [review]
LGTM 👍. 

Adding a screenshot or public preview link would be helpful to review PR(s) like this IMHO :)

**Comment by chaudum** [comment]
> Adding a screenshot or public preview link would be helpful to review PR(s) like this IMHO :)

Agree. Let me install the dashboards locally.

**Comment by chaudum** [comment]
@kavirajk Added a screenshot to the PR description.

**Comment by cyriltovena** [comment]
Can we stack CPU and memory graph or that is too much ?

**Review by owen-d — APPROVED** [review]

**Comment by kavirajk** [comment]
> @kavirajk Added a screenshot to the PR description.

I don't see it yet. I see it on the other PR though :) https://github.com/grafana/deployment_tools/pull/30245. Feel free to go ahead on merge. It's a non blocker.

**Pull request merged**
