### PR TITLE
Loki: Add multi-tenancy support based off labels in stream

### PR DESCRIPTION
**Pull request by Champ-Goblem**
**What this PR does / why we need it**:
Allows a user to specify a label in order to base org ID off its value, continues to support the two original methods (auth over http header and fake-auth).

I propose this design change so that a cluster running multiple user workloads for different tenants with a single set of collectors can classify the logs better than current implementation where the tenant ID (org ID) can only be statically set in the config for promtail (similar to a suggestion from a previous [issue](https://github.com/grafana/loki/issues/259)).

I'm happy to make adjustments based on your verdicts.

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
I require some advice on altering the documentation in order to add the new schema for multi-tenancy:
```
multi_tenancy:
  enabled: <bool>
  type: <auth|label>
  label: <label name> (can be nil for type auth)
  undefined: <fallback org ID for streams without label> (can be nil for type auth)
```

This schema is designed to replace the original `auth_enabled: <bool>`
**Checklist**
- [x] Tests updated - New tests added for multi-tenancy package as well
- [ ] Documentation added

### CODE REVIEW

**Comment by slim-bean** [comment]
Thanks for the PR @Champ-Goblem! we are a bit backed up at the moment and there is quite a bit to unpack here so it may take us a little bit to get a good response to you on this!

**Comment by midnightconman** [comment]
I have a question @Champ-Goblem ...

My use case is mostly around limiting ingestion (having the capability to throttle customers at the distributor layer), while allowing for a pretty open query (all tenants can query all tenants logs). This is not possible today, as the auth header can only include one tenant per request.
 
Would these changes enable something like that?

**Review by owen-d — COMMENTED** [review]
Hey, I was finally able to take a look at this in depth -- thanks for the PR! I think what you're trying to do seems reasonable (collect logs for multiple tenants from a single collector).

After I thought about it for a bit, I'm not sure this is the way that we should do this. The agents will _already_ need to be tenant-aware in order to assign some tenant label. Wouldn't it make more sense to reduce the coordination burdens between agent<->loki by adding a promtail stage to choose which tenant a log line is assigned to? That would allow the same functionality without the need to complicate the distributor code or expose these extra configs server side (which would require coordination with the agent anyway).

What do you think?

**Comment by Champ-Goblem** [comment]
Hi @midnightconman, unfortunately this change currently doesn't support something like that, although it was another idea that I would like to see implemented as well if this PR or a similar PR gets accepted. Currently the label processing is only done on the api/push endpoint and defaults to the original implementation of setting the org ID via a header for the query endpoints.

**Comment by Champ-Goblem** [comment]
@owen-d Thanks for the review, I see where you are coming from and it was also an alternative idea when I thought about viable solutions. I ended up choosing to implement it server side in order to cut down on the number of network requests that would potentially be made. Splitting the logs by tenant on the collector side we could only group logs of same tenant together each time we pushed, that means at each push interval there could be at most a request per tenant and if we had a large multi-tenant system, this could start to amount to a lot of requests. Wheres by implementing the logic server side we can bundle all of the log lines together and then separate them out once they reach loki, theoretically only needing one network request to send logs for a set of tenants at each push interval.
My other reason for implementing it server side is that the functionality then isnt collector dependent, if someone wanted to use a different collector to promtail, but still wanted the multi-tenancy feature, all they would need to do is enable it in the loki config.

Other than that, I am happy to make those suggest code changes once we deside on the best path moving forward.

**Comment by travis-sobeck** [comment]
whatever came of this?  The need still exists for multi-tenancy within a single cluster

**Comment by kavin-kr** [comment]
Is there any plan to reopen this PR?

**Pull request closed without merging**
