### PR TITLE
Fix documentation linter errors

### PR DESCRIPTION
**Pull request by MasslessParticle**
Documentation linting errors are preventing users from successfully submitting PRs for reasons unrelated the changes being made. This PR fixes all linting errors in the Loki documentation surfaced by the `doc-validator` tool

### CODE REVIEW

**Review by owen-d — APPROVED** [review]
LGTM 👑

**Review by dannykopping — APPROVED** [review]
LGTM with a couple minor corrections.
Thanks for this colossal effort!

**Review by kavirajk — APPROVED** [review]
:muscle:

**Comment by JStickler** [comment]
+1 thanks for taking this on.  One of the issues I was going to fix today was in this PR.

**Comment by GrafanaWriter** [comment]
❤️ and thank you

**Pull request merged**
