### PR TITLE
feat: Add writer addr to loki canary

### PR DESCRIPTION
**Pull request by yongzhang**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Currently loki canary supports only one endpoint, when using it with a loki distributed cluster and `push mode` is enabled, there's no way to query/send logs by single endpoint.

This PR added a new flag `write-addr` to allow users define dedicated write endpoint to support above use case, by default, this write addr use the same value as `addr`.

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [ ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by trevorwhitney** [comment]
Can you describe your use case a little more? We usually recommend running Loki behind a gateway to have a single address for both reads and writes. Is there a reason this topology doesn't work for you?

**Comment by yongzhang** [comment]
> Can you describe your use case a little more? We usually recommend running Loki behind a gateway to have a single address for both reads and writes. Is there a reason this topology doesn't work for you?

Seems like loki gateway is only introduced in Kubernetes deployment, I can't find any docs on it. If this is an optional component, probably it makes sense to allow push mode work with dedicated read/write endpoints without gateway?

**Comment by trevorwhitney** [comment]
@yongzhang yes, k8s is our most common deployment, but for OSS deployments we're just using an nginx reverse proxy in front of the cluster. You could borrow the nginx file from our [helm chart](https://github.com/grafana/loki/blob/4d6992982d99a542f1e99af18b691830b71469e0/production/helm/loki/templates/_helpers.tpl#L719) and set something similar up for however you're deploying.

There are already so many config in Promtail/Loki/etc., I'd love to avoid another flag if possible 😄 , wdyt?

**Comment by yongzhang** [comment]
> @yongzhang yes, k8s is our most common deployment, but for OSS deployments we're just using an nginx reverse proxy in front of the cluster. You could borrow the nginx file from our [helm chart](https://github.com/grafana/loki/blob/4d6992982d99a542f1e99af18b691830b71469e0/production/helm/loki/templates/_helpers.tpl#L719) and set something similar up for however you're deploying.
> 
> 
> 
> There are already so many config in Promtail/Loki/etc., I'd love to avoid another flag if possible 😄 , wdyt?

ok I can try, thanks.

**Pull request closed without merging**
