### PR TITLE
feat: add kms ecryption

### PR DESCRIPTION
**Pull request by jonathanmorais**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by kavirajk** [comment]
@jonathanmorais thanks for the PR. Can you please provide some details in the PR description to help the reviewer? mainly
1. what this PR is about?
2. why we need this?/your use-case for adding this support?

If it's still in-progress, you can take advantage of "Draft" PR.

**Comment by jonathanmorais** [comment]
> @jonathanmorais thanks for the PR. Can you please provide some details in the PR description to help the reviewer? mainly
> 
> 1. what this PR is about?
> 2. why we need this?/your use-case for adding this support?
> 
> If it's still in-progress, you can take advantage of "Draft" PR.

**Comment by jonathanmorais** [comment]
@kavirajk 

1. what this PR is about?
This PR provide an optional parameter for encrypt environment variables at Lambda that this module provide.

2. why we need this?/your use-case for adding this support?
 In our case, we have a cloud environment that do verifying if lambdas have their encrypted environment variables. This parameter go do this.

**Review by kavirajk — APPROVED** [review]
LGTM :+1:

**Comment by kavirajk** [comment]
@jonathanmorais looks like `license/cla` is stuck for some reason. Can you do some "dummy" push to re-check again? Thanks.

I can merge after that.

**Comment by jonathanmorais** [comment]
@kavirajk i think that is working now.

**Pull request merged**
