### PR TITLE
docs: Add config removals to release notes

### PR DESCRIPTION
**Pull request by shantanualsi**
**What this PR does / why we need it**:

Adds release notes for removed configs

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Review by chaudum — APPROVED** [review]

**Comment by JStickler** [comment]
@shantanualsi Could you please resolve the conflicts for this PR so that we can merge it?

**Comment by JStickler** [comment]
@shantanualsi  Could you please resolve the merge conflicts in this PR?

**Comment by shantanualsi** [comment]
@JStickler these exact points are already present in [2.9 release notes](https://grafana.com/docs/loki/latest/release-notes/v2-9/). I'll close this PR as redundant.

**Comment by JStickler** [comment]
Thanks @shantanualsi

**Pull request closed without merging**
