### PR TITLE
[querier] s3: add getObject retry

### PR DESCRIPTION
**Pull request by liguozhong**
fix https://github.com/grafana/loki/issues/4452
this pr fix  issues/4452
image

### CODE REVIEW

**Comment by DylanGuedes** [comment]
Btw, you forgot to write the changes on the CHANGELOG and to document the new parameters in the docs located at `docs/sources/configuration/_index.md`. 

Suggestion:
```
* [4453](https://github.com/grafana/loki/pull/4453) **liguozhong**: Loki: Implement retry to s3 chunk storage. 
```

**Comment by liguozhong** [comment]
> Btw, you forgot to write the changes on the CHANGELOG and to document the new parameters in the docs located at `docs/sources/configuration/_index.md`.
> 
> Suggestion:
> 
> ```
> * [4453](https://github.com/grafana/loki/pull/4453) **liguozhong**: Loki: Implement retry to s3 chunk storage
> ```

thanks,done

**Comment by liguozhong** [comment]
> Docs portion of this PR looks good to me now. Next time @liguozhong , you can just hit the 'commit suggestion' box to accept suggested changes. That would make it trivial for me to re-review.

👍 thanks

**Comment by DylanGuedes** [comment]
> @DylanGuedes review pr pls

Do you mind having a look at [this suggestion](https://github.com/grafana/loki/pull/4453/files#r728974417)? I think that check (starting at line 344) is unnecessary after the latest changes.

Besides that, this looks solid, good job. Not sure if the maintainers would like to see some tests (although I checked the test files and looks like that function wasn't being tested so maybe they won't block you for that).

**Pull request merged**
