### PR TITLE
fix: fix malformed struct tag

### PR DESCRIPTION
**Pull request by chavacava**
Fix a malformed struct tag

### CODE REVIEW

**Comment by MasslessParticle** [comment]
@chavacava thanks for contributing! If you sign the CLA, we can get this merged

**Comment by chavacava** [comment]
Found with [revive](https://github.com/mgechev/revive)

**Comment by chavacava** [comment]
> @chavacava thanks for contributing! If you sign the CLA, we can get this merged

Done. Thank you!

**Comment by MasslessParticle** [comment]
This adds something to the docs so you'll also need to run `make doc` and commit the result!

**Comment by ashwanthgoli** [comment]
sorry, i didn't notice this PR. fixed this along with an [unrelated change](https://github.com/grafana/loki/pull/14588)

**Pull request closed without merging**
