### PR TITLE
feat(helm): :sparkles: add additional service annotations for components in distributed mode

### LINKED ISSUE #8627: Support adding annotations to all service's templates
I want to use "[Topology Aware Hints](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/)" feature of Kubernetes, but currently the helm chart templatefor `service` only support adding annotation for [gateway](https://github.com/grafana/loki/blob/9f8aa4b98a0048c658f49a6f9c3ad76e115efc84/production/helm/loki/templates/gateway/service-gateway.yaml#L12-L14) nodes.

Could you please add annotation support to all other targets like read/write/backend?

### PR DESCRIPTION
**Pull request by dannylongeuay**
**What this PR does / why we need it**:
Support additional service annotations for components in distributed mode.

**Which issue(s) this PR fixes**:
Fixes #8627

**Special notes for your reviewer**:
A previous PR #10214 added support for the simple scalable components, this PR adds support for the distributed mode components.

**Checklist**

- \[x\] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- \[x\] Documentation added
- \[ \] Tests updated
- \[x\] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- \[ \] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- \[x\] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- \[ \] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by chaudum — APPROVED** [review]
Thanks for the contribution! LGTM

**Comment by dannylongeuay** [comment]
> Thanks for the contribution! LGTM

You're welcome, thanks for the quick review. I updated the docs, hopefully that fixes the remaining CI issues.

**Comment by chaudum** [comment]
@dannylongeuay The Helm docs lint check still fails :/

**Comment by dannylongeuay** [comment]
@chaudum fixed the readme versions I missed

**Pull request merged**
