### PR TITLE
[Typo fixed] in CHANGELOG.md

### PR DESCRIPTION
**Pull request by khalid586**
**What this PR does / why we need it**:

**Fixes Typo**

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory.

### CODE REVIEW

**Comment by khalid586** [comment]
@trevorwhitney can you please review this PR?

**Comment by khalid586** [comment]
@poyzannur @JStickler Can you please review my PR?

**Comment by JStickler** [comment]
@khalid586  Tagging five different people to review a non-urgent typo is unnecessary.  If you're doing Hacktoberfest, the goal is to make meaningful contributions to a project, not to make additional work for maintainers.

Your branch is out of date.

**Comment by khalid586** [comment]
> @khalid586 Tagging five different people to review a non-urgent typo is unnecessary. If you're doing Hacktoberfest, the goal is to make meaningful contributions to a project, not to make additional work for maintainers.
> 
> Your branch is out of date.

I apologize.

**Comment by khalid586** [comment]
I have updated the branch.

**Comment by JStickler** [comment]
Yes, I saw that. I'm still trying to decide if I'm going to close this PR and create a "spam" label for it.

**Comment by khalid586** [comment]
> Yes, I saw that. I'm still trying to decide if I'm going to close this PR and create a "spam" label for it.

why would it be a spam?

**Comment by khalid586** [comment]
If a PR is not necessary then it should be closed , it should not be unchecked.

**Comment by JStickler** [comment]
Because you may not have read the rules when you signed up for Hacktoberfest, but I've done the event for several years.
Spammy

**Comment by khalid586** [comment]
> Because you may not have read the rules when you signed up for Hacktoberfest, but I've done the event for several years. Spammy

I have read the rules but I think you didn't read my question properly. I asked why would it be a spam? I just corrected a mistake and generally these kinds of mistakes are hard to correct because generally nobody has that much time to go through the whole files/project to fix such trivial thus they go unchecked. I just wanted to get my PR reviewed. Merge it or close it. How can you say it a spam PR? Help me understand. @JStickler

**Comment by JStickler** [comment]
@khalid586 Your GitHub profile says you're a Hacktoberfest participant.  If this PR wasn't for Hacktoberfest, then why did you feel the need to tag five different people rather than waiting for a maintainer to review it when they had time?

Fixing a typo in the code, or a configuration parameter, or in a code example, or in the published docs is helpful because those typos might confuse users or prevent them from being able to use the software successfully.
Fixing a typo while you're submitting a PR for a bug fix or new feature is helpful, because you're cleaning up the code or docs while you're doing other, meaningful work.
Finding a typo in content that doesn't prevent users from being able to use the software, on the last day of Hacktoberfest, and then tagging five different maintainers because you want credit for another PR before Hacktoberfest is over?  I would consider that spam.   

As I said before, the spirit of Hactoberfest is to encourage people to make meaningful contributions to open source. In past years maintainers have been flooded with XS pull requests that did not provide a great deal of value to their projects, but took up a lot of their time.

**Pull request closed without merging**
