### PR TITLE
helm: make multi tenant easy: use tenant id from nginx $remote_user

### PR DESCRIPTION
**Pull request by a5r0n**
Uses helm values to generate htpasswd file based on tenants list.
i'm not quite sure about name conventions and such, so any help with this are welcome!

#8380

### CODE REVIEW

**Comment by a5r0n** [comment]
@jeschkies can u please take a look before i mark this as ready for review?
thanks.

**Review by jeschkies — APPROVED** [review]

**Comment by jeschkies** [comment]
Thanks. I think you need to generate the documentation.

**Comment by a5r0n** [comment]
i tried to run `make -C docs sources/installation/helm/reference.md`
but the output is:
```
make: Entering directory '/home/aaron/Dev/oss/loki/docs'
make: 'sources/installation/helm/reference.md' is up to date.
make: Leaving directory '/home/aaron/Dev/oss/loki/docs'
```
do i did something wrong?

**Comment by jeschkies** [comment]
Might be a timestamp thing could you run it with -B? `make -B -C docs...`

**Comment by a5r0n** [comment]
@jeschkies 
```
❯ make -B -C docs sources/installation/helm/reference.md
make: Entering directory '/home/aaron/Dev/oss/loki/docs'
podman run --rm --volume "/home/aaron/Dev/oss/loki:/helm-docs:z" -u "$(id -u)" "docker.io/jnorwood/helm-docs:v1.11.0" \
        -c /helm-docs/production/helm/ \
        -t reference.md.gotmpl \
        -o reference.md
time="2023-02-20T13:31:24Z" level=info msg="Found Chart directories [loki]"
time="2023-02-20T13:31:24Z" level=info msg="Generating README Documentation for chart /helm-docs/production/helm/loki"
time="2023-02-20T13:31:24Z" level=warning msg="Could not open chart README file /helm-docs/production/helm/loki/README.md, skipping chart"
mv "../production/helm/loki/reference.md" "sources/installation/helm/reference.md"
mv: cannot stat '../production/helm/loki/reference.md': No such file or directory
make: *** [Makefile:24: sources/installation/helm/reference.md] Error 1
make: Leaving directory '/home/aaron/Dev/oss/loki/docs'
```

**Comment by a5r0n** [comment]
@jeschkies finally it's looks good..?
it was some problem with the `-u "$(id -u)" ` in the podman command

**Comment by jeschkies** [comment]
@a5r0n I just ran into the same issue.

**Pull request merged**
