### PR TITLE
[Docs] Remove outdated canary logo

### PR DESCRIPTION
**Pull request by JStickler**
Remove the rather outdated canary logo on the page describing the Loki canary app.

https://grafana.com/docs/loki/latest/operations/loki-canary/ 

**Checklist**
- [X] Reviewed the `CONTRIBUTING.md` guide
- [X] Documentation added
- [N/A] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by slim-bean** [comment]
:( :( :( :( :( :( :( :(

**Comment by JStickler** [comment]
@slim-bean  I found the original PR, I know that's your pet canary.

**Comment by slim-bean** [comment]
Do we have to remove it? Creating this logo is one of my most proud accomplishments!

**Comment by JStickler** [comment]
I really think it's time to retire it.  But it will live on, someone already added it as an emoji on our Slack.

**Comment by JordanRushing** [comment]
I very much appreciate the initiative to open this PR and to express a fresh perspective on our documentation. That being said, I'm a fan of the canary graphic! Is there a compromise where we can keep this piece of Loki history while improving the docs quality?

**Comment by JStickler** [comment]
While there is precedent for primitive corporate logos (See the [Newbury Comics](https://en.wikipedia.org/wiki/File:Newbury_comics_logo.png) logo) I'm not under the impression that Grafana Labs has adopted that particular design aesthetic for branding.  There's also the question of why one feature has a logo when others do not?  In my mind, charming as the canary might be, it's a question of trying to have more consistency across the features and product suite.  But I am certainly open to discussion.

**Review by jeschkies — APPROVED** [review]

**Pull request merged**
