### PR TITLE
update local docker-compose file to provision the Loki data source

### PR DESCRIPTION
**Pull request by tab0r**
**What this PR does / why we need it**:
* auto-provisions the dockerized Loki as a datasource
* [existing docs](https://github.com/grafana/loki/tree/main/production#run-locally-using-docker) tell user to "follow the [steps for configuring the datasource in Grafana](https://github.com/grafana/loki/blob/main/docs/sources/getting-started/grafana.md)", but that link is broken
* and this docker-compose should be focused on getting the user up and running ASAP anyway, without requiring jumping to a different reference doc

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by kavirajk — COMMENTED** [review]
Thanks @tab0r. this is super nice :+1: 

Can you also [update the README](https://github.com/grafana/loki/tree/main/production#run-locally-using-docker) of the this docker-compose and remove "setting up Grafana" link?. We won't be needing that once this PR is merged.

I will merge after that.

**Comment by kavirajk** [comment]
@tab0r can you also sign your CLA license please?

**Comment by tab0r** [comment]
@kavirajk done and done! Thank you!

**Review by jeschkies — APPROVED** [review]

**Review by owen-d — APPROVED** [review]
<3

**Pull request merged**
