### PR TITLE
docs: Update _index.md

### PR DESCRIPTION
**Pull request by Barnaud**
Update config example file so each field is taken in account

**What this PR does / why we need it**:
Modify the example for the monolitic install so that all parameters are taken in account.

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Comment by JStickler** [comment]
This was part of the PR template checklist, any change to the Helm Charts requires a version bump.  Please update the Helm chart version in 
- production/helm/loki/Chart.yaml  
- production/helm/loki/CHANGELOG.md 
- production/helm/loki/README.md. 
- [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
(Depending on if other Helm updates merge before this PR, you may need to update the version more than once.)

**Comment by Barnaud** [comment]
This is not a change in the helm chart, only in the documentation.
I propose this change because the example of values.yaml provided here did not work, and did not seem consistent with this page: https://grafana.com/docs/loki/latest/setup/install/helm/install-scalable/ (but I may be wrong)

**Comment by JStickler** [comment]
Ah, my mistake. I was reading too quickly. I read "helm" and assumes it was an Helm Charts update.

**Review by JStickler — APPROVED** [review]
[docs team] LGTM

**Comment by JStickler** [comment]
@Barnaud if you could resolve the conflicts in this PR, we can get it merged.

**Comment by JStickler** [comment]
@Barnaud if you could resolve the conflicts in this PR, we can get it merged.

**Pull request merged**
