### PR TITLE
Loki: Make DNS resolver configurable in Gateway

### PR DESCRIPTION
**Pull request by irizzant**
Signed-off-by: Ivan Rizzante <i.rizzante@gmail.com>

**What this PR does / why we need it**:
Currently it's not possible to configure the DNS resolver in [Gateway](https://github.com/grafana/loki/blob/7299e3bdcdae5bd7dacd08be67f706fdbaab8543/production/ksonnet/loki/gateway.libsonnet#L42), which is a problem if `kube-dns` Service does not exists.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [X] Documentation added
- [X] Tests updated
- [X] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [X] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by irizzant** [comment]
How am I supposed to make the lint stage pass?

**Comment by kavirajk** [comment]
> How am I supposed to make the lint stage pass?

@irizzant you can do `make fmt-jsonnet`.

**Review by kavirajk — APPROVED** [review]
LGTM!

**Comment by irizzant** [comment]
Thank you!

**Pull request merged**
