### PR TITLE
helm: Allow altering the canary label name

### PR DESCRIPTION
**Pull request by MOZGIII**
**What this PR does / why we need it**:

Allows changing the label name at the canary in the helm chart.

**Which issue(s) this PR fixes**:
Idk, none?

**Special notes for your reviewer**:

This is a very trivial change.

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] `CHANGELOG.md` updated
  - [x] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Comment by MOZGIII** [comment]
Is it autogenerated somehow, or do I do it manually?

**Comment by MasslessParticle** [comment]
Please generate Helm Chart reference by running 'make -C docs sources/installation/helm/reference.md' and committing the difference.

**Comment by MOZGIII** [comment]
```
$ make -C docs sources/installation/helm/reference.md
make: `sources/installation/helm/reference.md' is up to date.
```
I think something's off with my system. Could you please do it for me?

**Comment by MichelHollands** [comment]
@MOZGIII Please run `touch production/helm/loki/reference.md.gotmpl` first and then rerun `make -C docs sources/installation/helm/reference.md`.

**Comment by MOZGIII** [comment]
Or, this doesn't for on my system, which is a mac:

```
$ make -C docs sources/installation/helm/reference.md
podman run --rm --volume "/Users/mozgiii/Desktop/loki:/helm-docs:z" -u "$(id -u)" "docker.io/jnorwood/helm-docs:v1.11.0" \
		-c /helm-docs/production/helm/ \
		-t reference.md.gotmpl \
		-o reference.md
Trying to pull docker.io/jnorwood/helm-docs:v1.11.0...
Getting image source signatures
Copying blob sha256:686a36f404693d6f5531eeb0b97fb41b5a919aaadb98da5cbb9e427c4ccd178b
Copying blob sha256:9981e73032c8833e387a8f96986e560edbed12c38119e0edb0439c9c2234eac9
Copying blob sha256:ab4ef5b593dd3af590bd9af92a729f11d596485a3957f8d4388e190cae06f0dd
Copying config sha256:1360023e3a71fc132eea2601247ca94a7579e69cc721da4f7b1df43a7df2cff8
Writing manifest to image destination
Storing signatures
Error: preparing container aa94641331cec3b309f3545bfe53771350cd09c623f82a1f7ca60a94a33605e9 for attach: lsetxattr /Users/mozgiii/Desktop/loki/.devcontainer: operation not supported
make: *** [sources/installation/helm/reference.md] Error 126
```

To fix, drop the `:z` from the mount in your tooling. I'll send you a separate PR to discuss. That said, I'm a bit preoccupied with other things, so feel free to just handle this on your end.

**Review by MichelHollands — APPROVED** [review]

**Pull request merged**
