### PR TITLE
update helm docs, add simple scalable

### PR DESCRIPTION
**Pull request by trevorwhitney**
**What this PR does / why we need it**:

Adds helm docs for the simple scalable deployment, improves existing helm docs to use distributed chart rather than `loki-stack`

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Review by DylanGuedes — APPROVED** [review]
few nits

**Review by kavirajk — APPROVED** [review]
LGTM 👍

**Review by KMiller-Grafana — APPROVED** [review]
Docs changes look good to me.  Thanks @trevorwhitney.

**Review by owen-d — APPROVED** [review]

**Review by vlad-diachenko — COMMENTED** [review]
looks awesome ! thanks

**Pull request merged**
