### PR TITLE
Gob vs protobuf benchmark comparison

### PR DESCRIPTION
**Pull request by DylanGuedes**
[This is a draft just to share to others the difference in performance between Gob vs Protobuf encoding]

Results: 
```
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -tags integration,requires_docker -bench ^BenchmarkCacheableIndexGobEncoding$ github.com/grafana/loki/pkg/storage/stores/tsdb

goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/storage/stores/tsdb
cpu: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
BenchmarkCacheableIndexGobEncoding/GetChunkRef/gob_encoding-12         	   27756	     43275 ns/op	   10136 B/op	     304 allocs/op
BenchmarkCacheableIndexGobEncoding/GetChunkRef/protbuf_encoding-12     	  125461	      9535 ns/op	    1577 B/op	      74 allocs/op
PASS
ok  	github.com/grafana/loki/pkg/storage/stores/tsdb	2.965s

```

### CODE REVIEW

**Comment by jeschkies** [comment]
Interesting just yesterday I was wondering if gob would be an alternative.

**Comment by DylanGuedes** [comment]
> Btw how do you feel about benchmarking flat buffers as well?

actually I've never heard of it :joy: but looking at the docs looks like it shouldn't be too hard to try it. I'll have a look at it this week then, let's see how it goes :eye:

**Comment by jeschkies** [comment]
> actually I've never heard of it

I haven't used them myself but they [claim](https://google.github.io/flatbuffers/) to be faster and avoid copying but are bigger.

**Comment by jeschkies** [comment]
While you are at it. Could you try [Cap'n Proto](https://github.com/capnproto/go-capnproto2) as well :slightly_smiling_face:

**Comment by jeschkies** [comment]
@DylanGuedes  I'm curious. Did you find anything interesting? I think it's worthwhile investigating different serializers.

**Comment by DylanGuedes** [comment]
I didn't, sorry. I don't even remember why I closed it :smile:

**Comment by jeschkies** [comment]
No worries. Will you keep working on it? Should we create a ticket instead?

**Comment by DylanGuedes** [comment]
> No worries. Will you keep working on it? Should we create a ticket instead?

I'd like to work on it, but I'll only have time once I finish the indexgateway work :(
Yes, maybe we should ticket this to not lose track of it

**Pull request closed without merging**
