### PR TITLE
tools/promtail.sh: remove useless option

### PR DESCRIPTION
**Pull request by daixiang0**
As [comment](https://github.com/grafana/loki/pull/97#issuecomment-447535426) said, the namespace option is useless, so remove it.

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by DanCech** [comment]
The yaml produced by ksonnet includes the namespace entry for the `promtail` `ClusterRoleBinding`.  If we update the ksonnet to not produce that then it can (and should) be removed here.  Because we want to produce promtail.sh from the ksonnet yaml output, we don't want to remove it here while it is still being output by the ksonnet.

**Comment by daixiang0** [comment]
In fact, As #96 said, promtail.sh produce useless namespace option since `kubectl` cover it.
To keep in sync, in grafana cloud should use `loki` namespace or `ksonnect` use `default` namespace could be better.

**Comment by daixiang0** [comment]
```
$ git grep ClusterRoleBinding
helm/templates/promtail/clusterrolebinding.yaml:2:kind: ClusterRoleBinding
```
@DanCech  seems that `promtail` `ClusterRoleBinding` in ksonnet has removed.

**Comment by daixiang0** [comment]
```
$ cd production
$ git grep ClusterRoleBinding
helm/templates/promtail/clusterrolebinding.yaml:2:kind: ClusterRoleBinding
```
there is not `ClusterRoleBinding` in ksonnet now.

**Comment by daixiang0** [comment]
any input?

**Comment by daixiang0** [comment]
@DanCech hi, any input?

**Comment by daixiang0** [comment]
any update?

**Comment by tomwilkie** [comment]
Sorry @daixiang0, been busy.  Need a rebase.

**Comment by daixiang0** [comment]
@tomwilkie Done.

**Comment by daixiang0** [comment]
@tomwilkie rebase done, thanks

**Pull request closed without merging**
