### PR TITLE
feat: API: Expose optional label matcher for label names API

### PR DESCRIPTION
**Pull request by yuri-rs**
**What this PR does / why we need it**:
This is an enhancement to add the optional matchers on the label names API

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
This change would be very useful for the Grafana enhancement https://github.com/grafana/grafana/issues/74432 that I'm working on.
Most of the changes just duplicate LabelValuesForMetricName implementation and it looks pretty straightforward.

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [x] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by yuri-rs** [comment]
@periklis this is almost a copy of https://github.com/grafana/loki/pull/8824
Could you please take a look and share your opinion?

**Comment by periklis** [comment]
@yuri-rs AFAIU the grafana/grafana/pull/83044 enhancement speaks about support the query selector on the label values API. I don't quite get the point on why we need the selector on the label names API too?!? I might miss something conceptual or simply misread your Grafana PR, please help me sort out why we need this change.

**Comment by yuri-rs** [comment]
@periklis The Grafana enhancement concerns label values, true, but why not extend the same enhancement to label names as well? 
For Grafana it would be simpler and more consistent if both APIs supported the match[] selector. 

It would also be much better for network efficiency. Using the `/labels` API with a selector could allow us to retrieve perhaps only 100 label names, as opposed to extracting thousands of series with `/series`.

**Comment by periklis** [comment]
> @periklis The Grafana enhancement concerns label values, true, but why not extend the same enhancement to label names as well? For Grafana it would be simpler and more consistent if both APIs supported the match[] selector.
> 
> It would also be much better for network efficiency. Using the `/labels` API with a selector could allow us to retrieve perhaps only 100 label names, as opposed to extracting thousands of series with `/series`.

Sure can you provide practical examples on how the Grafana tool would make use of it today? Does it support similar matchers on ther data sources?

**Comment by yuri-rs** [comment]
> Sure can you provide practical examples on how the Grafana tool would make use of it today? Does it support similar matchers on ther data sources?

Sure. '/labels' API with matchers works fine for Prometheus datasources, that supports this API:
image

**Comment by yuri-rs** [comment]
Hi @periklis, 
Do you have any further comments? 
Are there any remaining steps that you would recommend to finalize this update? 
Your insights would be greatly appreciated. 
Thank you!

**Comment by periklis** [comment]
@cyriltovena WDYT?

**Comment by cyriltovena** [comment]
Please rebase and ping me again to merge this.

**Comment by yuri-rs** [comment]
@cyriltovena Could you please take a look again?

**Pull request merged**
