### PR TITLE
Import sequence diagram for instant queries.

### PR DESCRIPTION
**Pull request by jeschkies**
Trying out Mermaid in GitHub.

### CODE REVIEW

**Comment by owen-d** [comment]
Is there a way to preview this or otherwise review it?

**Comment by jeschkies** [comment]
> Is there a way to preview this or otherwise review it?

You can click on the GitHub preview button. It's the little page here image

I'm not sure this should be merged. However, I still think this graph is valuable and would hate it to be lost. Where should we persist it?

**Comment by ssncferreira** [comment]
Wow 🤩 this diagram is great! Was trying to figure out the middleware flow and this helps a lot 🎉 
I definitely agree we should keep this image. Maybe add a new page on the LogQL section to explain the instant/range queries? 
The instant queries are only mentioned in the [k6 load testing section](https://grafana.com/docs/loki/next/clients/k6/query-scenario/), but this is in the context of query testing

**Comment by dannykopping** [comment]
> Wow star_struck this diagram is great! Was trying to figure out the middleware flow and this helps a lot tada I definitely agree we should keep this image. Maybe add a new page on the LogQL section to explain the instant/range queries? The instant queries are only mentioned in the [k6 load testing section](https://grafana.com/docs/loki/next/clients/k6/query-scenario/), but this is in the context of query testing

I'm concerned that this will go stale quite quickly, so it might become misleading very soon

**Comment by owen-d** [comment]
Diagram is definitely cool! I am worried about a few things though:
1) Staleness as @dannykopping suggested
2) This should have it's own subsection instead of in the `coding standards` section

**Comment by jeschkies** [comment]
Won't do.

**Pull request closed without merging**
