### PR TITLE
Promtail: Restart the tailer if we fail to read and upate current position

### PR DESCRIPTION
**Pull request by slim-bean**
Reworked how the tailers work a bit to restart if we ever fail to read the position file.

### CODE REVIEW

**Comment by wizard580** [comment]
I can report that this issue still happens with 1.6.1 promtail/loki.
After I see `error getting tail position and/or size, stopping tailer` for log file (K8S 1.16, KOPS 1.17, AWS) no more logs are streamed by this promtail instance... at least from that node/service. 

checked a bit in the code I see that go routine is exited in case of this error but I didn't notice when it will be started again. Maybe I missed something... didn't spend a lot of time here.

**Comment by wizard580** [comment]
I think original issue must be re-opened

**Comment by kazukousen** [comment]
i am still encountering this issue.

promtail 1.7.1, k8s(AWS EKS) 1.17

**Comment by wizard580** [comment]
exactly. And after a bit you'll get 0 logs from this node unless you restart pod manually.

**Comment by slim-bean** [comment]
There was another race condition fixed a week or so ago (#2717 ), this hopefully fixes the problems you are still seeing

**Pull request merged**
