### PR TITLE
Made the docker root configurable. Default is '/var/lib/docker'

### PR DESCRIPTION
**Pull request by nicknezis**
We had a use case in which we were running Docker in a location which had more storage. I'm adding the ability to modify the docker location.

### CODE REVIEW

**Comment by kfox1111** [comment]
I'd recommend renaming it too, as it is important not just for docker, but if you are using containerd or other runtime.

**Comment by nicknezis** [comment]
> I'd recommend renaming it too, as it is important not just for docker, but if you are using containerd or other runtime.

That's a great point. I thought of this but wasn't sure what to name it. Any suggestions? I'll make the change.

**Comment by kfox1111** [comment]
There are 2 hard problems in computer science. Naming things, cache invalidation, and off by one errors. :)

containerRoot? logDataRoot? extraDataRoot?

**Comment by nicknezis** [comment]
Does `containerd` have a `./containers` sub-folder? Might be a good idea to also make the sub-path configurable. Also can rename the volume `varlibdockercontainers` to a more generic name. If you agree, I can make those changes to the Helm and Ksonnet folders.

**Comment by kfox1111** [comment]
For containerd, it looks like /var/log/pods is where the logs are with a symlink farm from /var/log/containers to it.

**Comment by nicknezis** [comment]
> For containerd, it looks like /var/log/pods is where the logs are with a symlink farm from /var/log/containers to it.

Ok, cool. So perhaps this is ok to merge as is?

**Comment by steven-sheehy** [comment]
Duplicate of #238 

Though I prefer instead of either PR to just let the user supply their own volumes/volumeMounts. Then you can just put the current default volumes in the values.yaml and users can override them if their data root differs or they want to mount additional.

**Comment by nicknezis** [comment]
@steven-sheehy I updated based on your feedback for generic handling of `volumes` and `volumeMounts`.

**Comment by steven-sheehy** [comment]
Nice! 

Though instead of mapping over field by field it would be better to just copy it wholesale for both volumes and volumeMounts:
```
{{- if .Values.promtail.volumeMounts }}
{{ toYaml .Values.promtail.volumeMounts | nindent 12 }}
{{- end }}
```

**Comment by nicknezis** [comment]
Oh perfect. I'm new to Helm so wasn't sure how to do that. That would help with my `readOnly` conditional logic. I'll make the change now.

**Comment by nicknezis** [comment]
> Nice!
> 
> Though instead of mapping over field by field it would be better to just copy it wholesale for both volumes and volumeMounts:
> 
> ```
> {{- if .Values.promtail.volumeMounts }}
> {{ toYaml .Values.promtail.volumeMounts | nindent 12 }}
> {{- end }}
> ```

Not sure if this matters, but the `toYaml` seems to be putting the fields in alphabetical order so I end up with this flipping on `name` and `mountPath`.

```
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
```

**Comment by steven-sheehy** [comment]
The order doesn't matter

**Comment by steven-sheehy** [comment]
lgtm @davkal Can you take a look?

**Comment by nicknezis** [comment]
@davkal Let me know if there are any final cleanup changes you would like to see.

**Comment by davkal** [comment]
Almost there! Last step for consistency: rename `dataroot` also in `production/ksonnet/README.md` and `tools/promtail.sh`.

**Comment by nicknezis** [comment]
@davkal I got those remaining changes checked in based on your feedback. Thanks!

**Pull request merged**
