### PR TITLE
s3: Added option to skip tls verify

### LINKED ISSUE #10030: Skip tls verify for S3 bucket option on helm chart
**Is your feature request related to a problem? Please describe.**
We have local netapp with S3, which is internal soluion, once trying to use it we get "tls: failed to verify certificate: x509"
But this ok by me, we can skip the verify, today no option to do it.

**Describe the solution you'd like**
on s3 values: https://github.com/grafana/loki/blob/a0e9f1aeb5d557330eabde21efd02cca58d77b1a/production/helm/loki/values.yaml#L265C5-L265C7
add option to `tls_verify: true or false`

**Describe alternatives you've considered**
Use AWS, but this is not an option for the long term.

**Additional context** 
Logs when trying use https with
```
level=info ts=2023-07-24T07:13:17.404546324Z caller=compactor.go:497 msg="compactor started"
ts=2023-07-24T07:13:17.404617423Z caller=spanlogger.go:85 level=info msg="building index list cache"
ts=2023-07-24T07:13:17.417953887Z caller=spanlogger.go:85 level=info msg="index list cache built" duration=13.313664ms
level=error ts=2023-07-24T07:13:17.418041586Z caller=cached_client.go:65 msg="failed to build cache" err="RequestError: send request failed\ncaused by: Get \"http://logs-store.deeps3.netapp.local/?delimiter=&list-type=2&prefix=index%2F\": dial tcp 10.111.10.230:80: connect: connection refused"
ts=2023-07-24T07:13:17.418109085Z caller=spanlogger.go:85 level=info msg="building index list cache"
ts=2023-07-24T07:13:17.432629337Z caller=spanlogger.go:85 level=info msg="index list cache built" duration=14.501952ms
level=error ts=2023-07-24T07:13:17.432729936Z caller=cached_client.go:65 msg="failed to build cache" err="RequestError: send request failed\ncaused by: Get \"http://logs-store.deeps3.netapp.local/?delimiter=&list-type=2&prefix=index%2F\": dial tcp 10.111.10.230:80: connect: connection refused"
level=error ts=2023-07-24T07:13:17.432848335Z caller=compactor.go:460 msg="failed to run compaction" err="RequestError: send request failed\ncaused by: Get \"http://logs-store.deeps3.netapp.local/?delimiter=&list-type=2&prefix=index%2F\": dial tcp 10.111.10.230:80: connect: connection refused"
ts=2023-07-24T07:14:06.273192305Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-backend-0-0d372d5d has failed, no acks received"
level=error ts=2023-07-24T07:14:12.530152784Z caller=ruler.go:542 msg="unable to list rules" err="RequestError: send request failed\ncaused by: Get \"http://logs-store.deeps3.netapp.local/?delimiter=&list-type=2&prefix=rules%2F\": dial tcp 10.111.10.230:80: connect: connection refused"
ts=2023-07-24T07:14:20.563206136Z caller=memberlist_logger.go:74 level=info msg="Marking loki-backend-0-0d372d5d as failed, suspect timeout reached (2 peer confirmations)"
```

**Edit:** we need solution for local certificate, to mount "pem" file.

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #10030

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory.

### CODE REVIEW

**Comment by david-nano** [comment]
I don't see any change on the templates of the helm chart. How do the implementation will be applied?

**Comment by Sheikh-Abubaker** [comment]
> I don't see any change on the templates of the helm chart. How do the implementation will be applied?

I went through the official documentation : https://grafana.com/docs/loki/latest/configure/#s3_storage_config

Here there is a parameter defined ```insecure_skip_verify``` which states that enabling the mentioned parameter will
help to skip verification of certificate.
 
image

**Comment by Sheikh-Abubaker** [comment]
Hi @david-nano, is this PR up to the mark for resolving the respective issue ?

**Comment by j4rj4r** [comment]
Hello,

This variable must be added by the user only if he needs it. Why put it by default in values.yaml and make it even more complex?

**Comment by Sheikh-Abubaker** [comment]
> Yes it is

Glad to know that, can you tell me if this PR will be merged, I've just started contributing to Open Source and have also participated in Hacktoberfest2023 and I only need 1 more PR to be merged to fulfill the 4/4 PR merged criteria of Hacktoberfest, I only have a day left.

**Comment by Sheikh-Abubaker** [comment]
@JStickler can you please request review for this PR it's been a while since I've opened this PR, if there is any changes needed I'd be glad to contribute.

**Comment by Sheikh-Abubaker** [comment]
> @JStickler can you please request review for this PR it's been a while since I've opened this PR, if there are any changes needed I'd be glad to contribute.

**Comment by Sheikh-Abubaker** [comment]
@MichelHollands seems like folks are in need of this feature please see comments of issue #10030

**Comment by MichelHollands** [comment]
@Sheikh-Abubaker This is not needed. You should specify the `insecure_skip_verify` setting in the `http_config` block in the values.yaml you pass when deploying the chart. The change you are making here is changing it in the default values. This will make everyone's installation less secure.

**Pull request closed without merging**
