### PR TITLE
operator: Prepare bundle for openshift-logging release 5.6

### PR DESCRIPTION
**Pull request by jcantrill**
**What this PR does / why we need it**:
* Updates the max supported OCP version to 4.12
**Which issue(s) this PR fixes**:
* Fixes https://issues.redhat.com/browse/LOG-3120

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @periklis

**Comment by Red-GV** [comment]
@jcantrill Need to also modify the `metadata/properties.yml` too, no?

**Comment by periklis** [comment]
> @jcantrill Need to also modify the `metadata/properties.yml` too, no?

@Red-GV This is in a separate PR grafana/loki/pull/7296 so that we can backport it a single piece for OpenShift Logging 5.5

**Comment by Red-GV** [comment]
Ah, missed that one. Never mind my comment then.

**Review by periklis — APPROVED** [review]

**Pull request merged**
