### PR TITLE
fix(helm): fix query-frontend and ruler targetPort 'http-metrics' in Service template

### PR DESCRIPTION
**Pull request by archimeid**
**What this PR does / why we need it**:

This PR is a fix for Loki Helm Chart.

The templates for query-frontend-headless Service and ruler Service have an issue on "targetPort".

This issue is the same as the one detected for query-scheduler in version 6.6.1.

```
- name: http-metrics
   port: 3100
   targetPort: http
   protocol: TCP
```

`targetPort` is currently `http` but the port name in Deployment (or StatefulSet) template is `http-metrics`.

[Template for query-frontend deployment](https://github.com/grafana/loki/blob/4901a5c452fa6822a645f56e20e704db9366182a/production/helm/loki/templates/query-frontend/deployment-query-frontend.yaml#L74)

[Template for ruler stateful-set](https://github.com/grafana/loki/blob/4901a5c452fa6822a645f56e20e704db9366182a/production/helm/loki/templates/ruler/statefulset-ruler.yaml#L69)

Thus, those Services have no endpoint available for the `http-metrics` port because of the mismatch.

Setting targetPort to `http-metrics` has solved the issue.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
N/A

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [x] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by DylanGuedes — CHANGES_REQUESTED** [review]
could you also fix the ruler and QF?

**Comment by archimeid** [comment]
> could you also fix the ruler and QF?

Done

**Review by DylanGuedes — APPROVED** [review]

**Comment by DylanGuedes** [comment]
thanks, this is fantastic :heart: 
- I have changed the PR title to fix the CI
- could you also approve the CLA?

**Comment by archimeid** [comment]
> thanks, this is fantastic ❤️
> 
>     * I have changed the PR title to fix the CI
> 
>     * could you also approve the CLA?

Happy if I could help! 👍 

I've already approved it several times but it didn't refresh in here.

**Comment by DylanGuedes** [comment]
could you trigger a recheck by visiting https://cla-assistant.io/check/grafana/loki?pullRequest=13024?

**Comment by archimeid** [comment]
I did many times but it does not work.

**Comment by archimeid** [comment]
A fix seems to be merged for the same issue now apparently when trying to resolve conflicts with main branch.

**Comment by archimeid** [comment]
OMG, you're totally right. I have edited my commit. It was another user I am using at work.
As the issue was resolved for query-scheduler in 6.6.1 but not for query-frontend and ruler, I edited my commit to fix both and bump to 6.6.2.

**Comment by vpo-cdc** [comment]
Just need the approvals for the Github Actions and it should be good 🙏

**Pull request merged**
