### PR TITLE
promtail: no need for GCP promtail_instance label now that loki supports out-of-order writes

### LINKED ISSUE #4474: Remove gcplog prometheus_instance label
Now that loki accepts out-of-order writes, #3501 should be backed out.

### PR DESCRIPTION
**Pull request by james-callahan**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4474

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation updated
- [x] Tests updated

### CODE REVIEW

**Comment by james-callahan** [comment]
> Great catch. Are you willing to sign the CLA?

Done

**Review by kavirajk — COMMENTED** [review]
Thanks @james-callahan. LGTM!. 

@owen-d this could be a breaking change. should be add it to the upgrade guide?

**Comment by owen-d** [comment]
Good call @kavirajk. Let's add a small burb to the upgrade guide :)

**Comment by owen-d** [comment]
It also looks like we'll need one small change to pass the linter:
```
clients/pkg/promtail/targets/gcplog/formatter.go:21:5: var `instanceID` is unused (unused)
186s
19	var instanceID uuid.UUID
```

**Comment by james-callahan** [comment]
> It also looks like we'll need one small change to pass the linter

Fixed + rebased.

The tests now seem to be failing for unrelated reasons?

**Comment by owen-d** [comment]
Hey, the reason it's failing is because by removing some code, it's actually changed the expected `go.mod` configs:
```
-	github.com/gofrs/uuid v4.0.0+incompatible
+	github.com/gofrs/uuid v4.0.0+incompatible // indirect
```

You should be able to resolve this by running `go mod tidy` and committing after.

**Comment by james-callahan** [comment]
> Hey, the reason it's failing is because by removing some code, it's actually changed the expected go.mod configs because the uuid library is now an indirect dependency:

huh. weird that this manifested so far away in the tests (only failures in compactor retention tests); while the `lint` stage passed.

> You should be able to resolve this by running `go mod tidy` and committing after.

Done.

**Review by owen-d — APPROVED** [review]

**Pull request merged**
