### PR TITLE
Add v2 support to go module

### PR DESCRIPTION
**Pull request by ningyougang**
**What this PR does / why we need it**:

I want to import loki to my own project's go.mod, .e.g
```
module xxx

go 1.16

require (
	...
	github.com/grafana/loki v2.2.1 // indirect
)
```
But it reported below error
```
require github.com/grafana/loki: version "v2.2.1" invalid: should be v0 or v1, not v2
```
After checked, need to add v2 to grafana/loki's go.mod file

If this pr is merged, it is better to create a new tag(e.g. v2.2.2) with latest code.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by ningyougang** [comment]
btw, it seems below temp solution didn't work
```
github.com/grafana/loki v2.2.1+incompatible // indirect
```

**Comment by ningyougang** [comment]
hm..it seems this pr is not good due to need a lot of file changes.

have any other good method to support `import https://github.com/grafana/loki` in other project?

**Comment by kavirajk** [comment]
@ningyougang thanks for the PR!. There is already open PR https://github.com/grafana/loki/pull/3435 and issue for go v2 module support!

**Comment by ningyougang** [comment]
@kavirajk ,thanks for sharing, i will close this pr.

**Pull request closed without merging**
