### PR TITLE
Add support for ARM64 to lambda-promtail drone build job

### PR DESCRIPTION
**Pull request by tlinhart**
**What this PR does / why we need it**:

Using ARM64 architecture for Lambda functions can lead to significant price/performance gain. For reference:
- https://aws.amazon.com/about-aws/whats-new/2021/09/better-price-performance-aws-lambda-functions-aws-graviton2-processor/
- https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

Up until now, the solution was to custom-build an ARM64 image for Promtail Lambda and push it to the private ECR registry. However, since the release of pull through cache repositories (https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-ecr-cache-repositories/) it's now much easier to keep the images from public registries in private ECR registry up to date. This is especially true when using IaC (e.g. Pulumi).

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

Discussed on Slack with @cstyan (https://grafana.slack.com/archives/CEPJRLQNL/p1644258844007079).

I tried to build the ARM64 image and use it in production with success.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [x] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Review by cstyan — COMMENTED** [review]
This doesn't look right, at least I don't see the drone job building `lambda-promtail-arm64`
```
Successfully tagged 25e0d225ae133d9faf0acf560f7c6273b24f4064:latest
+ /usr/local/bin/docker tag 25e0d225ae133d9faf0acf560f7c6273b24f4064 public.ecr.aws/grafana/lambda-promtail:main-17a1a17-amd64
+ /usr/local/bin/docker tag 25e0d225ae133d9faf0acf560f7c6273b24f4064 public.ecr.aws/grafana/lambda-promtail:main
+ /usr/local/bin/docker rmi 25e0d225ae133d9faf0acf560f7c6273b24f4064
```

I think we need further modifications to the jsonnet code to make the lambda_promtail stages look more like the other images we're building.

**Comment by tlinhart** [comment]
Hi @cstyan,
I assume this is because I modified just the `drone.jsonnet` without regenerating the `drone.yml`. Running `make drone` should do in my opinion, but I don't posses the `DRONE_TOKEN` so I can't sign the YAML file. However, I tried running the `drone jsonnet --stream --format ...` command from `Makefile` and it builds a correct `drone.yml` (I diffed it against the current `drone.yml`).
I tried to reuse as much from the current `drone.jsonnet` as possible considering the Promtail Lambda is the only image pushed to ECR Public.

**Comment by cstyan** [comment]
:man_facepalming: Ah right, if you give me push access to your fork I can push a change with the new generated yaml.

**Comment by tlinhart** [comment]
Sure, I've sent you an invitation.

**Comment by cstyan** [comment]
Lets see how this goes.

**Comment by cstyan** [comment]
Okay, I think there's more that we need to do here. The docker image that runs to build the image on builds for the default architecture in the alpine image, that needs to be changed so that if we're doing the arm64 build we crosscompile for arm64.

**Comment by tlinhart** [comment]
I'll take a look it at. Any advice on testing it locally? Is `drone exec` the way?

**Comment by tlinhart** [comment]
Taking another look at it. The `drone.yml` seems to contain correct `platform` section and according to the documentation (https://docs.drone.io/pipeline/docker/syntax/platform/), this should lead to routing the build to the correct runner which, AFAIK, leads to trying to use the image with matching architecture. It seems like the problem is with the `cstyan/ecr` image not built for the ARM64 architecture?

**Comment by cstyan** [comment]
> Taking another look at it. The `drone.yml` seems to contain correct `platform` section and according to the documentation (https://docs.drone.io/pipeline/docker/syntax/platform/), this should lead to routing the build to the correct runner which, AFAIK, leads to trying to use the image with matching architecture. It seems like the problem is with the `cstyan/ecr` image not built for the ARM64 architecture?

`cstyan/ecr` is just a fork of drones existing ecr image build plugin that supports publishing to a public ecr repo. I think the issue is that the Dockerfile the job uses `tools/lambda-promtail/Dockerfile` doesn't attempt to cross compile the Go binary for arm64 and still builds the final `lambda-promtail` image into an alpine base image.

**Comment by cstyan** [comment]
> I'll take a look it at. Any advice on testing it locally? Is drone exec the way?

You can try running the drone pipeline locally, but I'd start with getting the dockerfile working to build an arm64 image that you confirm runs lambda-promtail as expected.

**Comment by tlinhart** [comment]
I'll try to convince you. Compare manifests for `plugins/docker` image:

```
pasmen@nyx:~$ docker manifest inspect --verbose plugins/docker | jq '.[].Descriptor.platform'
{
  "architecture": "amd64",
  "os": "linux"
}
{
  "architecture": "arm64",
  "os": "linux",
  "variant": "v8"
}
{
  "architecture": "arm",
  "os": "linux",
  "variant": "v7"
}
{
  "architecture": "amd64",
  "os": "windows",
  "os.version": "10.0.17134.706"
}
{
  "architecture": "amd64",
  "os": "windows",
  "os.version": "10.0.17763.1457"
}
{
  "architecture": "amd64",
  "os": "windows",
  "os.version": "10.0.18362.295"
}
{
  "architecture": "amd64",
  "os": "windows",
  "os.version": "10.0.18363.1139"
}
```

and `cstyan/ecr` image:

```
pasmen@nyx:~$ docker manifest inspect --verbose cstyan/ecr | jq '.Descriptor.platform'
{
  "architecture": "amd64",
  "os": "linux"
}
```

It's obvious there's ARM64 variant for `plugins/docker` Docker image while there's no ARM64 variant for `cstyan/ecr` Docker image. To confirm this, I tried to spin up the `t4g.small` (ARM64) EC2 and run both Docker images. For `plugins/docker` I got:

```
ssm-user@ip-xxx-xxx-xxx-xxx:~$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock plugins/docker
+ /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock
Registry credentials or Docker config not provided. Guest mode enabled.
+ /usr/local/bin/docker version
Client:
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:03:36 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true
...
```

while for `cstyan/ecr` I got:

```
ssm-user@ip-xxx-xxx-xxx-xxx:~$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock cstyan/ecr
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

Exactly the same as reported by the [Drone build](https://drone.grafana.net/grafana/loki/8566/14/3):

```
latest: Pulling from cstyan/ecr
Digest: sha256:a9a6085f477aa3fd5e5a3e05406c61b30e4123560064e40c527ac4a89187bdd1
Status: Downloaded newer image for cstyan/ecr:latest
standard_init_linux.go:228: exec user process caused: exec format error
```

As I already stated in the PR description, I tried to actually build the ARM64 `lambda-promtail` Docker image using the `Dockerfile` from repository with success, both on x86-64 architecture using QEMU emulation and on ARM64 architecture (EC2 machine). So I presume there's nothing wrong with the `Dockerfile` nor the Drone job configuration.

**Comment by cstyan** [comment]
I'm not sure how your build locally via the dockerfile to build the binary for arm64 works, the docker image only builds lambda-promtail for the default arch on the `golang:1-alpine3.14` image which I assume is amd64. 

I think we either need to modify the Dockerfile to optionally take an argument to change the Go build architecture to arm64, and have a second pipeline for that, or double check that the ECR image should work for arm64 and potentially publish another version of the image? 

I honestly don't know how this all currently works for the other images we build that do support arm64.

**Comment by tlinhart** [comment]
From the Drone documentation:

> Use the `platform` section to configure the target operating system and architecture and routes the pipeline to the appropriate runner.

I modified the `drone.jsonnet` so that it prepares two pipelines in `drone.yml`, one for x86-64 and one for ARM64 (pretty much the same way it does for other tools). The ARM64 pipeline tries to pull the ARM64 version of `cstyan/ecr` image for building the lambda-promtail, but as I posted earlier, there's none so it pulls the only available, x86-64 variant, which leads to architecture mismatch as shown above.

I'm pretty sure the only thing needed is to build and publish the ARM64 variant of `cstyan/ecr` Docker image.

**Comment by tlinhart** [comment]
Hi @cstyan,
I see your effort in https://github.com/grafana/loki/pull/5403. When I look at the [`cstyan/ecr`](https://hub.docker.com/r/cstyan/ecr/tags) repository, I see there a Docker image with `arm64` tag which itself is not enough, IMO. The Drone pipeline hasn't changed so it still tries to pull the `latest` tag, and that is a manifest for x86-64 architecture. I tried to clone your repository and build the Docker image the way I think is correct. Here's the exact steps I took:

```
git clone https://github.com/cstyan/drone-docker.git
cd drone-docker

export GOOS=linux
export CGO_ENABLED=0
export GO111MODULE=on

export GOARCH=amd64
go build -v -a -tags netgo -o release/linux/amd64/drone-ecr ./cmd/drone-ecr

export GOARCH=arm64
go build -v -a -tags netgo -o release/linux/arm64/drone-ecr ./cmd/drone-ecr

docker login -u tlinhart
docker build \
  --label org.label-schema.build-date=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --label org.label-schema.vcs-ref=$(git rev-parse --short HEAD) \
  --file docker/ecr/Dockerfile.linux.amd64 --tag tlinhart/drone-ecr-public:amd64 .
docker push tlinhart/drone-ecr-public:amd64

docker build \
  --label org.label-schema.build-date=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --label org.label-schema.vcs-ref=$(git rev-parse --short HEAD) \
  --file docker/ecr/Dockerfile.linux.arm64 --tag tlinhart/drone-ecr-public:arm64 .
docker push tlinhart/drone-ecr-public:arm64

docker manifest create tlinhart/drone-ecr-public:latest \
  --amend tlinhart/drone-ecr-public:amd64 \
  --amend tlinhart/drone-ecr-public:arm64
docker manifest push tlinhart/drone-ecr-public:latest
```

Now there's a Docker image [`tlinhart/drone-ecr-public`](https://hub.docker.com/r/tlinhart/drone-ecr-public/tags) with tags for both architectures and a `latest` tag with a manifest list for those architectures:

```
$ docker manifest inspect tlinhart/drone-ecr-public
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3036,
         "digest": "sha256:bc0e850763dcee8866b87b1ad9d51073af6919fd6bf54c416522c60659485fa4",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3036,
         "digest": "sha256:6dcc5c7a71e12854fac9875df4220fc3a7760fbcc26f593c0a41764a3f1fe4cd",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

I update the Drone pipeline to use this image to confirm it works, but it seems the build here is blocked (https://drone.grafana.net/grafana/loki/8807). If you could unblock it, we would see if that's the missing part or not.

The cross-compile way doesn't look the best to me, for couple of reasons:

- It makes the build process for Promtail Lambda diverged from the rest of the tools.
- It's a bit more complex that just using the correct runner.

Thus, in compliance with Occam's razor, I'd prefer this PR over the https://github.com/grafana/loki/pull/5403 (granted this approarch works).

**Comment by tlinhart** [comment]
As a sidenote, couple of days ago I create a PR to add ECR Public support to the official `drone-docker` plugins repository (see https://github.com/drone-plugins/drone-docker/pull/357). If it gets merged, it might streamline things a bit more.

**Comment by cstyan** [comment]
Thanks for the detailed step by step @tlinhart Honestly my experience using docker tagging and especially manifests was next to nothing, so that was really helpful.

If we were building everything from scratch I think cross compiling would have been simpler but I agree that at this point that there's value in building the lambda-promtail images in the same way that the other images are built.

The last thing I'm unsure about is the tags we're publishing the images for. We seem to have different sha values in each build + we're tagging and then probably pushing a tag `main` from both the arm64 and amd64 build jobs.

**Comment by tlinhart** [comment]
Hi @cstyan, I'm glad it worked! And you are right that there's one last thing that needs to be done – creating and pushing manifest list covering both architectures. Each build results in a distinct Docker image (identified by its digest). The tag is just a named reference to the image. So it's OK that both images (tags) are pushed. Now we just have to create and push manifest for tag `main` that will list both images for the respective architectures. I'll take a look at it tomorrow, if you agree.

**Comment by cstyan** [comment]
> Now we just have to create and push manifest for tag main that will list both images for the respective architectures. I'll take a look at it tomorrow, if you agree.

If this is what the other builds are doing then there's likely some jsonnet code we can reuse. Maybe the original jsonnet function I wrote for `lambda-promtail` needs to be refactored a bit more to be like the other clients functions?

**Comment by tlinhart** [comment]
Hi @cstyan, sorry for the late reply. I'm still trying to work around the https://github.com/estesp/manifest-tool/issues/124 issue which seems to be blocking the final step (i.e. push the `main` tag manifest listing images for individual architectures). Let's hope I'll get some more time to figure it out.

**Comment by tlinhart** [comment]
Hi @cstyan, I have some promising interim results. I tried to actually replicate the https://github.com/estesp/manifest-tool/issues/124 issue with `manifest-tool` and ECR Public and it seems I'm not having the issue. Here's what I did.

1. Log into ECR Public registry and push a couple of images for x86-64 and ARM64 architectures:

```
aws ecr-public get-login-password --region us-east-1 \
| docker login --username AWS --password-stdin public.ecr.aws

docker pull --platform linux/amd64 hello-world:latest
docker tag hello-world:latest public.ecr.aws/tlinhart/hello-world:amd64
docker push public.ecr.aws/tlinhart/hello-world:amd64

docker pull --platform linux/arm64 hello-world:latest
docker tag hello-world:latest public.ecr.aws/tlinhart/hello-world:arm64
docker push public.ecr.aws/tlinhart/hello-world:arm64
```

2. Prepare the `manifest.yml` specification for `manifest-tool` with this content:

```
image: public.ecr.aws/tlinhart/hello-world:latest
manifests:
  - image: public.ecr.aws/tlinhart/hello-world:amd64
    platform:
      architecture: amd64
      os: linux
  - image: public.ecr.aws/tlinhart/hello-world:arm64
    platform:
      architecture: arm64
      os: linux
```

This would create a manifest list with tag `latest` containing Docker images for individual architectures.

3. Push the manifests list to repository with `manifest-tool` (v2.0.3 binary downloaded from the GitHub release):

```
manifest-tool-linux-amd64 \
  --username AWS \
  --password "$(aws ecr-public get-login-password --region us-east-1)" \
  push from-spec manifest.yml
```

4. Replicate the same with Drone `plugin/manifest` Docker image to simulate the Drone pipeline as close as possible:

```
docker run --rm \
  -e PLUGIN_USERNAME=AWS \
  -e PLUGIN_PASSWORD="$(aws ecr-public get-login-password --region us-east-1)" \
  -e PLUGIN_SPEC=./manifest.yml \
  -v $(pwd)/manifest.yml:/tmp/manifest.yml -w /tmp plugins/manifest
```

5. Inspect the manifest to check the results:

```
docker manifest inspect public.ecr.aws/tlinhart/hello-world:latest

{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 525,
         "digest": "sha256:f54a58bc1aac5ea1a25d796ae155dc228b3f0e11d046ae276b39c4bf2f13d8c4",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 525,
         "digest": "sha256:432f982638b3aefab73cc58ab28f5c16e96fdb504e8c134fc58dff4bae8bf338",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      }
   ]
}
```

So far, this seems promising. The only two (hopefully) open points I see at the moment are:

1. The `plugin/manifest` expects `username` and `password` in the `settings`, however what we available instead are `ecr_key` and `ecr_secret_key` secrets. I first need to call `aws ecr-public get-login-password --region us-east-1` to get the password for Docker login from AWS credentials and then somehow make it available to the `plugin/manifest` step. I currently don't know Drone enough to be able to tell how to do it. If you have any suggestion, please let me know. I'll try to investigate possible solutions in the meantime.
2. Actually update the `drone.jsonnet` to add the `plugin/manifest` step.

**Comment by cstyan** [comment]
@tlinhart awesome! unless I am misunderstanding it sounds like the credentials bit is sorted out and you have a path forward

**Comment by cstyan** [comment]
Hey @tlinhart thanks again for all your awesome work here. There was a minor issue with the volumes definition in the ecr function, I made a small change to fix that and regenerated the `drone.jsonnet`, I also pushed a second commit that should allow the build to run even before a push to main. Lets see how that goes. On top of that, I had to merge master in and generate the jsonnet again, because merge conflicts :man_shrugging:

**Comment by cstyan** [comment]
okay @tlinhart it looks like maybe the way we're setting up the authentication is incorrect?

**Comment by tlinhart** [comment]
@cstyan thanks for the corrections! Seems like I forgot to define the Docker volume in the pipeline (https://docs.drone.io/pipeline/docker/syntax/volumes/temporary/). I added it to the `.drone/drone.jsonnet`, may I ask you to regenerate the `.drone/drone.yml` to see if it works now?

**Comment by cstyan** [comment]
@tlinhart it looks like we have a mismatch between the SHA used in the image tag when building and publishing the image, and the SHA used to try and find the images when creating the manifest. Unfortunately I haven't been able to track the source of that mismatch down, but I do have a few other things in progress right now. Let me know if you can find the issue, otherwise I can dig into this more later in the week.

**Comment by tlinhart** [comment]
Hi @cstyan, I tried to simulate the process and I think the problem is only due to the fact that we try to create and push the manifest list from the fork/PR. If pushed to the `main` branch the problem would not occur. This is not 100%, though, so I'd need your confimation or test it somehow. Here's my observations:

1. The latest commit to my fork is yours commit https://github.com/tlinhart/loki/commit/17d2382d5b7ca8d0c1eeb607670a46b5144c6c08 with ID `17d2382`. This corresponds to the tag(s) that `plugins/manifest` expects when creating the manifest list in the [`manifest-lambda-promtail` step of the `manifest-ecr` pipeline](https://drone.grafana.net/grafana/loki/10940/17/3):

```
time="2022-04-18T00:06:19Z" level=warning msg="Couldn't find or access image reference \"public.ecr.aws/grafana/lambda-
promtail:main-17d2382-amd64\". Skipping image."
time="2022-04-18T00:06:19Z" level=warning msg="Couldn't find or access image reference \"public.ecr.aws/grafana/lambda-
promtail:main-17d2382-arm64\". Skipping image."
```

This comes from `build.tag` used in the [manifest tool spec file](https://github.com/tlinhart/loki/blob/main/.drone/docker-manifest-ecr.tmpl).

2. The actual tag that the Lambda Promtail image is tagged with comes from the [`./tools/image-tag`](https://github.com/tlinhart/loki/blob/main/tools/image-tag) script run in the `image-tag` step of the pipeline, which is run after the `clone` step. Now consider what the `clone` step does and how it differs for a [push to fork/PR](https://drone.grafana.net/grafana/loki/10940/16/1) and for a [push to `main` branch](https://drone.grafana.net/grafana/loki/10984/17/1). For the push to a fork/PR, it first merges the PR head to `main` and the hash of the resulting merge commit becomes the hash used by `image-tag`. For the push to a `main` branch, this does not happen and thus the tags used by `image-tag` and by `plugins/manifest` match.

So, I'd say that everything will work just fine once merged to `main`. What do you think, does it make sense?

**Comment by tlinhart** [comment]
Hi @cstyan, just a quick ping if you could take a look at my last comment.

**Comment by tlinhart** [comment]
Hi @cstyan, is there anything I can do make a progress?

**Comment by cstyan** [comment]
Hey @tlinhart, sorry for the delay! 

Just read over your explanation, it makes sense to me. I will run it by another person on the team who has some experience with our CI and image build setup next week just to confirm. It looks like the `drone.yml` file has some conflicts as well, I will resolve that.

**Comment by tlinhart** [comment]
Great, thanks @cstyan!

**Comment by tlinhart** [comment]
Hi @cstyan, could you please give it a try and confirm my assumptions?

**Comment by cstyan** [comment]
I think we're probably good to go. I will regenerate the drone yaml file in the morning.

**Review by owen-d — APPROVED** [review]

**Comment by cstyan** [comment]
@tlinhart everything looking good?

**Comment by tlinhart** [comment]
Hi @cstyan,
regarding the ARM64 architecture, everything is working great. There's one minor hiccup with that AWS Lambda service doesn't yet support multi-arch container images (see the discussion [here](https://repost.aws/questions/QUIZjd2sL_TtCuoqtg5Q30LA/does-lambda-not-support-multi-architecture-container-images-manifests)). Thus, we can't simply use the tag `main` but have to stick with specific commit's tag (e.g. `main-b3b3da6-arm64`). Until AWS Lambda adds the support, it would probably be best to also generate tags for specific architectures like `main-arm64`. I'll consider opening another PR for this if you agree it's a good idea. I suppose that would be a minor change to the `drone.jsonnet` file.

**Pull request merged**
