### PR TITLE
feat(Helm): Support for Zone Awareness and rollout-operator

### PR DESCRIPTION
**Pull request by alex5517**
**What this PR does / why we need it**:
Adds support for zone awareness and use of rollout-operator
It also makes some changes to labeling and annotations so that it is done in a similar way to how the mimir-distributed helm chart does it. - A few other "alignments" have been done with the way mimir-distributed helm chart does it. 
**Which issue(s) this PR fixes**:
Fixes #N/A

**Special notes for your reviewer**:
I will be adding docs for how to migrate from single zone to zone-aware replication, and i know it is a large PR but i have have tried to keep it familiar by implementing it the "same" way as it is done for mimir-distributed helm chart, i have also used the "guide" (https://grafana.com/docs/loki/latest/operations/zone-ingesters/) for the jsonnet deployment to make the migration possible in almost the same way. 

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] `CHANGELOG.md` updated
  - [x] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [x] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by alex5517** [comment]
@JStickler or @MichelHollands 

Could you let me know if this PR contains to many changes/to large for it to have a chance of being merged?
If it does not have a chance i can also make a smaller PR where it is implemented by just hacking it into production/helm/loki/templates/write/_helpers-write.tpl

**Comment by alex5517** [comment]
Hi @MichelHollands or @JStickler,

Are you able to review this PR, or am i missing something before this is possible?

**Comment by MichelHollands** [comment]
> Hi @MichelHollands or @JStickler,
> 
> Are you able to review this PR, or am i missing something before this is possible?

@alex5517 Sorry for the late reply. Due to holidays we had a backlog. This PR is a bit too big to merge as is, as you alluded to. Is it possible to split this into multiple smaller PRs? There's too much of a risk of breaking other installs with large PRs. Thanks for the contribution though, this is really impressive work.

**Comment by alex5517** [comment]
@MichelHollands, 

I understand, the big changes in the PR is the change to how labeling is done, so i could possible split this PR into 3 seperate PRs
1. Labeling Change: Focused on alterations to the labeling mechanism.
2. Minor Adjustments to Statically Defined Elements: small changes.
3- Zone-Awareness Support: Dedicated to the integration of zone-awareness.

Do you believe this approach would be feasible? While the labeling PR might still appear substantial, it primarily results from identical changes applied across all resources. However, examining the YAML generated (old vs new) should facilitate easier validation.

Are you comfortable with reviewing and merging three distinct pull requests? Alternatively, I could create a pull request that quickly(hackish) integrates it into the helper.tpl file. Let me know your thoughts.

**Comment by alex5517** [comment]
@MichelHollands,

Have you had time to consider my previous comment?

**Pull request closed without merging**
