### PR TITLE
loki helm chart: fix indentation in single-binary pdb template

### PR DESCRIPTION
**Pull request by zarikx**
**What this PR does / why we need it**:
After enabling pdb in `loki` helm chart, occurs `unknown field "app.kubernetes.io/name" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector]` error

**Which issue(s) this PR fixes**:
Indentation in single-binary pdb template

**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [x] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by trevorwhitney — APPROVED** [review]
Thanks for the fix! LGTM!

**Comment by zarikx** [comment]
Updated fork and pushed small fix

**Comment by trevorwhitney** [comment]
@zarikx can you rebase with `main` to fix the CHANGELOG issue? thanks!

**Comment by zarikx** [comment]
done

**Comment by trevorwhitney** [comment]
@zarikx could you fix the Changelog conflict? Sorry things are moving so fast on helm these past few days

**Comment by zarikx** [comment]
done

**Comment by MichelHollands** [comment]
@zarikx Can you rebase this PR? I can commit it once that is done.

**Comment by zarikx** [comment]
@MichelHollands done

**Pull request merged**
