### PR TITLE
jsonnet: move boltdb-shipper configs set as compactor args to yaml config

### PR DESCRIPTION
**Pull request by sandeepsukhani**
**What this PR does / why we need it**:
Move some of the boltdb-shipper config set as compactor args to the yaml config file.
This is needed to keep the config consistent i.e set them using yaml instead of CLI args.

### CODE REVIEW

**Comment by dannykopping** [comment]
> **What this PR does / why we need it**: Move some of the boltdb-shipper config set as compactor args to the yaml config file.

Why do we need this?

**Comment by sandeepsukhani** [comment]
> > **What this PR does / why we need it**: Move some of the boltdb-shipper config set as compactor args to the yaml config file.
> 
> Why do we need this?

@dannykopping sorry, updated the PR description.

**Review by dannykopping — APPROVED** [review]
LGTM; we may want to mention this change in the upgrade guide

**Comment by sandeepsukhani** [comment]
> LGTM; we may want to mention this change in the upgrade guide

Updated the changelog entry which I guess would be looked at when doing a public release. To make it more reliable I think we should have github labels or some other way to call out such changes to help the person doing the release?

**Comment by dannykopping** [comment]
> > LGTM; we may want to mention this change in the upgrade guide
> 
> Updated the changelog entry which I guess would be looked at when doing a public release. To make it more reliable I think we should have github labels or some other way to call out such changes to help the person doing the release?

I think the general process is to add it under "Main / Unreleased" in `docs/sources/upgrading/_index.md`, but I agree we could have something more robust. Maybe labels like `patch`, `breaking`, `feature`, etc.

**Pull request merged**
