### PR TITLE
promtail: fix syslog udp messages never processed

### PR DESCRIPTION
**Pull request by unawarez**
**What this PR does / why we need it**:

Prior to this patch, incoming UDP syslogs would only be sent to promtail targets all at once when promtail shut down. The ultimate cause seems to be that `go-syslog`'s stream parsers are not emitting any messages until the input stream is closed, even after newline-delimiting the messages. This patch closes those streams after one packet's contents and a newline are sent.

**Which issue(s) this PR fixes**:

#6772 is probably this

**Special notes for your reviewer**:

**Checklist**
- [X] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added *(n/a)*
- [ ] Tests updated *(n/a)*
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md` *(n/a)*

### CODE REVIEW

**Comment by unawarez** [comment]
I'm backing this out to a draft, because it created another bug on a different machine... I think it's something about having a consistent source port for the packets, which points to something about `UDPTransport.streams` keeping pipes based on source address.

**Comment by unawarez** [comment]
OK I've now seen this work on both macOS and FreeBSD, forwarding real syslogs from the latter.

I just could not get any logs to post without closing the internal io.Pipes. I sort of wonder if it's framing-related, and if writing an octet count in front of the packet would make it work without closing...

Closing the pipes also meant they couldn't be persisted in the `streams` map. Without that, it might be worth directly using the non-stream-based parsers from `go-syslog` and dropping the internal pipes altogether for UDP...

**Comment by chaudum** [comment]
Thanks @unawarez for looking into this again! 

> Closing the pipes also meant they couldn't be persisted in the streams map. Without that, it might be worth directly using the non-stream-based parsers from go-syslog and dropping the internal pipes altogether for UDP...

That sounds like a reasonable approach to me. However, I would like to know whether this has performance implications. Writing a benchmark test would be great!

**Comment by unawarez** [comment]
Cool, I can try writing a benchmark test over the next couple days

**Comment by unawarez** [comment]
Haven’t had time unfortunately… I can definitely rebase this tonight, and if I can find a similar benchmark in this repo to start from then maybe I could put that together while I’m at it.

**Comment by unawarez** [comment]
somehow f7fa4c4 was categorically worse, and did not fix the extra newline test failure, which main does not have

**Comment by unawarez** [comment]
I found there is already a `Benchmark_SyslogTarget`. On my machine I get this for current main, a1d46d2bcc077e75333f2b23a0bcbe08dc8dadd6:
```
% (cd ../../pkg/promtail/targets/syslog; go clean && go test -bench=SyslogTarget -run='^#' -count=5)
goos: darwin
goarch: arm64
pkg: github.com/grafana/loki/clients/pkg/promtail/targets/syslog
Benchmark_SyslogTarget/tcp-10         	      1	1001671917 ns/op	  46704 B/op	    437 allocs/op
Benchmark_SyslogTarget/tcp-10         	      1	1001956250 ns/op	  46160 B/op	    433 allocs/op
Benchmark_SyslogTarget/tcp-10         	      1	1001519250 ns/op	  46368 B/op	    431 allocs/op
Benchmark_SyslogTarget/tcp-10         	      1	1001915375 ns/op	  46736 B/op	    432 allocs/op
Benchmark_SyslogTarget/tcp-10         	      1	1002232375 ns/op	  45792 B/op	    429 allocs/op
Benchmark_SyslogTarget/udp-10         	      1	1001507250 ns/op	  45096 B/op	    468 allocs/op
Benchmark_SyslogTarget/udp-10         	      1	1001478791 ns/op	  46048 B/op	    476 allocs/op
Benchmark_SyslogTarget/udp-10         	      1	1001407458 ns/op	  45416 B/op	    471 allocs/op
Benchmark_SyslogTarget/udp-10         	      1	1001726917 ns/op	  45992 B/op	    477 allocs/op
Benchmark_SyslogTarget/udp-10         	      1	1001358750 ns/op	  45352 B/op	    470 allocs/op
PASS
ok  	github.com/grafana/loki/clients/pkg/promtail/targets/syslog	10.718s
```
On this PR 94f4b16ffb2f7ef835190c7f4cfc6461686eb4b8 I get this instead:
```
Benchmark_SyslogTarget/tcp-10         	      1	1001681458 ns/op	  46296 B/op	    436 allocs/op
Benchmark_SyslogTarget/tcp-10         	      1	1002053958 ns/op	  46736 B/op	    432 allocs/op
Benchmark_SyslogTarget/tcp-10         	      1	1001664959 ns/op	  46048 B/op	    432 allocs/op
Benchmark_SyslogTarget/tcp-10         	      1	1002507042 ns/op	  46112 B/op	    429 allocs/op
Benchmark_SyslogTarget/tcp-10         	      1	1001686292 ns/op	  46400 B/op	    432 allocs/op
Benchmark_SyslogTarget/udp-10         	      1	1002141375 ns/op	 161752 B/op	    802 allocs/op
Benchmark_SyslogTarget/udp-10         	      1	1002111208 ns/op	 158616 B/op	    793 allocs/op
Benchmark_SyslogTarget/udp-10         	      1	1001899958 ns/op	 159288 B/op	    783 allocs/op
Benchmark_SyslogTarget/udp-10         	      1	1001866958 ns/op	 161096 B/op	    798 allocs/op
Benchmark_SyslogTarget/udp-10         	      1	1001939333 ns/op	 156520 B/op	    776 allocs/op
```
Much worse heap activity for sure, and still has the extra newline test failure. I'll see what else I can do.

But! There's another interesting story if you run more than one iteration. That's why I was using `-count=5` above. If I replace `-count=5` with `-benchtime=2s` then even on current main a1d46d2bcc077e75333f2b23a0bcbe08dc8dadd6 the UDP benchmark errors out:
```
% (cd ../../pkg/promtail/targets/syslog; go clean && go test -bench=SyslogTarget -run='^#' -benchtime=2s)
goos: darwin
goarch: arm64
pkg: github.com/grafana/loki/clients/pkg/promtail/targets/syslog
Benchmark_SyslogTarget/tcp-10         	  31761	    64496 ns/op	  32235 B/op	    360 allocs/op
Benchmark_SyslogTarget/udp-10         	--- FAIL: Benchmark_SyslogTarget/udp-10
    syslogtarget_test.go:350: 
        	Error Trace:	/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/syslogtarget_test.go:350
        	           				/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/benchmark.go:193
        	           				/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/benchmark.go:334
        	           				/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/asm_arm64.s:1172
        	Error:      	Condition never satisfied
        	Test:       	Benchmark_SyslogTarget/udp
        	Messages:   	expected: 9210 got:2072
--- FAIL: Benchmark_SyslogTarget
FAIL
exit status 1
FAIL	github.com/grafana/loki/clients/pkg/promtail/targets/syslog	44.354s
```
Maybe it's the "udp messages never emitted" bug manifesting, or maybe it's a coincidence.

Either way I should have time tomorrow to try out the string-based parser (https://github.com/grafana/loki/pull/7231#issuecomment-1255740151) and be able to get a comparison against main using this benchmark. I have some hope that approach could get past the extra newline issue.

**Comment by unawarez** [comment]
I dug pretty deep into the tests trying to figure out the flakiness. I'm about to rebase and start over with a commit that only makes some changes to the unit test and benchmark for UDP. The biggest thing is I think octet counting inside UDP packets is not allowed. Octet counting is only defined in the TCP RFC [6587](https://www.rfc-editor.org/rfc/rfc6587.html#section-3.4.1). The UDP RFC [5426](https://www.rfc-editor.org/rfc/rfc5426#section-3.1) just says the packet contents are formatted "according to RFC 5424".

**Comment by unawarez** [comment]
OK, here is a comparison of all 3 commits above. Sadly `-benchtime 1.1s` still makes all the UDP benchmarks die on all these commits, so it's still a `-count 5` comparison.

# 1f0a3c291 main w/ udp raw tests

## test
```
level=info msg="syslog listening on address" address=127.0.0.1:61445 protocol=tcp tls=false
level=info address=127.0.0.1:61445 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61447 protocol=tcp tls=false
level=info address=127.0.0.1:61447 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:55189 protocol=udp
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:55189: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
level=warn msg="error parsing syslog stream" err="unexpected EOF"
level=info msg="syslog listening on address" address=127.0.0.1:64234 protocol=udp
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:64234: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:62758 protocol=udp
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:62758: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
--- FAIL: TestSyslogTarget (4.11s)
    --- FAIL: TestSyslogTarget/udp_raw (2.01s)
        syslogtarget_test.go:415: 
            	Error Trace:	/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/syslogtarget_test.go:415
            	Error:      	Condition never satisfied
            	Test:       	TestSyslogTarget/udp_raw
            	Messages:   	Expected to receive 3 messages.
level=info msg="syslog listening on address" address=127.0.0.1:61450 protocol=tcp tls=false
level=info address=127.0.0.1:61450 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61452 protocol=tcp tls=false
level=info address=127.0.0.1:61452 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61456 protocol=tcp tls=true
level=warn msg="error parsing syslog stream" err="expecting a RFC3339MICRO timestamp or a nil value [col 7]"
level=warn msg="error parsing syslog stream" err="expecting a msgid (from 1 to max 32 US-ASCII characters) or a nil value [col 42]"
level=info address=127.0.0.1:61456 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61458 protocol=tcp tls=true
level=warn msg="error parsing syslog stream" err="expecting a RFC3339MICRO timestamp or a nil value [col 7]"
level=warn msg="error parsing syslog stream" err="expecting a msgid (from 1 to max 32 US-ASCII characters) or a nil value [col 42]"
level=info address=127.0.0.1:61458 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61460 protocol=tcp tls=true
level=warn msg="error initializing syslog stream" err="tls: client didn't provide a certificate"
level=info address=127.0.0.1:61460 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61463 protocol=tcp tls=true
level=warn msg="error initializing syslog stream" err="tls: client didn't provide a certificate"
level=info address=127.0.0.1:61463 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61466 protocol=tcp tls=false
level=warn msg="error initializing syslog stream" err="invalid or unsupported framing. first byte: 'x'"
level=info address=127.0.0.1:61466 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61468 protocol=tcp tls=false
level=info address=127.0.0.1:61468 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61470 protocol=tcp tls=false
level=warn msg="error initializing syslog stream" err="read tcp 127.0.0.1:61470->127.0.0.1:61471: i/o timeout"
level=info address=127.0.0.1:61470 msg="syslog server shutting down" protocol=tcp err="context canceled"
FAIL
exit status 1
FAIL	github.com/grafana/loki/clients/pkg/promtail/targets/syslog	4.753s
```

## bench
```
enchmark_SyslogTarget/tcp_octetcounting-10         	      1	1001722958 ns/op	  46656 B/op	    434 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1001921084 ns/op	  46096 B/op	    433 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1001236750 ns/op	  45712 B/op	    428 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1002382542 ns/op	  46592 B/op	    434 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1001309000 ns/op	  45856 B/op	    429 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	      1	1001906084 ns/op	  45096 B/op	    468 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	      1	1001936541 ns/op	  45352 B/op	    470 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	      1	1001572958 ns/op	  45832 B/op	    472 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	      1	1001894583 ns/op	  45416 B/op	    471 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	      1	1002085083 ns/op	  45704 B/op	    471 allocs/op
--- FAIL: Benchmark_SyslogTarget/udp_raw
    syslogtarget_test.go:352: 
        	Error Trace:	/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/syslogtarget_test.go:352
        	           				/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/benchmark.go:193
        	           				/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/benchmark.go:233
        	           				/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/asm_arm64.s:1172
        	Error:      	Condition never satisfied
        	Test:       	Benchmark_SyslogTarget/udp_raw
        	Messages:   	expected: 10 got:0
```



# 909bd94aa stream-based parser

## test
```
evel=info msg="syslog listening on address" address=127.0.0.1:61531 protocol=tcp tls=false
level=info address=127.0.0.1:61531 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61533 protocol=tcp tls=false
level=info address=127.0.0.1:61533 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:65005 protocol=udp
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:65005: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:53125 protocol=udp
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:53125: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:52738 protocol=udp
level=warn msg="error parsing syslog stream" err="found ILLEGAL(\n), expecting a MSGLEN"
level=warn msg="error parsing syslog stream" err="found ILLEGAL(\n), expecting a MSGLEN"
level=warn msg="error parsing syslog stream" err="found ILLEGAL(\n), expecting a MSGLEN"
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:52738: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
--- FAIL: TestSyslogTarget (3.12s)
    --- FAIL: TestSyslogTarget/udp_newline_separated (1.03s)
        syslogtarget_test.go:436: 
            	Error Trace:	/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/syslogtarget_test.go:436
            	Error:      	Not equal: 
            	           	expected: "An application event log entry..."
            	           	actual  : "An application event log entry...\n"
            	           	
            	           	Diff:
            	           	--- Expected
            	           	+++ Actual
            	           	@@ -1 +1,2 @@
            	           	An application event log entry...
            	           	+
            	Test:       	TestSyslogTarget/udp_newline_separated
level=info msg="syslog listening on address" address=127.0.0.1:61535 protocol=tcp tls=false
level=info address=127.0.0.1:61535 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61537 protocol=tcp tls=false
level=info address=127.0.0.1:61537 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61541 protocol=tcp tls=true
level=warn msg="error parsing syslog stream" err="expecting a RFC3339MICRO timestamp or a nil value [col 7]"
level=warn msg="error parsing syslog stream" err="expecting a msgid (from 1 to max 32 US-ASCII characters) or a nil value [col 42]"
level=info address=127.0.0.1:61541 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61543 protocol=tcp tls=true
level=warn msg="error parsing syslog stream" err="expecting a RFC3339MICRO timestamp or a nil value [col 7]"
level=warn msg="error parsing syslog stream" err="expecting a msgid (from 1 to max 32 US-ASCII characters) or a nil value [col 42]"
level=info address=127.0.0.1:61543 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61545 protocol=tcp tls=true
level=warn msg="error initializing syslog stream" err="tls: client didn't provide a certificate"
level=info address=127.0.0.1:61545 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61548 protocol=tcp tls=true
level=warn msg="error initializing syslog stream" err="tls: client didn't provide a certificate"
level=info address=127.0.0.1:61548 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61551 protocol=tcp tls=false
level=warn msg="error initializing syslog stream" err="invalid or unsupported framing. first byte: 'x'"
level=info address=127.0.0.1:61551 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61553 protocol=tcp tls=false
level=info address=127.0.0.1:61553 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61555 protocol=tcp tls=false
level=warn msg="error initializing syslog stream" err="read tcp 127.0.0.1:61555->127.0.0.1:61556: i/o timeout"
level=info address=127.0.0.1:61555 msg="syslog server shutting down" protocol=tcp err="context canceled"
FAIL
exit status 1
FAIL	github.com/grafana/loki/clients/pkg/promtail/targets/syslog	3.770s
```

## bench
```
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1001823916 ns/op	  47104 B/op	    437 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1002012750 ns/op	  46656 B/op	    434 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1002205500 ns/op	  47072 B/op	    436 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1002001500 ns/op	  45856 B/op	    429 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1002395792 ns/op	  46544 B/op	    433 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	      1	1002210042 ns/op	 157288 B/op	    785 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	      1	1002043209 ns/op	 160120 B/op	    785 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	      1	1001483750 ns/op	 162088 B/op	    805 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	      1	1001712667 ns/op	 157224 B/op	    785 allocs/op
Benchmark_SyslogTarget/udp_octetcounting-10         	      1	1001988000 ns/op	 156312 B/op	    772 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	      1	1001927791 ns/op	 101320 B/op	    691 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	      1	1002056459 ns/op	 101640 B/op	    693 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	      1	1002194500 ns/op	 107272 B/op	    712 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	      1	1001556875 ns/op	 101672 B/op	    694 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	      1	1001428875 ns/op	 101320 B/op	    691 allocs/op
```



# 4cf4dd2c6 string-based parser

## test
```
level=info msg="syslog listening on address" address=127.0.0.1:61624 protocol=tcp tls=false
level=info address=127.0.0.1:61624 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61626 protocol=tcp tls=false
level=info address=127.0.0.1:61626 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:54946 protocol=udp
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:54946: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:63490 protocol=udp
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:63490: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:55492 protocol=udp
level=warn msg="error parsing syslog stream" err="expecting a priority value within angle brackets [col 0]"
level=warn msg="error parsing syslog stream" err="expecting a priority value within angle brackets [col 0]"
level=warn msg="error parsing syslog stream" err="expecting a priority value within angle brackets [col 0]"
level=warn msg="error parsing syslog stream" err="expecting a priority value within angle brackets [col 0]"
level=warn msg="error parsing syslog stream" err="expecting a priority value within angle brackets [col 0]"
level=warn msg="error parsing syslog stream" err="expecting a priority value within angle brackets [col 0]"
level=warn msg="failed to read packets" addr=null err="read udp 127.0.0.1:55492: use of closed network connection"
level=info msg="syslog server shutting down" protocol=udp err="context canceled"
--- FAIL: TestSyslogTarget (4.11s)
    --- FAIL: TestSyslogTarget/udp_newline_separated (1.03s)
        syslogtarget_test.go:436: 
            	Error Trace:	/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/syslogtarget_test.go:436
            	Error:      	Not equal: 
            	           	expected: "An application event log entry..."
            	           	actual  : "An application event log entry...\n"
            	           	
            	           	Diff:
            	           	--- Expected
            	           	+++ Actual
            	           	@@ -1 +1,2 @@
            	           	An application event log entry...
            	           	+
            	Test:       	TestSyslogTarget/udp_newline_separated
    --- FAIL: TestSyslogTarget/udp_octetcounting (2.02s)
        syslogtarget_test.go:415: 
            	Error Trace:	/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/syslogtarget_test.go:415
            	Error:      	Condition never satisfied
            	Test:       	TestSyslogTarget/udp_octetcounting
            	Messages:   	Expected to receive 3 messages.
level=info msg="syslog listening on address" address=127.0.0.1:61628 protocol=tcp tls=false
level=info address=127.0.0.1:61628 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61630 protocol=tcp tls=false
level=info address=127.0.0.1:61630 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61634 protocol=tcp tls=true
level=warn msg="error parsing syslog stream" err="expecting a RFC3339MICRO timestamp or a nil value [col 7]"
level=warn msg="error parsing syslog stream" err="expecting a msgid (from 1 to max 32 US-ASCII characters) or a nil value [col 42]"
level=info address=127.0.0.1:61634 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61636 protocol=tcp tls=true
level=warn msg="error parsing syslog stream" err="expecting a RFC3339MICRO timestamp or a nil value [col 7]"
level=warn msg="error parsing syslog stream" err="expecting a msgid (from 1 to max 32 US-ASCII characters) or a nil value [col 42]"
level=info address=127.0.0.1:61636 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61638 protocol=tcp tls=true
level=warn msg="error initializing syslog stream" err="tls: client didn't provide a certificate"
level=info address=127.0.0.1:61638 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61641 protocol=tcp tls=true
level=warn msg="error initializing syslog stream" err="tls: client didn't provide a certificate"
level=info address=127.0.0.1:61641 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61644 protocol=tcp tls=false
level=warn msg="error initializing syslog stream" err="invalid or unsupported framing. first byte: 'x'"
level=info address=127.0.0.1:61644 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61646 protocol=tcp tls=false
level=info address=127.0.0.1:61646 msg="syslog server shutting down" protocol=tcp err="context canceled"
level=info msg="syslog listening on address" address=127.0.0.1:61648 protocol=tcp tls=false
level=warn msg="error initializing syslog stream" err="read tcp 127.0.0.1:61648->127.0.0.1:61649: i/o timeout"
level=info address=127.0.0.1:61648 msg="syslog server shutting down" protocol=tcp err="context canceled"
FAIL
exit status 1
FAIL	github.com/grafana/loki/clients/pkg/promtail/targets/syslog	4.759s
```

## bench
```
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1001689084 ns/op	  46784 B/op	    437 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1002926833 ns/op	  46272 B/op	    431 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1002085250 ns/op	  46800 B/op	    432 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1001580541 ns/op	  46904 B/op	    435 allocs/op
Benchmark_SyslogTarget/tcp_octetcounting-10         	      1	1002315875 ns/op	  47248 B/op	    437 allocs/op
--- FAIL: Benchmark_SyslogTarget/udp_octetcounting
    syslogtarget_test.go:352: 
        	Error Trace:	/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/syslogtarget_test.go:352
        	           				/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/benchmark.go:193
        	           				/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/benchmark.go:233
        	           				/Users/me/shelf/loki/clients/pkg/promtail/targets/syslog/asm_arm64.s:1172
        	Error:      	Condition never satisfied
        	Test:       	Benchmark_SyslogTarget/udp_octetcounting
        	Messages:   	expected: 10 got:0
Benchmark_SyslogTarget/udp_raw-10                   	      1	1001855250 ns/op	  42120 B/op	    495 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	      1	1002238750 ns/op	  38824 B/op	    484 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	      1	1001991292 ns/op	  38728 B/op	    483 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	      1	1001494708 ns/op	  38824 B/op	    482 allocs/op
Benchmark_SyslogTarget/udp_raw-10                   	      1	1001735458 ns/op	  42344 B/op	    491 allocs/op
```

**Comment by unawarez** [comment]
I don't think I'll be able to keep digging, but as one more experiment with the benchtime > 1 UDP benchmarks failing, I added a 1ms sleep after this line https://github.com/grafana/loki/blob/1f0a3c291d3e7498982a06e7f542697008af7d53/clients/pkg/promtail/targets/syslog/syslogtarget_test.go#L348 and then the benchmark passed. That makes me think the failure is from some UDP packets actually getting dropped when too many are sent at once...

**Comment by unawarez** [comment]
I learned more about some golang APIs and looked at syslogtarget_test again, and I'd actually like to propose another commit that tightens up the benchmark implementation. AFAICT it only had a 1s measurement resolution because it's relying on require.Eventually to block with a 1s tick. I'd like to write another fake Client impl that directly exposes a sync primitive for the caller to block on. I should have an example of that here pretty soon.

**Comment by MasslessParticle** [comment]
This looks good so far. CI is failing because you've got a test failure and a linting error.

**Comment by jeschkies** [comment]
@unawarez would you like us to take over?

**Comment by unawarez** [comment]
@MasslessParticle @jeschkies yes, see <https://github.com/grafana/loki/pull/7231#issuecomment-1345765029>

**Comment by jeschkies** [comment]
@unawarez World you grant me write access to your form so I can push to this branch? This would simplify things.

**Comment by jeschkies** [comment]
I've took a closer look and I'm not sure this approach is the correct one. Seems the original issue https://github.com/grafana/loki/issues/6772 has more details.

**Comment by MasslessParticle** [comment]
Based on the comments/activity for this one, I'm going to close it for now

**Pull request closed without merging**
