### PR TITLE
helm: add updateStategy for canary pods

### PR DESCRIPTION
**Pull request by Starefossen**
**What this PR does / why we need it**:
Allows configuring Canary DaemonSet rollout.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Review by JStickler — APPROVED** [review]
[docs team] LGTM

**Comment by MichelHollands** [comment]
@Starefossen Thanks for the contribution. A previous PR used the 5.8.3 version. Can you update this? Once that is done I'll merge it.

**Comment by Starefossen** [comment]
@MichelHollands done 🚀

**Comment by MichelHollands** [comment]
@Starefossen You still need to update production/helm/loki/README.md. There is a CI check for this.

**Comment by Starefossen** [comment]
Done ✅

**Comment by MichelHollands** [comment]
@Starefossen There is a problem with the indentation of the update strategy. It's at the wrong level. Please see the helm-ci CI step for the error.

**Pull request merged**
