### PR TITLE
[fix]  cassandra: reconnection when k8s cassandra pods restart

### LINKED ISSUE #1821: Auto reconnect or quickly exit when cassandra cluster down and then up.
**Is your feature request related to a problem? Please describe.**
Using cassandra cluster as storage.When the cassandra cluster down, this error occurs.And it will never recover though the cassandra is UP. 
And if we want to restart loki, loki will fall because of loop forever.
image

**Describe the solution you'd like**
As gocql wounld fix it (eg. [gocql-915](https://github.com/gocql/gocql/issues/915) created at 2017 and never closed.)
Would loki do something to reconect? Or do not retry to flush forever.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by liguozhong**
**What this PR does / why we need it**:

level=error ts=2022-07-20T04:07:11.881370946Z caller=flush.go:146 org_id=166256_8sxv2 msg="failed to flush user" err="store put chunk: gocql: no hosts available in the pool"

The restart of cassandra （on k8s） caused the production accident that loki had to restart. It happened 4 times in our production environment in only half a year. 

I hope this problem can be fixed. The code of this PR is not particularly complete, but this PR seems to be available. 

 If this PR does not merge, I also hope that other contributors in the loki community can propose another PR to fix this problem. 

The restart of cassandra that caused loki to be unavailable is already a conclusion recorded in our JIRA.

**Which issue(s) this PR fixes**:
Fixes #1821 #7140

**Special notes for your reviewer**:
test success in my online loki prod cluster.  it works.
image
log
image
log
image

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by CoreMoni** [comment]
We have the same problem in our company. This fix will be very helpful for us.

**Comment by Espe0n** [comment]
Would be nice to have this fix, currently using Cassandra as a storage is quite prone to failure due to this Issue 
( Please see https://github.com/grafana/loki/issues/7140 )

**Comment by liguozhong** [comment]
I know that cassandra index storage is likely to be deleted in loki 3.0, but we still need to run on cassandra at present.

I know this PR is not on the roadmap of loki. This is difficult. 

Although I have solved this problem in my own code branch, other loki users are still plagued. This is a very troublesome thing.

**Comment by liguozhong** [comment]
I agree to delete cassandra related code, and I will gradually migrate to tsdb-index mode after waiting for tsdb-index to stabilize.

**Review by MichelHollands — APPROVED** [review]
LGTM

**Pull request merged**
