### PR TITLE
[nix] Move logcli, promtail, and canary into own nix pkgs

### PR DESCRIPTION
**Pull request by trevorwhitney**
**What this PR does / why we need it**:
The main reason for this is when running logcli or promtail, I don't want to wait for loki to compile as well. For example, I have `logcli` aliased to `nix run github:grafana/loki#logcli -- `, and when compiling a new version, I don't want to have to wait for Loki, promtail, loki-canary, and logcli to all compile.

* This also refactors the folder structure under the nix folder to better organize packages and overlays.
* This also create new apps using the now top level packages.

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by trevorwhitney** [comment]
adding the backport label so people can start pinning their flakes for these packages to released version starting with at least 2.8.2

**Review by jdbaldry — COMMENTED** [review]
The Nix changes make sense to me but I don't tend to need these binaries during my docs focused development in this repository. 

When I try to build any package with `nix build`, like `nix build #logcli` I get the following integration test failure that is likely related to the sandbox. Is this expected?

```console
--- FAIL: TestCompactor_RunCompaction (0.01s)  
    compactor_test.go:53:   
        	Error Trace:	/build/y1qgi2jl0rl5r5snh68l0nfxdcw35q0k-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:53  
        	            				/build/y1qgi2jl0rl5r5snh68l0nfxdcw35q0k-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:94  
        	Error:      	Received unexpected error:  
        	            	no useable address found for interfaces [eth0 en0 lo]  
        	            	invalid ring lifecycler config  
        	            	github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.NewCompactor  
        	            		/build/y1qgi2jl0rl5r5snh68l0nfxdcw35q0k-source/pkg/storage/stores/indexshipper/compactor/compactor.go:217  
        	            	github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.setupTestCompactor  
        	            		/build/y1qgi2jl0rl5r5snh68l0nfxdcw35q0k-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:50  
        	            	github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.TestCompactor_RunCompaction  
        	            		/build/y1qgi2jl0rl5r5snh68l0nfxdcw35q0k-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:94  
        	            	testing.tRunner  
        	            		/nix/store/3wpbn0nv1yhb47njlb3z3vicj20cp2mj-go-1.20.2/share/go/src/testing/testing.go:1576  
        	            	runtime.goexit  
        	            		/nix/store/3wpbn0nv1yhb47njlb3z3vicj20cp2mj-go-1.20.2/share/go/src/runtime/asm_amd64.s:1598  
        	Test:       	TestCompactor_RunCompaction  
--- FAIL: TestCompactor_RunCompactionMultipleStores (0.02s)  
    compactor_test.go:53:   
        	Error Trace:	/build/y1qgi2jl0rl5r5snh68l0nfxdcw35q0k-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:53  
        	            				/build/y1qgi2jl0rl5r5snh68l0nfxdcw35q0k-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:165  
        	Error:      	Received unexpected error:  
        	            	no useable address found for interfaces [eth0 en0 lo]  
        	            	invalid ring lifecycler config  
        	            	github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.NewCompactor  
        	            		/build/y1qgi2jl0rl5r5snh68l0nfxdcw35q0k-source/pkg/storage/stores/indexshipper/compactor/compactor.go:217  
        	            	github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.setupTestCompactor  
        	            		/build/y1qgi2jl0rl5r5snh68l0nfxdcw35q0k-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:50  
        	            	github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.TestCompactor_RunCompactionMultipleStores  
        	            		/build/y1qgi2jl0rl5r5snh68l0nfxdcw35q0k-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:165  
        	            	testing.tRunner  
        	            		/nix/store/3wpbn0nv1yhb47njlb3z3vicj20cp2mj-go-1.20.2/share/go/src/testing/testing.go:1576  
        	            	runtime.goexit  
        	            		/nix/store/3wpbn0nv1yhb47njlb3z3vicj20cp2mj-go-1.20.2/share/go/src/runtime/asm_amd64.s:1598  
        	Test:       	TestCompactor_RunCompactionMultipleStores  
FAIL  
```

@trevorwhitney Would you like me to check any other specific things to ensure they are working as you intended?

**Comment by trevorwhitney** [comment]
Thanks @jdbaldry, pinging you more for your nix knowledge than your daily use of these tools, hope you don't mind :) and thanks for the review!

I know exactly why that error is occuring, going to see if I can recreate it. Thanks!

**Comment by jdbaldry** [comment]
Always happy to help :) 
It might not be a sandboxing issue but instead an interface naming problem. I haven't looked into the issue but the only interface I have in the set listed in the error is `lo`, the loopback interface. My other interfaces all use the consistent network interface device naming convention.

**Comment by trevorwhitney** [comment]
I don't think this flake is getting used enough to invest in this refactor, as there are packages in nixpkgs using the standard go package build methods. Please re-open if interested in helping out, but I'm closing this for now.

**Pull request closed without merging**
