### PR TITLE
Add support for or between pattern parsers

### PR DESCRIPTION
**Pull request by MichelHollands**
**What this PR does / why we need it**:

The `pattern` parsers can be combined with an `or` statement as in this example:

```
| pattern `=== FAIL <testname>` or pattern `PASS <testname>`
```

Only the captured fields of the first matching pattern are added as labels.

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [X] Documentation added
- [X] Tests updated
- [x] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by JStickler — APPROVED** [review]
[Docs squad} Documentation LGTM

**Review by jeschkies — CHANGES_REQUESTED** [review]
Thanks for the initiative but I'm working off this should have gone through a LID first. Eg I'd prefer `pattern "===FAIL..." or `===OK ...`.

Maybe some others prefer it to be inline. Furthermore, how many `or`s are we going to support.

**Comment by jeschkies** [comment]
I think I know where this is coming from. LogQL [allows](https://grafana.com/docs/loki/latest/logql/log_queries/) chaining filter expressions. Could we use those instead? Basically extract an `outcome` label compare it. Btw is there a different outcome than FAIL and PASS?

**Comment by MichelHollands** [comment]
Chaining them together will work.

**Pull request closed without merging**
