### PR TITLE
Readiness: Readiness probe for Distributor

### LINKED ISSUE #504: Add readiness handlers to distributor and querier modules
**Is your feature request related to a problem? Please describe.**
Currently only the ingester has a readiness handler (https://github.com/grafana/loki/blob/master/pkg/loki/modules.go#L148). If you deploy the three Loki components (distributor, ingester and querier) separately not all of them have a readiness handler to use as Kubernetes readiness/liveness probe paths. For the querier the path `/api/prom/label` could be used as readiness/liveness path. The readiness/liveness probes for the distributor had to be disabled though.

**Describe the solution you'd like**
Separate ready handlers for all three modules.

### PR DESCRIPTION
**Pull request by adityacs**
**What this PR does / why we need it**:

Adds Readiness probe for Distributor
**Which issue(s) this PR fixes**:
Fixes #504

### CODE REVIEW

**Comment by adityacs** [comment]
@cyriltovena Kindly requesting you to review this. If the logic is fine for you I can go ahead and add the same logic for querier.

**Comment by cyriltovena** [comment]
Hello @adityacs this is correct however when running as a single binary there will be the same route registered twice for different component.

Can you check if the route has already been registered and if yes wrap the old route with the new check ? When running distributed routes won't be already registered at all.

Does that makes sense ?

**Comment by adityacs** [comment]
@cyriltovena Makes sense. I will make the changes you mentioned.

**Comment by adityacs** [comment]
@cyriltovena 
> Can you check if the route has already been registered and if yes wrap the old route with the new check ? When running distributed routes won't be already registered at all.

Didn't exactly get what is "wrap the old route with the new check". Could you please elaborate? Also, when running as single binary, if ingestor is ready, we should be good since ring won't be empty and distributor should also be ready. We have to just make sure that `/ready` of ingestor is taken precedence when registering routes for all targets.

**Comment by adityacs** [comment]
@cyriltovena 
May be we can do this

```
if t.cfg.Target.String() == "distributor" {
	t.server.HTTP.Path("/ready").Handler(http.HandlerFunc(t.distributor.ReadinessHandler))
}
```

**Comment by cyriltovena** [comment]
@adityacs Yes that would do it.

However you can use this too.

```
if t.cfg.Target == Distributor { ...
```

**Comment by cyriltovena** [comment]
Actually I think it would still works if its registered twice. Let's take it as it is.

**Comment by cyriltovena** [comment]
For the record it is not called. The ingester take precedence.

**Pull request merged**
