### PR TITLE
Add persistent volume and move data to data

### PR DESCRIPTION
**Pull request by mikesplain**
Add persistent volume claim! I also changed the default location of data, open to any changes!

### CODE REVIEW

**Comment by mikesplain** [comment]
CLA is signed!

**Comment by tomwilkie** [comment]
Thanks @mikesplain!

Do we need to turn the deployment into a statefulset first though, so we get the right semantics around PVCs and upgrades?

**Comment by mikesplain** [comment]
@tomwilkie Not necessarily. Since this is a single instance deployment it wouldn't matter. If a user were to want multiple Loki's then yeah but currently that wouldn't be recommended, right?

That said Grafana or Promtheus both use deployments and PVCs in their [open source charts](https://github.com/helm/charts/tree/master/stable/grafana/templates) so I tend to sway that direction for now. We could offer both approaches but this is what I developed for my team internally.

Statefulsets are more useful when assignment is important, something like an etcd cluster where volume assignment to a specific instance (etcd1 vs etcd2 vs etcd3) needs to always stay the same.  That said, maybe that's what you intend with Loki, I just tried to expand on @jgsqware and everyones great work!

**Comment by huydinhle** [comment]
Also we are going to create volume, we might need to modify the psp we created as well to add volumes in there

**Comment by mikesplainsonos** [comment]
Great eye @huydinhle! Looks like I hadn't added the file to git, dohhh. And nice catch with the psp. Thanks!

**Comment by sboschman** [comment]
> @tomwilkie Not necessarily. Since this is a single instance deployment it wouldn't matter. If a user were to want multiple Loki's then yeah but currently that wouldn't be recommended, right?

This deployment in its current state is indeed single instance, @mikesplain . But it would be great to be able to deploy Loki in a scalable and high-available way with this chart. Looking at the [ksonnet config](https://github.com/grafana/loki/blob/f66d9e93d256998f6d4d79827f633ab61cde25f7/production/ksonnet/loki/config.libsonnet#L35), I think we are missing the option to configure consul as lifecycler with this chart. Once we can configure consul as lifecycler it starts to make sense to have a multi-instance loki setup.
 
> That said Grafana or Promtheus both use deployments and PVCs in their [open source charts](https://github.com/helm/charts/tree/master/stable/grafana/templates) so I tend to sway that direction for now. We could offer both approaches but this is what I developed for my team internally.

Prometheus does offer a statefulset (https://github.com/helm/charts/pull/7116) nowadays. Which allows you to scale the number of replicas to have a ha setup. As each pod will now have its own storage.

**Comment by tomwilkie** [comment]
@jgsqware LGTM is enough for me - hes the helm expert here.

**Pull request merged**
