### PR TITLE
Helm: Add podlabels to backend

### PR DESCRIPTION
**Pull request by jimgus**
**What this PR does / why we need it**:

This PR makes it possible configure ` podlabels` in Helm for `backend` in the same fashion as for all other components.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by jeschkies — APPROVED** [review]

**Comment by jeschkies** [comment]
Could you update the documentation?

**Comment by jimgus** [comment]
> 

I was actually trying what was suggested by the CI checks: `Please generate Helm Chart reference by running 'make -C docs sources/installation/helm/reference.md'` and `Please update generated documentation by running 'make doc' and committing the changes`. I did however not get any changes. Can you please point me to how to do it?

**Comment by jeschkies** [comment]
What happens when you call `make -C docs sources/installation/helm/reference.md`?

**Comment by jimgus** [comment]
> make -C docs sources/installation/helm/reference.md

````
loki on  backend_podlabels via 🐹 v1.19.5 
❯ make -C docs sources/installation/helm/reference.md
make: Entering directory '/home/jim/dev/3pp/loki/docs'
podman run --rm --volume "/home/jim/dev/3pp/loki:/helm-docs:z" -u "$(id -u)" "docker.io/jnorwood/helm-docs:v1.11.0" \
	-c /helm-docs/production/helm/ \
	-t reference.md.gotmpl \
	-o reference.md
time="2023-02-03T14:09:06Z" level=info msg="Found Chart directories [loki]"
time="2023-02-03T14:09:06Z" level=info msg="Generating README Documentation for chart /helm-docs/production/helm/loki"
time="2023-02-03T14:09:06Z" level=warning msg="Could not open chart README file /helm-docs/production/helm/loki/README.md, skipping chart"
mv "../production/helm/loki/reference.md" "sources/installation/helm/reference.md"
mv: cannot stat '../production/helm/loki/reference.md': No such file or directory
make: *** [Makefile:24: sources/installation/helm/reference.md] Error 1
make: Leaving directory '/home/jim/dev/3pp/loki/docs'
```

**Comment by jimgus** [comment]
> 

Looks like I have a Podman/docker issue. I will try to fix it .

**Review by JStickler — APPROVED** [review]
[Docs squad} LGTM

**Comment by jimgus** [comment]
Something remaining or is it possible to get this one merged?

**Review by JStickler — APPROVED** [review]
[Docs squad] LGTM

**Comment by jimgus** [comment]
@JStickler I'm not authorized to merge

**Comment by MasslessParticle** [comment]
Thanks for contributing!

**Pull request merged**
