### PR TITLE
feat: Update error handling when targeting symlink

### PR DESCRIPTION
**Pull request by chesha1**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
#2090  
#429

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

**What this Pr is about?**   
When promtail scans files in the directory, symbolic files will be reported as "failed to tail file, stat failed".  
So I add more information for users to identify where the errors come from.

### CODE REVIEW

**Review by dannykopping — COMMENTED** [review]
Thank you for your contribution @chesha1 👍 
Can you please add a test to validate?

**Comment by chesha1** [comment]
> Thank you for your contribution @chesha1 👍 Can you please add a test to validate?

Thanks for your comments, but I don't get you clearly.

Do you mean add a unit test in the `filetarget_test.go` or build an image to show the expected behaviours?

**Comment by chesha1** [comment]
Hi @dannykopping , I have just add test for `startTailing` in `TestFileTargetStartTailingHandlesFilesAndSymlinks` as your request. Could you please take a moment to review my PR when you have a chance?

**Comment by littlepangdi** [comment]
Sorry but i've notice this PR will make promtail not able to tail symlink files anymore. Maybe we should be prudent about this `os.Lstat()` replacement. 
Previously this method was first quoted here, but replaced with `os.Stat()` later https://github.com/grafana/loki/commit/f6d0857ddf1e058a85946e77f80df346c353b614#diff-f3a0cd60bdb26d0913106519efed527be125a04b5ae468c320da592defe52162R33-R48

**Comment by littlepangdi** [comment]
`"failed to tail file, stat failed"`
This error will only be reported when the pointer to the symbol file does not exist or Promtail scraping config doesn't suit environment. It should be noticed by user.

**Comment by chesha1** [comment]
> `"failed to tail file, stat failed"` This error will only be reported when the pointer to the symbol file does not exist or Promtail scraping config doesn't suit environment. It should be noticed by user.

I am sorry I didn't get your clearly. What does 'the pointer to the symbol file does not exist' mean?

When promtail scans the path scrape_config provided and finds a symbolic link, what is the expected behaviour? From the symbolic link to get the real log file even though it is not in the path scrape_config provided, or treating the symlink as a empty file, or throw an error?

**Comment by littlepangdi** [comment]
Consider this scene: symbolic link  is given in the scrape_config path, we should  get the real log file and start to tail.

**Comment by littlepangdi** [comment]
> Sorry but i've notice this PR is similar to first version of `tailer`. Maybe we should be prudent about `os.Lstat()` replacement. Previously the method was first quoted here, but replaced with `os.Stat()` later. [f6d0857#diff-f3a0cd60bdb26d0913106519efed527be125a04b5ae468c320da592defe52162R33-R48](https://github.com/grafana/loki/commit/f6d0857ddf1e058a85946e77f80df346c353b614#diff-f3a0cd60bdb26d0913106519efed527be125a04b5ae468c320da592defe52162R33-R48)

Sorry I made a mistake here about this PR will stop promtail from tailing symbolic link. I've changed the description of my concern.

**Comment by chesha1** [comment]
> > Sorry but i've notice this PR is similar to first version of `tailer`. Maybe we should be prudent about `os.Lstat()` replacement. Previously the method was first quoted here, but replaced with `os.Stat()` later. [f6d0857#diff-f3a0cd60bdb26d0913106519efed527be125a04b5ae468c320da592defe52162R33-R48](https://github.com/grafana/loki/commit/f6d0857ddf1e058a85946e77f80df346c353b614#diff-f3a0cd60bdb26d0913106519efed527be125a04b5ae468c320da592defe52162R33-R48)
> 
> Sorry I made a mistake here about this PR will stop promtail from tailing symbolic link. I've changed the description of my concern.

So when promtail finds a symbolic link, it will stop the first tail, reopen and get the real file which symbolic link points to.

And `failed to tail file, stat failed` is not caused by symbolic link.

Is the above two understandings correct?

**Pull request closed without merging**
