### PR TITLE
fix(helm/loki): Add namespace to Loki templates for ruler and index-gateway

### PR DESCRIPTION
**Pull request by site0801**
**What this PR does / why we need it**:

When installing Loki in Distributed mode using the Helm chart, the ruler and index-gateway were missing a namespace.
I would like them to refer to .Release.Namespace, like the other templates, even if the namespace is not specified in the Helm CLI. 
However, if someone has intentionally omitted this description for some reason, I apologize.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by trevorwhitney — APPROVED** [review]
looks good, thanks!

**Comment by site0801** [comment]
@trevorwhitney 
Thanks for approve!
I followed the Branch of this PR to upstream as it was failing in git with the lint-check of this PR's test.
If there is anything else I could do, please let me know!

**Comment by site0801** [comment]
Sorry for the repeated CI failures.
I'm looking at a few other PRs, but is it possible that the recommended way to create a PR for loki's helm is to create a Branch directly in grafana/loki, rather than folk and create a PR?

**Comment by site0801** [comment]
I found the cause of the failure in `.github/workflows/helm-ci.yml`.
It seems to be failing because it is probably unable to reference the commit sha in my `site0801/loki`.
So, I changed it to reference `${{ github.event.pull_request.head.sha }}` in https://github.com/grafana/loki/pull/15011.

**Comment by site0801** [comment]
I would like to run lint again because @trevorwhitney fixed it at https://github.com/grafana/loki/pull/15001.
The above PR is no longer needed, so it has been closed.

**Pull request merged**
