### PR TITLE
Helm: Add extraContainers to write pods

### PR DESCRIPTION
**Pull request by someStrangerFromTheAbyss**
**Adds the extraContainers to the write pod**:

**Which issue(s) this PR fixes**:
This fix will allow my team to add a pods that makes modification to the incoming logs before sending them to loki with minimal network transfer.

**Special notes for your reviewer**:
NONE

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] `CHANGELOG.md` updated
  - [x] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [x] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by JStickler** [comment]
Could you also please update the version in the  and `production/helm/loki/README.md`?

**Comment by someStrangerFromTheAbyss** [comment]
> Could you also please update the version in the and `production/helm/loki/README.md`?

Update the version in the README and in the link in the README

**Comment by MichelHollands** [comment]
@someStrangerFromTheAbyss Thanks for the contribution. Can you update the version to 5.40 as 5.39 is already taken?

**Comment by someStrangerFromTheAbyss** [comment]
@MichelHollands 

Bumped to 5.40

**Comment by MichelHollands** [comment]
@someStrangerFromTheAbyss The CI is failing. As mentioned in the error message "Please generate Helm Chart reference by running 'make -C docs sources/setup/install/helm/reference.md'". You might have to remove the file if no changes are generated at first. Once that is done I'll merge this.

**Review by MichelHollands — APPROVED** [review]
LGTM

**Pull request merged**
