### PR TITLE
Revert "Hide duplicates caused by stream sharding (#7005)"

### PR DESCRIPTION
**Pull request by MasslessParticle**
@owen-d had a suggestion that was dramatically dimpler. Revert this whole thing and the simplified PR will be forthcoming

### CODE REVIEW

**Review by DylanGuedes — APPROVED** [review]
lgtm

**Comment by liguozhong** [comment]
@MasslessParticle 
hi, is the simplified PR completed? Is there a url address?

**Comment by MasslessParticle** [comment]
@liguozhong It turns out duplicates were unavoidable in either approach. Instead we're taking the following approach to stream sharding:

- Create an API on ingesters that reports stream rates ([pr])(https://github.com/grafana/loki/pull/7176))
- Distributors poll ingesters on an interval to understand stream rates (PR not ready)
- Distributors make a best effort to shard streams based on those rates ([pr](https://github.com/grafana/loki/pull/7199))

**Comment by liguozhong** [comment]
thanks 👍

**Pull request merged**
