### PR TITLE
Request to change the loki-overview-2 image

### PR DESCRIPTION
**Pull request by jasuade**
**What this PR does / why we need it**:
We in support are doing some review of public documents in general, the Overview is okay but the image seemed quite outdated, I was wondering if it would be nice to have it updated to this or something else ( not sure if it is the correct format).

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by jasuade** [comment]
Hey, thank you for the feedback!

Let me know also about the quality and if there any other requirement we need to be compliant with to include image in the docs. Is the first time that I do modifications to the public docs and I do not want to mess anything around :sweat_smile:

**Comment by jasuade** [comment]
Hello @JStickler thank you for the replay! and sorry for the late reply.
I took a look at the developer's toolkit and I resize the image accordingly [to match the requirements](https://grafana.com/docs/writers-toolkit/writing-guide/image-guidelines/#image-and-diagram-standards). Let me know if anything else is missing.

**Review by JStickler — APPROVED** [review]
[docs team] LGTM

**Comment by JStickler** [comment]
@jasuade, you'll need to resolve the conflicts before this can be merged.  [This PR](https://github.com/grafana/loki/pull/9717) made changes to the Getting Started section that need to be resolved in your PR to pass the CI checks.

**Comment by jasuade** [comment]
@JStickler got it! I moved the image to the correct path, let me know if anything else.

**Comment by JStickler** [comment]
@jasuade I think the only thing left is that you need to sign off on the Contributor License Agreement and we can merge this.

**Pull request merged**
