### PR TITLE
Promtail: Add 'country' to geoip pipeline-stage

### PR DESCRIPTION
**Pull request by superstes**
**What this PR does / why we need it**:

Maxmind provides multiple GeoIP2 databases.
The three most used ones are City, Country and ASN as they are also available as [free GeoLiteIP2 databases](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data).

Some users might want/need to use the 'Country' database - so I added support for it.
A reason: If the user only has the 'Country' database licensed.

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
    Skipped because it's a `simple enhancement`

### CODE REVIEW

**Comment by cstyan** [comment]
Hello @superstes , thanks for your PR.

We're currently reevaluating promtails position as a project within Grafana Labs. Internally we're actually using the [Agent](https://github.com/grafana/agent) for both metrics and logs collection at this point. Additionally, the agent team is more likely to have time to dedicate to your PR.

While we haven't made a formal decision yet, we expect in the near future that all new feature work will be done in the Agent's log collection pipelines rather than in Promtail.

**Comment by superstes** [comment]
@cstyan Thanks for information.
Is there any public discussion regarding this promtail/agent topic?
I would be interested in it as I'm currently implenting a `Syslog => Promtail => Loki <= Grafana` solution in one of my projects.

**Comment by cstyan** [comment]
@superstes public discussion in what sense?

I'll also point out that the agent has a hard fork of promtail code, so you can likely make a very similar improvement there: https://github.com/grafana/agent/blob/b7f7c57a9420af409508eb3acc5618371b3f8107/component/loki/process/stages/geoip.go

**Comment by superstes** [comment]
@cstyan 'Discussion' might've been the wrong word.
I meant: 'Where could one ask questions regarding the comparison/overlap of grafana-agent and promtail?'

Per example: I would guess grafana-agent does not (yet) implement all functionality of promtail, or does it?

**Comment by JStickler** [comment]
There should be feature parity because the Agent team took a fork of Promtail back in March 2023 and incorporated it into Grafana Agent.  We’re just starting the process of trying to point requests for new features to [grafana/agent](https://github.com/grafana/agent). 
https://grafana.com/docs/agent/latest/flow/getting-started/migrating-from-promtail/

**Comment by superstes** [comment]
@JStickler Thank you for the information.
Then I'll take the time and migrate to the agent and create a PR at the [grafana/agent](https://github.com/grafana/agent) repository.

**Comment by cstyan** [comment]
closing since it looks like your agent pr was merged, thanks for your time @superstes we appreciate it :)

**Pull request closed without merging**
