### PR TITLE
Fix/validate compactor config

### PR DESCRIPTION
**Pull request by owen-d**
Closes https://github.com/grafana/loki/issues/2815

Tested with defined & non-defined compactor configs when:
- target=all
- target=ruler (non-compactor)
- target=compactor

### CODE REVIEW

**Review by sandeepsukhani — COMMENTED** [review]
I was wondering if we should return a wrapped error at https://github.com/grafana/loki/pull/2824/files#diff-578848847155a57366a0b3f50e1457ff1d2aea470a8a662663aea51cb4b30ec1L49

Or add a validate function for config which checks for expected values instead of using reflect. It would be cleaner I feel.

**Comment by owen-d** [comment]
I chose reflect because it's extensible (if we add a field with new defaults, etc, this code will still work. We already have a validate function for configs (I actually spent some time trying to make that work), but we unfortunately diverge from it in a few places at runtime both for validations and for module hierarchy, see

https://github.com/grafana/loki/blob/master/pkg/loki/modules.go#L419-L436
https://github.com/grafana/loki/blob/master/pkg/loki/loki.go#L361-L365

I'd definitely prefer the config validation scenario, but I wasn't able to find a clean way to refactor that. Suggestions _very_ welcome.

As for the wrapped error, can you reformat the link? All I see is an entire commit.

**Comment by sandeepsukhani** [comment]
> I chose reflect because it's extensible (if we add a field with new defaults, etc, this code will still work). We already have a validate function for configs (I actually spent some time trying to make that work), but we unfortunately diverge from it in a few places at runtime both for validations and for module hierarchy, see
> 
> https://github.com/grafana/loki/blob/master/pkg/loki/modules.go#L419-L436
> https://github.com/grafana/loki/blob/master/pkg/loki/loki.go#L361-L365
> 
> I'd definitely prefer the config validation scenario, but I wasn't able to find a clean way to refactor that. Suggestions _very_ welcome.
> 
We could do the validation in either the factory method i.e `NewCompactor` or where it is being called i.e in `initCompactor` function in modules. 

> As for the wrapped error, can you reformat the link? All I see is an entire commit.
Sorry, my bad. This is where I meant returning a wrapped error https://github.com/grafana/loki/blob/d8fe7fa8577937c5a81974f163870034c131540a/pkg/storage/stores/shipper/compactor/compactor.go#L56

I am open to suggestions too and please feel free to correct me if I am wrong here.

**Comment by owen-d** [comment]
Good idea moving it into the `New` function @sandeepsukhani -- I've added that.

**Review by sandeepsukhani — APPROVED** [review]
LGTM! Thanks for taking care of the requested changes.

**Pull request merged**
