### PR TITLE
fix duplicate metrics "cortex_distributor_ingester_clients"

### PR DESCRIPTION
**Pull request by liguozhong**
fix duplicate metrics "cortex_distributor_ingester_clients"
fix：https://github.com/grafana/loki/issues/5129

### CODE REVIEW

**Review by kavirajk — APPROVED** [review]
LGTM. thanks @liguozhong

**Comment by DylanGuedes** [comment]
Hey I also overlooked this at other places :facepalm: do you mind also fixing it in `queryrange/queryrangebase` and `ruler/base`?

**Comment by liguozhong** [comment]
> Hey I also overlooked this at other places 🤦 do you mind also fixing it in `queryrange/queryrangebase` and `ruler/base`?

👌

**Comment by liguozhong** [comment]
new case, grpc conflict 

panic: proto: duplicate enum registered: frontend.Type

goroutine 1 [running]:
github.com/gogo/protobuf/proto.RegisterEnum(...)
	/Users/fuling/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/properties.go:520
github.com/grafana/loki/pkg/lokifrontend/frontend/v1/frontendv1pb.init.0()
	/Users/fuling/go/pkg/mod/github.com/liguozhong/loki@v1.6.2-0.20220113084522-58e430f6c2a1/pkg/lokifrontend/frontend/v1/frontendv1pb/frontend.pb.go:258 +0x1e7
image

**Comment by liguozhong** [comment]
done. @DylanGuedes 
image

**Comment by cyriltovena** [comment]
Yep let's not change metric name for now.

**Pull request closed without merging**
