### PR TITLE
batchRetries to countersWithHost

### LINKED ISSUE #7261: Metric `promtail_batch_retries_total` is absent when has value == 0
**Describe the bug**

Metric `promtail_batch_retries_total` is absent when has value == 0

**To Reproduce**

1. Run Loki then Promtail
```bash
docker compose up -d loki
docker compose up -d promtail
```
2. Collect Promtail metrics: `curl 127.0.0.1:9080/metrics 2>/dev/null | grep promtail_batch_retries_total` - you should see no `promtail_batch_retries_total` metric
3. Stop Loki `docker compose stop loki`
4. Collect Promtail metrics: `curl 127.0.0.1:9080/metrics 2>/dev/null | grep promtail_batch_retries_total` - you should see `promtail_batch_retries_total` metric with value > 0

**Expected behavior**

`curl 127.0.0.1:9080/metrics 2>/dev/null | grep promtail_batch_retries_total` - should return `promtail_batch_retries_total` metric regardless of it value

**Environment:**

 docker-compose.yml:
 ```yaml
version: "3.5"

services:
  loki:
    image: grafana/loki:2.6.1

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail.yml:/etc/promtail-config/promtail.yml
    command: "-config.file=/etc/promtail-config/promtail.yml"
    ports:
      - "127.0.0.1:9080:9080"
```

promtail.yml:
```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
    - targets:
        - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
    - json:
        expressions:
          output: log
          stream: stream
          attrs:
    - output:
        source: output
```

### PR DESCRIPTION
**Pull request by gelo22**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #7261

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by dannykopping — COMMENTED** [review]
Hi, please fill in the PR template.
What is the purpose the PR?

**Comment by liguozhong** [comment]
What this PR does / why we need it:

hi ,There is no content here

**Comment by MichelHollands** [comment]
@gelo22 Thanks for this fix. Can you sign the Contributor License Agreement? Without it we can't accept outside contributions.

**Comment by gelo22** [comment]
> @gelo22 Thanks for this fix. Can you sign the Contributor License Agreement? Without it we can't accept outside contributions.
Signed

**Review by MichelHollands — APPROVED** [review]

**Pull request merged**
