### PR TITLE
Helm: add cilium networkpolicies

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
**What this PR does / why we need it**:

This PR adds `ciliumnetworkpolicies` that are equivalent to the standard `networkpolicies` already present in the templates. As `cilium` usage as a CNI is rising and the usage of `ciliumnetworkpolicies` is more and more widespread, having the possibility to deploy those directly from a setting in the values would be a time-saving option for a lot of deployments.

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [x] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by MichelHollands** [comment]
@QuantumEnigmaa Another release came in earlier. Can you use version 5.41.2? Once the other PR is in I'll merge this one.

**Comment by QuantumEnigmaa** [comment]
> Can you use version 5.41.2

Done @MichelHollands

**Comment by MichelHollands** [comment]
@QuantumEnigmaa Sorry, 2 more things. Can rebase or merge main into your branch. Also please run the command `make -C docs sources/setup/install/helm/reference.md` as mentioned in the failing CI step. This will update the reference.md file.

**Comment by QuantumEnigmaa** [comment]
Its done @MichelHollands :)

**Review by MichelHollands — APPROVED** [review]

**Pull request merged**
