### PR TITLE
production/helm: add standard k8s label for name

### PR DESCRIPTION
**Pull request by 7AC**
This adds `app.kubernetes.io/name` to all kubernetes objects following https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/.

### CODE REVIEW

**Comment by owen-d** [comment]
Make sure you sign the CLA and we'll be able to accept this.

**Comment by 7AC** [comment]
I signed it twice already but looks like the PR doesn't get updated with it

**Comment by owen-d** [comment]
Ugh, CI problems 😢 . Any chance you can fix the conflicts with the current promtail helm chart? I'm guessing it's just the version field needs re-incrementing. That might also kickstart the license/cla check!

**Comment by 7AC** [comment]
I solved the conflict but it's still complaining about the CLA

**Comment by owen-d** [comment]
Thanks. I'll see what I can do about this.

**Comment by owen-d** [comment]
Apparently this always happens when the email on the git commit doesn't match the email on the github account. Usually you can amend the commit with an email on your github account. Can you check this -- and apologies for the bad user experience :(

**Comment by 7AC** [comment]
@owen-d I have 2 emails associated with my GitHub account, I'm using the one from my employer for this as it's for work

**Pull request closed without merging**
