### PR TITLE
[WIP] TOC Sync: Move configuration files under Configure.

### LINKED ISSUE #8713: [Docs] Create top-level Configure section
Move the following files under Configure:
./sources/configuration/_index.md
./sources/configuration/examples.md
./sources/configuration/query-frontend.md

### PR DESCRIPTION
**Pull request by JStickler**
**Which issue(s) this PR fixes**:
Fixes #8713 

**Special notes for your reviewer**:
Part of the Database products table of contents alignment project.
Moves configuration files from Configuration to new Configure heading in TOC.
Updates front matter for the topic.
Fixes links broken by the move.

### CODE REVIEW

**Review by MasslessParticle — APPROVED** [review]

**Comment by MasslessParticle** [comment]
@JStickler lgtm. You'll also need to point the makefile at the new location for the build to pass: https://github.com/grafana/loki/blob/55045add9373f7b566bb3ac431d0cba74360bb0b/Makefile#L782

**Comment by MasslessParticle** [comment]
@JStickler Is this still in progress?

**Comment by JStickler** [comment]
@MasslessParticle At this point it's so old that I think I need to close it and start over.  I was going to work on it next week.  Leave it open for now, and I'll either manage to get it updated or close it when I open a fresh PR.

**Comment by JStickler** [comment]
Closing, replaced by #9879

**Pull request closed without merging**
