### PR TITLE
Docs: Add doc-validator tool to lint technical documentation

### PR DESCRIPTION
**Pull request by jdbaldry**
Source code:
https://github.com/grafana/technical-documentation/tree/main/tools/doc-validator

Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

**What this PR does / why we need it**:

Adds a CI step for pull requests that validates links in technical documentation and performs linting of technical documentation source files.

**Special notes for your reviewer**:

- Lots of issues will need to be fixed before we can merge this.
- The tool is still in early development so each error should be scrutinized for validity.

**Checklist**
- [ ] Documentation added
- [na] Tests updated
- [na] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [na] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by GrafanaWriter** [comment]
@slim-bean @kristiandeppe @minhdanh - can we get some help with merging this.

**Comment by jeschkies** [comment]
This is a long list of errors. @jdbaldry do you think we could run the linter only on new or changed files?

**Review by jeschkies — APPROVED** [review]

**Comment by jdbaldry** [comment]
Converting to draft because I need to make a few more changes to the doc-validator CI image to better support GitHub actions and facilitate this workflow more easily. Will revisit this tomorrow.

**Comment by jdbaldry** [comment]
Yes! :tada:

**Review by kavirajk — APPROVED** [review]
:ok_hand: LGTM.

**Comment by kavirajk** [comment]
@jdbaldry can you rebase your branch?. CI is failing to arm docker images. Should be unrelated to your changes.

**Comment by jdbaldry** [comment]
I can't merge this PR because I'm not a maintainer but if you'd like to merge it, keep an eye on it for for future PRs and ping me if you see odd behavior :) You're the first repository to test out the "only run on changed files" version of the workflow so there might be some kinks.

**Comment by jdbaldry** [comment]
Just rebased and squashed all the test commits while I was there.

**Comment by osg-grafana** [comment]
FYI, @JStickler

**Pull request merged**
