### PR TITLE
fixed helm template fails with default values yaml

### LINKED ISSUE #10410: helm template fails with default values yaml
**Describe the bug**
helm template for Loki helm chart with values.yaml from (current) main branch fails.

root cause seems to be this commit https://github.com/grafana/loki/commit/04685ea5123956f7b0936e88552a9947156b510a
that contains a change with
```
{{ include "loki.rulerConfig" . }}
```
to
```
{{ include "loki.rulerConfig". }}
```

**To Reproduce**
executing command
```
helm template grafana/loki --version 5.15.0 -f values.yaml
```
when the `values.yaml` contains content of file https://github.com/grafana/loki/blob/bcf917f65ad70568467d4af02c385607c7032ac9/production/helm/loki/values.yaml

will result in 
```
Error: template: loki/templates/write/statefulset-write.yaml:43:28:
...
parse error at (loki/templates/write/statefulset-write.yaml:81): unexpected <.> in operand
```

**Expected behavior**
Succesful helm tempalte

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #10410 

**Special notes for your reviewer**:

Hey as per my understanding the issue "helm template fails with default values yaml #10410" appeared due to the absence of  space in this line "{ include "loki.rulerConfig". }}", It should be fine now.  

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Review by aschaber1 — APPROVED** [review]
Fixes problem I had.

**Comment by Sheikh-Abubaker** [comment]
Glad to hear that.

When will this PR be merged ?

**Comment by aschaber1** [comment]
I did hit the approve button, but that didn't do much, as it needs to be approved by the Loki team. Hope this gets merged too.

**Comment by MichelHollands** [comment]
@Sheikh-Abubaker Thanks for this contribution. By chance this was also fixed earlier in https://github.com/grafana/loki/pull/10479/files. So this PR becomes a empty change. I'll close it therefore.

**Pull request closed without merging**
