### PR TITLE
[promtail helm chart] Enable support for syslog service

### PR DESCRIPTION
**Pull request by billimek**
**What this PR does / why we need it**:

This should allow the chart to be configured for an optional syslog service

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by billimek** [comment]
Hi @rfratto, is there anything I can do with this PR to help it move along?

**Comment by billimek** [comment]
Thanks @rfratto.  As I understand it, the configuration of syslog would be handled in the [extraScrapeConfigs](https://github.com/grafana/loki/blob/master/production/helm/promtail/values.yaml#L72) section of the promtail helm chart configuration, e.g.

```yaml
      extraScrapeConfigs:
      - job_name: syslog
        syslog:
          listen_address: 0.0.0.0:1514
          labels:
            job: "syslog"
        relabel_configs:
        - source_labels: ['__syslog_message_hostname']
          target_label: 'host'
```

What's missing is having the promtail helm chart actually expose a syslog endpoint via a service.

We could consider enhancing this pull request to encompass the entire syslog configuration.  What do you think @joe-elliott?

**Comment by cyriltovena** [comment]
Looks good @billimek can you improve the documentation of the helm chart on how to use the syslog in promtail ? With the snippet above ? here https://github.com/grafana/loki/tree/master/production/helm

Thanks !

**Comment by billimek** [comment]
> Looks good @billimek can you improve the documentation of the helm chart on how to use the syslog in promtail ? With the snippet above ? here https://github.com/grafana/loki/tree/master/production/helm

Thanks @cyriltovena  - this should be present now.  Can you please take a look?

**Pull request merged**
