### PR TITLE
helm: improve gitops compatibility

### PR DESCRIPTION
**Pull request by LinAnt**
**What this PR does / why we need it**:

In its current form, this helm chart is annoying to deploy using GitOps tools like fluxcd/argocd. This is due to missing fields that get added automatically once the objects are applied in the cluster.

A workaround is to just add exceptions for these fields in the gitops tool, but I think this is a more robust solution.

Screenshot from ArgoCD app diff:
image

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Review by k2589 — APPROVED** [review]

**Comment by MichelHollands** [comment]
@LinAnt For Helm chart changes please bump the Helm chart version in production/helm/loki/Chart.yaml and update production/helm/loki/CHANGELOG.md and production/helm/loki/README.md. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

**Comment by LinAnt** [comment]
> @LinAnt For Helm chart changes please bump the Helm chart version in production/helm/loki/Chart.yaml and update production/helm/loki/CHANGELOG.md and production/helm/loki/README.md. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

I think I got all of them changes in there now :+1:

**Comment by LinAnt** [comment]
Bumped version again :+1:

**Comment by LinAnt** [comment]
Bumped version again :+1:

**Pull request merged**
