### PR TITLE
Added Architecture Diagram

### PR DESCRIPTION
**Pull request by wardbekker**
**What this PR does / why we need it**:

Added Loki Architecture Diagram

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [X] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Review by owen-d — APPROVED** [review]
LGTM, thanks!

@sandeepsukhani can you confirm we don't use the index cache from the ingesters anymore with boltdb-shipper?

**Review by sandeepsukhani — COMMENTED** [review]
The diagram looks really good. Just a couple of feedbacks:
1. What does `Q` mean in the `Ruler` and `Querier` block?
2. I think we should point `Compactor` to the index store with both `Read` and `Write` arrows.
3. We support `Redis` as well for caching so maybe we should add that as well.

**Comment by owen-d** [comment]
The `Q` means the ruler embeds a querier as a subcomponent.

**Comment by sandeepsukhani** [comment]
> The `Q` means the ruler embeds a querier as a subcomponent.

Ahh. Sorry, it was confusing to me. What do you folks think about removing it? I think it is more of an implementation detail but I do not strongly oppose keeping it.

@wardbekker The `Q` on the `Ruler` component looks a little out of alignment too. Can you please take care of it too if we decide to keep it?

**Comment by owen-d** [comment]
I think this is a good starter - we can improve in the future, but I dont' want to hold this up.

**Pull request merged**
