### PR TITLE
[Helm] Add the ability to add extraObjects

### PR DESCRIPTION
**Pull request by xinbinhuang**
**What this PR does / why we need it**:

 Add the ability to create extraObjects in helm chart. This'll allow users to inject a configmap of loki rules or secrets for object storages. Also, the `extraObjects` is also a common fields for helm charts (i.e. https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L1148)

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/loki/issues/7629

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by vlad-diachenko** [comment]
Hey @xinbinhuang . thanks a lot for the contribution. 
 
Also, could you please bump the version of the chart running the following steps:
1. bump chart version https://github.com/quentinplessis/loki/blob/feature/helm-add-container-lifecycle/production/helm/loki/Chart.yaml#L7 to `3.8.1`
2. run this command to re-generate the docs `docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.8.1`
3. add a section above 3.8.0 (https://github.com/grafana/loki/blob/main/production/helm/loki/CHANGELOG.md#380) for 3.8.1 version and add changes description.

Sorry that we do not have it documented anywhere, we are working on this. let me know if you need any help.

**Comment by xinbinhuang** [comment]
> Hey @xinbinhuang . thanks a lot for the contribution.
> 
> Also, could you please bump the version of the chart running the following steps:
> 
> 1. bump chart version https://github.com/quentinplessis/loki/blob/feature/helm-add-container-lifecycle/production/helm/loki/Chart.yaml#L7 to `3.8.1`
> 2. run this command to re-generate the docs `docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.8.1`
> 3. add a section above 3.8.0 (https://github.com/grafana/loki/blob/main/production/helm/loki/CHANGELOG.md#380) for 3.8.1 version and add changes description.
> 
> Sorry that we do not have it documented anywhere, we are working on this. let me know if you need any help.

@vlad-diachenko  Thanks for the info! I've updated the doc. However, it's still failing one of the test. I'm not sure how to interpret the failure from logs. Would you give me some pointers?

**Comment by vlad-diachenko** [comment]
Hey @xinbinhuang . sorry for delay, I was on vacation ) taking care of your PR to get it merged ;)

**Review by vlad-diachenko — APPROVED** [review]
looks great ;) huge thanks for the contribution @xinbinhuang .

**Pull request merged**
