### PR TITLE
LogQL: Extract syntax to its own logql/syntax package.

### LINKED ISSUE #1854: Create a syntax package for LogQL
Looking at what's coming, I think we should in the future extract the syntax code from the LogQL package and move it to a logql/syntax package so it can be reused by other without having to embed the whole engine. There is a lot places where we need to just parse logql.

This will means also export each supported expression.

/cc @owen-d

### PR DESCRIPTION
**Pull request by bastjan**
**What this PR does / why we need it**:

Adds a `logql/syntax` package to manipulate and  build logQL queries.

I’ve recently tried to implement a permission gateway to allow (temporary) label based permissions.

Inspired by #1854 I extracted the parser and the types as closely as possible and made them public to test how my two use-cases, inserting labels into queries and building queries, would look like.

See [TestLabelInserter](https://github.com/grafana/loki/compare/master...bastjan:logql-syntax-package#diff-e77c17a7ca32d518e5a78ff13167686d350f2f94d9e51e6a6c7ea9e420ab7e5bR22) and [TestBuildQuery](https://github.com/grafana/loki/compare/master...bastjan:logql-syntax-package#diff-e77c17a7ca32d518e5a78ff13167686d350f2f94d9e51e6a6c7ea9e420ab7e5bR70).

It is not yet finished and most of the code was more or less just copy-pasted but I have some time to finish it up.

I tried reusing just the `expr.y` and moving the lexer to a separate package, but these seem to be quite intertwined. I think the easiest way to deduplicate the code is the logql packaga just wrapping the `logql/syntax` package.

Feedback appreciated!

**Which issue(s) this PR fixes**:
Fixes #1854

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by cyriltovena** [comment]
In my opinions I think expr.y should belong to syntax package ? By the way, `syntax` or `parser` ? naming is fun :)

**Comment by dannykopping** [comment]
I prefer the "parser" terminology.

I'm not a huge fan of the duplication - if this is going to be done I'd prefer we `git mv` the existing implementation into its new location (so as to retain the valuable git history) and implement the feature based on that.

**Comment by amvaidya** [comment]
@bastjan - Is this PR still being worked on? We are interested in using this.

**Comment by bastjan** [comment]
@amvaidya yes I still plan on finishing this. but currently no ETA had to shift priorities a bit.

**Pull request closed without merging**
