### PR TITLE
renames skip -> ok in ProcessString

### PR DESCRIPTION
**Pull request by owen-d**
This confuses me every now and then, so I fixed the method var name and the last 2 references that used it as the name `skip`. Looking at how it's _used_, it should be named `ok` or `keep` or `passes`.

### CODE REVIEW

**Comment by slim-bean** [comment]
What about 'matched' instead of 'ok' ?

**Comment by cyriltovena** [comment]
I hear you but not sure ok does a better job no ? The point is that the line is filtered out.

**Comment by owen-d** [comment]
I was being lazy trying to avoid replacing all the other references which already use `ok` 😆 . Pushed an update to fix them 👍

**Review by cyriltovena — APPROVED** [review]
LGTM

**Pull request merged**
