### PR TITLE
GCS: Add service_account option

### PR DESCRIPTION
**Pull request by lxwzy**
**What this PR does / why we need it**:
Add `service_account` option to configure GCS directly using service account key.
This will change the situation which have to use JSON file and `GOOGLE_APPLICATION_CREDENTIALS` env for service account (such as [#932](https://github.com/grafana/loki/issues/932#issuecomment-839846952) and #6125).

**Checklist**
- [x] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by periklis — COMMENTED** [review]
Looks good to me

**Review by KMiller-Grafana — APPROVED** [review]
Docs for this configuration look good to me.

**Review by kavirajk — APPROVED** [review]
LGTM. thanks @lxwzy

**Comment by NoviceEric** [comment]
LGTM

**Pull request merged**
