### PR TITLE
fix: Update out_grafana_loki.go to handle unknown timestamp format

### PR DESCRIPTION
**Pull request by CalebHock**
**What this PR does / why we need it**:

When using the Fluent Bit plugin to send logs from Fluent Bit to Loki, the time format used is unrecognized, resulting in a warning being logged. Fluent bit will scrape this warning and then send out a new log to the plugin in Loki with the same unrecognizable time format, resulting in an infinite loop.

This is caused by the time data being sent as a slice of interfaces. There was some [development done on Fluent Bit](https://github.com/fluent/fluent-bit-go/pull/68/files) to handle this new format, that this PR will mimic.

This fix now handles situations where the timestamp is received as a slice of interfaces, ensuring the proper handling of this data. 

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
This PR is a duplicate of [this PR](https://github.com/grafana/loki/pull/11407), but the creator of the old one has not followed up on responses. I am unable to update Fluent Bit past 2.0.9, which is end of life and has many critical vulnerabilities that I cannot take patches for.

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by cstyan** [comment]
> When using the Fluent Bit plugin to send logs from Fluent Bit to Loki, the time format used is unrecognized, resulting in a warning being logged. Fluent bit will scrape this warning and then send out a new log to the plugin in Loki with the same unrecognizable time format, resulting in an infinite loop.
> 
> This is caused by the time data being sent as a slice of interfaces. There was some [development done on Fluent Bit](https://github.com/fluent/fluent-bit-go/pull/68/files) to handle this new format, that this PR will mimic.
> 
> This fix now handles situations where the timestamp is received as a slice of interfaces, ensuring the proper handling of this data.

Thanks for the detailed description. It's still unclear to me why the timestamp can be returned as a slice in the first place.

**Comment by leo198706** [comment]
I also encountered the same problem, using fluent-bit 2.2.3 to collect logs and send them to loki, "timestamp isn't known format. Use current time."

After looking through the documentation of fluent-bit, I found that the fluent-bit event format has changed, and I think this is the reason. Reference documentation: https://docs.fluentbit.io/manual/v/dev-2.2/concepts/key-concepts#event-format

current event format: [[TIMESTAMP, METADATA], MESSAGE]
Fluent Bit versions prior to v2.1.0 instead used: [TIMESTAMP, MESSAGE]
https://docs.fluentbit.io/manual/v/dev-2.2/concepts/key-concepts#event-format

Adjusting the output of GetRecord is a better approach:
https://github.com/grafana/loki/blob/f6529c293e3281ba1c19ff36d6018c0ef338f3e6/clients/cmd/fluent-bit/out_grafana_loki.go#L122

I see that the corresponding code has been adjusted
https://github.com/fluent/fluent-bit-go/commit/149565b4a060bc37699018a5ac2d5634adbb8a89

And loki has also been upgraded
https://github.com/grafana/loki/commit/a02d686dd18265f583985d3fe399f3f943f66323

This PR is unnecessary. You can solve the above problem by upgrading loki 3.0.0 and recompiling the plug-in.

**Comment by 18nygara** [comment]
@leo198706, When using Loki v3.0.0 and Fluent Bit v3.0.6 (latest at the time of writing this) or v2.2.3, we still run into
`level=warn caller=out_grafana_loki.go:135 id=0 msg="timestamp isn't known format. Use current time."` errors before Fluent Bit crashes.
 
We're deploying on AKS and using this dockerfile to build the plugin:
```dockerfile
FROM <artifactoryURL>/golang:1.22.3-bullseye as build
ENV LOKI_VERSION="3.0.0"
WORKDIR /src
RUN apt-get update && apt-get install -y --no-install-recommends gcc make \
&& wget -q "[https://github.com/grafana/loki/archive/refs/tags/v${LOKI_VERSION}.tar.gz"](https://github.com/grafana/loki/archive/refs/tags/v$%7BLOKI_VERSION%7D.tar.gz%22) \
&& tar xzf "v${LOKI_VERSION}.tar.gz" \
&& ln -s "loki-${LOKI_VERSION}" loki \
&& cd loki \
&& make fluent-bit-plugin
 
FROM <artifactoryURL>/fluent/fluent-bit:3.0.6
COPY --from=build /src/loki/clients/cmd/fluent-bit/out_grafana_loki.so /fluent-bit/bin/out_grafana_loki.so
CMD ["/fluent-bit/bin/fluent-bit", "-e","/fluent-bit/bin/out_grafana_loki.so", "-c", "/fluent-bit/etc/fluent-bit.conf"]
```

**Comment by leo198706** [comment]
> @leo198706, When using Loki v3.0.0 and Fluent Bit v3.0.6 (latest at the time of writing this) or v2.2.3, we still run into `level=warn caller=out_grafana_loki.go:135 id=0 msg="timestamp isn't known format. Use current time."` errors before Fluent Bit crashes.
> 
> We're deploying on AKS and using this dockerfile to build the plugin:
> 
> ```dockerfile
> FROM <artifactoryURL>/golang:1.22.3-bullseye as build
> ENV LOKI_VERSION="3.0.0"
> WORKDIR /src
> RUN apt-get update && apt-get install -y --no-install-recommends gcc make \
> && wget -q "[https://github.com/grafana/loki/archive/refs/tags/v${LOKI_VERSION}.tar.gz"](https://github.com/grafana/loki/archive/refs/tags/v$%7BLOKI_VERSION%7D.tar.gz%22) \
> && tar xzf "v${LOKI_VERSION}.tar.gz" \
> && ln -s "loki-${LOKI_VERSION}" loki \
> && cd loki \
> && make fluent-bit-plugin
>  
> FROM <artifactoryURL>/fluent/fluent-bit:3.0.6
> COPY --from=build /src/loki/clients/cmd/fluent-bit/out_grafana_loki.so /fluent-bit/bin/out_grafana_loki.so
> CMD ["/fluent-bit/bin/fluent-bit", "-e","/fluent-bit/bin/out_grafana_loki.so", "-c", "/fluent-bit/etc/fluent-bit.conf"]
> ```

Looks like nothing's wrong. I packaged the plugin with the following dockerfile and it works fine on **aws eks**, for reference only

```
FROM golang:1.22.2-bullseye as plugin-builder

ENV LOKI_VERSION=3.0.0
ENV GIT_HASH=b4f7181

ARG LOKI_TARBALL=https://github.com/grafana/loki/archive/v$LOKI_VERSION.tar.gz

ENV LOKI_SOURCE $LOKI_TARBALL

RUN curl -L -o "loki.tar.gz" ${LOKI_SOURCE} \
    && mkdir -p /src/loki \
    && tar zxfv loki.tar.gz -C  /src/loki --strip-components=1 \
    && cd /src/loki

WORKDIR /src/loki

RUN make BUILD_IN_CONTAINER=false GIT_REVISION=$GIT_HASH GIT_BRANCH=v$LOKI_VERSION IMAGE_TAG=$LOKI_VERSION fluent-bit-plugin

FROM fluent/fluent-bit:2.2.3

COPY --from=plugin-builder /src/loki/clients/cmd/fluent-bit/out_grafana_loki.so /fluent-bit/bin

EXPOSE 2020

CMD ["/fluent-bit/bin/fluent-bit", "-e","/fluent-bit/bin/out_grafana_loki.so", "-c", "/fluent-bit/etc/fluent-bit.conf"]
```

**Pull request closed without merging**
