### PR TITLE
fix app label miss

### PR DESCRIPTION
**Pull request by daixiang0**
Fix `app` label can not be scraped.

igned-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
```
        - source_labels:
          - __meta_kubernetes_pod_label_app
          target_label: __service__
```
`__meta_kubernetes_pod_label_app` turn to `__service__` and `__service__` drop, so `__meta_kubernetes_pod_label_app` drop.

**Comment by daixiang0** [comment]
@tomwilkie hi, mind have a look? The change that app label missing is from #154.

**Comment by davkal** [comment]
> __meta_kubernetes_pod_label_app turn to __service__ and __service__ drop,
so __meta_kubernetes_pod_label_app drop.

Streams are only dropped if `__service__` is empty (`regex: ^$`). It looks like `__meta_kubernetes_pod_label_app` is empty to begin with. May that be the issue?

**Comment by daixiang0** [comment]
@davkal It is what i am confused. While regex match empty line and drop it, remove this rule works.

**Comment by davkal** [comment]
I still can't reproduce this issue. Here is what I'm doing:
1. Fresh kubernetes on docker for mac.
2. `helm init`
3. Go to loki helm dir and run `helm install . -n loki --namespace default`

After a couple of minutes all pods are ready, and I can see both loki and promtail itself being scraped, even though promtail only has a an app label:
```
Name:           loki-promtail-srtp6
Namespace:      default
Node:           docker-for-desktop/192.168.65.3
Start Time:     Tue, 02 Apr 2019 10:57:59 +0200
Labels:         app=promtail
                controller-revision-hash=2774997145
                pod-template-generation=1
                release=loki
Annotations:    <none>
```

And here is the output of logcli (I've got a local portforward from 33100 to 3100 on the docker host):
```
./logcli --addr="http://localhost:33100/" labels app
http://localhost:33100//api/prom/label/app/values
loki
promtail
```

I've used c4bddc7.

**Comment by daixiang0** [comment]
There are too many failure in promtail which scrape loki log in my env:
```
level=warn ts=2019-04-02T11:05:18.844813838Z caller=client.go:181 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.103.86.243:3100: connect: no route to host"
level=warn ts=2019-04-02T11:05:22.812271233Z caller=client.go:181 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.103.86.243:3100: connect: no route to host"
level=warn ts=2019-04-02T11:05:25.707481909Z caller=client.go:181 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.103.86.243:3100: connect: no route to host"
```
I guess it scrape but not send since reach max try times, so i change `promtail.config.client.backoff_config.maxretries` to `0`, now i can get `loki` label.

**Comment by daixiang0** [comment]
Seems that remove this rule make scrape slow, then it can send to loki within maxtries, while it is still confused since less rules should be faster i think.

**Comment by daixiang0** [comment]
So need to change the default `promtail.config.client.backoff_config.maxretries` as `0`?

**Comment by davkal** [comment]
I still don't see how removing the `__service__` rule will solve your issue, hence I recommend closing this PR.

Regarding the connection issues, they are expected at the beginning of the pod lifecycle, since Loki usually takes longer to start up than promtail. 

To make sure all logs are sent since promtail started, I recomment setting the retry count to cover Loki's start up time which is roughly 60 secs. So you could to a min/max delay of 1sec and 10sec, and then to cover the startup time relatively certain use 90 sec / 5 sec = 18 retries. Notice that the more retries you allow, the faster you get results but also the more error output you have when loki is not up yet.

**Comment by daixiang0** [comment]
> I still don't see how removing the `__service__` rule will solve your issue, hence I recommend closing this PR.

Seem this [comment](https://github.com/grafana/loki/pull/432#issuecomment-478953006), after remove rule, the time of scrape become large.

> I recomment setting the retry count to cover Loki's start up time which is roughly 60 secs. So you could to a min/max delay of 1sec and 10sec, and then to cover the startup time relatively certain use 90 sec / 5 sec = 18 retries.

need to change the default helm config?

**Comment by davkal** [comment]
I'm lost on what the issue is.

If you are missing pods with a certain app label, we need to configure the relabling rules differently (but not by removing the `___service__` mechanism).
We're using `__service__` as field to filter for, allowing empty values for this makes no sense. If anything, new `keep` or `relabel` rules that write `__service__` need to be added.

I'm closing this PR. If anyone still can't scrape certain pods, please open a new issue with reproducible steps.

**Comment by davkal** [comment]
Which k8s version are you running?
This comment might be useful https://github.com/grafana/loki/issues/393#issuecomment-481139862

**Pull request closed without merging**
