### PR TITLE
use fifocache.duration instead of fifocache.interval in warn deprecated

### PR DESCRIPTION
**Pull request by lxwzy**
**What this PR does / why we need it**:
I configured fifo cache with `validity` option (which is [deprecated](https://github.com/grafana/loki/blob/b92f113cb0961b628b643f4f3f9fddc1c18ed921/docs/sources/configuration/_index.md?plain=1#L2004) in v2.6.0, `fifocache.duration` as an flag) and loki print that:

```
level=warn ts=2022-07-08T17:01:30.134251284Z caller=fifo_cache.go:125 msg="running with DEPRECATED flag fifocache.interval, use fifocache.ttl instead" cache=frontend.fifocache
```

However, there is no flag `fifocache.interval`.
As #5148 changed, the deprecated flag should be `fifocache.duration`, not `fifocache.interval`.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by MichelHollands — APPROVED** [review]
LGTM

**Comment by MichelHollands** [comment]
@lxwzy Can you rebase this change? It's complaining in the CI about some generated protobuf file. Thanks

**Comment by lxwzy** [comment]
> @lxwzy Can you rebase this change? It's complaining in the CI about some generated protobuf file. Thanks

Very sorry, I think there are something wrong with the rebase. Can you give me some advice?

**Comment by MichelHollands** [comment]
@lxwzy It might be easier to create a new PR now instead of trying to clean this up, especially as it's a small change.

**Comment by lxwzy** [comment]
> @lxwzy It might be easier to create a new PR now instead of trying to clean this up, especially as it's a small change.

Thank you for your advice. I will create a new PR.

**Pull request closed without merging**
