### PR TITLE
Update Prometheus dependency to latest release (v2.40.4)

### LINKED ISSUE #7811: Update Prometheus dependency to v2.40
Grafana Agent would like to update to Prometheus v2.40 to support native histograms (grafana/agent#2492), but Loki needs to be updated first.

I already spent some time working on this but got blocked by weaveworks/common#262. I'm opening this issue just to track, but I'll open a PR on my own once I'm able to.

### PR DESCRIPTION
**Pull request by rfratto**
Closes #7811, which is needed for Grafana Agent to update to v2.40 and add support for native histograms.

I did not add support for native histograms to Loki, sorry :)

### CODE REVIEW

**Comment by rfratto** [comment]
Hm, this is failing on the protobufs:

```
github.com/weaveworks/common/httpgrpc/httpgrpc.proto: Import "gogoproto/gogo.proto" was not found or had errors.
pkg/lokifrontend/frontend/v1/frontendv1pb/frontend.proto: Import "github.com/weaveworks/common/httpgrpc/httpgrpc.proto" was not found or had errors.
pkg/lokifrontend/frontend/v1/frontendv1pb/frontend.proto:30:3: "httpgrpc.HTTPRequest" is not defined.
pkg/lokifrontend/frontend/v1/frontendv1pb/frontend.proto:39:3: "httpgrpc.HTTPResponse" is not defined.
``` 

I'm not sure what I should do here; I think it might be related to @krajorama's resent changes to weaveworks/common but I can't tell.

**Comment by krajorama** [comment]
> Hm, this is failing on the protobufs:
> 
> ```
> github.com/weaveworks/common/httpgrpc/httpgrpc.proto: Import "gogoproto/gogo.proto" was not found or had errors.
> pkg/lokifrontend/frontend/v1/frontendv1pb/frontend.proto: Import "github.com/weaveworks/common/httpgrpc/httpgrpc.proto" was not found or had errors.
> pkg/lokifrontend/frontend/v1/frontendv1pb/frontend.proto:30:3: "httpgrpc.HTTPRequest" is not defined.
> pkg/lokifrontend/frontend/v1/frontendv1pb/frontend.proto:39:3: "httpgrpc.HTTPResponse" is not defined.
> ```
> 
> I'm not sure what I should do here; I think it might be related to @krajorama's resent changes to weaveworks/common but I can't tell.

Yes, we've fixed non-reproducable build in https://github.com/weaveworks/common/pull/264 and https://github.com/weaveworks/common/pull/265 . See comment here on knock on effect: https://github.com/weaveworks/common/pull/262#issuecomment-1331759655

**Comment by rfratto** [comment]
@krajorama Thanks! Looks like there was two set of issues:

1. I needed to add the `-I` directive for `gogoproto/gogo.proto` as you mentioned 
2. I needed to update Loki protos to import `gogoproto/gogo.proto` instead of the full path, otherwise it caused a collision from protoc and failed to compile.

**Review by slim-bean — APPROVED** [review]
thanks for putting in all the effort to make this change @rfratto !

**Pull request merged**
