### PR TITLE
fix(helm): fix extraObjects

### PR DESCRIPTION
**Pull request by hervenicol**
**What this PR does / why we need it**:

Fixes a regression introduced with https://github.com/grafana/loki/pull/12397

When we had multiple extraObjects the rendering was missing linefeed before the separation triple-dashes (`---`).
Like here:
```
apiVersion: testResource/v1alpha1
kind: testResource
metadata:
  name: test1
spec: void---
apiVersion: testResource/v1alpha1
kind: testResource
metadata:
  name: test2
spec: void---
apiVersion: testResource/v1alpha1
kind: testResource
metadata:
  name: test3
spec: void
---
```

With the fix it looks like this:
```
apiVersion: testResource/v1alpha1
kind: testResource
metadata:
  name: test1
spec: void
---
# Source: loki/templates/extra-manifests.yaml
apiVersion: testResource/v1alpha1
kind: testResource
metadata:
  name: test2
spec: void
---
# Source: loki/templates/extra-manifests.yaml
apiVersion: testResource/v1alpha1
kind: testResource
metadata:
  name: test3
spec: void
---

```

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
@MichelHollands could you please take a look at this patch?

**Comment by hervenicol** [comment]
Maybe @TheRealNoob would be interested in having a look at it as well.

**Comment by QuentinBisson** [comment]
@MichelHollands @jeschkies is there a way to help merging this PR? The change is really small and it fixes a real issue

**Review by jeschkies — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Thank you :)

**Comment by TheRealNoob** [comment]
@hervenicol sorry I missed this notification.  Apologies for not catching this!  Thank you for fixing it

**Comment by QuentinBisson** [comment]
@TheRealNoob I think we forgot to bump the chart version in this PR

**Pull request merged**
