### PR TITLE
fix(loki): allow global and per tenant sigv4 config

### LINKED ISSUE #6293: [loki] Configuration for sigv4 authentication in the ruler being ignored
**Describe the bug**
Currently, the sigv4 authentication configuration in the Ruler is being overwritten, and ignored, when the per tenant overrides are merged in (see https://github.com/grafana/loki/blob/v2.5.0/pkg/ruler/registry.go#L232). As a result, there is no way to configure sigv4 authentication for remote writes. Remote writes fail with the error:

```
err="server returned HTTP status 403 Forbidden: {\"message\":\"Missing Authentication Token\"}"
```

**To Reproduce**
1. Started Loki v2.5.0
2. Configured Ruler to use sigv4 authentication for the remote write URL
3. Create a recording rule

**Expected behavior**
Expected the sigv4 authentication configuration to be passed into the client configuration.

**Environment:**
 - Infrastructure: k8s
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

### PR DESCRIPTION
**Pull request by taharah**
Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>

**What this PR does / why we need it**:
Fixes an issue that prevented the sigv4 authentication configuration from being set during the resolution of the per tenant overrides. This fixes the issue by allowing the global value to be properly propagated as well as enables setting the sigv4 authentication on a per tenant basis. 

**Which issue(s) this PR fixes**:
Fixes #6293

**Special notes for your reviewer**:
N/A

**Checklist**
- [x] Documentation added
- [x] Tests updated
- [x] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by dannykopping — APPROVED** [review]
Thanks for the great contribution @taharah!
Let's wait for @KMiller-Grafana to approve the docs & merge

**Review by KMiller-Grafana — APPROVED** [review]
Docs in this PR look good to me.

**Review by kavirajk — APPROVED** [review]
Thanks @taharah :tada:

**Comment by taharah** [comment]
Just wanted to add: We deployed this into our internal environment and were able to use remote write with sigv4 authentication now 🎉

**Pull request merged**
