### PR TITLE
Upgrade to dskit without log.Interface and logrus

### PR DESCRIPTION
**Pull request by duricanikolic**
**What this PR does / why we need it**:
This PR upgrades `dskit` and uses `dskit`'s `log` package for the creation of the global logger.
For the main in the `dskit` see https://github.com/grafana/dskit/pull/359.

Additionally, it improves `log.InitLogger` function, accordingly to the `dskit` change.

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Comment by chaudum** [comment]
@duricanikolic  I think this was superseded by #10300, right?

**Comment by duricanikolic** [comment]
> @duricanikolic I think this was superseded by #10300, right?
@chaudum I think that #10300 removes some additional things that are not needed anymore, but this is relevant only from the syntactical point of view and I can take care of it once I am back from PTO.
My biggest concern though is another one: I think that switching to `dslog.NewGoKitLogWithWriter` implies that we need to skip 5 stack frames when printing logs, otherwise we might get a wrong caller information. Could you please double-check that? This is what I had to change in `pyroscope`.

**Comment by chaudum** [comment]
> @chaudum I think that #10300 removes some additional things that are not needed anymore, but this is relevant only from the syntactical point of view and I can take care of it once I am back from PTO.

Got you!

> My biggest concern though is another one: I think that switching to `dslog.NewGoKitLogWithWriter` implies that we need to skip 5 stack frames when printing logs, otherwise we might get a wrong caller information. Could you please double-check that? This is what I had to change in `pyroscope`.

I tested your branch and it seems that skipping 3 stack frames is still correct.

**Comment by chaudum** [comment]
Superseded by https://github.com/grafana/loki/pull/10434

**Comment by duricanikolic** [comment]
This PR is not needed anymore, since PRs https://github.com/grafana/loki/pull/10300 and https://github.com/grafana/loki/pull/10434 have been merged instead.

**Pull request closed without merging**
