### PR TITLE
Helm: Allow emptyDir data volumes for backend and write

### LINKED ISSUE #9131: grafana/loki helm chart installation pending on pvc storage even though S3 is configured?
Hi,

I am trying to deploy the grafana loki helmchart (version 5.0.0) on our EKS cluster, and I noticed the read and write pods are stuck in the "pending" state.

After doing some research I figured out that the pods are stuck in the pending state because they are reliant on persistent storage. Since we have no persistent storage configured in our EKS cluster (And we are not intending to do so) the pvc's for these mentioned pods are also stuck in the pending state:

```
NAME                STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-loki-read-0    Pending                                      gp2            10s
data-loki-read-1    Pending                                      gp2            10s
data-loki-read-2    Pending                                      gp2            10s
data-loki-write-0   Pending                                      gp2            10s
data-loki-write-1   Pending                                      gp2            10s
data-loki-write-2   Pending                                      gp2            10s
```

This is the values.yaml I used to deploy the chart:

```
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: **MASKED**
 
loki:
  storage:
    bucketNames:
      chunks: **MASKED**/chunks
      ruler: **MASKED**/ruler
      admin: **MASKED**/admin
    type: s3
    s3:
      endpoint: https://s3.eu-central-1.amazonaws.com/
      region: eu-central-1
 
  schema_config:
    configs:
      - from: 2023-04-13
        store: boltdb-shipper
        object_store: aws
        schema: v12
        index:
          prefix: index_
          period: 24h
```

I was under the impression that when S3 is configured as a storage backend there is no need to use persistent storage within the cluster. Did I misconfigure something? Is there a bug in the helm chart? Or.... is this expected behavior?

If the latter is the case it is actually a bit confusing since the loki-distributed helm chart (which is no longer recommended according to a Grafana Loki Configuration webinar I just watched) has no need for persistent storage within kubernetes. And the same goes for the lok-stack helm chart.

### PR DESCRIPTION
**Pull request by matschaffer-roblox**
**What this PR does / why we need it**:

This enables deployment of write and backend modules using emptyDir in place of a PersistentVolume for the data volume.  

This is useful for Kuberenetes clusters (for example, on-prem) that are unable to easily provide persistent volumes. 

This is intended for use with something like s3 storage where (per [comment](https://github.com/grafana/loki/blob/45b127cfd62d8dedd46b189081d4259e6416ca24/production/helm/loki/templates/backend/statefulset-backend.yaml#L30-L33) on `persistentVolumeClaimRetentionPolicy`)

> Data on the (write or backend) nodes is easy to replace ... and will rely on re-fetching data when needed.

**Which issue(s) this PR fixes**: 

Fixes #9131

**Special notes for your reviewer**:

If there are other modules this should be applied to, please let me know.

I'm just getting started with Loki this month and have added  only the modules which come with the default chart (gateway, read, write, backend) and make persistent volume claims (write, backend).

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- ~Tests updated~
  - no tests for modified helm modules found
- ~`CHANGELOG.md` updated~
  - not used for helm changes
  - ~If the change is worth mentioning in the release notes, add `add-to-release-notes` label~
    - unlikely to be noteworthy
- ~Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`~
  - not related to loki upgrade
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Comment by JStickler** [comment]
[docs team]  Since you're adding a new parameter, you should document it in the Helm reference (../production/helm/loki/reference.md.gotmpl ).

**Comment by matschaffer-roblox** [comment]
Thanks @JStickler - pretty sure the latest commit is what I needed to do. Let me know if there's anything else!

**Comment by MichelHollands** [comment]
@matschaffer-roblox Thanks for this contribution. Can you use version 5.17? Another PR got it just before you. Also, can you sign the CLA? Without this we can't accept contributions. Thanks in advance

**Comment by matschaffer-roblox** [comment]
Thanks @MichelHollands ! I'm still holding on approval here. It might take a couple more days so I'll update my version number once the CLA is clear.

**Comment by matschaffer-roblox** [comment]
@YannickTeKulve not yet. Making some progress but still no CLA signature on this end.

**Comment by JStickler** [comment]
@matschaffer-roblox You are the one who needs to sign the Contributor License Agreement before this PR can be merged  Right-click the Details to get to the CLA page to sign it.
CLA

**Comment by matschaffer-roblox** [comment]
@JStickler sorry if I was unclear. I mean I'm waiting on my employer's legal team.

**Comment by JStickler** [comment]
@matschaffer-roblox ah, that makes sense.  It might be worth asking your legal team about creating a policy for open source contributions, if they don't already have one.

**Comment by matschaffer-roblox** [comment]
CLA is signed and PR is updated. Thanks very much for your patience folks! And extra thanks to @JStickler for the additional help 🧡 

If there's anything else you'd like before merge, please let me know.

**Comment by MichelHollands** [comment]
@matschaffer-roblox Thanks for the contribution. Can you use version 5.26? A few other PRs were merged so the number has gone up.

**Comment by matschaffer-roblox** [comment]
@MichelHollands done! And re-merged main.

Thanks for the previous main merge. Feel free to bump the version on my behalf as well if you need to.

**Comment by matschaffer-roblox** [comment]
@rlaisqls has closed https://github.com/grafana/loki/pull/10617 in favor of this PR, I merged master, and checks are all green.

@MichelHollands if you're able to merge, please do. If there's anything outstanding please let me know and I'll address it as quickly as possible.

Thanks everyone for the continued support 🧡

**Review by MichelHollands — APPROVED** [review]

**Comment by matschaffer-roblox** [comment]
This is working great @MichelHollands - thanks so much for the merge and release! 🧡

**Pull request merged**
