### PR TITLE
feat(mixins): merge resources dashboards for ssd into one

### PR DESCRIPTION
**Pull request by QuentinBisson**
**What this PR does / why we need it**:

Single Scalable deployment mixins were not showing the full resource usage as the backend pods were ignored.

This PR merges the existing read-resources and write resources dashboard into 1 for SSD and adds the backend resources. The idea was already communicated in with @cstyan in this PR https://github.com/grafana/loki/pull/13023

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by QuentinBisson** [comment]
@cstyan or @MichelHollands I would love some inputs if you have the time of course

**Comment by cstyan** [comment]
@QuentinBisson am I understanding correctly, this should supersede your other PR https://github.com/grafana/loki/pull/13023 ?

**Comment by QuentinBisson** [comment]
Yes and no 😅 because thé other PR also include the addition of a backend path in the Loki opérational dashboard so I will rename it later on :)

**Comment by cstyan** [comment]
@QuentinBisson need to merge in again after some of the other PRs have been merged

**Comment by QuentinBisson** [comment]
Should be good @cstyan :)

**Review by cstyan — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Hey @cstyan I regened the mixins on my hand but I have some weird layout on this one
image

I think I need to play with `gridpos` but I'm not sure how to do it so if you have some insight that would be awesome :)

**Pull request merged**
