### PR TITLE
helm chart: fix role/PSP mapping

### LINKED ISSUE #8652: Helm: wrong role config, breaking podsecuritypolicy
**Describe the bug**

When enabling PSPs, the generated `role` does not reference the right name for the `podsecuritypolicy`.

**To Reproduce**

* Tested on `helm-loki-4.7.0` tag.
* We will generate the chart with an easy-to-spot name, let's use mine :stuck_out_tongue_winking_eye: 
* We will enable PSPs.

* Let's look at the generated `role`:
```
$ helm template herve . --set "rbac.pspEnabled=true" -s templates/role.yaml
---
# Source: loki/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki
  namespace: default
  labels:
    helm.sh/chart: loki-4.7.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: herve
    app.kubernetes.io/version: "2.7.3"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - herve-loki
```

* Then look at the generated PSP:
```
$ helm template herve . --set "rbac.pspEnabled=true" -s templates/podsecuritypolicy.yaml 
---
# Source: loki/templates/podsecuritypolicy.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: loki
  labels:
    helm.sh/chart: loki-4.7.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: herve
    app.kubernetes.io/version: "2.7.3"
    app.kubernetes.io/managed-by: Helm
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'persistentVolumeClaim'
    - 'secret'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: true
  requiredDropCapabilities:
    - ALL
```

=>  The role sets `.rules.resourceNames` to `herve-loki`.
=> The PSP is named `loki`.
=> They don't match, so the PSPs are not applied as expected.

**Expected behavior**

The role should use the right PSP.
* either the role references the `loki` PSP.
* or the PSPs are named according to the chart's name, `herve-loki` - but for homogeneity that should be the case for all generated resources then.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: helm 3.8.0
 - Helm charts from https://github.com/grafana/loki/tree/main/production/helm/loki, tag `helm-loki-4.7.0`

### PR DESCRIPTION
**Pull request by hervenicol**
**What this PR does / why we need it**:

Fixes role/PSP and role/SCC mapping in Helm chart.

**Which issue(s) this PR fixes**:
Fixes #8652

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [x] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by hervenicol** [comment]
Re-based to latest master (`helm-loki-4.8.0`).

**Comment by hervenicol** [comment]
rebased to latest main branch.

**Comment by hervenicol** [comment]
CI failing because of flakiness as far as I can tell :cry:

**Review by trevorwhitney — APPROVED** [review]
Sorry this took so long to get a review, thanks for the fix!

**Comment by hervenicol** [comment]
Thanks! Rebased to latest main so it could be merged.

**Pull request merged**
