### PR TITLE
Support promtail reload config

### LINKED ISSUE #16: Add config reload endoint / signal to promtail
So we don't have to restart all the pods just to change the scrape config etc.

### PR DESCRIPTION
**Pull request by daixiang0**
Based on [comment](https://github.com/grafana/loki/pull/482#pullrequestreview-233827278)
Fix #16 

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
since load config rather than register flag, and some default values can not be set, need to wait upstream fix(https://github.com/weaveworks/common/pull/155, https://github.com/weaveworks/common/pull/157)

**Comment by daixiang0** [comment]
@Kuqd[ lint error](https://circleci.com/gh/grafana/loki/5420?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) seems a bug in golang-lint, i test with latest version at local, no lint about this.
```
[root@long promtail]# GOGC=20 golangci-lint run   
[root@long promtail]# golangci-lint --version
golangci-lint has version 1.16.0 built from 97ea1cb on 2019-03-31T19:48:46Z
[root@long promtail]# pwd
/go/src/github.com/grafana/loki/pkg/promtail
```

**Comment by daixiang0** [comment]
@gouthamve mind have a look?

**Comment by daixiang0** [comment]
@gouthamve mind have a look?

**Comment by daixiang0** [comment]
@gouthamve mind have a look?

**Comment by Lysholm** [comment]
@daixiang0: Would this also cause promtail to reload TLS client config, even if say `tls_config.cert_file` config is unchanged? That is what i need for promtail to work as a telemetry provider in a mTLS enabled istio mesh :)

**Comment by daixiang0** [comment]
@Kuqd @gouthamve mind have a look?

**Comment by daixiang0** [comment]
hi, @Kuqd, any input?

**Comment by daixiang0** [comment]
@cyriltovena hi, mind have a look?

**Comment by daixiang0** [comment]
@slim-bean @rfratto hi, mind have a look for this? If meaningful, i would update and fix conflicts.

**Comment by daixiang0** [comment]
@slim-bean @cyriltovena any update?

**Comment by daixiang0** [comment]
@sh0rez @rfratto @slim-bean any input?

**Comment by sh0rez** [comment]
Hi, we have completely refactored and rewritten the configuration framework used in the meantime, so these changes are obsolete ;)

In case this issue still needs a fix, please open a new PR :D

**Pull request closed without merging**
