### PR TITLE
helm: Use "loki.clusterLabel" template for PodLogs cluster label

### LINKED ISSUE #10212: Use "loki.clusterLabel" template for PodLogs cluster label
**Is your feature request related to a problem? Please describe.**
When I configure Loki helm chart with kube-prometheus-stack and want to set up proper monitoring (including dashboards) I must set up a few relabelings according to https://grafana.com/docs/loki/next/setup/install/helm/monitor-and-alert/with-local-monitoring/

It suggests using a value for the cluster label to be the same as the Loki helm release, which can't be used if I already use this cluster label with some different value.

This isn't an issue for ServiceMonitor, which sets this label to "loki.clusterLabel" template. This template takes the value from clusterLabelOverride if it is defined.

https://github.com/grafana/loki/blob/f25b5bdbf2c166391f661797bc539bb7225a1e09/production/helm/loki/templates/monitoring/servicemonitor.yaml#L43-L44

However, the PodLogs sets this label to "loki.fullname" template, so it can't be overridden without other side effects.

https://github.com/grafana/loki/blob/f25b5bdbf2c166391f661797bc539bb7225a1e09/production/helm/loki/templates/monitoring/pod-logs.yaml#L44-L45

**Describe the solution you'd like**
I suggest using "loki.clusterLabel" template for PodLogs as it is used for serviceMonitor.

**Describe alternatives you've considered**
Setting Loki chart release name the same as the intended cluster label value and not setting clusterLabelOverride.

**Additional context**
If you consider this useful, I can make PR for this issue ASAP.

### PR DESCRIPTION
**Pull request by elcomtik**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #10212

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Comment by MichelHollands** [comment]
@elcomtik Thanks for this fix. Can you rebase this? The helm docs also need to be updated as seen in the helm CI. Once that is done I'll merge it.

**Comment by elcomtik** [comment]
@MichelHollands I just rebased, it is ready for review.

**Comment by MichelHollands** [comment]
@elcomtik Someone else had their PR ready with version 5.12 earlier so that got merged. Can you use 5.23? Please also rebase and run helm-doc as indicated in the CI error.

**Comment by elcomtik** [comment]
Ok, I'll do it ASAP

**Comment by elcomtik** [comment]
It is done and also helm-doc is generated as needed.

**Pull request merged**
