### PR TITLE
Add support for Query Range String: Change step to string and support standard time.Duration parsing

### LINKED ISSUE #1209: Query range step does not support duration string.
From slack:

> prometheus seems to accept a "step" parameter as either a duration string or float, but loki seems to >only accept integers representing seconds - are there plans for loki's API to be brought more in line with >Prometheus' API in this respect?

Easy change to support and we should be as close as possible to Prometheus.

Please also update the doc.

### PR DESCRIPTION
**Pull request by nehayward**
**What this PR does / why we need it**:
This changes Query Range to a string to support step changes.

**Which issue(s) this PR fixes**:
Fixes #1209 

**Special notes for your reviewer**:
This still needs some refinement and I wanted to get some eyes on it from the Loki community before moving forward with the changes.

**Checklist**
- [x] Documentation added
- [ ] Tests updated -- (in progress)

### CODE REVIEW

**Comment by cyriltovena** [comment]
Thanks a lot for this, don’t forget we need to support both format.

See https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries

> step=<duration | float>: Query resolution step width in duration format or float number of seconds

**Comment by nehayward** [comment]
Any suggestion on how you'd like to do that. Should add another optional arg

**Comment by cyriltovena** [comment]
No the same argument just try converting to integer if it fails try parsing a duration if it fails it fails ;)

**Comment by cyriltovena** [comment]
@nehayward any news, I might need this too.

**Comment by nehayward** [comment]
Let me update my PR.

**Comment by huihuiy02** [comment]
It seems loki still doesn't support float numbers.  I got error when I run query via Grafana. 

rpc error: code = Code(400) desc = strconv.Atoi: parsing "54.982": invalid syntax

**Comment by cyriltovena** [comment]
yes @nehayward do you want me to take over ?

**Comment by cyriltovena** [comment]
Fixed.

**Pull request closed without merging**
