### PR TITLE
helm: values to override read/write/backend paths in gateway config

### LINKED ISSUE #8488: Helm: would like to be able to override read/write/backend paths in gateway config
**Is your feature request related to a problem? Please describe.**

I run some multi-tenant proxies similar to https://github.com/k8spin/loki-multi-tenant-proxy.
I have one for each path.

So it is "inserted" between the gateway and the read/write/backend pods.
For instance read requests do: `gateway => multi-tenant-proxy => read`

With the current chart, setting it in the gateway's configuration is cumbersome.

**Describe the solution you'd like**

I would like to be able to set, in my helm values, the URLs for read, write and backend.

**Describe alternatives you've considered**

Currently I maintain a chart that depends on this Loki chart, and overrides the whole gateway config.
But:
- this is difficult to maintain
- I may not be the only one with this need

### PR DESCRIPTION
**Pull request by hervenicol**
**What this PR does / why we need it**:

With this PR we could override the generated read/write/backend URLs for the gateway.

For instance, here I show the differences in proxy_pass definitions when overriding these paths:
```
[loki]$ helm template . | grep proxy_pass
          proxy_pass       http://loki-write.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-write.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-write.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-write.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-write.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
          proxy_pass       http://loki-write.default.svc.cluster.local:3100$request_uri;
[loki]$ cat values-custom.yaml 
gateway:
  nginxConfig:
    customLokiReadUrl: "https://myproxy/read"
    customLokiBackendUrl: "https://myproxy/backend"
    customLokiWriteUrl: "https://myproxy/write"
[loki]$ helm template . -f values-custom.yaml | grep proxy_pass
          proxy_pass       https://myproxy/write$request_uri;
          proxy_pass       https://myproxy/read$request_uri;
          proxy_pass       https://myproxy/read$request_uri;
          proxy_pass       https://myproxy/backend$request_uri;
          proxy_pass       https://myproxy/backend$request_uri;
          proxy_pass       https://myproxy/backend$request_uri;
          proxy_pass       https://myproxy/write$request_uri;
          proxy_pass       https://myproxy/read$request_uri;
          proxy_pass       https://myproxy/backend$request_uri;
          proxy_pass       https://myproxy/write$request_uri;
          proxy_pass       https://myproxy/write$request_uri;
          proxy_pass       https://myproxy/write$request_uri;
          proxy_pass       https://myproxy/backend$request_uri;
          proxy_pass       https://myproxy/backend$request_uri;
          proxy_pass       https://myproxy/backend$request_uri;
          proxy_pass       https://myproxy/read$request_uri;
          proxy_pass       https://myproxy/write$request_uri;
[loki]$ 
```

**Which issue(s) this PR fixes**:
Fixes #8488 

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [x] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by JStickler — APPROVED** [review]
[Docs squad]  Documentation LGTM

**Comment by hervenicol** [comment]
hmmm... I don't understand how I could have broken the CI.

I checked some local renders with default values and each of the ci/ values, and compared before/after my changes: the resulting files are identical.

```
[loki]$ git checkout main
Switched to branch 'main'
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
[loki]$ helm template . -f ci/default-values.yaml > render-master-ci-default.yaml
[loki]$ helm template . -f ci/enterprise.yaml > render-master-ci-enterprise.yaml
[loki]$ helm template . -f ci/ingress-values.yaml > render-master-ci-ingress.yaml

[loki]$ git checkout lokicharts_gwcustompaths
Switched to branch 'lokicharts_gwcustompaths'
Your branch is up to date with 'herve/lokicharts_gwcustompaths'.
[loki]$ helm template . -f ci/default-values.yaml > render-branch-ci-default.yaml
[loki]$ helm template . -f ci/enterprise.yaml > render-branch-ci-enterprise.yaml
[loki]$ helm template . -f ci/ingress-values.yaml > render-branch-ci-ingress.yaml

[loki]$ diff render-master-ci-default.yaml render-branch-ci-default.yaml
[loki]$ diff render-master-ci-enterprise.yaml render-branch-ci-enterprise.yaml
[loki]$ diff render-master-ci-ingress.yaml render-branch-ci-ingress.yaml 
```

I'm not familiar with `ct`, I'm can't spot the error in the job logs.
I'll try to reproduce the job locally on my laptop, see if I can spot what happens :shrug:

**Comment by hervenicol** [comment]
Well, ran the tests locally, they passed.
Rebased to latest master, re-pushed, and this time tests passed.
I guess it was just flakiness :sweat_smile:

**Review by DylanGuedes — APPROVED** [review]
looks great, lgtm.

Nit and personal preference, but maybe it is better to not have `Loki` in the configs? Like `customWriteUrl`, `customBackendUrl` etc instead of `customLokiWriteUrl`?

**Comment by hervenicol** [comment]
> Nit and personal preference, but maybe it is better to not have `Loki` in the configs? Like `customWriteUrl`, `customBackendUrl` etc instead of `customLokiWriteUrl`?

Makes sense. Done.

**Comment by hervenicol** [comment]
Tests are failing again... flaky tests, again? :cry:

**Review by DylanGuedes — APPROVED** [review]

**Pull request merged**
