### PR TITLE
promtail: add RFC3164 syslog support

### PR DESCRIPTION
**Pull request by aparcar**
I'm no Go programmer so somewhat glued ends together, please be patient. If this is of general interest I'm happy to fill the gaps like testing, documentation and change log. Since this requires changes of a vendor package, I created [a PR](https://github.com/influxdata/go-syslog/pull/46) there as well.

**What this PR does / why we need it**:

It adds RFC3164 support to promtail. Commonly used for OpenWrt and Ubiquiti syslogs.

**Which issue(s) this PR fixes**:

I opened a PR directly instead of an issue first.

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by MasslessParticle** [comment]
This is a reasonable idea. Given this is setup as a configuration option, it'd probably be cleaner to implement it as it's own target rather than having `if rfc3164...` everywhere.

Of course, also it'd need tests

**Review by chaudum — COMMENTED** [review]
How likely do you think it is to get https://github.com/influxdata/go-syslog/pull/46 into the upstream library (the project is rather stale)?

**Comment by chaudum** [comment]
> This is a reasonable idea. Given this is setup as a configuration option, it'd probably be cleaner to implement it as it's own target rather than having `if rfc3164...` everywhere.
> 
> Of course, also it'd need tests

I'm not sure about making a separate target, but I agree that we should have a better abstraction for the various syslog implementations.

E.g. in the config, there are would now be options for `UseRFC5424Message` and `IsRFC3164Message`, which are hard to distinguish and are not mutually exclusive.

Maybe the syslog target should have a single option `syslog_format` which could default to `rfc5424` and also takes `rfc3164` as possible value.

That configuration change would probably be breaking and therefore something for Loki/Promtail 3.0?

**Comment by chaudum** [comment]
> How likely do you think it is to get [influxdata/go-syslog#46](https://github.com/influxdata/go-syslog/pull/46) into the upstream library (the project is rather stale)?

@MasslessParticle @aparcar What do you think about forking the `go-syslog` project to the `grafana` Github org and reference the fork as long as the addition is not added to the upstream project?

**Comment by MasslessParticle** [comment]
> Maybe the syslog target should have a single option syslog_format which could default to rfc5424 and also takes rfc3164 as possible value.

This is totally reasonable. Putting the syslog stuff behind an interface would help keep the implementation cleaner

**Comment by MasslessParticle** [comment]
Sounds like there's still some demand for this but we may have to pick it up ourselves

**Comment by aparcar** [comment]
Uhm where can I follow your work? I can also give this another go

**Comment by catap** [comment]
@aparcar, @MasslessParticle any news?

**Pull request closed without merging**
