### PR TITLE
feat(helm): Replace bloom compactor with bloom planner and builder

### PR DESCRIPTION
**Pull request by chaudum**
**What this PR does / why we need it**:

This is PR is part of the process of removing the bloom compactor and replace it with bloom planner and bloom builder.

**Special notes for your reviewer**:

Part of https://github.com/grafana/loki/issues/13957

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by trevorwhitney — APPROVED** [review]
looks good. this adds a lot though so can we bump the version number?

**Comment by chaudum** [comment]
> looks good. this adds a lot though so can we bump the version number?

Done. Can you check once more?

**Review by trevorwhitney — APPROVED** [review]
lgtm

**Comment by z0rc** [comment]
Please revert this change, there are multiple problems with bloom-builder, that affect not only bloom filter feature:
- https://github.com/grafana/loki/issues/14082
- https://github.com/grafana/loki/issues/14084
- https://github.com/grafana/loki/issues/14083

...but also break general chart usability:
- https://github.com/grafana/loki/issues/14090

**Comment by chaudum** [comment]
Hi @z0rc @diranged  I'm sorry for any inconvenience this PR caused and I appreciate your reports. We will try to get issues sorted as soon as my availability allows for it. Any help with PRs is welcome.

**Comment by chaudum** [comment]
https://github.com/grafana/loki/pull/14128 contains fixes for the issues mentioned above.

**Pull request merged**
