### PR TITLE
Update nix configuration

### PR DESCRIPTION
**Pull request by angaz**
Hi.

I found the nix configuration here to be a bit broken, it looks like it hasn't been updated in a while, so I had a look at fixing some of the issues. It creates a workable dev environment now. I also fixed the linter errors I came accross.

One problem I have run into is that some of the tests are failing, so I can't actually build the packages with this setup. I tried it without running the tests, and it does build, but the default is to run the tests. We can disable that if we don't want to run the tests at build time.

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by SN9NV** [comment]
I've figured out why those two tests are failing, they seem to rely on the fact that the variables are captured and in parallel. Is this expected?

**Comment by trevorwhitney** [comment]
@angaz I clearly missed this, so sorry it's been sitting for so long. I'll try to take a look today.

**Comment by angaz** [comment]
It's been such a long time. Fixing the tests was done already, so that's not relevant anymore. Should I update the branch again?

**Comment by angaz** [comment]
I'm running the tests locally because the CI is quite slow on GH and I see there are tests failing trying to find addresses for all the interfaces, which is interesting. I'm not sure what to do about it, but it seems like the test is possibly wrong.

```
--- FAIL: TestInstanceCountDelegate_CorrectlyInvokesOtherDelegates (0.00s)
    instance_count_test.go:107:
         Error Trace:    /build/z5wlqr5j57n2i2jn8cdmmvqiw4x40z0d-source/pkg/distributor/instance_count_test.go:107
         Error:          Received unexpected error:
                         no useable address found for interfaces [lo]
         Test:           TestInstanceCountDelegate_CorrectlyInvokesOtherDelegates
FAIL
--- FAIL: TestCompactor_RunCompaction (0.01s)
    compactor_test.go:53:
         Error Trace:    /build/z5wlqr5j57n2i2jn8cdmmvqiw4x40z0d-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:53
                                                 /build/z5wlqr5j57n2i2jn8cdmmvqiw4x40z0d-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:94
         Error:          Received unexpected error:
                         no useable address found for interfaces [eth0 en0 lo]
                         invalid ring lifecycler config
                         github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.NewCompactor
                                 /build/z5wlqr5j57n2i2jn8cdmmvqiw4x40z0d-source/pkg/storage/stores/indexshipper/compactor/compactor.go:228
                         github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.setupTestCompactor
                                 /build/z5wlqr5j57n2i2jn8cdmmvqiw4x40z0d-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:50
                         github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.TestCompactor_RunCompaction
                                 /build/z5wlqr5j57n2i2jn8cdmmvqiw4x40z0d-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:94
                         testing.tRunner
                                 /nix/store/3wpbn0nv1yhb47njlb3z3vicj20cp2mj-go-1.20.2/share/go/src/testing/testing.go:1576
                         runtime.goexit
                                 /nix/store/3wpbn0nv1yhb47njlb3z3vicj20cp2mj-go-1.20.2/share/go/src/runtime/asm_amd64.s:1598
         Test:           TestCompactor_RunCompaction
--- FAIL: TestCompactor_RunCompactionMultipleStores (0.01s)
    compactor_test.go:53:
         Error Trace:    /build/z5wlqr5j57n2i2jn8cdmmvqiw4x40z0d-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:53
                                                 /build/z5wlqr5j57n2i2jn8cdmmvqiw4x40z0d-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:165
         Error:          Received unexpected error:
                         no useable address found for interfaces [eth0 en0 lo]
                         invalid ring lifecycler config
                         github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.NewCompactor
                                 /build/z5wlqr5j57n2i2jn8cdmmvqiw4x40z0d-source/pkg/storage/stores/indexshipper/compactor/compactor.go:228
                         github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.setupTestCompactor
                                 /build/z5wlqr5j57n2i2jn8cdmmvqiw4x40z0d-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:50
                         github.com/grafana/loki/pkg/storage/stores/indexshipper/compactor.TestCompactor_RunCompactionMultipleStores
                                 /build/z5wlqr5j57n2i2jn8cdmmvqiw4x40z0d-source/pkg/storage/stores/indexshipper/compactor/compactor_test.go:165
                         testing.tRunner
                                 /nix/store/3wpbn0nv1yhb47njlb3z3vicj20cp2mj-go-1.20.2/share/go/src/testing/testing.go:1576
                         runtime.goexit
                                 /nix/store/3wpbn0nv1yhb47njlb3z3vicj20cp2mj-go-1.20.2/share/go/src/runtime/asm_amd64.s:1598
         Test:           TestCompactor_RunCompactionMultipleStores
FAIL
```

**Comment by angaz** [comment]
It looks like this is also happening in the CI. I think everything else is good. I don't know what to do about the tests.

**Comment by trevorwhitney** [comment]
if you wouldn't mind, it looks pretty much good to go from my perspective, so just a matter of getting the tests to pass

**Comment by angaz** [comment]
I do not understand this code or these tests. Is the code wrong or are the tests wrong? I have no idea. So I can't say if I know how they need to be fixed. Are they just broken for the nix-run tests or are they also broken for everyone else?

**Comment by trevorwhitney** [comment]
I understand the code and the failure, but not how to fix it :frowning_face: 

Loki uses your local network interface to find your IP when setting up memberlist communication with the other processes. The normally works fine as there's a default that covers the standard nic naming strategies across most OSes. I'm assuming in whatever sandbox nix is building in there is no networking interface, or it's named something totally different, I'm just not sure how to discover that?

**Comment by trevorwhitney** [comment]
@angaz sorry for the long delay on this. I'm going to look into this a bit today. FYI I've force pushed to your branch to rebase these changes on the latest in `main`.

**Comment by angaz** [comment]
Yeah, cool, sounds good. No problem. You can take over if you need to.

**Review by trevorwhitney — APPROVED** [review]
Thanks for helping fix this! It's easy for this nix stuff to get neglected as it has a smaller user base. I would love continuing help in the future keeping it up to date!

**Pull request merged**
