### PR TITLE
Add SASL&mTLS authentication support for Kafka in Promtail

### LINKED ISSUE #4662: [Promtail] Kafka Authentication Support
**Is your feature request related to a problem? Please describe.**

In our environment, we need authentication to connect to Kafka cluster.
Therefore, it would be nice if promtail supports kafka authentication like SASL and mTLS.

**Describe the solution you'd like**

* As the first step, support SASL/PLAIN, SASL/SCRAM and mTLS

### PR DESCRIPTION
**Pull request by taisho6339**
**What this PR does / why we need it**:

Currently, Promtail doesn't support Kafka authentication so we can only connect with no auth.
Let me suggest changes to add some authentication for Kafka.
This PR adds the following auth method.

* mTLS
* SASL/PLAIN
* SASL/SCRAM
* SASL/PLAIN over TLS
* SASL/SCRAM over TLS

In addition, 

* Add documentation to configure authentication
* Add testing tools to check auth with Kafka locally
* Add go module to implement SASL/SCRAM

**Most of the changes are due to additional modules and testing tools.**

**Which issue(s) this PR fixes**:
Fixes #4662 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by taisho6339** [comment]
## TODO

* Add TLS support
* Add unit tests for these changes
* Add documentations
* Add auth tool for kafka to test

**Comment by taisho6339** [comment]
"shell check" in CI is failed but I didn't touch the files.
Should I fix in another PR?

**Review by cyriltovena — COMMENTED** [review]
Nice contribution @taisho6339. Went through the code once and it looks awesome. I'll run it locally this week an circle back.

**Comment by taisho6339** [comment]
Thank you so much!

**Review by cyriltovena — APPROVED** [review]
I wasn't able to connect with SSL locally, because of : ` java.security.cert.CertificateException: No name matching host.docker.internal found` 

Otherwise LGTM

**Comment by taisho6339** [comment]
Maybe we need to add "host.docker.internal" as SAN field in create certs script.
Anyway thank you for your review!

**Pull request merged**
