### PR TITLE
Support AWS Storage w/ HELM template

### PR DESCRIPTION
**Pull request by granular-ryanbonham**
- Adds support for AWS Storage in Helm Template
- Moves config from configMap to Secret as Config can contain AWS Access Keys & Secrets.

### CODE REVIEW

**Comment by granular-ryanbonham** [comment]
@davkal  Thanks for the feedback. I will get the changes made you suggested for the storage_config so it is not in multiple if blocks.

**Comment by granular-ryanbonham** [comment]
@davkal I have consolidate the aws_storage_configs into storage_configs. I moved the existing local storage under a "local_storage" in storage_configs. Let me know if you have any other concerns.

**Comment by davkal** [comment]
We're slowly establishing practices in the chart. One is that the `values` file contains good default as is. This PR needs to be adapted to accommodate that:

1. Get rid of the `storage_configs` arrays and remove related code from the `_helper` file.
2. Make `local_storage` the default `storage_config` 
3. Add documentation on how to modify `values.yaml` (or configmaps) on how to overwrite `storage_config` for AWS.

The main problem with the existing approach is boilerplate for every storage provider (e.g., we run GCS).

**Comment by sboschman** [comment]
missing loki enabled check on the secret (https://github.com/grafana/loki/commit/3fc4873b08601cc0739a5c37af763b1168228bf3#diff-aee8ca2c204d84be72c5c4d96ae5e330)

**Pull request merged**
