### PR TITLE
Update references to 2.6.1 binaries to 2.7.0

### PR DESCRIPTION
**Pull request by trevorwhitney**

### CODE REVIEW

**Review by ssncferreira — APPROVED** [review]
LGTM 📜

**Review by periklis — CHANGES_REQUESTED** [review]
Can you please remove the updates in the operator subfolder? We update them always after a Loki release.

**Comment by trevorwhitney** [comment]
@periklis will do (should have asked first, thought I was being helpful)

**Comment by periklis** [comment]
> @periklis will do (should have asked first, thought I was being helpful)

No worries it just breaks merging this before the Tag exists.

**Comment by trevorwhitney** [comment]
@periklis how does that look?

**Review by periklis — APPROVED** [review]

**Pull request merged**
