### PR TITLE
cmd/loki: minor consistency patch

### PR DESCRIPTION
**Pull request by michaelgrigoryan25**
**What this PR does / why we need it**:

Consider this PR as a refactor.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by dannykopping — COMMENTED** [review]
Thank you for your contribution @michaelgrigoryan25, but I'm hesitant to merge this because it might have side-effects that are not immediately obvious. To be honest I don't see the value this PR brings besides for slightly more idiomatic Go in this one file.

So maybe you can help me understand by elaborating on what the problem was that you encountered and why you submitted the PR?

**Comment by michaelgrigoryan25** [comment]
Hey @dannykopping, thanks for reviewing my PR!

> So maybe you can help me understand by elaborating on what the problem was that you encountered and why you submitted the PR?

It makes the code just a bit more idiomatic, and easier to read. 

> I'm hesitant to merge this because it might have side effects that are not immediately obvious.

What side effects might it have? I don't think that it would have any, since all the errors are immediately returned after being checked.

**Comment by dannykopping** [comment]
@michaelgrigoryan25 OK, thank you. Looking at it more closely I can't see any issues.
Please sign the CLA and I will merge it

**Comment by michaelgrigoryan25** [comment]
Thank you @dannykopping. I have successfully signed the CLA.

**Review by dannykopping — APPROVED** [review]

**Pull request merged**
