### PR TITLE
Add help info for how flag work

### LINKED ISSUE #638: promtail can not parse cmd flag override configfile
**Describe the bug**

**To Reproduce**
1. add config
```
# cat cmd/promtail/promtail-docker-config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push
    batchwait: 3s <===
scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
```
2. add value print in `pkg/promtail/client/config.go` and build
```
// UnmarshalYAML implement Yaml Unmarshaler
func (c *Config) UnmarshalYAML(unmarshal func(interface{}) error) error {
    type raw Config
    var cfg raw 
    if c.URL.URL != nil {
        // we used flags to set that value, which already has sane default.
        cfg = raw(*c)
    } else {
        // force sane defaults.
        cfg = raw{
            BackoffConfig: util.BackoffConfig{
                MaxBackoff: 5 * time.Second,
                MaxRetries: 5,
                MinBackoff: 100 * time.Millisecond,
            },
            BatchSize: 100 * 1024,
            BatchWait: 1 * time.Second,
            Timeout:   10 * time.Second,
        }
    }   

    if err := unmarshal(&cfg); err != nil {
        return err 
    }   

    *c = Config(cfg)
    fmt.Println("config yaml", c.BatchWait)
    return nil 
}
```
3.set config in cmd line and run
```
./promtail --config.file=cmd/promtail/promtail-docker-config.yaml --client.batch-wait=1s
config yaml 3s
level=warn ts=2019-05-31T09:39:25.628290877Z caller=filetargetmanager.go:101 msg="WARNING!!! entry_parser config is deprecated, please change to pipeline_stages"
level=info ts=2019-05-31T09:39:25.629777023Z caller=server.go:120 http=[::]:9080 grpc=[::]:46530 msg="server listening on addresses"

```

**Expected behavior**
cmd line config should override configfile.

Additional context:
#520 
#636

### PR DESCRIPTION
**Pull request by daixiang0**
**What this PR does / why we need it**:
FIx #638

### CODE REVIEW

**Comment by daixiang0** [comment]
@gouthamve not update dep since:
```
$ dep ensure -add github.com/imdario/mergo
Fetching sources...

Solving failure: No versions of github.com/cortexproject/cortex met constraints:
	master: unable to update checked out version: fatal: reference is not a tree: 88541de7a8aafbf501395ec767f059421c25d4c9
: command failed: [git checkout 88541de7a8aafbf501395ec767f059421c25d4c9]: exit status 128
	master: unable to update checked out version: fatal: reference is not a tree: af1bb6e68d188f768c351ae26e4c08de801a96d0
: command failed: [git checkout af1bb6e68d188f768c351ae26e4c08de801a96d0]: exit status 128
	1342-cassandra-config-yaml: Could not introduce github.com/cortexproject/cortex@1342-cassandra-config-yaml, as it is not allowed by constraint master from project github.com/grafana/loki.
	416-lazy-series-fetch-chunks: Could not introduce github.com/cortexproject/cortex@416-lazy-series-fetch-chunks, as it is not allowed by constraint master from project github.com/grafana/loki.
	619-new-endpoints: Could not introduce github.com/cortexproject/cortex@619-new-endpoints, as it is not allowed by constraint master from project github.com/grafana/loki.
	alertmgr-small-improvements: Could not introduce github.com/cortexproject/cortex@alertmgr-small-improvements, as it is not allowed by constraint master from project github.com/grafana/loki.
	allow-no-peer-discovery: Could not introduce github.com/cortexproject/cortex@allow-no-peer-discovery, as it is not allowed by constraint master from project github.com/grafana/loki.
	aws-unprocessed-keys: Could not introduce github.com/cortexproject/cortex@aws-unprocessed-keys, as it is not allowed by constraint master from project github.com/grafana/loki.
	backwards-compatible-series-ids: Could not introduce github.com/cortexproject/cortex@backwards-compatible-series-ids, as it is not allowed by constraint master from project github.com/grafana/loki.
	benchmark-distributor: Could not introduce github.com/cortexproject/cortex@benchmark-distributor, as it is not allowed by constraint master from project github.com/grafana/loki.
	bigchunks-compute-remaining-samples: Could not introduce github.com/cortexproject/cortex@bigchunks-compute-remaining-samples, as it is not allowed by constraint master from project github.com/grafana/loki.
	check-context-terminated: Could not introduce github.com/cortexproject/cortex@check-context-terminated, as it is not allowed by constraint master from project github.com/grafana/loki.
	chunk-desc: Could not introduce github.com/cortexproject/cortex@chunk-desc, as it is not allowed by constraint master from project github.com/grafana/loki.
	dynamodb-scanning: Could not introduce github.com/cortexproject/cortex@dynamodb-scanning, as it is not allowed by constraint master from project github.com/grafana/loki.
	fetch-client: Could not introduce github.com/cortexproject/cortex@fetch-client, as it is not allowed by constraint master from project github.com/grafana/loki.
	gcb-enablement: Could not introduce github.com/cortexproject/cortex@gcb-enablement, as it is not allowed by constraint master from project github.com/grafana/loki.
	integration-tests: Could not introduce github.com/cortexproject/cortex@integration-tests, as it is not allowed by constraint master from project github.com/grafana/loki.
	julius/tmp-rule-format-version-json: Could not introduce github.com/cortexproject/cortex@julius/tmp-rule-format-version-json, as it is not allowed by constraint master from project github.com/grafana/loki.
	khaines/drop-invalid-messages-from-flush: Could not introduce github.com/cortexproject/cortex@khaines/drop-invalid-messages-from-flush, as it is not allowed by constraint master from project github.com/grafana/loki.
	more-trace-spans: Could not introduce github.com/cortexproject/cortex@more-trace-spans, as it is not allowed by constraint master from project github.com/grafana/loki.
	oneshot: Could not introduce github.com/cortexproject/cortex@oneshot, as it is not allowed by constraint master from project github.com/grafana/loki.
	optimise-label-entries: Could not introduce github.com/cortexproject/cortex@optimise-label-entries, as it is not allowed by constraint master from project github.com/grafana/loki.
	pool-snappy-reader: Could not introduce github.com/cortexproject/cortex@pool-snappy-reader, as it is not allowed by constraint master from project github.com/grafana/loki.
	prom2-port-newam: Could not introduce github.com/cortexproject/cortex@prom2-port-newam, as it is not allowed by constraint master from project github.com/grafana/loki.
	query-stats: Could not introduce github.com/cortexproject/cortex@query-stats, as it is not allowed by constraint master from project github.com/grafana/loki.
	rebased-rules-by-file: Could not introduce github.com/cortexproject/cortex@rebased-rules-by-file, as it is not allowed by constraint master from project github.com/grafana/loki.
	setup-doc: Could not introduce github.com/cortexproject/cortex@setup-doc, as it is not allowed by constraint master from project github.com/grafana/loki.
	simple-scanner: Could not introduce github.com/cortexproject/cortex@simple-scanner, as it is not allowed by constraint master from project github.com/grafana/loki.
	spread-flushes: Could not introduce github.com/cortexproject/cortex@spread-flushes, as it is not allowed by constraint master from project github.com/grafana/loki.
	test-chunk-compatibility: Could not introduce github.com/cortexproject/cortex@test-chunk-compatibility, as it is not allowed by constraint master from project github.com/grafana/loki.
	troubleshoot-ruler: Could not introduce github.com/cortexproject/cortex@troubleshoot-ruler, as it is not allowed by constraint master from project github.com/grafana/loki.
	update-alertmanager: Could not introduce github.com/cortexproject/cortex@update-alertmanager, as it is not allowed by constraint master from project github.com/grafana/loki.
	update-am-vendoring: Could not introduce github.com/cortexproject/cortex@update-am-vendoring, as it is not allowed by constraint master from project github.com/grafana/loki.
	update-rule-format-tmp: Could not introduce github.com/cortexproject/cortex@update-rule-format-tmp, as it is not allowed by constraint master from project github.com/grafana/loki.
	wip-querier-speedup: Could not introduce github.com/cortexproject/cortex@wip-querier-speedup, as it is not allowed by constraint master from project github.com/grafana/loki.
```

**Comment by Kuqd** [comment]
Actually I think we want to fix this instead. Currently multiple flags works, there is just special case for --client.url= where if that one exist it will add another client config to the clients in the config struct for backward compatibility.

The only problem though is that flag don't supersede the config file and they should

**Comment by daixiang0** [comment]
@Kuqd yep, i asked a PR which can merge those config but you said it is [expected behaviour](https://github.com/grafana/loki/issues/638#issuecomment-497709071) so i ask this PR.
If confirmed, i will close this one and ask new PR to support merge.

**Comment by Kuqd** [comment]
how to use --client and clients is expected like I've describe, the rest is not and a bug.

**Comment by daixiang0** [comment]
Do you mean support config from cmd flag overvide config from file is what need to fix?

**Comment by daixiang0** [comment]
@Kuqd any update?

**Comment by daixiang0** [comment]
@Kuqd any input?

**Comment by rfratto** [comment]
Hi @daixiang0, this is a bug we want to fix rather than documenting; command line flags should take precedence over the config file. Just re-parsing the flags after unmarshaling the config file will do the trick. Thanks for the PR, though!

**Comment by daixiang0** [comment]
@rfratto is it in process or in plan? i would like to do it if possible.

**Comment by rfratto** [comment]
@daixiang0 nobody is working on it right now, feel free to submit something!

**Pull request closed without merging**
