### PR TITLE
Support GET for /ingester/shutdown

### LINKED ISSUE #11431: Make `/ingester/shutdown` endpoint work with `GET`
**Is your feature request related to a problem? Please describe.**
Currently the `/ingester/shutdown` endpoint only works with the `POST` method, but the kuberentes lifecycle `httpGet` (as the name implies) sends a `GET` requests, which doesn't do anything when triggered against that pod.

**Describe the solution you'd like**
The `/ingester/shutdown` endpoint should work with a HTTP `GET` request

**Describe alternatives you've considered**
The work around is using the `exec` to use a tool like `wget` or `curl` to send a `POST` request to the endpoint.

**Additional context**
In the loki chart is using the `httpGet` as well which is basically a no-op: https://github.com/grafana/loki/blob/main/production/helm/loki/templates/write/statefulset-write.yaml#L121

https://grafana.com/docs/loki/latest/operations/storage/wal/#kubernetes-hacking
https://grafana.com/docs/loki/latest/reference/api/#flush-in-memory-chunks-and-shut-down

### PR DESCRIPTION
**Pull request by MichelHollands**
**Which issue(s) this PR fixes**:
Fixes #11431 

**Checklist**
- [X] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [X] Documentation added
- [ ] Tests updated
- [x] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by paul1r — APPROVED** [review]
lgtm

**Review by JordanRushing — APPROVED** [review]

**Comment by andresperezl** [comment]
Will the update to the chart template (which still [uses the deprecated `flush_shutdown`](https://github.com/grafana/loki/blob/main/production/helm/loki/templates/write/statefulset-write.yaml#L122))  endpoint come later?

**Comment by MichelHollands** [comment]
> Will the update to the chart template (which still [uses the deprecated `flush_shutdown`](https://github.com/grafana/loki/blob/main/production/helm/loki/templates/write/statefulset-write.yaml#L122)) endpoint come later?

If you create a PR I'll merge it :)

**Comment by andresperezl** [comment]
@MichelHollands I opened the PR here https://github.com/grafana/loki/pull/11490, I guess we still need to wait for the next loki release for this change to be available

**Pull request merged**
