### PR TITLE
[Hot Fix] Fix receiver to implement Filterer

### PR DESCRIPTION
**Pull request by taisho6339**
**What this PR does / why we need it**:

Just now, main branch is failed to test so let me pull request.
Someone has already started to fix this, Please ignore and I'll close this PR.

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Review by cyriltovena — APPROVED** [review]
LGTM

**Comment by cyriltovena** [comment]
This is because of a merge conflict we actually have now two way to case sensitive check logs. Are you up for merging the two into one improve using the latest case sensitive check ?

**Comment by taisho6339** [comment]
Trying...

**Comment by taisho6339** [comment]
@cyriltovena 
I've just rebased using your latest merged commit.
Is that correct?
https://github.com/grafana/loki/pull/4804

**Comment by cyriltovena** [comment]
https://github.com/grafana/loki/pull/4803/files#diff-1eceeba414fe144ac5ef69a91caf908d339429cd1a6308327662ab9cd8ea14c8R331

This line should be doing the new way of case sensitive. I suggest we add a function and use that function in both filter.

**Pull request closed without merging**
