### PR TITLE
fix(helm): add missing `loki.storage.azure.chunkDelimiter` parameter to Helm chart

### LINKED ISSUE #14010: Missing chunkDelimiter parameter for Azure storage in Helm chart
**Describe the bug**
The Loki helm chart is missing the `loki.storage.azure.chunkDelimiter` parameter. This is needed when migrating from S3 (which uses `:`) to Azure Blob Storage (which uses `-` by default *(why?!)*).

**To Reproduce**
1. Set `loki.storage.azure.chunkDelimiter` to `:`
2. Deploy to Kubernetes
3. Delimiter is still using `-` because parameter is not set in the template.

**Expected behavior**
Being able to set `chunkDelimiter` as part of the helm values.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
N/A

### PR DESCRIPTION
**Pull request by NGPixel**
**What this PR does / why we need it**:

The helm chart is missing the `chunk_delimiter` parameter for Azure storage. This PR adds it to the values as `chunkDelimiter`.

**Which issue(s) this PR fixes**:
Fixes #14010

**Special notes for your reviewer**:
N/A

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [x] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by vlad-diachenko — APPROVED** [review]
lgtm 👍  thanks @NGPixel

**Comment by vlad-diachenko** [comment]
@NGPixel could you please fix the CI and bump the version in chart.yaml, add an entry to the changelog, and regenerate the docs.

**Comment by NGPixel** [comment]
@vlad-diachenko It should be fixed now.

**Comment by NGPixel** [comment]
@vlad-diachenko Any updates?

**Comment by trevorwhitney** [comment]
@NGPixel sorry this fell through the cracks. Any chance you can resolve the conflicts today, I'm happy to shepard it through.

**Comment by NGPixel** [comment]
Thanks @trevorwhitney, I updated the files against the latest version.

**Comment by NGPixel** [comment]
Can @trevorwhitney or @vlad-diachenko merge this PR before anything else comes up? I've had to update the PR 3 times already because the version keeps incrementing. Why is the version numbering not automatically calculated during release (like almost any other software) instead of manually inside the PR itself?? This is wasting a lot of time on the contributors and getting quite ridiculous.

**Comment by trevorwhitney** [comment]
@NGPixel I agree. We have changed the helm release process to not cut a release and bump the version on every merged PR

**Pull request merged**
