### PR TITLE
Fix blank messages in CRI & support CRI in Helm

### PR DESCRIPTION
**Pull request by steven-sheehy**
Follow up to #365.

- Fix blank messages showing up as an error 'Line did not match the CRI log format'. CRI splits lines that contain newlines as multiple logging lines, so if application adds blank lines for spacing then these were ignored. For example, my app starts up and prints a multi-line ascii banner with some empty lines around it.
- Add an option to set the entryParser in the promtail configMap so helm users can switch from docker (default) to cri.
- Fix fullnameOverride not properly namespaced in Helm chart. Previously it assumed both sub-charts would have the same fullname.
- Bumped the Helm chart version for new features as is [recommended](https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#immutability)

### CODE REVIEW

**Comment by slim-bean** [comment]
@steven-sheehy could you rebase this on master, I reorganized the test file you created a little to add some docker test coverage, but hopefully the merge isn't too bad.

**Comment by steven-sheehy** [comment]
@slim-bean Done

**Comment by slim-bean** [comment]
and thanks for the detailed PR notes :)

**Pull request merged**
