### PR TITLE
Promtail targets page

### LINKED ISSUE #463: ServiceDiscovery page for Promtail
**Is your feature request related to a problem? Please describe.**
Prometheus has a Service Discovery page that displays the state of discovery things being relabelled and dropped. You can look at the page by visiting `/service-discovery` on your Prometheus.

**Describe the solution you'd like**
For PromTail's discovery it would be helpful to have a similar page in the internal http server of PromTail so that, when configuring or debugging PromTail's config, one can more easily see what PromTail discovers.

**Describe alternatives you've considered**
We could also just log more information to the logs, but that might get cluttered very quickly.

**Additional context**
- 

/cc @gouthamve

### PR DESCRIPTION
**Pull request by Kuqd**
This adds a page at /targets to see all configured targets with labels, files and positions.

See screenshot :

Screen Shot 2019-04-30 at 12 08 31 PM

All static files are server using github.com/shurcooL/vfsgen which embed files within binary, use `tag=dev` to run file from local.

We should also be able to build and improve upon this PR more tools...

PS: templating is mostly inspired by Prometheus.

~~Move forward #463 however this is not the exact same page, but I figured this one is more important.~~
EDIT: Fixes #463

### CODE REVIEW

**Comment by Kuqd** [comment]
hum external labels are not honored, I'll look into it after sending to multiple loki task as this is area will change.

**Comment by steven-sheehy** [comment]
Sexy! Can there be different types besides File? That column seems too wide and labels not wide enough.

**Comment by Kuqd** [comment]
Good question we thought about this and we want to keep the door open for syslog or kafka for instance as targets. Now I'll for sure make the change to get a wider row for labels and less wider for type

**Comment by steven-sheehy** [comment]
Tested it out. I was hoping to find a way to see pods not scraped. This currently only shows scraped targets. Is that something the service discovery page is supposed to do?

**Comment by steven-sheehy** [comment]
Also, would be good to know which job_name from relabel_configs it used if that's possible?

**Comment by Kuqd** [comment]
Job is part of the title above each table, is it not what you want ?

**Comment by steven-sheehy** [comment]
Ah, I'm blind. That's perfect.

What about the non-scraped pods? What if we add a fallback job to scrape config that drops everything else so that it shows up as a "non-scraped" jobs in /targets?

**Comment by Kuqd** [comment]
I need to investigate this. It's on my todo.

**Comment by steven-sheehy** [comment]
LGTM. Only thing I think missing is some docs. Maybe add to api page and to troubleshooting? Some short  summary on the /target page itself on how to interpret the results would be useful, too.

**Comment by Kuqd** [comment]
how about this now ?

Screen Shot 2019-05-02 at 3 41 53 PM

I think this is much better now. I'm going to add some bit in the documentation about this also.

**Comment by steven-sheehy** [comment]
Gave it a spin and this looks awesome. Thanks for this @Kuqd

**Comment by Kuqd** [comment]
flaky test we need the #533

**Pull request merged**
