### PR TITLE
Loki: Improve spans usage

### PR DESCRIPTION
**Pull request by DylanGuedes**
**What this PR does / why we need it**:
- At different places, inherit the span/spanlogger from the given context instead of instantiating a new one from scratch, which fix spans being orphaned on a read/write operation.
- At different places, turn spans into events. Events are lighter than spans and by having fewer spans in the trace, trace visualization will be cleaner without losing any details.
- Adds new spans/events to places that might be a bottleneck for our writes/reads.

### CODE REVIEW

**Review by MasslessParticle — APPROVED** [review]

**Comment by MasslessParticle** [comment]
Didn't see that this was a draft. It looks totally reasonable, though

**Comment by DylanGuedes** [comment]
> Didn't see that this was a draft. It looks totally reasonable, though

Np, thanks for the review. I tested in on our infra today and it definitely helped the orphaned spans.

**Comment by DylanGuedes** [comment]
On this same PR I'm mixing fixes with new things. If you'd like to see things separated in smaller PRs just let me know.

**Review by JStickler — APPROVED** [review]
[docs team] LGTM

**Pull request merged**
