### PR TITLE
Reuse allocated buffer space in merge iterator.

### PR DESCRIPTION
**Pull request by jeschkies**
**What this PR does / why we need it**:
We saw a performance decrease when running the merge iterator with a very small pool of ingesters. The reason was that we would allocate a new buffer with each next call.

**Special notes for your reviewer**:
`main` is missing `merge_sort_dedupe-16` so I ran it once with a small patch to generate the data.

```goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/iter
cpu: AMD Ryzen 7 3700X 8-Core Processor             
                                  │ mergeiter-old.txt │         mergeiter-new.txt          │
                                  │      sec/op       │   sec/op     vs base               │
SortIterator/merge_sort-16                1.350m ± 4%   1.368m ± 4%       ~ (p=0.579 n=10)
SortIterator/merge_sort_dedupe-16         2.566m ± 4%   2.462m ± 5%       ~ (p=0.105 n=10)
SortIterator/sort-16                      1.034m ± 6%   1.029m ± 6%       ~ (p=0.684 n=10)
SortSampleIterator/merge-16               1.877m ± 2%   1.857m ± 2%       ~ (p=0.075 n=10)
SortSampleIterator/sort-16                432.7µ ± 6%   436.0µ ± 4%       ~ (p=0.579 n=10)
geomean                                   1.238m        1.229m       -0.72%

                                  │ mergeiter-old.txt │           mergeiter-new.txt           │
                                  │       B/op        │     B/op      vs base                 │
SortIterator/merge_sort-16               21.22Ki ± 0%   21.22Ki ± 0%       ~ (p=1.000 n=10)
SortIterator/merge_sort_dedupe-16        41.47Ki ± 0%   41.47Ki ± 0%       ~ (p=1.000 n=10) ¹
SortIterator/sort-16                     13.94Ki ± 0%   13.94Ki ± 0%       ~ (p=1.000 n=10) ¹
geomean                                  23.06Ki        23.06Ki       +0.00%
¹ all samples are equal

                                  │ mergeiter-old.txt │          mergeiter-new.txt          │
                                  │     allocs/op     │ allocs/op   vs base                 │
SortIterator/merge_sort-16                 7.000 ± 0%   7.000 ± 0%       ~ (p=1.000 n=10) ¹
SortIterator/merge_sort_dedupe-16          7.000 ± 0%   7.000 ± 0%       ~ (p=1.000 n=10) ¹
SortIterator/sort-16                       5.000 ± 0%   5.000 ± 0%       ~ (p=1.000 n=10) ¹
geomean                                    6.257        6.257       +0.00%
¹ all samples are equal
```

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

### CODE REVIEW

**Comment by jeschkies** [comment]
image

**Review by chaudum — APPROVED** [review]
lgtm

**Comment by bboreham** [comment]
I think it would be good to run the existing benchmarks too, just to check that `len-1` isn't unexpectedly expensive.

**Comment by chaudum** [comment]
Quickly ran existing benchmarks:

```
$ gotest -v -count=10 ./pkg/iter/... -test.run="^$" -test.bench=Benchmark -test.benchtime=2000x
```

```console
$ benchstat mergeiter-old.txt mergeiter-new.txt                                                                                      
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/iter
cpu: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
                           │ mergeiter-old.txt │         mergeiter-new.txt          │
                           │      sec/op       │   sec/op     vs base               │
SortIterator/merge_sort-8          742.8µ ± 1%   718.8µ ± 1%  -3.24% (p=0.000 n=10)
SortIterator/sort-8                632.9µ ± 4%   608.6µ ± 2%  -3.84% (p=0.001 n=10)
SortSampleIterator/merge-8         1.554m ± 2%   1.529m ± 3%  -1.63% (p=0.035 n=10)
SortSampleIterator/sort-8          274.5µ ± 8%   274.9µ ± 7%       ~ (p=0.853 n=10)
geomean                            669.2µ        654.8µ       -2.15%

                          │ mergeiter-old.txt │           mergeiter-new.txt           │
                          │       B/op        │     B/op      vs base                 │
SortIterator/merge_sort-8        21.22Ki ± 0%   21.22Ki ± 0%       ~ (p=1.000 n=10) ¹
SortIterator/sort-8              13.94Ki ± 0%   13.94Ki ± 0%       ~ (p=1.000 n=10) ¹
geomean                          17.20Ki        17.20Ki       +0.00%
¹ all samples are equal

                          │ mergeiter-old.txt │          mergeiter-new.txt          │
                          │     allocs/op     │ allocs/op   vs base                 │
SortIterator/merge_sort-8          7.000 ± 0%   7.000 ± 0%       ~ (p=1.000 n=10) ¹
SortIterator/sort-8                5.000 ± 0%   5.000 ± 0%       ~ (p=1.000 n=10) ¹
geomean                            5.916        5.916       +0.00%

```

**Review by JordanRushing — APPROVED** [review]

**Comment by jeschkies** [comment]
We have to hold this merge. I've found that the benchmark has no duplicates.

**Pull request merged**
