### PR TITLE
Helm: Allow cluster label to be something other than loki.fullname

### PR DESCRIPTION
**Pull request by jontg**
**What this PR does / why we need it**:
The default behavior for this helm chart is to add a `cluster` label to its rules and monitoring.  That's a pretty general label name, and forcing use of full name feels pretty restrictive.

This change allows developers to override this value, while preserving the original behavior by default.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [X] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Review by JStickler — APPROVED** [review]
[docs team] LGTM

**Comment by jontg** [comment]
It's unclear to me what the doc-validator failure is in reference to. The error,
```
ERROR: docs/sources/installation/helm/reference.md:11:3 The first heading "Helm Chart Values" does not match the title "Helm chart values".
[5](https://github.com/grafana/loki/actions/runs/4759427729/jobs/8458684277?pr=9218#step:4:6)
```
makes me think there's something up with the validator?

Notably, [L11](https://github.com/grafana/loki/blame/main/docs/sources/installation/helm/reference.md#L11), the title of the article, is auto-generated from [here](https://github.com/grafana/loki/blob/main/production/helm/loki/reference.md.gotmpl#L2), and spot-checking other docs suggests that capitalizing the title is expected behavior.

**Comment by JStickler** [comment]
>The first heading "Helm Chart Values" does not match the title "Helm chart values".

@jontg, the docs-validator is pretty particular, in this case the capitalization doesn't match.  Change the heading to be "Helm chart values" (to match the Style Guide for sentence capitalization) and it should pass.

**Comment by kavirajk** [comment]
@jontg can you resolve the conflict please?

**Comment by jontg** [comment]
@kavirajk done

**Pull request merged**
