### PR TITLE
bump up prometheus from v0.41.0 to v0.42.0

### PR DESCRIPTION
**Pull request by mar4uk**
**What this PR does / why we need it**:
Bumps [github.com/prometheus/prometheus](https://github.com/prometheus/prometheus) from v0.41.0 to v0.42.0.

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by bboreham** [comment]
As it happens I had fixed up the iterators already: https://github.com/grafana/loki/commit/59f6b4ca16ddcffc1ce5522934361c5062ea65ec

(sorry didn't get round to posting my PR)

**Comment by mar4uk** [comment]
@bboreham Shall I close this PR then? you are probably already on bumping prometheus version to v0.42.0 :)

**Comment by bboreham** [comment]
No, you got here first; I’m happy for you to finish it. Just thought I could save you part of the work.

**Comment by bboreham** [comment]
After discussion, I pushed my version as #8571

**Comment by mar4uk** [comment]
Great! thank you! closing this one

**Pull request closed without merging**
