### PR TITLE
allow read only components to *not* configure an index gateway client…

### PR DESCRIPTION
**Pull request by afayngelerindbx**
…, if they so choose

**What this PR does / why we need it**:
This PR fixes a recently introduced bug. The bug being fixed does not allow loki to run read path components without an index gateway client.

This is due to a nil check in https://github.com/grafana/loki/blob/435391661f4e0f03eb378f77c07aaad5009cd6e9/pkg/storage/store.go#L205 that returns true when a nil struct typed reference is assigned to an interface reference.

### CODE REVIEW

**Comment by cyriltovena** [comment]
me and @DylanGuedes where looking at this. Thanks let's see

**Comment by cyriltovena** [comment]
I think it works, we might need to reintroduce the nil check in the store. Let's me test it and push commit if that works.

Thanks for helping btw.

**Comment by cyriltovena** [comment]
Great spot thank you so much for the hint, I've merged another PR to solve this but again thanks for helping, appreciated.

**Comment by afayngelerindbx** [comment]
Thanks for fixing! Your patch looks much cleaner.

**Pull request closed without merging**
