### PR TITLE
fix labels path in logcli

### PR DESCRIPTION
**Pull request by sandeepsukhani**
**What this PR does / why we need it**:
Labels path in logcli is incorrectly set to `/loki/api/v1/labels` instead of `/loki/api/v1/label` causing it to error out with 404. This PR fixes that.

### CODE REVIEW

**Comment by cyriltovena** [comment]
The doc says https://github.com/grafana/loki/blob/master/docs/api.md#get-lokiapiv1labels labels ?

**Comment by cyriltovena** [comment]
Also we seems to support both 

```
	t.server.HTTP.Handle("/loki/api/v1/label", httpMiddleware.Wrap(http.HandlerFunc(t.querier.LabelHandler)))
	t.server.HTTP.Handle("/loki/api/v1/labels", httpMiddleware.Wrap(http.HandlerFunc(t.querier.LabelHandler)))
```

**Comment by cyriltovena** [comment]
we can change it but I would prefer to have the documented one used :)

**Comment by sandeepsukhani** [comment]
Nevermind, the problem was in our gateway routes which it seems you have already fixed but is not deployed yet. Closing this.

**Pull request closed without merging**
