### PR TITLE
Replace memberlist service in favor of cortex provided service

### PR DESCRIPTION
**Pull request by periklis**
**What this PR does / why we need it**:
This PR addresses the wiring work needed to use the non-experimental version of memberlist as provided by: cortexproject/cortex#2638

**Which issue(s) this PR fixes**:
-

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

cc @cyriltovena @pstibrany

### CODE REVIEW

**Comment by periklis** [comment]
@pstibrany I believe it's time to give documentation also some love regarding memberlist. I can add an example configuration with a reference to a headless k8s service.

**Comment by pstibrany** [comment]
> @pstibrany I believe it's time to give documentation also some love regarding memberlist. I can add an example configuration with a reference to a headless k8s service.

That's a great idea. We have some documentation in Cortex, but nothing in Loki.

- https://cortexmetrics.io/docs/getting-started/getting-started-with-gossiped-ring/
- https://cortexmetrics.io/docs/configuration/arguments/#memberlist

**Comment by periklis** [comment]
Hmm... i noticed that we don't expose the memberlist flags for loki. Maybe also a good time to do so. WDYT?

**Comment by pstibrany** [comment]
> Hmm... i noticed that we don't expose the memberlist flags for loki. Maybe also a good time to do so. WDYT?

Interesting, yes, we should do that. Thanks!

**Comment by periklis** [comment]
@pstibrany @cyriltovena PTAL with the added docs and examples

**Pull request merged**
