### PR TITLE
refactor(loki/logcli): standalone client

### PR DESCRIPTION
**Pull request by sh0rez**
Moves the http client logic out of logcli into its own package to use it other
software speaking with loki as well

### CODE REVIEW

**Comment by woodsaj** [comment]
seems like we should merge this client with the pkg/promtail/client package.  Then we can have a single client package that supports both reads and writes to loki.

**Comment by sh0rez** [comment]
I agree to you @woodsaj, a single unified client for the Loki API would be nice to have. However, I do not know quite how to achieve this:

The client that used to live inside of `logcli` is basically a set of utility methods to wrap the a REST interface.

The client of `promtail` on the other hand is far more complicated because is async. There is a goroutine running once the client is initialized. Calls to `Handle` result in the Entry being appended to the current batch (read state). Once the batch is big enough it is flushed.

It is tricky to unite a stateless REST wrapper with a stateful batch client.
Could somebody give me some input here?

**Comment by cyriltovena** [comment]
are you ok with this !?

**Comment by sh0rez** [comment]
Hrm, I experienced the long standing problem of Config management, because the promtail client is full of flag handling and so on.

Very unsure how of deal it without messing to much with the Config

**Comment by rfratto** [comment]
Closing this as stale after discussion with @sh0rez.

**Pull request closed without merging**
