### PR TITLE
helm chart: Fix broken logo

### PR DESCRIPTION
**Pull request by scottrigby**
**What this PR does / why we need it**:
The log has moved, so Chart.yaml logo is incorrect. This causes tools like CNCF Artifact Hub to fail displaying the logo.

**Which issue(s) this PR fixes**:
~Fixes #<issue number>~

**Special notes for your reviewer**:
Similar to https://github.com/grafana/loki/pull/2385

**Checklist**
~- [ ] Documentation added~
~- [ ] Tests updated~

### CODE REVIEW

**Comment by slim-bean** [comment]
Thanks @scottrigby! 

Could you also bump the loki-stack chart patch version too?

**Comment by scottrigby** [comment]
@slim-bean sure, do you want that as a separate PR?￼

**Comment by slim-bean** [comment]
same PR, thanks!

**Review by cyriltovena — COMMENTED** [review]
You'll also need to bump the umbrella chart loki-stack.

**Review by cyriltovena — APPROVED** [review]

**Pull request merged**
