### PR TITLE
loki: enable PathPrefix for queryHandler endpoints

### PR DESCRIPTION
**Pull request by ryoshindo**
**What this PR does / why we need it**:

Hi, loki developers.

I would like to use the option `http_path_prefix` as described in the official documentation. 
This setting is valid for endpoints defined at https://github.com/grafana/loki/blob/4d55a24ed3cbed399c189dafb8c4140cbffce21d/pkg/loki/loki.go#L477-L494 but not for the endpoints defined at https://github.com/grafana/loki/blob/4d55a24ed3cbed399c189dafb8c4140cbffce21d/pkg/loki/modules.go#L366-L392 .

The current latest version with `http_path_prefix` will return the expected response for the former endpoint, but will return a 404 not found error when accessing the latter endpoint.
For example, if you define `http_path_prefix = /xxx`, requests for `/xxx/ready` will work as expected, but requests for `/xxx/loki/api/v1/query` will result in 404 errors.

I've created a pull request for this issue because I've been experiencing some inconvenience when using loki. Please check it out.

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/loki/issues/4756

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Tests updated

### CODE REVIEW

**Comment by MichelHollands** [comment]
@ryoshindo This should also apply to the write path else it will be inconsistent.

**Comment by ryoshindo** [comment]
@MichelHollands 
I didn't know about loki's write path, are you referring to the `distributor` feature according to the following documentation?
https://grafana.com/docs/loki/v2.7.x/fundamentals/architecture/#write-path
I have made the `querier` modification this time, so that means I have modified the read path functionality.

So I looked at the `distributor` implementation.
The `distributor` endpoint is likely to be defined here.
https://github.com/grafana/loki/blob/4c227bd268280980e6f8519652a2e91661a7003f/pkg/loki/modules.go#L306-L313

The paths of these endpoints are all defined as `t.Server.HTTP.Path`, like `t.Server.HTTP.Path("/distributor/ring")`.
If written as above, `PathPrefix` will be given by the `weaveworks/common` module if `http_path_prefix` is defined in `config.yml`.
https://github.com/weaveworks/common/blob/16871410fca4a9fc55b07211496be1faff2ab34b/server/server.go#L387

Therefore, I am aware that the inconsistency has been resolved with this implementation.

I actually ran `curl` on `distributor/ring` with `http_path_prefix = /xxx` and got the following results.

<details><summary> `curl localhost:3100/xxx/distributor/ring` </summary>

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Ring Status</title>
</head>
<body>
<h1>Ring Status</h1>
<p>Current time: 2023-02-11 14:48:35.806287 &#43;0900 JST m=&#43;145.337819042</p>
<form action="" method="POST">
    <input type="hidden" name="csrf_token" value="$__CSRF_TOKEN_PLACEHOLDER__">
    <table width="100%" border="1">
        <thead>
        <tr>
            <th>Instance ID</th>
            <th>Availability Zone</th>
            <th>State</th>
            <th>Address</th>
            <th>Registered At</th>
            <th>Last Heartbeat</th>
            <th>Tokens</th>
            <th>Ownership</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>


                <tr>

            <td>Ryos-MacBook-Pro.local</td>
            <td></td>
            <td>ACTIVE</td>
            <td>127.0.0.1:0</td>
            <td>2023-02-11T05:46:10Z</td>
            <td>10.806s ago (05:48:25)</td>
            <td>1</td>
            <td>100%</td>
            <td>
                <button name="forget" value="Ryos-MacBook-Pro.local" type="submit">Forget</button>
            </td>
            </tr>

        </tbody>
    </table>
    <br>

        <input type="button" value="Show Tokens" onclick="window.location.href = '?tokens=true'"/>



</form>
</body>
</html>
```

</details>

<details><summary> `curl localhost:3100/distributor/ring` </summary>

```
404 page not found
```

</details>

Thank you for your confirmation.

**Review by MasslessParticle — APPROVED** [review]
LGTM, thanks for your contribution!

**Comment by fsiler** [comment]
I think I've discovered a regression from this: it breaks the `/loki/api/v1/series` and `/loki/api/v1/query_range` endpoints when server.http_path_prefix is set. I manually bisected the docker images and concluded that the change of series->broken and labels->working back to this commit. @ryoshindo, @MasslessParticle, any ideas on how to fix that?

```yaml
#          image: grafana/loki:latest        #     2.8.4        labels broken,BR: series works
#          image: grafana/loki:main-6bb8a07  #     5 months ago:labels broken,BR: series working
#          image: grafana/loki:main-79c5fdd  #     3 months ago:labels broken,BR: series working
#          image: grafana/loki:main-35465d0  # p50 2mo          labels busted,BR: series working
#          image: grafana/loki:main-3e1f2fc  # p49              labels busted,BR: series work
          image: grafana/loki:main-ed0d15a  # p49               labels work, sBR:eries busted
#          image: grafana/loki:main-30fff3c  # p49              labels work, sBR:eries busted
#          image: grafana/loki:main-d4cfbaa  # p47              labels work, sBR:eries busted
#          image: grafana/loki:main-26f36d0  # p45              labels work, sBR:eries busted
#          image: grafana/loki:main-9e19ff0  # p40 2mo          labels work,  BR: series busted
#          image: grafana/loki:main-a7536ef  #     60 days ago: labels work,  BR: series busted
#          image: grafana/loki:main          #     today:       labels work,  BR: series busted
```

**Comment by Pexers** [comment]
Any updates on this? I'm experiencing the same error when using the `http_path_prefix`. Without it, Loki health checks work just fine.

**Comment by fsiler** [comment]
@Pexers I'm halfway to the point of considering trying [VictoriaLogs](https://docs.victoriametrics.com/victorialogs/).

**Pull request merged**
