### PR TITLE
Improve ksonnet to be more manageable

### PR DESCRIPTION
**Pull request by gouthamve**
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

### CODE REVIEW

**Comment by tomwilkie** [comment]
I don't see why this needs to be so complicated - can we follow the patterns in https://github.com/raintank/deployment_tools/blob/master/ksonnet/lib/cortex/config.libsonnet#L41?

**Comment by gouthamve** [comment]
I think this is much simpler and that pattern gets ugly fast. Specially as we'll have to add cassandra and possibly other setups to it.

If you take a look, we'll have to do the `storage_backend` check twice for each backend, once for the object store, and once for the index. And that way renders empty blocks for aws and others (afaics) if gcp is chosen which is slightly confusing.

**Comment by tomwilkie** [comment]
Right, but the AWS config for this isn't implemented - I'd prefer it be missing rather than non working or incomplete.  There for if we remove it, this looks overcomplicated.

**Comment by tomwilkie** [comment]
Closing this and opening it from a branch on this repo.

**Pull request closed without merging**
