### PR TITLE
docs: fix row_shards doc

### PR DESCRIPTION
**Pull request by jk2K**
for v10 or greater, default is 16

refer to https://github.com/grafana/loki/blob/1002ba00dff58ed588987169c0d3a0ddac2d022b/pkg/storage/config/schema_config.go#L336

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by JStickler — APPROVED** [review]
[docs team] LGTM.   Thanks for your contribution to keeping the docs updated.

**Comment by JStickler** [comment]
The build is failing with the following error message, "Please update generated documentation by running 'make doc' and committing the changes."

**Comment by jk2K** [comment]
> The build is failing with the following error message, "Please update generated documentation by running 'make doc' and committing the changes."

updated

**Review by JStickler — CHANGES_REQUESTED** [review]
@jk2K My apologies, I wasn't paying enough attention when I originally reviewed this PR.  The file `docs/sources/configure/_index.md` is a generated file. When you make updates to the configuration reference, you need to make them in the `reference.template` file then run 'make doc' to update the generated file and commit the changes.

**Comment by jk2K** [comment]
@JStickler not found `reference.template`

**Comment by JStickler** [comment]
@jk2K I am really having problems reviewing this PR.  It's `index.template` not `reference.template`.

**Comment by jk2K** [comment]
row_shards not in `index.template`, it's read from `pkg/storage/config/schema_config.go`

**Review by JStickler — APPROVED** [review]
[docs team]  LGTM

Sorry for all the back and forth.  I admit that I need more sleep.

**Pull request merged**
