### PR TITLE
[release-2.9.x] chore(promtail): Use minimal init config in rpm/deb packaging.

### PR DESCRIPTION
**Pull request by grafanabot**
Backport 86f2001c39a56bd9760fb51807096aba0b62ecdd from #11511

---

**What this PR does / why we need it**:
Related issue: https://github.com/grafana/loki/issues/11398

This minimal config scrape only single file thus not overloading the systems as described in the issue

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by janfickler** [comment]
any updates on this ?

**Comment by poyzannur** [comment]
Hi @janfickler, working on getting this out this week.

**Review by poyzannur — APPROVED** [review]

**Comment by janfickler** [comment]
@poyzannur there is still no new version 2.9.4 released ?

**Comment by poyzannur** [comment]
Hi @janfickler, you might already seen 2.9.4 ([releases](https://github.com/grafana/loki/releases)) is out. Apologies for the wait, thanks for your patience.

**Comment by janfickler** [comment]
@poyzannur, yes but it seems that it is not available in the official Grafana-RPM-Repository or Grafana-DEV-Repository.

Or maybe it was currently not packaged and pushed ?

we use for our rpm-based systems - https://packages.grafana.com/oss/rpm - and there is currently only version 2.9.3 available.

**Pull request merged**
